### ISSUE TITLE
Public programs/actions

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#100]
## Rationale

We aim to help our leaders (platform admin) to showcase their programs and actions in the public site and to make it happen, we have to update the way programs with "public" / "open" audience are considered.
Indeed, currently, even actions from a program for which the audience is an open space cannot be listed to logged in users.
This reduce the onboarding and this requests to the administrator to check, to look for default spaces, etc.

So we need to make it more simple and easier to manage.

### Top User Stories

**"Public" term meaning**

If platform is closed, then programs are not public to anyone, only registered users can see it from actions / programs page.
- programs which the audience is open are listed in those pages as well as actions and leaderboard

If platform is opened AND public site made visible:
- programs which the audience is open are listed as well as actions and leaderboard
- actions page is listed in the topbar (public page) AND leaderboard, actions and programs are listed in the overview page of the website page

**Access to public programs and related actions**

When it comes to try announcing an achievement for a program that is considered "open", then it proposes you to participate. 
_**Public site access case:**_
If not logged in, then you are sent to the login page

_**Access from the platform as logged in user:**_
If not yet member of the space, then you can participate AND you are considered member of that space

### Impacts
- Program / actions
- Space membership

#### Gamification

When a program's audience is an open space, then all user can see the actions. 
By participating to one of the action, then the user is considered member of the space
If the action is automatic, propose to participate when not user yet so the user becomes member of the space.

#### Notifications
NA

#### Analytics
NA

#### Unified Search
Make the "public" action searchable from the unified search even if not member of the audience

### Expected Volume & Performance

The algorithm of programs retrieving will change to retrieve the list of programs where the user is member + (new condition) the program has a Space with Open Registration. To not having to request spaces each time the list of programs are retrieved (lower the performance thus the UX), the Space Registration information has to be duplicated in Programs. this information has to be of type Enum to optimize the storage size (which will not considerably increase considering the number of programs that a platform can have).

### Security 

The endpoints programs, actions and leaderboard endpoints has to be publically accessible and make the access restriction made in Service layer.

### Upgradability

The existing programs has to follow the new business rule where the program becomes publically accessible if the corresponding space audience is Open to registration.

### Feature Flags

No need to feature flags.

### Security

The REST endpoints `gamification/rules`, `gamification/programs` and `gamification/leaderboard/rank/all` to to be publically accessible. The user information has to be retrieved in those endpoints to **not having to expose** publically the endpoint of identities (`v1/social/users`).

### Access 

The portlets `programsOverview`, `challengesOverview` and `topChallengers` has to be reworked to be publically accessible with the 3 endpoints mentioned above only without additional endpoints.

### Services & processing

When updating or creating a program the Program Visibility has to be stored in the program, following Space registration. A space listener has to be implemented to update the visibility each time the space registration is updated.

### Data and persistence

We will have to add in Database Table `GAMIFICATION_DOMAIN` the new field `VISIBILITY` of type `INT` in order to hold the Visibility type: either `OPEN` or `RESTRICTED` enum ordinal value. The default value of enum has to be `RESTRICTED = 0`.

### Migration strategy

The existing programs has to be migrated to hold the value of Space Registration Type.
To do this:
1. The list of spaces will be retrieved from programs list
2. Only OPEN Registration spaces will be filtered
3. Update using one query all programs having as audience one of the OPEN Registration spaces or no audience at all

**Comment by srenault-meeds** [comment]
Open to review @margondicco

**Comment by srenault-meeds** [comment]
Hello @margondicco Can you please take a look at this one?
Thanks

**Comment by margondicco** [comment]
Hello Go fonc :-)

**Comment by boubaker** [comment]
Ready for Tech review by DAO members (eXo: @rdenarie )

**Comment by rdenarie** [comment]
Go tech

**Comment by boubaker** [comment]
The PRs list (**incomplete in MIP Links, due to limitation in github** ):
* https://github.com/Meeds-io/gatein-portal/pull/719
* https://github.com/Meeds-io/platform-ui/pull/706
* https://github.com/Meeds-io/social/pull/3143
* https://github.com/Meeds-io/gamification/pull/1302
* https://github.com/Meeds-io/kudos/pull/420
* https://github.com/Meeds-io/perk-store/pull/289
* https://github.com/Meeds-io/wallet/pull/440
* https://github.com/Meeds-io/task/pull/306
* https://github.com/Meeds-io/app-center/pull/295
* https://github.com/Meeds-io/analytics/pull/154
* https://github.com/Meeds-io/notes/pull/828
* https://github.com/Meeds-io/meeds/pull/1253
* https://github.com/Meeds-io/meeds-qa-ui/pull/213

**Comment by boubaker** [comment]
ACCs and PRs ready for review by DAO members (eXo : @rdenarie )

**PRs are listed** in the comment https://github.com/Meeds-io/MIPs/issues/100#issuecomment-1795371964

(Due to limitation to 10 PRs when linking)

**Comment by boubaker** [comment]
> ACCs and PRs ready for review by DAO members (eXo : @rdenarie )
> 
> **PRs are listed** in the comment [#100 (comment)](https://github.com/Meeds-io/MIPs/issues/100#issuecomment-1795371964)
> 
> (Due to limitation to 10 PRs when linking)

Meeds QA PR added as well.

**Comment by boubaker** [comment]
Added additional issue that is blocked waiting for MIP merge (Meeds-io/meeds#1250)

**Comment by rdenarie** [comment]
All pr approved

**Comment by boubaker** [comment]
> All pr approved

Thanks all PRs merged to develop. I let you define the custom value of properties in eXo side for engagement and myCraft sites until the corresponding MIP is merged into meeds as well.
