### ISSUE TITLE
Meeds Website User journey review

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#102]
## Rationale

The current user journey in the meeds website is not accurate with what we are looking to reach.
As for example, the homepage is more about why meeds is about and leaders or contributors have to dig into the website to understand how to join a hub or how to create a hub.

### Top User Stories

The homepage will be replaced by the current hub explorer with slight UI improvements
A buy page will be created so visitors can create hubs thanks to 3 types of hub creation:
- One month free trial 
- Rental offers
- Buy or Mint a Deed

When requesting for a one month trial, only rental offers proposing a _common_ type of Deed will be provided and this rental will be taken care by the Meeds DAO so the visitor access it freely.
If no _common's_  rental offer, then an invitation to join a waitlist will be provided 

#### Gamification
--

#### Notifications
--

#### Analytics
--

#### Unified Search
--

### Security 

All communicated user information are private and must be protected again any external user acces, which means that those personal informations musn't be communicated via REST endpoints, only in ingestion phase.
Any communicated email has to be validated first (as done in Markeplace forms), which means when the user enter his email, a code has to be sent by email to approve that the user has access to the entered email.

### Feature Flags

No Feature flag is needed

### Security

The same flow as used in Deed Renting for email validation will be used to send the code via email and allow user to enter it in order to validate his email.

### Access & Services & processing

The modifications has to be made in `deeds-dapp` and `deeds-tenant-provisioning` whithout impacting Meeds package.
The UI of users onboarding will be made on `deeds-dapp`.

A new REST endpoint (`/api/trials`) will be needed in order to create a new Demo instance request and to retrieve the available trial instance count.
A sub resource of this same endpoint will be used to POST a new trial request: `/api/trials/contact` This endpoint will receive the user contact information (with valid email code) before storing the user personal information in database.
Another sub resource `/api/trials/available` has to be added to determine the available trial instances.

In each step of the whole process, emails will be sent to user to inform him about the progression of demo instance deployment.
The list of email templates can be management using `deeds-tenant-provisioning` which has already an email template engine.
We will have to enhance the UI to allow adding the management of Trials and the management of Trial email templates as well.
We will not need to automatically disable demo instances or make it available after a certain date. All we can do will be to send email notification to administrators to manually disable demo instance if needed or contact the user to ensure that there is no further delay is needed (to backup data, require a real host ...)

The list of available instances will be computed switch the number of active trials that aren't manually marked as inactive by an administrator on `deeds-tenant-provisioning` UI.

### Data and persistence

A new Elasticsearch Entity (+Repository + Service layer) has to be added with the following attributes:
- Contact information
- Status (Enum for status with possible values = all possible steps of the process)

**Comment by srenault-meeds** [comment]
@margondicco to review please :)

**Comment by margondicco** [comment]
OK for me

**Comment by srenault-meeds** [comment]
ready for tech spec if needed @boubaker

**Comment by boubaker** [comment]
> ready for tech spec if needed @boubaker

Thanks @srenault-meeds . As discussed, I need more information about user journeys to be able to elaborate the technical requirement and to know which parts of the product to change.

**Comment by boubaker** [comment]
Ready to tech review by DAO members (eXo: @rdenarie )

**Comment by boubaker** [comment]
> > ready for tech spec if needed @boubaker
> 
> Thanks @srenault-meeds . As discussed, I need more information about user journeys to be able to elaborate the technical requirement and to know which parts of the product to change.

Done by registered video. Thanks @srenault-meeds

**Comment by boubaker** [comment]
Ready to tech review by DAO members (eXo: @rdenarie )

**Comment by rdenarie** [comment]
Go tech
