### ISSUE TITLE
Overview review

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#104]
## Rationale

After a year of using the overview page, UX needs to be slightly improved:
- Placeholder needs to be reviewed to have consistent display between items
- Labels as well
- End-users'd rather know what actions to do than their achievements, kudos, wallet, etc.

So we suggest a slight review of this page to answer these feedbacks

### Top User Stories

Overview items are reversed so we have in first row, the information of what to do:
<img width="430" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/e3347b12-2584-4dd7-9279-2c460fd46c9e">

When accessing the platform and nothing has been setup yet
Then placeholders are reviewed to be more concise and with better balance between them
<img width="433" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/d98a0271-6d5e-4892-acfd-7f6c7862c2d6">

For weekly achievements portlet, then display the pie-chart as is with no subtitles as currently
<img width="139" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/a7efeab5-2fb9-4900-aeec-57327cf94bf4">

AND when clicking to see all, then display the achievement list of the user in the drawer
<img width="306" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/7abe0d66-f7b7-44d7-a3f7-4fe6d09dd4ba">

When no kudos yet, the same placeholder is displayed in the same place no matter we have badges or not
<img width="143" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/210d4e59-d8b6-4979-ae3c-5c39f66a55a2">

And the contrary as well (kudos but no badges)
<img width="143" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/44f9b844-82f9-4fca-8741-64ab2bb38a03">

And an access to dedicated drawer is proposed for each (kudos creation or badges)
<img width="133" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/a1069780-57b3-4b37-9944-44fe466e7c70">

When no wallet yet, then no need to display the perkstore placeholder
<img width="135" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/27e3739e-b286-4a2c-9971-dc379f78a066">

When wallet init, but no perks, then depending on ability to create, two placeholders are proposed
- When ability to create:
<img width="143" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/12c19a87-5ab7-4946-831c-fae2cb895641">

- When no ability to create:
<img width="137" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/aee2ec62-9a03-4f06-866b-0920513b1e14">

**PRECISION**

Condidering that the overview lists users, we need to make sure that username is not displayed when not logged in. Thus, the URL for avatar of users will be modified to hide the username with an anonymous ID

#### Gamification
Overview gadgets review

#### Notifications
NA 

#### Analytics
NA 

#### Unified Search
NA 

### Upgradability

The Overview page will changed to reorder the portlets. This change will be applied automatically since the import mode is `merge` of `meeds` and `global` sites.

### Feature Flags

No feature flags

### Access 

The UIs has to be enhanced without adding new portlets. (UI modifications only for better UX)

**Comment by srenault-meeds** [comment]
@margondicco can you please check this?
Thanks

**Comment by margondicco** [comment]
Hello Go Fonc
Thanks

**Comment by srenault-meeds** [comment]
Thanks. @boubaker ready for tech spec

**Comment by boubaker** [comment]
Ready for tech review by DAO members ( eXo: @rdenarie )

**Comment by rdenarie** [comment]
Go tech

**Comment by srenault-meeds** [comment]
FYI I have added this to avoid any security breach:

> PRECISION
> 
> Condidering that the overview lists users, we need to make sure that username is not displayed when not logged in. Thus, the URL for avatar of users will be modified to hide the username with an anonymous ID

**Comment by boubaker** [comment]
1. ACCs ready to be reviewed by DAO members (eXo: @rdenarie @margondicco )
2.PRs to develop ready for review by DAO members (eXo: @rdenarie)

- https://github.com/Meeds-io/social/pull/3178
- https://github.com/Meeds-io/gamification/pull/1342
- https://github.com/Meeds-io/kudos/pull/432
- https://github.com/Meeds-io/perk-store/pull/298
- https://github.com/Meeds-io/wallet/pull/450
- https://github.com/Meeds-io/notes/pull/850
- https://github.com/Meeds-io/poll/pull/120
- https://github.com/Meeds-io/task/pull/315
- https://github.com/Meeds-io/gamification-github/pull/128
- https://github.com/Meeds-io/meeds/pull/1295
- https://github.com/Meeds-io/meeds-qa-ui/pull/220

**Comment by boubaker** [comment]
> 1. ACCs ready to be reviewed by DAO members (eXo: @rdenarie @margondicco )
> 2. PRs to develop ready for review by DAO members (eXo: @rdenarie)

Should I help by a video if it's difficult for the review ?

**Comment by rdenarie** [comment]
All pr validated exect meeds one

**Comment by boubaker** [comment]
> All pr validated exect meeds one

Answered, in fact the import mode flags, when defined in `meeds.war` will affect **Meeds Package** only.

**Comment by rdenarie** [comment]
Ok. 
For the portal meeds, we are not impacted. 
Should we do something for our overview page (https://community.exoplatform.com/portal/engage/overview) ?

For group navigation : 
why do you reload all group navigation ? 
Should we do something on our side ? 
What if we do not overwrite theses navigation on exo side ?
Can you confirm that space group navigations are not impacted ?

**Comment by boubaker** [comment]
> For group navigation :
> why do you reload all group navigation ?

We need to delete the navigations that has been deleted by code as well (No UI to do it)

> For group navigation :
> ...
> Should we do something on our side ?

For group navigations no, because the MIP #88 will delete them anyway and will replace them by a site.
> [!IMPORTANT]
> For public site, yes, you will need to reimport the pages using the flag `io.meeds.public.portalConfig.metadata.importmode=OVERWRITE` **only once** (Delete flag once restarted) + re-publish manually on Tribe the public site once server restarted.

> For group navigation :
> ...
> What if we do not overwrite theses navigation on exo side ?

No need to them anymore since the group navigations aren't defined in group sites anymore with MIP #88 

---

> [!IMPORTANT]
> What will remain to reimport from sources on your side, will be the **overview/Participate** page. All of this will be enhanced (for pages upgrade) after fixing the Enhancement issue https://github.com/Meeds-io/meeds/issues/1307

**Comment by boubaker** [comment]
I let you review the PR again if this answers your questions.

**Comment by rdenarie** [comment]
al lpr validated

**Comment by rdenarie** [comment]
Can you ping me when all merged (for rebase) ?

**Comment by boubaker** [comment]
> al lpr validated

Thanks, all PRs merged
