### ISSUE TITLE
Automated Actions Parameters

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#105]
## Rationale

We have built-in connectors and we aim to provide more and more connectors to our users.
 
Yet, now that we are about to finish the Twitter connector implementation, it is time to take a step back.
 
Indeed, a review of the action creation drawer is needed so our Program Owners can create the automatic flow they need. That means, that depending on the event, they will be able to clearly identify which action will be gamified.
 
### Top User Stories

**Creation / update of a manual action**

No change for this case.

**Creation / update of an automatic action**

Given the program owner chooses to add an automatic action, then a second step is added called "Create the automatic flow" so he can detail the use case as he wants:

1. The application needs to be chosen. In case, no connector is configured but the Meeds one, then events selection is proposed directly
<img width="186" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/a2ad30de-1a9e-4b60-870f-4e12048cf5ad">

2. Once the application is chosen, the program owner will have to precise the event. Depending on the case, additional options can be requested. Here are examples:

- Send a kudos (meeds) / Set your profile avatar (meeds) > No additional detail requested
<img width="187" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/a93293d1-09f1-415f-b198-ec6918f3a115">

- Create a task (meeds) > Ability to add the link of the project OR to choose any project (if rewarding admin)
<img width="196" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/d5b2a3f7-6192-43db-8b0a-dfa94727a4d8">

- Like an activity (meeds) 
-> Need to choose the space > then add the link of the activity or any activity of that space
-> Can choose any space (if reward admin) > then any like to any activity will be considered
<img width="187" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/c1689643-78d7-4ca1-b0c3-5113ae6906e3">

- Mention an account (X) > Remind the account enabled to be watched and if more than one, then list choices so the user can identify it
<img width="188" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/e872993e-df04-4376-8e33-246b72a64279">

- Like a tweet (X) OR Repost a tweet (X) > Tweet link (no ability to check "Any" as it requests to have a bigger plan so in order to avoid losing request credits, we limit the search to one tweet AND no use case interesting to gamify any like to any tweet) -> A check is done if this tweet is related to a configured account to be watched
<img width="188" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/2322df01-2e96-4929-9604-67b42c66c295">

- Create a Pull Request (GitHub) > Organization to select (if more than one set) > Repository selection upon permissions set from admin (or any if reward admin)
- Create an issue (GitHub) >  Organization to select (if more than one set) > Repository selection upon permissions set from admin (or any if reward admin) > Project to select 
<img width="187" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/d907e9ba-8aba-4ada-b272-ad1f92d977d2">

4. Once the second step of the creation of an automatic action is completed, the program owner can decide in the third step:
- if the action should be announced in the audience
- how achievement can be announced (by default, it is disabled) for an additional check when needed
- conditions to achieve (duration, recurrence, action)

<img width="185" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/216fe5a1-9f7a-4e21-a26c-3444970f274f">

#### Gamification
Update of action creation / update drawer

#### Notifications
NA

#### Analytics
NA

#### Unified Search
NA

### Security 
NA

### Extensibility 
* A program owner has to be provided to manage creation and update automatic action and its details (application, space, entityId ...). 
* Each connector has to be able to add specific settings for events inside the action drawer UI.
* Each trigger has to be able to add specific settings inside the action drawer UI.

### Configurability 
NA

### Upgradability
* An upgrade has to be made for rules to use eventId instead of the event title.

### Existing Features
NA

### Feature Flags

No feature flag is needed.

### Security
NA

### REST endpoints
 REST endpoint has to be added to serve new assets:
* `/gamification/triggers`: this will allow to retrieve configured triggers switch installed addons. (Readonly listing)

### Access UI
* Action drawer UIs have to be extensible (injected using extensionRegistry) so that it prepares integration with each connector.

### Data and persistence
There is no need to add a new table or column, all event specifications will be stored in the already existing table `GAMIFICATION_EVENT_SETTINGS`

**Comment by srenault-meeds** [comment]
@margondicco Please can you review it? Thanks
Additional explaination available here: https://builders.meeds.io/portal/meeds/activity?id=7163

**Comment by margondicco** [comment]
Hello Go Fonc

**Comment by srenault-meeds** [comment]
Thanks. Ready for tech spec @AzmiTouil cc @boubaker

**Comment by boubaker** [comment]
Thanks @AzmiTouil.

Ready for tech review by DAO members (eXo : @rdenarie )

**Comment by rdenarie** [comment]
go tech

**Comment by plamarque** [comment]
Renamed MIP to be more descriptive.
This filter is about enabling automated actions to have extra params in order to capture more granular events.

**Comment by AzmiTouil** [comment]
ACC and PRs ready for review by the DAO members (cc @rdenarie ) [(Connector documentation)](https://builders.meeds.io/portal/g/:spaces:developers/developers/notes/394)
NB: the **exoplatform** connector must have an extension as a default connector to be displayed in the administration interfaces and list its events.

**Comment by rdenarie** [comment]
Hello @AzmiTouil 
Can you add more detail and example (the meeds example) about what I need to do for the 'exoplatform' connector ?

In addition, as I can see, modifications are not present in https://exo-mips-ft.meeds.io/

**Comment by AzmiTouil** [comment]
Hello @rdenarie 
yes, an extension for the **exoplatform** connector to define the image/icon, description, and if it's a default connector.
meeds extension : 
```
extensionRegistry.registerExtension('engagementCenterConnectors', 'connector-extensions', {
  id: 'meeds',
  name: 'meeds',
  image: '/gamification-portlets/images/connector/meeds.svg',
  title: 'Meeds',
  description: 'gamification.admin.meeds.label.description',
  defaultConnector: true,
  rank: 10
});
```
Acceptance up to date!

**Comment by rdenarie** [comment]
thanks for the example, have you a url of this code in meeds module ? 
thanks

**Comment by srenault-meeds** [comment]
@rdenarie I think that you can check this documentation
https://builders.meeds.io/portal/g/:spaces:developers/developers/notes/394

In the meantime, I have found that you have some css overlap to check in the eXo-mips. Indeed, something is not ok in the action drawer. See below:
<img width="327" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/29c72e78-fec3-41d9-a8d2-76c7fcb03e14">

**Comment by AzmiTouil** [comment]
https://github.com/Meeds-io/gamification/blob/develop/portlets/src/main/webapp/vue-app/connectors-extensions/extensions.js#L19.
For more detail about connector [(Connector documentation)](https://builders.meeds.io/portal/g/:spaces:developers/developers/notes/394)
Thanks.

**Comment by rdenarie** [comment]
Hello
On connecteurs page in administration there is a js error :
![image](https://github.com/Meeds-io/MIPs/assets/807839/519b534d-f66d-44ef-bd76-6722f59ce3f6)
It is present on both acc.

I'm not sure it is related to this development.

Can you check on your side ? If it is related, it should be fixed I think
If  it is not related, you can proceed to merge

Thanks

**Comment by AzmiTouil** [comment]
> Hello On connecteurs page in administration there is a js error : ![image](https://private-user-images.githubusercontent.com/807839/310061897-519b534d-f66d-44ef-bd76-6722f59ce3f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mzc2MjEsIm5iZiI6MTcwOTYzNzMyMSwicGF0aCI6Ii84MDc4MzkvMzEwMDYxODk3LTUxOWI1MzRkLWY2NmQtNDRlZi1iZDc2LTY3MjJmNTljZTNmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMTE1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTg3YTk1N2UyNDZlMzNhZDE3YjQzZWJiMjMwOGJiMDMzYzE5ZDRkZDEzYjUwYzNiNWM1YmQ5ZmJkMzIyMzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ape1UGo6Sodu2cEz6RzuB1WSw7TWSbWMqMm6JjiBWHI) It is present on both acc.
> 
> I'm not sure it is related to this development.
> 
> Can you check on your side ? If it is related, it should be fixed I think If it is not related, you can proceed to merge
> 
> Thanks

Hello @rdenarie 
Yes, it's related to this MIP.
Fix added to gamification PR!

Thanks

**Comment by rdenarie** [comment]
ok, then you can proceed to merge.
