### ISSUE TITLE
Connect Hub to the WoM

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#106]
## Rationale

In order to be listed in the Hubs explorer AND to participate to the UEM (aka Mintium rewards), Hubs need a way to connect to the WoM. It means to reference a Deed they use.

It must be done "automatically" when starting a hub (AKA moving in) from the holders dApp.

It should be doable from the Hub when the server was not provisioned through the "Move In" feature of the dApp.

Also, it should be possible to change the Deed through which a Hub is connected to the WoM.

#### Case 1: Connection from the Hub when not done yet

From the Hub itself, a platform admin can access a menu from Platform Settings > Recognition

<img width="419" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/a84b1b9f-62fe-4d32-b310-134897ffda13">

**_Prerequisite to see the connection:_** 
- confirm the ethereum account to use by signing a message with Metamask (so we check in addition to the admin role if the user has access to the wallet that owns the Deed NFT)
- with the ability to switch to another Ethereum account in Metamask if needed

<img width="287" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/2d7d1146-cf3d-473a-92d1-d089b707ed8e">

**_Once the wallet is connected, then list Deed NFTs that the Ethereum account owns or rents (lease)_** 
- If no Deed, then suggest to get one through the offers page on meeds.io (link to it)
- If a Deed is found, then list only the ones that are ready to use (not used nor currently under lease) 

Each Deed  that is available and then listed will be introduced with the following characteristics:
- Owned or Rent 
- Lease end date (if rent)
- Minting power
- Deed ticker
- User limit

<img width="251" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/dd335141-1831-4088-80da-73850d2a9516">

**_Validation of the connection_** 
Once the Deed NFT is chosen, the admin is informed that:
- From now on, the Hub is connected to the WoM 
- It is thus listed in the Hub Explorer (with a link and/or a card preview)
- It's ready to participate to the Mintium

The Hub's card is initialized from the Hubs data as follows:
- logo = branding logo
- banner = primary color OR banner added in the public site
- name = branding name
- description = abstract of the one added in the public site

And other pieces of information will be added to the card based the Hub status:
- NFT ID ticker [deed logo] [number of the NFT ex. '# 22']
- If no reward has been sent yet, then "getting started"
- If rewards were sent, then active users + rewards sent ATM the reward has been sent

<img width="247" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/84c9a6b8-5f33-4df0-9ffb-8d4477da2501">

#### Case 2: Connection from the dApp when moving in

From the dApp, user can rent or acquire a Deed.
Once he requests to move in, the new hub that will be started must be automatically connected to the WoM. This way, the admin doesn't need to do additional action to connect its hub to the WoM.

**In case the user is wondering how to connect to the WoM, the user can access a user guide to know how to**

#### Case 3: Update of the connection

In case you already have associated your Hub to a Deed, then you can decide to update it in order to benefit from different minting power or user limit, or to use a different lease.

Indeed, this can be useful when:
- The community is getting more and more active so an upgrade to a bigger Deed is needed (from Common to Uncommon for example)
- The community is losing activity but you want it to be still listed so a downgrade to a lesser Deed can be done (From Legendary to Rare for example)

So from the same menu, the admin (after signing a message in Metamask to authenticate) will be able to edit the connection and choose another Deed NFT.
In case you have Deeds available to use in another wallet, then you can easily switch to another blockchain account in Metamask and lead the Deeds and leases of this account

<img width="288" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/4dd2a73e-15be-46fc-8edf-4aa2093a0c66">

-> If the hub is no more connected to the WoM (end of lease for example), then a notification is sent to the admin that sends the user to this display:

<img width="241" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/6578dcd9-d21e-4114-b3f4-cf0d666687e3">

#### Gamification
NA

#### Notifications
Notification when the hub is no more connected to WoM (end of lease for example)

#### Analytics
Collect informations from hub to hub card (users, actions, rewards sent)

#### Unified Search
NA

### Expected Volume & Performance

This feature shouldn't affect global performance of all applications of the Hub since this feature shouldn't be part of the applications business logic flows.

### Security 

The Meeds Product security model shouldn't be affected. Whereas, this new Feature should follow the following security Model:
1. Only Deed NFT Host (the renter if exists else the owner) can attach a deed to a new Community
2. Once a community is created by a Deed renter or a Deed owner, the community will be owned by the creator wallet
3. Only Community owner (first wallet having requested to start a Deed) should be able to update related Deed NFT to a Hub
4. A Community owner can transfer ownership to 0x wallet so that current Deed Host will acquire the priviledge to change the associated Deed NFT to the community or can as well transfer it to a dedicated wallet
5. Each community has to be identified by a dedicated wallet address to be identified in the WoM.

### Extensibility 
N/A

### Configurability 

By default the `deeds-tenant` addon has to be installed in Meeds Package. This will allow anyone acquiring the Meeds package to connect its Hub, hosted by Association or in an owned infrastructure, to connect the Hub into the WoM.

### Upgradability
N/A

### Existing Features
N/A

### Feature Flags
N/A

### Other Non Functional Requirements
N/A

### Security

Knowing that the Deed NFT is managed in Ethereum Blockchain and that the WoM will be deployed on Polygon Blockchain, a centralized server will be used to allow bridging between both to submit any change on the WoM which will have to make the security checks before changing the WoM Hubs. Thus, any Hub connection to the WoM or modification of the Hub characteristics will be submitted through this server (wom.meeds.io) which will have to copy associated Deed NFT charcateristics from Ethereum Blockchain to Polygon Blockchain.

### Access

The WoM Connection application will be part of the `deeds-tenant` addon which have to be part of the Meeds Product by default.
This configuration has to be injected in Recognition Setup Portlet through `extensionRegistry` as made for Kudos, Wallet and Perks.

### Services & processing

The following picture shows the used flow to Join the WoM by a Hub Owner:
![UEM-Software-Architecture-SequenceDiagramV2-Connect To WoM](https://github.com/Meeds-io/MIPs/assets/594824/32cfe31b-844a-448f-af7f-31d3a44a5ee0)

A subset of information sent will be added into Polygon Blockchain such as:
- Hub Address
- Used Deed NFT Id

The other information will be stored in WoM Centralized Server only in order to optimize Gas Fees. Those information, (such as URL, Desciption, Name and Color) will be used to display the Hub characteristics in Hubs Explorer under https://www.meeds.io/hub.

### Data and persistence

The WoM contract will be deployed on Polygon Blockchain and will hold the following list of information

![image](https://github.com/Meeds-io/MIPs/assets/594824/ddb560e6-1131-4e8d-8f7d-3e0ed69d1680)
![image](https://github.com/Meeds-io/MIPs/assets/594824/8f74947d-fef7-44a8-a6c0-a8f86a401fee)
![image](https://github.com/Meeds-io/MIPs/assets/594824/724691b2-261d-4c98-90c6-2c72b84055f5)

- nfts: The Bridged Deeds NFT with their characteristics using the auto updated NFT Tenant & Owner from Ethereum Deed Contracts to the WoM Contract on Polygon.
- hubs: a list of hubs with their associated Deed NFTs. The Hub owner is transferable using a dedicated method by the first creator of the Hub. If the Hub Owner is a Deed Manager and then looses privileges on the Deed, it will remain the Hub Owner and can transfer it if wanted to. Same flow is possible too when the Hub Owner is the Deed Owner.

**Comment by plamarque** [comment]
@srenault-meeds updated with quite a few changes. Pease review fully.

**Comment by srenault-meeds** [comment]
Done! thanks for your update and proposition

**Comment by srenault-meeds** [comment]
Hi @margondicco Can you check please?
Feedbacks are welcome

Thanks

**Comment by margondicco** [comment]
Hello very complete and no question :-)

**Comment by plamarque** [comment]
reviewed functional requirements one more time : LGTM

**Comment by boubaker** [comment]
Ready for tech spec review by DAO members ( eXo: @rdenarie )

**Comment by rdenarie** [comment]
Go tech

**Comment by boubaker** [comment]
Technical design has been updated to make the WoM connection more decentralized.

**Comment by margondicco** [comment]
Go Fonc for me

**Comment by boubaker** [comment]
> Go Fonc for me

Sorry, we had already a Go-Func & Go-tech for this MIP. You may want to give a Go-func on #58 may be ?

**Comment by margondicco** [comment]
> > Go Fonc for me
> 
> Sorry, we had already a Go-Func & Go-tech for this MIP. You may want to give a Go-func on #58 may be ?

sorry and thank you

**Comment by boubaker** [comment]
ACC & PRs ready to review ( eXo : @rdenarie )

**Comment by rdenarie** [comment]
Hello,
You can proceed to the merge.

**Comment by boubaker** [comment]
> Hello, You can proceed to the merge.

Thanks, merged to develop
