### ISSUE TITLE
Add link to text

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#107]
## Rationale

Currently, when you post a message, a comment, and you want to share a link, you have no way to insert this link into a text in order to make it nicer.
Example:
<img width="610" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/49d2b4b2-9a83-49af-9ed9-0a67f5b1316b">

Suggestion: allow user to select a content, then add link to it so that:
- message is nicer
- readers can see it is a hyperlink text

Alternative: any editor provides nowadays options to add link into a content

### Top User Stories

When writing a message (activity, comment, kudos, task comment, action) OR when writing a note, a SNV, 
Then I can select a text so a balloon toolbar proposes me to add a link
<img width="354" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/552a1074-9c6e-4bf9-a2a6-10b7ff039f43">

When doing so, I can insert the link
<img width="352" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/ec5e678f-94e2-46a3-8ce8-64fe03be4930">

Once done, when clicking to it while editing, the toolbar suggests me to edit or to remove the link.
<img width="350" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/74ee8a14-7c79-431b-b590-c080320e06b0">

**Precision**
To study: add other options in the balloon toolbar to quickly make the text bold or italic (still quicker than clicking to the editor toolbar)

### Security 

Generated links must be secure and don't allow **XSS attacks**.

### Extensibility 

This plugin has to be proposed as an extension but not defined by default in all RicheEditor instances.

### Feature Flags

No feature flag is needed.

### Access 

The CKEditor plugin [Balloon Toolbar](https://ckeditor.com/docs/ckeditor4/latest/features/balloontoolbar.html) should be used. This plugin will require a customization to integrate desired buttons into it.
This feature has to be part of `RichEditor.vue` to be able to enable it when needed in all existing rich editor instances.

**Comment by srenault-meeds** [comment]
To check please @margondicco

**Comment by margondicco** [comment]
Hello Go Fonc

**Comment by srenault-meeds** [comment]
Thanks. Ready for tech spec writing  @boubaker

**Comment by boubaker** [comment]
> Thanks. Ready for tech spec writing @boubaker

ok, thanks.

**Comment by boubaker** [comment]
Ready for spec Review by DAO Members (eXo : @rdenarie )

**Comment by rdenarie** [comment]
ok for me go tech

**Comment by boubaker** [comment]
Ready for Review with ACCs Up & Running.

**Comment by rdenarie** [comment]
Hello
@SaraBoutej Can you link PRs in this MIPs ? 
You can use the right column : 


![Image](https://github.com/Meeds-io/MIPs/assets/807839/fb607ca7-3f9d-44b2-81aa-95239fba1b8b)


Or add a comment listing PRs. 

It make it easier to be sure that all PRs are validated.

I just validate 2 prs (social and commons), but I'm not sure it is the only 2 ones

**Comment by boubaker** [comment]
> @SaraBoutej Can you link PRs in this MIPs ?

Done, boths PRs seems reviewed. Thanks.
