### ISSUE TITLE
Quick Search on Profile Attributes

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/MIPs#110]
# Rationale
Make the profile more useful and allow a quicker search experience based on contact information. 

# 1. Functional requirements
## Profile user quick search
On the user profile, we can do a quick search by clicking on the value of the contact information except for:

- full name
- first name
- email
- phone
- social network
- URL

A drawer with the integration of the people page component in mobile

- Filter by name: only filter by name should remain
- Advanced filter must be deactivated
- Quick filter must be deactivated

- Expand drawer: we display the people list component on the full page with the card as displayed in the people page.

- Complementary filters: based on the information included in the profiles of the people of the results and the profile complementary filters are automatically proposed
  - Rule: 
     - if one of the users of the results has a value of its contact information that matches one of the visited profiles then it's proposed
     - if no match no complementary filters displayed

## People page improvements
- Integration of the application top bar component to replace the top bar of the people page (filters)
- UI modification of the mobile view
   - reduce the size of the avatar
   - if no the field "function" is empty, nothing is displayed and the name is aligned with the avatar
- New order of actions menu
   - Kudos
   - Connect

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/90668168-d93f-41e4-8d0c-6ef66ddd21ff)

# 2. NonFunctional Requirements
## Expected volume & Performance requirements
Security requirements (Authentication, Authorizations, Audit track / traceability, data retention…)
No additional requirements, this will integrate an existing application and inherit its security requirements

## Extensibility requirements (Identified extension points, plugables implementations...)
 - All unsearchable fields will be added to an array in the frontend application
 
## Configurability requirements (properties introduced, default settings, jobs, etc...)
No specific configuration is required

## Requirements related to existing users data
Application will use existing user data and won't alter it

## Requirements related to existing features (ex: Add a button to existing modules...)
In the quick search feature, we will :
 - Add an  event to make searchable fields clickable
 - This event will start a search based on the selected field and the clicked value
 - This will open a drawer with the list of users having the same UI as the Mobile view of cards in the people page 
 - The compact cards will have the same information and actions available as in People card
**Added section 1**
In the quick search results drawer we will:
 - Propose a list of complementary filters based on common values of attributes in the profiles of the resulted user list
 - When clicking on a complementary filter, the returned list of users is filtered based on the clicked criteria/combination of criteria
**End Added section 1**

## Feature Flag (property name, default status, target audience, functional behaviour)
No feature flag will be added

# Other NFR (ex: Use of VueX, Vue, Vuetify)
N/A

# 3. Impacts
Documentation to update?
Training level / Change management needs

# 4.  Software Architecture
## Security
security will be inherited from existing application

## Access (GUI, API…)
Access will be inherited

## Rest API design (Entry points, domain objects)
 - No need to add a REST endpoint
**Added section 2**
 - We will add a dedicated Rest endpoint for the complementary fields, to avoid latency on search results and make it possible to disable the functionality if needed
   - When the search is performed, another request will be sent to fetch the possible complementary filters
   - When complementary filter request is fulfilled, they will appear on top of the search results with the dedicated animation
   - To request the complementary filters, we will use the Elatic search aggregations. We will add as needed aggregation as the active & displayed fields in the user profile. This will exclude just the fields : "full name" "first name" "email" "phone" "social network" "URL"
     Here is an exemple of the aggregation to use for generating the complementary filters :
     ```
     {
	  "size": 0,
	  "query": {
		"terms": {
		  "_id": ["10003","10004","100005","10007","10008"]  
		}
	  },
	  "aggs": {
		"common_professions": { 
		  "terms": {
			"field": "profession.keyword",
			"min_doc_count": 2,
			"size": 10
		  }
		},
		"common_cities": { 
		  "terms": {
			"field": "city.keyword",
			"min_doc_count": 2,
			"size": 10
		  }
		},
		"common_teams": { 
		  "terms": {
			"field": "city.team",
			"min_doc_count": 2,
			"size": 10
		  }
          }
        }
      }

     ```
 **Added section 2**
## Portlet Vue & Vuetify, simple portlet, extension WAR ...
 - Fields will be changed in the existing user profile application to make their values clickable
 - A drawer will be added to list the search results
 - Search results will use the compact People card item component when the drawer by default, and will use the full people card item when the drawer is expanded
**Added section 3**
 - A dedicated Vue component will be added to represent each complementary filter
  - The field will be initiated with all the current search criteria and has the complementary filter as value.
  - The field should take the Profile index as parameter to be reused if needed in other search contexts (documents, tasks, etc ...)
**Added section 3** 

## Services & processing
Ex: Scheduled Jobs
 - Existing services will be used

## Data and persistence
Macro data model
N/A

## Persistence layer (RDBMS, elasticsearch...)
N/A

## 5. Annexes
Reasoning that explain the technical choices
Impacts (ex: impact on public REST/Java API)
References (links...)

**Comment by rdenarie** [comment]
@srenault-meeds can you check for go-fonc ?
Thanks

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds I need to do some modifications before go-fonc.

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds could you check for go-fonc, please? 
@ahamdi could you complete the tech part, please?

**Comment by srenault-meeds** [comment]
Thanks @Julien-Dubois-eXo 
Can you detail more the rationale please? Indeed, we don't the problem you are trying to solve.

> On the user profile, we can do a quick search by clicking on the value of the contact information.

Any attribute or only few of them?

> Filter by name: only filter by name should remain
Advanced filter should be deactivated
Quick filter should be deactivated

Not "should" but "must" IMO

> Expand drawer: we display the people list component on the full page.

Do you mean that the people page with card is displayed when expanding the view?

+ can you please add screenshots for better understanding?

**Comment by Julien-Dubois-eXo** [comment]
MIP edited to answer the questions. 

> Do you mean that the people page with card is displayed when expanding the view?
Yes.

**Comment by srenault-meeds** [comment]
Ok thanks.

> can you please add screenshots for better understanding?

**Comment by srenault-meeds** [comment]
Hello, I can see this has begun. No problem for me. However, I have heard that the design needed to be reviewed to match your expectations. Thus, can you please attach a screenshot to confirm the final view of the quick search drawer?
Thanks

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds I have edited the design and add a screenshot. Maybe the alignments are not perfect.  I'm not sure about the +4 but we could discuss it.

**Comment by margondicco** [comment]
@rdenarie @boubaker tech review needed.

**Comment by boubaker** [comment]
> @rdenarie @boubaker tech review needed.

**Comment by boubaker** [comment]
> @rdenarie @boubaker tech review needed.

A go func is needed first IMO. @srenault-meeds

**Comment by srenault-meeds** [comment]
> I have edited the design and add a screenshot. 

Here is my proposition to avoid losing space at the top of the drawer
![People drawer when quick searching](https://github.com/Meeds-io/MIPs/assets/58853195/cbc8443c-e42a-4bf5-9112-74a7d9a5652a)

Please, confirm it 

> I'm not sure about the +4 but we could discuss it.

It is ok for me but it misses a second level drawer which is a list of combinations in a drawer with a arrow-left to go back to main drawer
No blocker for me

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds I'm not a big fan. It's unclear to me that you could click a second time to display the filter by name. 

We could just remove the sentence "Try these others combination" to directly display the "filter by name" field. 

If we put these filters here does it mean it should be in the application top bar component? 

You are right about the drawer, it's just my Adobe xd skill that blocks me from being fast in making it. I will try to make it but not sure to success.

**Comment by srenault-meeds** [comment]
like that?
![people quick search](https://github.com/Meeds-io/MIPs/assets/58853195/279964b4-ba05-4f88-a2b1-4c86e1eb60a5)

**Comment by srenault-meeds** [comment]
Ok Go-Func

Precision discussed:
If no combinations, then no text before filter icon
If combination, then text to introduce these combinations
Ok in the description

**Comment by boubaker** [comment]
Go-tech added

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds @boubaker I confirm you we will implement: 

`Complementary filters: based on the information included in the profiles of the people of the results and the profile complementary filters are automatically proposed

Rule:
if one of the users of the results has a value of its contact information that matches one of the visited profiles then it's proposed
if no match no complementary filters displayed`

@ahamdi will provide a technical specification in the days coming.

**Comment by ahamdi** [comment]
@boubaker @rdenarie I've added three sections in the specification about how we will generate the complementary filters, they are annotated with **Added section X** and **End Added section X**
Thank you

**Comment by rdenarie** [comment]
@boubaker can you confirm the go tech after @ahamdi technical additions

**Comment by boubaker** [comment]
> @boubaker can you confirm the go tech after @ahamdi technical additions

Yes, it was already added 3 weeks ago. No change about it and I 've no objections with modifications made.

**Comment by ahamdi** [comment]
> > @boubaker can you confirm the go tech after @ahamdi technical additions
> 
> Yes, it was already added 3 weeks ago. No change about it and I 've no objections with modifications made.

thanks @boubaker

**Comment by ahamdi** [comment]
PRs ready and acceptance is up with latest changes
ready to review by Meeds DAO members @boubaker

**Comment by margondicco** [comment]
@Julien-Dubois-eXo please, could you push a functional information for @srenault-meeds  ? thank you

**Comment by boubaker** [comment]
> PRs ready and acceptance is up with latest changes ready to review by Meeds DAO members @boubaker

Thanks, can you please link PRs

**Comment by srenault-meeds** [comment]
Yes we need some information so we post a new product update to inform our users and customers (they are on CI/CD)

**Comment by srenault-meeds** [comment]
Hello, 

FYI no delivery for now until we have the functional information.
Thanks

**Comment by srenault-meeds** [comment]
Hi,

I have some feedbacks regarding the feature.

1. Click to a field, then it opens the drawer -> no functional.
> Indeed, I have clicked to a position and in the list I have profiles with other positions listed
<img width="698" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/8f1fcf0f-d689-4a36-ae80-e4dc60fbfcc2">

2. Bad horizontal alignement for (+xx) 
<img width="249" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/aede29cd-e8b9-4dfa-977e-de3c6eb6cdd4">

3. Bad vertical alignement for other combination
<img width="308" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/46669067-a62e-4559-8f8e-fece0d4d110a">

4. UI glitch for label "try with other combinations"
<img width="292" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/46cd656f-805a-4a00-8522-050d5a0fc96a">

5. No FR labels for header and try with other combination

6. When using multiple additional filters, it sometimes display a placeholder with no way to cancel. And then the filters is not ok, I need to reload the page

7. I can't click to position label from the drawer while hand cursor is suggested.

8. We miss the behaviour when clicking to a user (was ok in people mobile view) 
> Same for mobile view or in quick search drawer

Thanks.

**Comment by srenault-meeds** [comment]
@Julien-Dubois-eXo to help you decide, here are the blocker items to accept MIP delivery:

> 1. Click to a field, then it opens the drawer -> no functional.
> Indeed, I have clicked to a position and in the list I have profiles with other positions listed
> 
> 6. When using multiple additional filters, it sometimes display a placeholder with no way to cancel. And then the filters is not ok, I need to reload the page

Of course, other items can be fixed once it is delivered

**Comment by ahamdi** [comment]
@srenault-meeds Mips acceptance was redeployed with latest fixes. Ready to review

**Comment by srenault-meeds** [comment]
Ok for me. No blocker for me and as discussed, remaining feedbacks will be managed later by your team.

I'll report issues to be managed as discussed. Remaining feedbacks are:
> Click to a field, then it opens the drawer -> no functional.
Indeed, I have clicked to a position and in the list I don't have expected profile. it seems indexation of position is not ok (users have been imported with a .csv file)
![people search](https://github.com/Meeds-io/MIPs/assets/58853195/1e576093-ad63-47b1-89f9-41483178d0a7)

> Bad vertical alignement for other combination

> When using multiple additional filters, it display a placeholder OK but when clicking to reset, it doesn't list the default search

cc @margondicco FYI

**Comment by margondicco** [comment]
@Julien-Dubois-eXo please could you capture these feedbacks ? Thank you

**Comment by boubaker** [comment]
> Ok for me. No blocker for me and as discussed, remaining feedbacks will be managed later by your team.

For my part, no objection to merge MIPs (no need to review PRs to merge BTW)
