### ISSUE TITLE
Breakpoints review (css)

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#113]
## Rationale

No Breakpoint System is precisely identified in the product.

Thus, we have at least 2 Problems:
- Breakpoints identified in the product are not consistent with the modern UX guidelines. An update is needed
- Breakpoints are not consistent between JS and CSS

## 1. Functional Requirements

Breakpoints list is identified as follow:

| ID | Device | Type | Screen Size | 
| -- | -------- | ----- | ------------ | 
| xs | Extra small | Small to large phone | < 600px | 
| sm | Small | Small to medium tablet | 600px > < 960px | 
| md | Medium | Large tablet to laptop | 960px > < 1264px* | 
| l | Large | Desktop | 1264px > < 1904px* | 
| xl | Extra large | 4k and ultra-wide | > 1904px* | 

_*-16px on desktop for browser scrollbar_

### Impacts
Check any page to see if impacts to be updated

#### Gamification
NA

#### Notifications
NA

#### Analytics
NA

#### Unified Search
NA

### Existing Features

The existing Features and classes shouldn't change, thus no Upgrade should be necessary to adopt new breakpoints.

### Feature Flags

No feature flags is necessary

### Access 

The [Javascript Breackpoints](https://github.com/Meeds-io/social/blob/develop/webapp/portlet/src/main/webapp/groovy/social/webui/UISocialPortalApplicationHead.gtmpl#L57-L61) are defined to use the following breakpoints:

```javascript
         thresholds: {
           xs: 768,
           sm: 980,
           md: 1024,
           lg: 1280,
           xl: 1700,
         },
```
It should be changed to use the new ones:

```javascript
         thresholds: {
           xs: 0,
           sm: 600,
           md: 960,
           lg: 1264,
           xl: 1904,
         },
```

The same adaptation has to be made in CSS in [variables.less](https://github.com/Meeds-io/platform-ui/blob/develop/platform-ui-skin/src/main/webapp/skin/less/variables.less#L421-L430) :

```less
@smallMobileWidth: 380px;
@maxMobileWidth: 767px;
@minTabletWidth: (@maxMobileWidth + 1px);
@maxTabletWidth: 979px;
@minLargeTabletWidth: (@maxTabletWidth + 1px);
@maxLargeTabletWidth: 1023px;
@minDesktop: (@maxLargeTabletWidth + 1px);
@maxDesktop: 1279px;
@minLargeDesktop: (@maxDesktop + 1px);
@maxLargeDesktop: 1700px;
```

To be updated by

```less
@smallMobileWidth: 380px;
@maxMobileWidth: 599.98px;
@minTabletWidth: (@maxMobileWidth + 0.02px);
@maxTabletWidth: 959.98px;
@minLargeTabletWidth: (@maxTabletWidth + 0.02px);
@maxLargeTabletWidth: 1263.98px;
@minDesktop: (@maxLargeTabletWidth + 0.02px);
@maxDesktop: 1903.98px;
@minLargeDesktop: (@maxDesktop + 0.02px);
```

Those variables has to be used consequently in [vuetify.less](https://github.com/Meeds-io/platform-ui/blob/develop/platform-ui-skin/src/main/webapp/skin/less/vuetify/lib/vuetify.less) in order to harmonize the display wheter when using Javascript or CSS.

**Comment by srenault-meeds** [comment]
@margondicco Can you check please?

**Comment by srenault-meeds** [comment]
@margondicco after internal discussion, I removed the layout columns as this MIP is only about updating CSS

**Comment by margondicco** [comment]
GO FONC

**Comment by srenault-meeds** [comment]
Thanks. @boubaker ready for tech spec :)

**Comment by boubaker** [comment]
> Thanks. [@boubaker](https://github.com/boubaker) ready for tech spec :)

Thanks

**Comment by boubaker** [comment]
Ready for tech review by DAO Members (eXo : @rdenarie )

**Comment by rdenarie** [comment]
Go tech

**Comment by SaraBoutej** [comment]
ACC and PRs ready for review by the DAO members (cc @rdenarie )

**Comment by rdenarie** [comment]
Hello,
I'm afraid there is a problem on people page 
![image](https://github.com/Meeds-io/MIPs/assets/807839/b86baf73-e84f-4969-8e0c-b9f226d4ff01)
This is visible on mips-ft and exo-mips-ft instance

I think it would be preferable to fix it in this mip if it is related.
wdyt @boubaker ?

**Comment by rdenarie** [comment]
The rest seems ok for me

**Comment by boubaker** [comment]
> I think it would be preferable to fix it in this mip if it is related. wdyt @boubaker ?

It's due to the fact that there are some changes made in Meeds-io/MIPs#110 which is added into MIPs branch as well.

**Comment by boubaker** [comment]
BTW, the Meeds-io/MIPs#110 is still with Dev In Progress status:

![image](https://github.com/Meeds-io/MIPs/assets/594824/36097cea-38ac-40be-82ba-6aa931b3b491)

Should we remove the commits and then proceed to current MIP merge, then let the process continue on Meeds-io/MIPs#110 when it's ready ? @rdenarie

**Comment by ahamdi** [comment]
@boubaker I am adapting the code of #110 with the changes added to the #113
If I am unable to provide the fix tomorrow morning, I am ok to remove the commits of #110, we will add them after the merge of the current MIP is done. WDYT ?

**Comment by boubaker** [comment]
> @boubaker I am adapting the code of #110 with the changes added to the #113 If I am unable to provide the fix tomorrow morning, I am ok to remove the commits of #110, we will add them after the merge of the current MIP is done. WDYT ?

Thanks for your help

**Comment by rdenarie** [comment]
Adaptation is done by @ahamdi 
All is ok now.

@SaraBoutej you can proceed to the merge

**Comment by SaraBoutej** [comment]
Thank you @rdenarie 
Merged cc @boubaker
