### ISSUE TITLE
Bottom Bar in Left menu

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#117]
## Rationale

Now that the administration site is by default something we can access from the topbar, it would be interesting to review the access to the settings and to the logout.

Indeed, it is not a major access as any other pages (spaces, my craft, contribute, etc.) and it would be more interesting to list these options at the bottom of the left menu.
That way, only pages the user access the most are listed in first place.

### Top User Stories

Given I access the left menu
Then at the bottom, I can see three informations:
1. Meeds (or anything else depending the package*)
2. User Settings icon to access the user settings
3. Logout icon to log out from the platform

Given I have a small device OR/AND I have lots of spaces listed
Then the bottom of the menu is sticked so I can see these options 
AND I can scroll down when needed

Given I click to "Meeds"
Then I am sent to a link that we can configure. 
For meeds for example, it can be the product updates blog

<img width="471" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/4d856c4a-1cbc-4b49-a47b-2d212a3a4245">

Given I want to check the version
Then I can do it using rest services as currently

_***Label and link need to be extensible so we can update it depending on the package used**_

#### Gamification
NA

#### Notifications
NA

#### Analytics
Access to meeds version link

### Extensibility

The Package Link displayed in bottom left of the menu should be extensible so that it can be set by package.

### Existing Features

> [!NOTE]
> No change on current behavior of features, this is just a UI change

### Feature Flags

> [!NOTE]
> No feature flag is needed

### Access

Two properties should be available in frontend to be able to display information:
- `eXo.env.portal.productName` ([already exists](https://github.com/Meeds-io/meeds/blob/develop/services/plf-community-edition-service/src/main/resources/conf/platform.properties#L18))
- `eXo.env.portal.productLink` to add the same way as `eXo.env.portal.productName`, packaged in product artifacts which defines the product characteristics.

Both variables should be used to display the Product Label.

**Comment by srenault-meeds** [comment]
@margondicco to check :)

**Comment by margondicco** [comment]
Hello

good idea

my feedback

Version label : i suggest "powered by Meeds (or eXo) x.y.z"
button disconnect : add a rule : if there is an authentification SAML, the button disconnect is hidden

Thank you

**Comment by rdenarie** [comment]
Hello : NOGO for displaying the platform version : it reveal sensible platform informations.
Only administrators have access to that on endpoint /platform/rest/info

**Comment by srenault-meeds** [comment]
Ok I have reviewed the description and the design accordingly.

Plus, I have added something regarding the display of the version: 
> Given I want to check the version
Then I can do it using the current rule 
BUT this can be hidden thanks to a feature flag in case it is needed

Ok for you @rdenarie @margondicco ?

**Comment by rdenarie** [comment]
> Then I can do it using the current rule

You mean via the rest service, as administrator ?

If you mean that, no need of feature flag. Keep the version for admin as currently is ok

If "current rule" mean something else, please explain

**Comment by srenault-meeds** [comment]
Yes I meant the current rest service. Updated

**Comment by srenault-meeds** [comment]
@margondicco I have updated the description considering different feedbacks.
FYI, no "powered by..."
AND regarding SAML, it is another concern we need to address sometime.

**Comment by margondicco** [comment]
Go fonc

**Comment by srenault-meeds** [comment]
Thanks. Ready for tech spec @boubaker

**Comment by boubaker** [comment]
Ready for Tech Review by DAO Members ( eXo : @rdenarie )

**Comment by rdenarie** [comment]
Go tech

**Comment by boubaker** [comment]
Ready for Review by DAO Members ( eXo : @margondicco @rdenarie  )

ACCs Up and Running (https://mips-ft.meeds.io)

In order to change this, you may need to adopt changes in your distribution files, like made for meeds:

https://github.com/Meeds-io/meeds/pull/1580/files#diff-4a7581bde069bf35bf92f159bdc5f507aff0ce6d1ce7bc15ecfc68b8afef8edcR18-R19

**Comment by plamarque** [comment]
Updated title to something simpler

**Comment by rdenarie** [comment]
Feature ok for me.
One small feedback related to accessibility on settings and logout button.

Ok to merge after fixing it

**Comment by srenault-meeds** [comment]
> One small feedback related to accessibility on settings and logout button.

How can we help you please?

**Comment by rdenarie** [comment]
I comment the PR and require for a modification before merge.
This one : https://github.com/Meeds-io/social/pull/3437

You just need to add the aria-label for both button

**Comment by rdenarie** [comment]
My last comment is resolved.
You can proceed to merge

**Comment by boubaker** [comment]
> My last comment is resolved. You can proceed to merge

ok, thanks can you review the PR again, it's blocked in fact:
![image](https://github.com/Meeds-io/MIPs/assets/594824/8c03499b-a4cc-4e70-9570-50413c8fc890)

**Comment by rdenarie** [comment]
Done
