### ISSUE TITLE
Pending Status

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#122]
## Rationale

More you have contributors, more you need to organize the contribution review.
Currently, any action submitted is considered accepted. The problem is that:
- some contribution need to be reviewed and it is difficult to know which one has been reviewed by other reviewer, etc.
- meanwhile, points are considered earned for users
- and after some time, the review can be done and thus, points are removed. 
Result: contributors can get confused and reviewer get tired of checking all contributions. 

In addition to this, we have observed that some contributions captured automatically need to be checked afterwards.
Indeed, for example, a user can add a twitter account with no follower and he can Like, RT a tweet. 
Result: this twitter account has no follower so it is inefficient for our community

### Top User Stories

**Regarding account connection:**
When someone connects his account, then the action for connecting this account is pending by default
AND any related action to this account connection can be manually added as locked until this action app connection is accepted
_rejecting the achievement doesn't disconnect the account_

**Regarding automatic actions**
No change, any contribution is by default accepted
If needed, the acceptation can be changed to rejected or to pending
_no notification flow identified for this case_

**Regarding manual actions**
Any manual action is, by design, _pending_
The owner when creating the action cannot change this parameter for now

**Review of contributions**

- Board is reviewed:
1. to display all status
2. to display an extract of the contribution
3. to remove type

<img width="872" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/36876194-4d43-41d9-b7d4-115cb55601a8">

- Board can be filtered to status (one choice)
<img width="175" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/f15bc247-3ac6-463e-976a-fdff341ad6ba">

- When the user submit his contribution (manual or connection to an account), then current notification for "Contribution submitted" remain enabled. It is still possible to disable it if needed.
_A work will be done later to improve targeting of notifications_

- For each contribution, it is possible to:
1. Access the detail by clicking to detail and it opens a new tab.
_No drawer for it for now. We will study the fact to open the comment drawer for now_
2. Update the status from the board (no more three dots) 
3. Update the status of the contribution from the contributions comment in the stream
<img width="413" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/07cfc0b7-a7f3-45a7-b618-549a4a386bbc">

4. Adding a comment will be done directly from the stream

- When the contribution is pending
1. Then the comment is visible to anyone with a mention "Pending" (instead of the current "Done!")
4. The contributor can still edit its contribution during the time it is on pending status
<img width="157" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/d1a53c3c-cd33-4bb2-9b47-5cd769b821f0">

- When the contribution is accepted,
1. Then the comment is visible to anyone with a mention "Approved" (instead of the current "Done!")
2. A notification is sent to the user so he knows the contribution is accepted 
3. The contributor cannot edit its contribution once it is accepted
<img width="216" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/26ba8a21-71ca-49b3-883b-829e1eb62750">

- When the contribution is rejected,
1. Then the comment is made visible to anyone with a mention "Rejected" (instead of the current "Done!")
2. A notification is sent to the user so he knows the contribution is rejected
3. The contributor cannot edit its contribution. If needed to submit it again, then a new contribution can be submitted
<img width="212" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/b7f67246-7a54-4b02-9937-8e7ef2077793">

**Regarding rewards computing**
- Pending contribution is not considered in the computing, neither in the total of points of the contributor (leaderboard)
- Contribution is considered in the computing once accepted. So, at the time, the reward is computed, we collect all contributions submitted during the period AND accepted
- Those which are still pending while submitted during the last period are eligible for next period

**_To study_**
- Ability to clone an action to start creating a new one so it is more easy and quicker to add recurrent actions (twitter, linkedin, etc.)
- Ability to use an action from another program than the current one as a condition to complete the action

#### Gamification
Connectors and profile list
Contributions board to review
Contributions are added once accepted

#### Notifications
Add a notification type for contribution status: to provide a way to inform when accepted/rejected

### Security 
NA

### Extensibility 
Add new types of activity actions to update the status of the contribution from the stream.

### Configurability 
NA

### Upgradability
NA

### Existing Features
The existing achievements Board has to be improved.

### Feature Flags

No feature flag is needed.

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  |   |   |   |

### Security
NA

### Services & processing
The default **PENDING** value of automatic realization status will be known from the trigger config (default false).
For a manual rule, always true.

A new notification type is to be added `GamificationActionVerifiedNotification`.

Update the earned points account based on the pending status.

### Data and persistence
We will have to add in Database Table `GAMIFICATION_ACTIONS_HISTORY` a new field `REWARDED` of type `BOOLEAN` to hold the realization rewarding status(default FALSE).

### Migration strategy
no need for migrating old realization.

**Comment by srenault-meeds** [comment]
To check please @margondicco @plamarque

**Comment by plamarque** [comment]
How about the CANCELLED and DELETED statuses ?

**Comment by srenault-meeds** [comment]
Currently it is considered as "rejected" or it is empty. To avoid too much actions, I suggest to consider it as "rejected" with no ability to accept it, nor review it. WDYT?

**Comment by plamarque** [comment]
> I  suggest to consider it as "rejected" with no ability to accept it, nor review it. 

OK, these  states are final anyway. And anything particular to consider for notifications when reaching these statuses?

**Comment by srenault-meeds** [comment]
Good question.
If we notify program owners when a contribution is submitted, then why not notifying them when the contribution is cancelled/rejected?

We have two options:
1. Notification -> Too much noise for nothing
2. No notification but a page with a placeholder -> Less noise

WDYT?

**Comment by srenault-meeds** [comment]
tt

**Comment by srenault-meeds** [comment]
FYI, we have reviewed the part regarding the notification when a contribution is submitted:

> New requirement

- When the user submit its contribution (manual or connection to an account), then current notification remain enabled. It is still possible to disable it if needed.
_A work will be done later to improve reach of notifications_

> The following will be worked later

- When the user submit its contribution (manual or connection to an account)
1. Then a notification to let the owner know a new contribution has been done is sent. 
2. The comment is hidden for any other user. Only program owner and contributor can see it
- If needed, he can unwatch this activity and then he will no more receive any notification for this action

**Comment by srenault-meeds** [comment]
Added screenshots and reviewed the notification part.
Ready for go-fonc check @margondicco

**Comment by margondicco** [comment]
Go Fonc

**Comment by AzmiTouil** [comment]
Ready for tech review by DAO Members (eXo: @rdenarie )

**Comment by rdenarie** [comment]
Go tech

**Comment by AzmiTouil** [comment]
MIP ready for review by the DAO members (cc @rdenarie ).
Acc up & running.

**Comment by rdenarie** [comment]
Ok for me on technical side

**Comment by margondicco** [comment]
ok for me on functional side

**Comment by boubaker** [comment]
Merged to develop
