### ISSUE TITLE
People page UI/UX improvements

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/MIPs#125]
## Rationale
We need to unify the people card between organizational chart and people card in the people directory for UX consistency.

End-users have reported that the card is not useful in some way:
1. connection CTA is not helpful
2. to send a kudos, we need to access the three dots or the profile
3. Informations from the profile cannot be highlighted in the card. only the full name and the position are listed

End-users are disturbed to not been able to find themselves in People page.

### Top User Stories
In order to unify the UX between card in organizational chart and in the people page, we need to:
- UI review of the user card
- Remove the "Connection" CTA from the user card
- Display the interaction buttons with the user directly on the card
- Remove the "i" button
- Add the open organizational chart action
- Display the current user in the list of users so they can find themselves

And finally, some improvements will be done to make the page more readable
- Remove the "Showing XX results" in the top bar application
- Display 21 users at first load instead of 20 presently. So we have 7 full lines of 3 in case of max width of the app. 

![image](https://github.com/Meeds-io/MIPs/assets/105866381/d8ee0602-59af-4b9c-a74e-61725a8c6532)

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  |   |   |   |

### Access 
   - GUI 
   - API 

### Services & processing
   - Ex: Scheduled Jobs

### Data and persistence
   - Macro data model
   - Persistence layer 
   - Use of caches
## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts 
   - References

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds MIP updated as requested

**Comment by srenault-meeds** [comment]
@Julien-Dubois-eXo DO you plan to rework the description of this MIP so it takes into account the characteristics of the space members page?
see https://github.com/Meeds-io/MIPs/issues/127

Indeed, I think we must add informations regarding cases of members app:
> - Hide the deactivated user when filtering on the values "Members","redactors","hosts"
> - Add a new quick filter value "Deactivated" only available for space hosts. It display only the deactivated users so the space hosts can easily manage them
> - Role management action will be listed in a dedicated action menu only available for the space hosts.
> - On mobile , interaction actions and role management actions will be separated in 2 different sections in the bottom drawer. The section dedicated to role management action will be only displayed for space hosts.

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds you closed the wrong MIP. I have edited the one you have closed.
