### ISSUE TITLE
Deactivated user

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/MIPs#126]
## Rationale

Presently when a user is deactivated we have no information on the activities generated by him and a user may want to comment or interact with them. No information is provided to let them know that the user is deactivated and he will probably have no feedback.

For the manager feature, we have implemented the status information in the avatar component. We display a slash user icon and on hovering over it a tooltip display Disable (it will be changed in crowdin). 

### Top User Stories
We propose to implement it everywhere the user name will be displayed. 
![image](https://github.com/Meeds-io/MIPs/assets/105866381/f8d8dbf6-da3c-41fa-8108-37cb3e37eee1)

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  |   |   |   |

### Access 
   - GUI 
   - API 

### Services & processing
   - Ex: Scheduled Jobs

### Data and persistence
   - Macro data model
   - Persistence layer 
   - Use of caches
## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts 
   - References

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds I do it again as requested. I hope this time is at the right place.

**Comment by srenault-meeds** [comment]
Is it a MIP?
If yes, ok to be listed here
If no, list it there as any other feedback/issue: https://github.com/Meeds-io/meeds/issues/new/choose

**Comment by Julien-Dubois-eXo** [comment]
Yes it's a MIP. We already have implemented it. I just need you go to provide it as we already discussed it. 

It's the one you already accepted but asked me to create here.

**Comment by srenault-meeds** [comment]
Hello, as discussed with @rdenarie weeks ago, this is not a MIP but an issue. So I close it. thanks
