### ISSUE TITLE
News to notes - Part 4 - News display revamping and automatic target creation

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/MIPs#129]
## Rationale
1. We need to review the article's display to answer end-user feedback and align with note UI: 

- the organization of the headline elements is not good
- the article title is too small
- the elements about author, spaces and date are too much visible
- redaction space is not enough visible

2. Space administrators and publishers cannot be autonomous for publishing. They need to ask an administrator to create a target for their space. With the review of space permissions and layout manager, we should provide this autonomy to the space in a secure scope. 

3. End-user have provided feedback around article notification that is causing issues:

- Unread notifications for publishing and mentions in articles generate an unread indicator that cannot be removed without marking all as unread. 
- UI harmonization with others notifications

### Feedback from MIP128 and small improvement on properties

- Char limit on the summary
- Tooltip on the property icon
- Integration of cropping drawer for the featured image insertion
- Export/import note includes the properties

### Targets

- Automatic creation of a target at the space creation
  - Default permission on the target = the space created

### News display

- UI harmonization with notes display
- Action menu revamping to align UI guidelines
- Display only the last redactor and update date on a news
- Add copy link option the News 3 dots

![image](https://github.com/Meeds-io/MIPs/assets/105866381/c2465bac-aed0-439d-8349-283864abacbb)

#### Notifications
- Remove unread activity for publishing a news and mention someone in the article
- Fix of "go to news" redirection URL on e-mail publishing notification --> redirection to the public URL
- Small UI harmonization on notification
  - "Harmonization of publishing an article notification --> remove the article title in the notification title"

### Listeners

We need to implement a SpaceListenerPlugin in order to create a news target when a new space is created

**Comment by Julien-Dubois-eXo** [comment]
@azayati you can check and start to complete the technical part. @margondicco FYI. I would also like to add an improvement about the "Publisher promotion". Presently no matter if a space cannot publish news (no targets allowed for the space), we have the Publisher role present. It generates confusion for the end users (what this role means, why we have it while it's useless etc). I would suggest showing the promotion action and the publisher filter only if at least one target is allowed for the space. 

@srenault-meeds for review.

**Comment by Julien-Dubois-eXo** [comment]
@margondicco @srenault-meeds je me demande également si on ne devrait pas mettre visuellement en avant quand un article est issue d'une note. WDYT? 

Actuellement j'ai mis l'option "Accéder à la note" dans les 3 points, ce qui n'est pas visible. Ca me semble important de savoir quand un article est la publication d'une note.

**Comment by Julien-Dubois-eXo** [comment]
@margondicco j'ai ajouté la partie "Target" (création auto des targets à la création de l'espace) pour permettre l'ajout et la gestion des Newslists en autonomie par l'animateur d'espace. Je n'ai pas mis ici la partie admin qui permet de désactiver cela. De ce que j'ai compris c'est surement après qu'on ferait cela dans une logique plus globale de permission.

**Comment by srenault-meeds** [comment]
Hello, is that submitted? I still see it as "Opened" and I don't see any rationale explaining the WHY.
Thanks @Julien-Dubois-eXo

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds I have added the rationale section.

**Comment by srenault-meeds** [comment]
If you allow me to do it, here are my observations:

> space host **should have** by default the publish permission. Redactor has not by default the publish permission

I would say **must have** instead of **should have**
Redactor **does not have**

> Publication drawer with publishing permissions

I don't see the default start date for this case. Do we plan to suggest it or not?
This makes a different UX in comparison with the simple scheduling which suggesting the day after at 8am

> Add a target management menu in the space settings with only the targets authorized for the space

Can we not implement it for now? Indeed, we plan to review this settings page soon (in 2 or 3 weeks).

> Add publish options in the 3 dots actions menu of a note

Can we rearrange the list of options please?
Indeed, export/import options are only proposed at the root page. I don't see anymore the delete option.
Suggestion of sorting:
1. Publish
2. Copy Link
3. Print to PDF
4. History version
5. Export
6. Import
7. Delete

> "Go to Note" option in the 3 dots of the article when the article is published from a note.
- open the note related to the article

When reading it, I have the feeling that two contents are created for one. One note and one article while it is the same I thought.
Do we agree on this? Maybe, we can suggest something different: Open in Notes App

> UX review of the location when clicking on the back arrow on a new activity

Not understood.

> Display only the last redactor and update date on a news

How can we list other redactors? In the version history drawer?

> Display of redactor/space

Can we display it after the summary like it is done on Medium, Lemonde.fr, lequipe.fr, etc.?
Please, can you make sure the square space avatar is displayed with a square and a radius applied to it? Actually, I only want to make sure you reuse the display we have for a space.

> Refer to a note

Can we undo this? I mean, can we remove an article from the notes app without removing the whole article?

> Remove unread activity for publishing a news

Are you sure about this? Why this proposition?


> Feature flags

Lots of feature flag. Can we imagine less FF or one only?
Is that only for dev? Or do you plan to deliver it once the MIP is ready to be delivered?

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds Here are my answers. 

> space host should have by default the publish permission. Redactor has not by default the publish permission
> 
> I would say must have instead of should have
> Redactor does not have

Do not hesitate to correct directly this kind of mistake. 

> Publication drawer with publishing permissions
> 
> I don't see the default start date for this case. Do we plan to suggest it or not?
> This makes a different UX in comparison with the simple scheduling which suggesting the day after at 8am

We will keep this behavior. I just did not mention it. I have added them

> Add a target management menu in the space settings with only the targets authorized for the space
> 
> Can we not implement it for now? Indeed, we plan to review this settings page soon (in 2 or 3 weeks).

I let you check that with @margondicco. For the moment we are not ready to start this part so I don't see any issue. 

> Add publish options in the 3 dots actions menu of a note
> 
> Can we rearrange the list of options please?

No problem with changing the order. I will update the design. The action menu is the one of the "Home" so it's not possible to Delete it. I can make the design of another note if it's disturbing. 

> "Go to Note" option in the 3 dots of the article when the article is published from a note.
> Do we agree on this? Maybe, we can suggest something different: Open in Notes App

Yes, it's the same content. No problem to change the label. Description updated.

> UX review of the location when clicking on the back arrow on a new activity
> 
> Not understood.

When you read an article and you click on the "back arrow" you have different behavior according to where you open the article. In main cases, it's not where you open the article but the Home of the platform. 

> Display only the last redactor and update date on a news
> 
> How can we list other redactors? In the version history drawer?

The history version of the note must list the modification done also from the News editor so yes you should be able to check all the redactors when the note is referenced in a note tree. If it's only an article we just can't but I don't see the interest to have this ability. We are changing this behavior especially because we notice that the information is not used. 

> Display only the last redactor and update date on a news
> 
> How can we list other redactors? In the version history drawer?

I will change the design

> Refer to a note
> 
> Can we undo this? I mean, can we remove an article from the notes app without removing the whole article?

Good point, I have added a feature to undo it. 

> Remove unread activity for publishing a news
> 
> Are you sure about this? Why this proposition?

Yes, it's causing an issue for the end user. They have a red dot on the space but there is no new activity at all in the space.  They thought there was a bug. Publishing is not generating activity so no unread activity. The activity is linked to the "post an article". 

> Feature flags
> 
> Lots of feature flag. Can we imagine less FF or one only?
> Is that only for dev? Or do you plan to deliver it once the MIP is ready to be delivered?

As mentioned at the beginning they will be all removed at the end of the iteration and before we deliver the MIP to you. I need to have several to manage the delivery for CI/CD. If I use only one or less the delivery will be less smooth or not managed. I mentioned them here to be able to discuss with tech lead.

**Comment by Julien-Dubois-eXo** [comment]
Designs updated

**Comment by srenault-meeds** [comment]
Ok for me. Thanks

**Comment by azayati** [comment]
@boubaker technical part ready to be checked.

**Comment by boubaker** [comment]
@azayati good for me except feature flags, we intend to not have feature flags in order to not complexify maintenability nor evolutivity of existing features. Until now, we have a very few feature flags that wasn't cleaned yet, can you please decide to display or not the buttons without adequate feature flags for each added button ? @srenault-meeds have you a concern if deleting all of them ?

> As mentioned at the beginning they will be all removed at the end of the iteration and before we deliver the MIP to you

Ah ok, so will be removed, thus not expected in the delivery, thus no need to specify in specification because here we describe and design what's expected as outcome rather than how we will to build it.

**Comment by azayati** [comment]
> Ah ok, so will be removed, thus not expected in the delivery, thus no need to specify in specification because here we describe and design what's expected as outcome rather than how we will to build it.

cc @Julien-Dubois-eXo for answering

**Comment by srenault-meeds** [comment]
AFAIU, these feature flags will be deleted indeed for the delivery.
I also suggest to not list them here as the MIP doesn't aim to be a functional spec during the delivery, but the final output.

**Comment by Julien-Dubois-eXo** [comment]
I will remove it from the MIP before delivering if you prefer but until then, please, I want to keep them. I want to have all in one list to quickly refer to. We are using this MIP to discuss also specifications on our part. If I remove it I have to create a note just for that elsewhere and have a part on one side and another part on another side.

**Comment by srenault-meeds** [comment]
Why not using the file you have for FF on eXo Tribe? That way, you centralize all FF no matter the feature.

**Comment by Julien-Dubois-eXo** [comment]
As discussed with @srenault-meeds before summer break, I have added the "copy link" option for a News forecasting the PWA.

**Comment by margondicco** [comment]
My feedbacks

**1. UI Glitches on news only (ok for note) on the button translate**

![image](https://github.com/user-attachments/assets/32216051-720e-4334-adbd-2bce9c60b91a)


**2. Editor (news and note)**
add an information on hover on the button properties

![image](https://github.com/user-attachments/assets/257730c3-f73d-42dc-aebb-0d3cfd294fbb)

**3. illustration and summary lost when i create a new version** 

Only for a news
Create a news with an illustration and summary AND validate
Edit the news and create a new version
issue : the drawer property is empty

https://github.com/user-attachments/assets/809e1786-f83a-4855-84a6-8b709dd2f48a

**4.  drawer favorites**

add a news as a favorite. Open the page members or an other page but not a page stream
the label of the news doesn't display

![image](https://github.com/user-attachments/assets/151ba53e-5e5c-4a9c-857a-314eb583f94b)

it's ok if i open the drawer when i am on a page stream (general stream or a space stream)


cc @Julien-Dubois-eXo  
@srenault-meeds

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds @boubaker MIP129 split in 2 with the [MIP169](https://github.com/orgs/Meeds-io/projects/4/views/1?pane=issue&itemId=82047038).

We have also included feedback from the MIP128 and small improvements on properties to integrate your work on the cropping component.

**Comment by azayati** [comment]
PRs:

- https://github.com/Meeds-io/content/pull/233
- https://github.com/Meeds-io/notes/pull/1121
- https://github.com/Meeds-io/commons/pull/654

**Comment by srenault-meeds** [comment]
Hello, 

What does that mean, please?
- Does that mean the delivery process is on?
- Does that mean the feature can be tested on both ACC?
- Does that mean you are preparing the delivery?

Thanks in advance for clarification

**Comment by azayati** [comment]
@srenault-meeds I have removed the label, it will be added once the ACC is ready to test, we are preparing the delivery.
Thanks

**Comment by srenault-meeds** [comment]
Ok, thanks. I was wondering because Julien told me before this PR notifications the MIP will be ready to test.
Thanks for your clarification :)

**Comment by azayati** [comment]
ACCs & PRs ready for review (Meeds @boubaker @srenault-meeds)

**Comment by azayati** [comment]
PRs:

- https://github.com/Meeds-io/content/pull/233
- https://github.com/Meeds-io/notes/pull/1121
- https://github.com/Meeds-io/commons/pull/654

**Comment by boubaker** [comment]
ok for me

**Comment by Julien-Dubois-eXo** [comment]
FYI, we have identified a bug with the import of the featured images between 2 different platforms. As agreed with @srenault-meeds, this bug will not block the merge. We will quickly create an issue to solve it.

**Comment by srenault-meeds** [comment]
Hi,

Feedbacks I let you prioritize:
- Copy Link:
   - Platform Admin cannot access a notes from a space is not member of

- Deleted news:
   - When trying to access a news that has been deleted
   - Then I have an error "This site can't be reached" (browser window)
   - Expected: Page "We couldn't find the activity"

- How do we not display the author?

- How can we "publish" a note into a news target?

Thanks

**Comment by srenault-meeds** [comment]
Questions:
Are FF still available?
I see no technical requirements but FF. Is that expected?

@Julien-Dubois-eXo

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds for the FF I forgot to remove them from the description. There is not technical point for this MIP.

**Comment by srenault-meeds** [comment]
I know that you had to edit the MIP to split it to two different.
That might be the reason of the removal of the technical requirement.

Now, I am not sure we can implement something without having technical requirements, even if this is only UI.

I let @rdenarie and @azayati confirm this or not

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds here are my answer

> Copy Link:
> 
> Platform Admin cannot access a notes from a space is not member of

We just give the access to the link, so it's something already present before. It's an improvement to treat with another MIP.


> Deleted news:
> When trying to access a news that has been deleted
> Then I have an error "This site can't be reached" (browser window)
> Expected: Page "We couldn't find the activity"

We just reviewed the UI of the action menu, it's not related to this MIP. It's an improvement to treat with another MIP.


> How do we not display the author?

I forgot to remove this design. It's in the next MIP.

> How can we "publish" a note into a news target?

I forgot to remove this design. It's in the next MIP.

Let me know if it's ok for you to merge regarding my feedbacks. 

For the technical part, I let @azayati answer as it's him who told me it's normal.

**Comment by azayati** [comment]
> For the technical part, I let @azayati answer as it's him who told me it's normal.

@srenault-meeds I have just added a part for listeners, no technical part needed for other modifications.

**Comment by srenault-meeds** [comment]
Ok for me to merge thanks

**Comment by azayati** [comment]
> Ok thanks

@srenault-meeds does it mean that it is ok for u to merge ?
