### ISSUE TITLE
Contribution Center

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#13]
## Rationale

Challenges feature has been provided lately to enable users to declare what they have done using the platform or not. This was the beginning of the engagement / contribution center we want to implement.
FYI, challenges is related to domains, to achievements and to rewards features.
And to conclude this first information, the challenges app was the first way to hilight the way the platform can help companies and any other kind of organizations to engage users, employees, volunteers.

Now that this first use case of declaring and gathering challenges has been implemented and used, we would like to enhance this use case with a whole Contributions center. This, to be consistent with the Meeds project and its White paper The Work Metaverse.

This Contributions center aims to elaborate our way of engaging people as well as it aims to make it easier:
as a user
- to know what to do, to know how to play and to earn points
- to check achievements
as a program driver
- to market challenges within one or multiple programs
- to drive challenges
as a funds owner
- to drive programs
- to check achievements

### Contributions center perequirements
- This Contributions center will gather three items from the most general to most detailed: programs, challenges and achievements

- Any user can access the Contributions center from the appcenter by clicking to Contributions center icon (replacing the old challenges app)

- When accessing the app, the user will see three tabs: Programs, Challenges, Achievements

- Depending its role, the user will access the app with more or less abilities: 
-- Regular user:
will see programs depending his membership to the program's audience
that way, the user can see programs and rules, challenges related to it no matter he is external or internal. 
will see challenges grouped by program
will only see its achievements from the achievements tab
-- Funds owner:
will see all the programs running in the organization with the ability to create new ones or to edit/delete current ones.
will identify programs hosts so they can manage their program autonomously
will see all challenges running in the organization with the ability to create new ones or to edit/delete current ones
will see all achievements done in the organization with the ability to reject challenge announcement or to accept / delete
-- Program owners:
will see all the programs for which they have been identified program owners with ability to edit it, to identify more program owners
will have the ability to see all challenges running depending its membership programs' audience
will have the ability to edit challenges related to the program he owners

### Contributions center display
From the first tab which gathers any program running in the organization, the user will access by default enabled programs. Admin can see disabled programs thanks to a dropdown.
Programs are listed from the more recently created to the less one, 9 programs per page

![image](https://user-images.githubusercontent.com/58853195/193580193-fb8fda79-75df-43f0-bedf-45611691f961.png)

From this tab, I can click to each program to see the detail full page. This full page display the details of the program: cover, description, rules (automatic rules, manual rules like challenges). Each program is accessible from a direct link. (/progams/[id])

![image](https://user-images.githubusercontent.com/58853195/193581438-8ae574b0-cb44-44c5-b9d0-83ff304d96be.png)

From the second tab, the user list the challenges grouped by the more recent created to less ones and challenges are grouped by programs itself sorted from the more recent created to the less ones. He will have the choice to filter by all, active, upcoming and ended challenges.
![image](https://user-images.githubusercontent.com/58853195/193581378-222da789-22fa-4790-b105-6396c312f096.png)

By clicking to a challenge, a challenge details drawer displays the informations for the challenge: description, audience, points, programs, participants.

![image](https://user-images.githubusercontent.com/58853195/193581538-18336fe4-0365-44ec-8ef3-a3044f8acb36.png)

From the third tab, users depending their role (see above) will see achievements with the ability to sort by date (by default), action type and status. And actions for admin can be done from there.

![image](https://user-images.githubusercontent.com/58853195/193581635-90c7ec0f-581f-4f21-9e50-b0019b02836b.png)

Advanced filters will be added so the user depending its role can filter the list per program and/or per grantee.
<img width="950" alt="image" src="https://user-images.githubusercontent.com/58853195/207854882-4f91a74e-c5fc-42cd-bb2a-92beba4a6409.png">

> In the future, we plan to improve way items are displayed and way items are accessible (i.e announce a challenge from the challenge details drawer). For now, we aim to make sure the whole contributions center gives an easy way for differents users persona to manage contributions.

### 2.1. Performance requirements
The needed volumetry shouldn't change, since the programs, challenges and rules already exists. In term of realizations, we should expect to have the same data volumetry as well.
For performances, no special requirement is needed.

### 2.2. Security requirements (Authentication, Authorizations, Audit track / traceability, data retention…)
Some administrative elements will be visible by simple users and external users at the same time for administrators. The UI has to be adapted to end user profile and permissions, especially for REST endpoints that has to constantly verify and secure access to all elements.

### 2.3. Requirements related to existing users data
The pre-defined domains (AKA programs) will not change for fresh and existing installations. In fact, the predefined programs (Social, Knowledge ...) will be displayed as any other programs that will not be assigned to an audience (space) by default. Besides, when editing one of those programs, the administrator will have to choose an audience in order to save the changes. 

### 2.4. Requirements related to existing features (ex: Add a button to existing modules...)
No changes are required by this new feature, except that when the Contributions center feature is finished, we may delete Administrative pages for:

- Rules
- Domains
- Achievements
- The Badges management UI will remain

### 2.5. Feature Flag
- Feature flag name: `exo.feature.engagementCenter.enabled`
- Default value: `true`
- By disabling this feature flag, the engagement center with the list of programs and achievements tabs shouldn't be displayed, but challenges tab.
- No target audience

### 3.1. Security
In REST APIs, we will have to use @RolesAllowed to restrict access to endpoints for authenticated internal and external users. In addition, the Service Layer has to make a fine security check for access & modification of elements switch program owners, platform administrators and roles of the authenticated user.

### 3.2. Access (GUI, API…)
The UI will be made using Vue 2 & Vuetify inside portlets. The frontend will access data through REST APIs.

#### 3.2.1. Portlet
A New Portlet will be defined for Contributions Center. As long as this feature remain in development phase, we should keep this portlet merged at the same time with challenges portlet. Thus a single portlet has to be used for both UIs to be able to display only one UI depending on Feature flag status. 

#### 3.2.2. Rest API Design
We will define REST APIs for :
Programs CRUD (update)
* Change rules endpoint to allow associating a challenge to a dedicated domain/program
* Change rules endpoint to retrieve list by excluding rules already associated to a given program
* Change achievements endpoint to allow accessing cumulative points per program & rule

### 3.3. Services & processing

Comparing to existing business rules, those new business rules will be applied when the feature flag of engagement center is enabled:

- A program (AKA domain) will have the newly added audience field as mandatory
- A program will be automatically owned by audience/space hosts (AKA managers)
- A program/domain can have optional owners. Those owners must be members of the audience/space
- A program can be edited either by owners, space hosts, rewarding admins or platform administrators
- A challenge can be edited only by associated program owners
- Any program owner can add a new associated challenge
- Rules & Challenges will be associated to only one program at a time.

### 3.4. Data and persistence
The data model of gamification domains will be changed to allow adding :
- Owners (Users Owning Programs) identifier by their identity id
- Cover file id (technical identifier of Uploaded file inside FileStorage API)
- Budget: program budget
- Type : an enum that will be used to allow differentiating built-in domains used for built-in rules and the manual programs introduced by users.
 
![EngagementCenterV1](https://user-images.githubusercontent.com/594824/207545454-f6bdbe2e-bf18-4bdb-b1b3-234428d0ce5c.png)

### 3.5. Migration strategy

No migration procedure is needed but liquibase changelogs to add new fields. The newly added fields of type enum will have as default value the first item, such as `EntityType.AUTOMATIC` for programs/domains & achievements.

**Comment by boubaker** [comment]
Ready to tech review @rdenarie

**Comment by boubaker** [comment]
ready to review @rdenarie

**Comment by boubaker** [comment]
Ready for PR review @rdenarie 

https://github.com/Meeds-io/gatein-portal/pull/483
https://github.com/Meeds-io/social/pull/2049
https://github.com/Meeds-io/gamification/pull/709
https://github.com/Meeds-io/kudos/pull/256
https://github.com/Meeds-io/app-center/pull/254
https://github.com/Meeds-io/notes/pull/646
https://github.com/Meeds-io/task/pull/151
https://github.com/Meeds-io/gamification-github/pull/65

**Comment by rdenarie** [comment]
All open PR are validated.
Social one is closed so I think it is not necessary.

Ok for merge

**Comment by boubaker** [comment]
MIP merged
