### ISSUE TITLE
Upgrade news data model to note Part 2

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/MIPs#130]
## 1. Functional Requirements

First part : https://github.com/Meeds-io/MIPs/issues/119#issue-2102504523

Second part : 

- news article migration datas upgrade news to note
- delete the flag (cf part 1)
- Scheduled publication
- filters in the news app

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  newsScheduleAndFilterDisplaying|   false|  users |   enable/disable new scheduling and filters in news app except draft filter|

The FT flag will be deleted at the end of dev.

### Configurability 
**Content addon**
- In order to post scheduled "News" articles on their schedule post date, a period job should be configured:
  - The job will be executed every 15 minutes.
  - The job will implement these steps:
    - Get all scheduled articles based on the "SCHEDULED" attribute of the NEWS_ARTICLES table.
    - When the "SCHEDULE_POST_DATE" attribute value of the scheduled article is reached, the article should be posted in AS if the "ACTIVITY_POSTED" attribute value is true and the "SCHEDULED" attribute value is set to false. Also the  "SCHEDULE_POST_DATE" attribute value can be set to empty.

### Upgradability
**Content addon**
- The existing News articles should remain unchanged after the upgrade from JCR data storage to JPA data storage.
- All migrated JCR News article should be removed after the upgrade from JCR data storage to JPA data storage.
- News search connector should return the same old search results.

### Services & processing

Same as [MIP-119](https://github.com/Meeds-io/MIPs/issues/119)

### Migration strategy

**Notes addon**

- An async upgrade plugin should be implemented into meeds social module in order to migrate notes draft pages created for the same note page by different users by keeping only the last created note draft page and delete the others. 

**Content addon**

- An async upgrade plugin should be implemented into eXo data-upgrade module in order to migrate JCR news articles:
  - Get the list of JCR news articles with an sql query on JCR.
  - For each JCR news article:
    - Create the corresponding original notes page into the WIKI_PAGES table with their metadata items and metadata items properties.
      - The ES indexation should be executed correctly
      - The news article activity should not be recreated
    - If the news article has targets, update the OBJECT_ID of each corresponding news target metadata item (jcr node UUID) with the newly created notes page id, this will ensure that the news articles are still associated with their targets after migration.
  - If the creation of some news article fails, the upgrade plugin should be re-executed the next server startup in order to proceed the migration of failed news articles.
  - Remove all JCR news articles with an sql query on JCR when the migration procedure is finished and all JCR news articles are successfully migrated.
  - The ES un-indexation of removed JCR news articles should be performed.

**Comment by azayati** [comment]
Ready for tech review @boubaker (just after Go-func cc @Julien-Dubois-eXo @srenault-meeds )

**Comment by boubaker** [comment]
@azayati can you please include in the technical requirements the migration to use Spring. All new addon introduced in Meeds has to be based on Spring and no more on deprecated Kernel & WS modules.

**Comment by srenault-meeds** [comment]
Ok for me.

One thing to check please @margondicco 
You tell that the flag will be deleted but I still see it listed in the MIP's description

**Comment by azayati** [comment]
> Ok for me.
> 
> One thing to check please @margondicco You tell that the flag will be deleted but I still see it listed in the MIP's description

yes @srenault-meeds the FT flag will be deleted at the end of this iteration. I have added that in the description.

**Comment by srenault-meeds** [comment]
ok

**Comment by azayati** [comment]
> @azayati can you please include in the technical requirements the migration to use Spring. All new addon introduced in Meeds has to be based on Spring and no more on deprecated Kernel & WS modules.

@boubaker I have added that requirement in Upgradability section: 
> We should springify existing service & rest layer

**Comment by boubaker** [comment]
> > @azayati can you please include in the technical requirements the migration to use Spring. All new addon introduced in Meeds has to be based on Spring and no more on deprecated Kernel & WS modules.
> 
> @boubaker I have added that requirement in Upgradability section:
> 
> > We should springify existing service & rest layer

ok, thanks. Ok for me

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds @boubaker  FYI we had to enable the ability to create a note or a news with the same title. It was something available for the news so we have to keep it and it was a pain point for the note.

**Comment by Julien-Dubois-eXo** [comment]
> @srenault-meeds @boubaker FYI we had to enable the ability to create a note or a news with the same title. It was something available for the news so we have to keep it and it was a pain point for the note.

@srenault-meeds @boubaker FYI about this point we have decided not to do it right now due to technical complexity. We will just manage during the migration the case of news with the same title. If we want it we need more technical study to do it safely. 

FYI @margondicco

**Comment by srenault-meeds** [comment]
Questions:
- would it be possible to use a title of a content previously used but the content has been deleted?
- how do you manage news posted in a space and other posted in another space with same title?
- why is that complicated?

**Comment by Julien-Dubois-eXo** [comment]
@azayati I let you answer as it's a technical decision.

**Comment by azayati** [comment]
> * would it be possible to use a title of a content previously used but the content has been deleted?

It is possible now without modification.

> * how do you manage news posted in a space and other posted in another space with same title?

It is not possible right now with the limitation of notes.

> * why is that complicated?

The models and services are designed to have the name considered as a key for the note page, we can not retrieve many notes with same name, so this needs a reflexion and decision if we should allow to create many notes having the same title with the same name or with random names (as for drafts). Anyway a lot of changes and tests should be done and this is not the context of that MIP IMO

**Comment by margondicco** [comment]
Hello agree with @srenault-meeds , the restriction on the title is a big regression (for news). My case : i create each week an article "Weekly reporting". Imagine that some clients will create more than 10 000 notes and article per year with more than 1000 spaces.... 

My proposal : we will move this requirement in the next MIP

**Comment by srenault-meeds** [comment]
Ok to move this requirement in the next MIP #128 
Let me know as soon as it is added in the fonctional specifications

**Comment by azayati** [comment]
Ready for Review by DAO Members ( Meeds: @srenault-meeds @boubaker)

PRs and ACCs Up and Running

**Comment by srenault-meeds** [comment]
LGTM.

Two observations though:
- If you have removed the FF, then delete it from the MIP description IMO for better clarity (I have tested it using runtime fetch and it seems to be removed but I wasn't sure)
- No relation to the current MIP, but two bugs:
1. cannot edit advanced settings of a target without losing characteristics added at first
2. CSS pb I think for the slider: everything is moved to the top and this is not centered (see scrreenshot)
<img width="769" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/041eb5c6-b361-4b64-b9e5-028fbb45c630">

**Comment by Julien-Dubois-eXo** [comment]
> If you have removed the FF, then delete it from the MIP description IMO for better clarity (I have tested it using runtime fetch and it seems to be removed but I wasn't sure)


@srenault-meeds I prefer to keep them. It's part of the specifications. If I remove it, it is we who will lose clarity. The MIP should also be practical for us. I cannot have two different specifications in several places.

**Comment by srenault-meeds** [comment]
I'm sorry to insist about it but if this is not included anymore in the implementation, this is not clear then to keep it.

**Comment by boubaker** [comment]
> LGTM.

Ok for me as well, Thanks.
