### ISSUE TITLE
Upgrade Page Layout

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#131]
## Rationale

A layout is now [ready to use ](https://github.com/Meeds-io/MIPs/issues/120) for any platform using Meeds.
For now, this option is only provided for new page.
Hence, we need to upgrade "product" pages and any other pages that has been customized.

##### Case 1: Platform is new OR any Meeds Hub

- Every page will be upgraded to use the new model for using the Meeds Layout Manager.
- Any app listed previously in these pages will be added in dynamic section, with same layout display
- In case, the app was injected dynamically thanks to a dynamic container, the app will be added as any other app
_Precision: In case the app cannot be added in the page, then this will be studied to see if possible or blocker_

##### Case 2: Platform is already up and running

- It will be possible to edit "old" pages using the Meeds Layout Manager
- When accessing the edit option, then all apps with their data will be added in a dynamic section (one column) on top of another dynamic section of 2 columns
- Thus, administrator will be able to move apps with their data in the section they want the app to be displayed
_Precision: A reminder message will be used to inform the admin about this change_

![upgrade page layout](https://github.com/Meeds-io/MIPs/assets/58853195/b10e4592-0272-4f2d-beb6-73c23a4cc95b)

#### Gamification
NA

#### Notifications
NA

#### Analytics
Know wich page has been edited using layout

#### Unified Search
NA

### Expected Volume & Performance

N/A (Not applicable)

### Security 

No changes

### Extensibility

The **dynamic containers** has to remain possible to use in combination with the new layout editor.

### Configurability 

**No changes**

### Upgradability

**No data upgrade** is needed since the existing pages layout will be upgraded manually.

### Existing Features

N/A

### Feature Flags

**No feature flags**

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  |   |   |   |

### Security

N/A

### Access 

The layout editor UI has to evolve in order to allow upgrading incompatible pages. The compatibility of pages is made using a simple algorithm:

1. Does the parent container has a template with value `system:/groovy/portal/webui/container/UIPageLayout.gtmpl`
2. Does the child containers are of type sections only (Dynamic or Fixed)

If the current page isn't eligible to one of those conditions, then a new dynamic section with two columns will be initiated by listing all application in the first column to let the user move them if needed to add them in a different Dynamic section/column.

For the dynamic containers in existing pages, when using the layout editor, the list of applications listed in the dynamic container will be listed as is in the corresponding column, so that the administrator, willing to change the page, will be able to delete/configure the applications.

**Comment by srenault-meeds** [comment]
To check please @margondicco

**Comment by boubaker** [comment]
> To check please @margondicco

Technical section added as well @rdenarie ( I will wait for `Go-func` first before seeking for `Go-tech` , so this is just informative for now )

**Comment by margondicco** [comment]
Hello Go Fonc

Thank you

**Comment by boubaker** [comment]
Thanks, ready for tech review. @rdenarie

**Comment by rdenarie** [comment]
Ok for me

**Comment by boubaker** [comment]
ACCs & PRs ready for review by DAO members ( eXo: @margondicco @rdenarie )

**Comment by margondicco** [comment]
Hello tested and validated !! Thank you !

**Comment by rdenarie** [comment]
Ok for on tech side

**Comment by boubaker** [comment]
Merged to develop

**Comment by Christyempire** [comment]
Any help on what to do here please

**Comment by Christyempire** [comment]
This upgrade will go a long way
