### ISSUE TITLE
Page Templates Management

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#133]
## Rationale

The Meeds Layout Manager offers to its users an option to create templates. This standed for delivering out a first version of the Meeds Layout Manager.

Now that this feature is available and admins can edit page, we need to enhance the experience of creating and managing templates
Indeed, we aim to provide solutions to following problems:
- Managing templates: name, description, preview, permissions, template edition, template deletion
- Allowing usage of data to be reused

#### Page Templates Management

**Access to templates management**
As an admin (* in platform/administrators or manager in web-contributors group), I can access the list of templates from the administration site 
- Category: Content Management
- Page: Pages Templates

**List templates**
Templates are listed:
- alphabetically with an option to filter by name or description (text filter)
- if activated (a filter suggests to list deactivated ones, or all, AND templates from a category)
- with characteristics: name, description, preview thumbnail (see below), category, edit options, status option, delete option

When clicking to preview thumbnail, I can see it full screen

**Edition**
When editing a template, I can change name, description, preview as currently when creating a template
When switching the status from activated to not activated, then it will be no more listed in the main list
I cannot edit, neither delete a product template. I can deactivate it if needed.
I can access the layout template edition using the same icon for consistency

**Ability to add template**
From this page templates management page, I can duplicate an existing template to start a new one

Of course, I can add a template from scratch
When doing so, the layout manager opens in a new tab so I can start creating a template. Empty columns template will be used to start from scratch
Instead of "publish" option, I have "Save"

#### Analytics
Template creation
Template usage

### Expected Volume & Performance

Minor changes should be applied to Data Model, thus no major changes on data volumetry is needed.

### Security 

Page templates management should be accessible for `/platform/administrators` and `manager:/platform/web-contributors` only.

### Extensibility 

N/A

### Upgradability

N/A

### Existing Features

N/A

### Feature Flags

No feature flag is needed

### Security

The security checks has to be made user `UserACL` service in Service layer. The REST endpoints has to give access to all `/platform/users` members.

### Access 
- Vue 2 and Vuetify 2 will be used for the new Page Template Management portlet.

### Services & processing
- The Page Templates Analytics will be collected using a frontend listener which will inject data when user creates a page or a page template
- The Page Templates data will be stored in the Data Model introduced in MIP #131 
- In order to allow editing a page template, we will need to have a temporary page that should be created in global site for each user and that should be of type `DRAFT` in order to avoid displaying it in other portlets

**Comment by srenault-meeds** [comment]
To check please @margondicco

**Comment by srenault-meeds** [comment]
I added an item regarding the option to keep data

**Comment by srenault-meeds** [comment]
Description updated as discussed @margondicco I let you check. Thanks

**Comment by margondicco** [comment]
Hello thank you @srenault-meeds. Go fonc

**Comment by srenault-meeds** [comment]
_**Update**_
> Node ID can be customized on demand at the creation as it is currently. Once created, I cannot edit it indeed.

Indeed, we won't work on "alias" implementation for now. So we keep the UX regarding node id's management as is

**Comment by boubaker** [comment]
Ready for tech review @rdenarie

**Comment by rdenarie** [comment]
Hello, Go tech

**Comment by Treasureth** [comment]
Let's make this count

**Comment by srenault-meeds** [comment]
**Update**

We have reviewed the scope of this MIP to only address the Page Templates Management.
Thus: 
1. I have created another MIP for UX for page creation -> #137 (draft for now)
2. I have removed the following cases: import/export and Keep data when saving template
Indeed, these last cases must be studied once we implement the app registry and the ability to instantiate portlets to create apps with configuration and data.

FYI @margondicco

**Comment by boubaker** [comment]
> **Update**
> 
> We have reviewed the scope of this MIP to only address the Page Templates Management. Thus:
> 
> 1. I have created another MIP for UX for page creation -> [DRAFT - UX review - Create a page #137](https://github.com/Meeds-io/MIPs/issues/137) (draft for now)
> 2. I have removed the following cases: import/export and Keep data when saving template
>    Indeed, these last cases must be studied once we implement the app registry and the ability to instantiate portlets to create apps with configuration and data.
> 
> FYI @margondicco

Technical Specification changed as well to delete portlets data inclusion in page templates. (FYI @rdenarie )

**Comment by boubaker** [comment]
ACCs and PRs are ready to review by Meeds DAO members (eXo: @margondicco @rdenarie )

**Comment by rdenarie** [comment]
Hello, you can process to the merge

**Comment by boubaker** [comment]
MIP merged to develop
