### ISSUE TITLE
Portlets compliance with layout

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#135]
## Rationale

Using the Meeds Layout Manager hilights the fact that some portlets need to be reviewed to make sure it is well displayed.

Some are not "responsive". Indeed when you add links, SNV portlet in a grid zone, there is empty room to fill. The aspect when viewing the page can be confusing

Others needs to be reviewed so we make sure the user is not confused: Add an image portlet in a grid section is confusing. Indeed, the frame to use in that case must be equal to the selected zone. A contrario, when using it in a dynamic section, frames can be selected using the current option

#### Portlet generic review

Any portlet will be reviewed to follow these guidelines:
**Height**
- Dynamic: height is dynamic depending on the content to display
- Fixed: height is fixed and no matter there is no content to fill the zone, the portlet takes the whole height
 
**Transparency**
- Any portlet needs to be compliant with transparency
- By editing the app properties (when editing the page layout), I can setup transparency
- Then icons/images, text are displayed on front of transparent background

**Text Color**
- Any portlet needs to be compliant with layout options
- And as we can add dark background color or image, we need to make sure, text color can be updated by users (content-managers)
- Hence, By editing the app properties (when editing the page layout), I can update the text-color

![image](https://github.com/Meeds-io/MIPs/assets/58853195/70437da5-fce3-46be-b661-5fb81ac5f4d3)

#### Portlet specific review

Few portlets need to be reviewed

**1. External Spaces**
- Rename it "User Spaces"
- If dynamic, list by default 10 spaces and provide a load more
- If fixed, list minimum 10 spaces, and if more, list more until there is a load more + scrollbar if needed
- Spaces are sorted alphanumerically
- Sort option is proposed next to header of the portlet so the user can change it to "Sorted by last access"
- When changing the sort option, this choice is saved for the user
 
**2. Image portlet**
- No matter the device's width, we need to make sure the image is displayed in its whole width
- Add a free cropped sise / frame to frame options so the user can decide to use it
- Add a label below the selected frame so the user can understand the ratio
- If used in a fixed section, then only one frame can be used, the one corresponding to the selected zone

### Expected Volume & Performance

N/A

### Security 

N/A

### Extensibility 

N/A

### Configurability 

N/A

### Upgradability

N/A

### Existing Features

N/A

### Feature Flags

No feature flag is needed

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  |   |   |   |

### Other Non Functional Requirements

N/A

### Security

N/A

### Access 

The portlet styles will change in order to allow its usage in fixed sections, especially for CMS based portlets. To do so, no generic CSS will be used, but each portlet has to be reworked properly in order to allow it.

**Comment by rdenarie** [comment]
Hello @srenault-meeds 
For external-spaces, I see that maintenance have a task on it : https://community.exoplatform.com/portal/dw/tasks/taskDetail/61391

Perhaps you should synchronize to be sure to be aligned ?

cc @mkrout

**Comment by srenault-meeds** [comment]
@margondicco To check please.
During this MIP, we will focus to compliance of portlets to Meeds Layout Manager and Sections management.

Then, we will rework some portlets (overview portlet, userStatistics portlet) in another MIP

**Comment by margondicco** [comment]
Hello Go Fonc

**Comment by boubaker** [comment]
Ready for tech review (No major technical change, just portlets UI has to be improved for better compliance to `Fixed Section`)
(cc @rdenarie )

**Comment by rdenarie** [comment]
Ok, go tech

**Comment by srenault-meeds** [comment]
Hello @margondicco 

As we have made the Layout Manager much more flexible with UI, I suggest two more items for this portlet review:

>  Make sure any portlet is compliant with transparent background
> Make sure any portlet text color can be updated so it is compliant with the background and thus, accessible

Do you have any objection?

**Comment by margondicco** [comment]
No objection

**Comment by srenault-meeds** [comment]
Ok thanks. @boubaker does that change the technical specification?

**Comment by srenault-meeds** [comment]
I cancel the acceptation of this MIP as a framework will be implemented before 
cc #144

**Comment by boubaker** [comment]
> Ok thanks. @boubaker does that change the technical specification?

Yes, indeed

**Comment by srenault-meeds** [comment]
Cancelled as portlets have been reviewed during the #144 MIP
And for other requirements, we will review it site by site starting with contribute #155 and mycraft #156
