### ISSUE TITLE
DRAFT - New Admin Portlets to customize experience

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#136]
## Rationale

Terms of use, welcome, invitation, addition of users cannot be done using portlets
We have workaround thanks to different tools proposed bu the platform.
Still, it is not straightforward and most of the modern service propose such options.

In addition, some admin are willing to set specific CSS/JS to customize the experience in the platform. We would like to give them solutions for it.

### Top User Stories

1. Terms of use
From the admin menu, I can access Main Settings page.
From there, I have a new entry "Welcome options", below Platform Access
Then I can enable an option to request users to accept terms of use before using the platform with following options:
- Title
- Text with rich editor except tags and images

When saving, I can decide to request all users or only new users
Once confirmed, the page is proposed at the next refresh or login with UI consistency of the theme

2. Welcome text
From the admin menu, I can access Main Settings page.
From there, I have a new entry "Welcome options", below Platform Access
Then I can enable an option to welcome users once they have logged in, with following options:
- Title
- Text with rich editor except tags and images

Once confirmed, the page is proposed at the first login for only new users with UI consistency of the theme

3. Information
From the admin menu, I can access Main Settings page.
From there, I have a new entry "Welcome options", below Platform Access
Then I can enable an option to inform users about something going on, with following options:
- Title
- Text with rich editor except tags and images

Once confirmed, the page is proposed at the next refresh/login for any user with UI consistency of the theme

4. CSS/JS options
From the admin menu, I can access Main Settings page.
From there, I access the theme page
Then I can access form to set CSS/JS templatized options:
... to study...
+ preview of changes when needed?

5. Addition / invitation of users
From the main settings > platform access, I can add or invite users

When adding users, I can set their full profile (current form) + their role and finally invite them to onboard
When inviting users, I can add their emails to send invitation mail with a token (optionally, I would be able to set a specific time for the token from a range of 1 day to 14 days, or forever)

6. Referral option
From the main settings > platform access, I can authorize users to invite anyone or to refer the platform using a link

When doing such a thing, then this option is proposed from user settings
AND each referral link is monitored so we can know who has onboarded the platform and thanks to the sender
AND this can be gamified to incentivize such achievement

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  |   |   |   |

### Access 
   - GUI 
   - API 

### Services & processing
   - Ex: Scheduled Jobs

### Data and persistence
   - Macro data model
   - Persistence layer 
   - Use of caches
## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts 
   - References

**Comment by rdenarie** [comment]
Hello
About

> Addition / invitation of users
From the main settings > platform access, I can add or invite users
When adding users, I can set their full profile (current form) + their role and finally invite them to onboard
When inviting users, I can add their emails to send invitation mail with a token (optionally, I would be able to set a specific time for the token from a range of 1 day to 14 days, or forever)

What this feature add regarding the current UserAdministration Portlet ? 
In UserAdministration Portlet, you can add users, and you can invite them (onboarding email)
The featuer to fill the profile is not present currently, you are right. 
But, should we have a new portlet for that ? or should we complete the current existing one ?

**Comment by margondicco** [comment]
Hello


> Terms of use

Another important requirement : we must track user who accept the terms of use

> CSS/JS

IMO we could have several CSS or JSS properties we could activate or not (title, perhaps descriptions + css or js code, activation yes or no)

> When adding users, I can set their full profile (current form) + their role and finally invite them to onboard
full profile or full account ? 

> When inviting users, I can add their emails to send invitation mail with a token (optionally, I would be able to set a specific time for the token from a range of 1 day to 14 days, or forever)

Don't forget the capabilities to copy paste a list of mail

Another point : IMO we could extend the default space function to all users logging in for the first time, not just those created by register

Another points (branding i don't know if it's the good MIP but i try ): 
 - hide or not the button "define your own home page"
 - stick the left menu by default
 - and last but not least it's christmas : define your own font for Title 1, Title 2, Title 3 Title 4, body, etc.

**Comment by Treasureth** [comment]
Keep the good works going

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds @margondicco why do not propose inserting images? In some cases (information or welcome) it might be interesting to include an image. 

Is it because the new insert image option has not yet been delivered?

**Comment by srenault-meeds** [comment]
No because the MIP was thought last May, so few months ago...
I will remove it from the board MIP.

Thanks for the head-sup :)
