### ISSUE TITLE
Navigation Management Review

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#137]
## Rationale

As we constantly are wanting better UX consistency, we would like to improve the UX of page creation. Indeed, technical labels are used (nodes, node name) and some items can be displayed only on demand, and not by default.
Additionally, from now on, Space Hosts can access this UI to manage navigation and to create pages/nodes.

Thus, we aim to providing a UX that helps any user to create an item (node) and to associate to it a page, a link, etc only when needed.

#### UX to create an item

**Review of the UX to create an item:**
- Node ID can be customized on demand at the creation as it is currently. Once created, I cannot edit it indeed.
- Icon addition UI is reviewed
- Visibility option UI is kept as is
- Default option is "creating a new page". Users can still add a node without a page using the option "Menu Section"

**Review of the UX to attach an existing page to the item**
- Same UX as when selecting github repositories or spaces in the action creation
- Default setting: will be open in the same tab (same UX as the links portlet)

**Review of the UX to attach an external link to the item**
- Default setting: will be open in a new tab (as it is an external link)

**Review the UX to access templates list**
- List templates
- Expanded view when needed

https://youtu.be/NXEELK1H2uY

#### UX to access templates list (creation)

**Default display**
- Blank templates (grid & dynamic)
- Default templates (sorted alphabetically if not used, to study: then sorted upon latest selection): General Stream, Dashboard, Analytics, Space Stream
- If description, then this will be displayed below the name of the template as follow
<img width="276" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/ad95b507-63d8-40da-94df-6550f18fd937">

**Custom display**
Depending on templates added by users, the list can be long. Hence, we recommend to list 2 templates (same sorting as previously explained) per category, starting by the blank and the default ones and finally the customized ones.
As we have more than 6 templates to list (2 category like default display), users can click to see more from each category to expand the drawer and view all templates

![list expand](https://github.com/Meeds-io/MIPs/assets/58853195/6bcb37a6-fae7-48e3-89aa-384b472b651e)

**Selection UX**

When hovering a preview, I can either preview or select the template.
When clicking to preview, I see the image full screen like any other image AND I have an option to select this template

![preview](https://github.com/Meeds-io/MIPs/assets/58853195/a45d9265-72b9-4f01-bdee-8cc9508a06f4)

#### To study
When needed, it must be possible to browse the navigation of a space like it is for any other sites
Indeed, we can add subnode to space navigation. However, it is not possible to access it from the space menu (desktop/mobile) or from the left menu.
It needs to be studied so space hosts can create nodes and manage their navigation.

### Expected Volume & Performance

No change on data models and backend performances. 

### Security 

No change on security schema of Navigation and Pages.

### Extensibility 

N/A

### Configurability 

N/A

### Upgradability

N/A

### Existing Features

N/A

### Feature Flags

No feature flags

### Other Non Functional Requirements

N/A

### Access 
   - No major change on Rest endpoints
   - No new portlets will be added, the existing portlets of Page Templates and Navigations will be reworked to enhance UX

**Comment by srenault-meeds** [comment]
To check please @margondicco

**Comment by margondicco** [comment]
Hello, 

One feedback for the step 2

We can search on description but we don't display it anywhere.

**Comment by srenault-meeds** [comment]
Indeed. Updated!
Description will be displayed below the name
And we will try to display the whole description (minimum: when expanding the view)

<img width="276" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/55111874-deef-4420-b08a-46c2be6dc104">

**Comment by margondicco** [comment]
go fonc

**Comment by srenault-meeds** [comment]
Thanks!

**Comment by boubaker** [comment]
Ready for tech review by DAO members (eXo : @rdenarie )

**Comment by rdenarie** [comment]
Go tech

**Comment by SaraBoutej** [comment]
Ready for review by DAO Members (eXo: @rdenarie )

**Comment by boubaker** [comment]
> Ready for review by DAO Members (eXo: @rdenarie )

Thanks @SaraBoutej . ACCs up to date as I see, ready for functional review as well @margondicco

**Comment by srenault-meeds** [comment]
Hello @margondicco 

I have seen your comments there: https://github.com/Meeds-io/layout/pull/202#issuecomment-2320692670

Here are my answers:
1. Missing labels on crowdin
-> Wait for the merge and it will be available there :)

2. Hide "draft pages" from the search when selecting existing pages
-> To be addressed in a maintenance issue / enhancement issue IMO

3. Increase the border size of the Selected template
-> Indeed, we have thought about it. The problem is that this UI will go against our UI guidelines. We need to find another way. -> Can be adressed as enhancement issue IMO

4. Group node clickable
-> No change here done by the MIP
-> Can be adressed as enhancement issue IMO

I let you tell us

I'm dealing with the documentation :-p

**Comment by srenault-meeds** [comment]
Documentation ready @margondicco 

[Edit Navigation](https://docs.meeds.io/meeds-guides/admin-guide/customizing-your-platform/edit-navigation)
[Add Pages](https://docs.meeds.io/meeds-guides/admin-guide/customizing-your-platform/add-a-page)

**Comment by margondicco** [comment]
Ok for me thank you

**Comment by boubaker** [comment]
> Ok for me thank you

Thanks @rdenarie is it ok for you ?

**Comment by boubaker** [comment]
https://github.com/Meeds-io/layout/pull/202#issuecomment-2321324403

> Ok for me, you can proceed to merge

@SaraBoutej I let you merge PRs
