### ISSUE TITLE
App Registry (Existing Portlets)

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#139]
## Rationale

The Meeds Layout Manager suggests adding apps listed in a registry. The current problem is that:
- There is no UI to manage these apps currently for Meeds Administrators
- Some Apps cannot be templatized while it is expected (portlet can be configured and admins need to do repetitive actions)
- The apps list when editing a page layout is not modern.

### Top User Stories

**As admin, I can manage apps to list for layout managers**
- Ability to list product portlets, to manage it (name, description, status) and to see related instances
- Ability to instantiate an app from a portlet
- Ability to list the instance in a category with a name, description, permissions and a preview
- Ability to add / edit / delete categories

_Note: By default, permissions for instances = * or publisher in web-contributor group_

**As layout manager (publisher admin), I can access a modern apps list**
- Ability to access categories upon my permissions
- Ability to access list of apps in a category
- Ability to preview it before deciding to use it
- Ability to identify spaces apps from instance properties

**Instances will be packaged as "product-based"**
- Category and instances will be provided by default, based on real usage
- If needed, this list can be updated by configuration without overwriting customization

**Additional items to consider**
- Only * in admin group or * in web-contributor group can access the admin Developement menu
- From admin entry, filtering portlets/instances is possible using text (search done to name / description)
- Clicking to the name or to the thumbnail opens the preview
- Apps proposed by the product package cannot be deleted
- If instances are not listed in a category, then these will be grouped in "No category" and will not be listed for layout managers
- If no access to any app in the category, then no listing of it for users

Explaination: https://www.youtube.com/watch?v=_CHWuTIvyog

#### Gamification
NA

#### Notifications
NA

#### Analytics
Usage of portlet to create instances

#### Unified Search
NA

### Security 

A permissions list has to be managed in portlet instances and categories. The users who are member of either administrators or/and Web Contributors group can access to the full list of instances and categories.

### Extensibility 

N/A

### Configurability 

In order to inject default applications and categories into the new Application Registry, we will have to use the JSON format for files instead of XML to make data injection independent from implementation.

### Upgradability

No need to preserve the existing Application Categories to the new Model of Application Instances.

### Existing Features

The Application Registry Services and app aren't useful anymore, thus we may need to design a new feature based on different data model.
The spaces administration and layout editor applications listing has to be migrated to use the new model.
The Social Spaces Services has to not rely on application registry anymore.

### Feature Flags

No feature flag is needed

### Other Non Functional Requirements

N/A

### Security

The `Application` and `Category` models has to allow to save a list of permissions. By default, the access permission has to be set to '**Administrators**' and '**Web Contributors**' when empty. The REST endpoints has to be set with `@Secured("users")` in order to allow fine Access Control Check.

### Access 
   - As described in Architecture Guidelines, a dedicated REST for each entity will be added to manage:
     - portlets
     - instances
     - categories
   - A Vue/Vuetify application will be used to develop the Application Registry

### Services & processing

   - The spaces applications has to be deleted in favor of Spaces Applications Management embedded in the new Application instance properties drawer. Consequently, the Space Service has to delete its dependency on application-registry module **which has to be deleted**.
   - The application instances management has to be used only in layout addon without being mandatory or added as dependency to other addons.
   - An instance of portlet has to be defined as the following:
     - Portlet id (portlet name without WebARchive name)
     - Permissions
     - Portlet preferences (`List` of `PortletPreference=Name/Value`)
     - Footprint of portlet instance configuration (= `Hash of Portlet id + Portlet preferences`). This will allow to know whether a same instance configuration is used or not.
     - Whether Application can be used as a standalone page in spaces context or not
   - The `AppRegistryImportService` has to be decoupled from the `AppRegistryService` itserlf

### Data and persistence

We will reuse the existing data model of current application registry after dropping its content and deleting some columns (such as name and description wich has to be managed using `TranslationService`)

The new Data model of Application instances added in registry is:

![AppRegistryModel](https://github.com/Meeds-io/MIPs/assets/594824/4617fddd-59b2-46d1-83f0-7b336e8692dc)

**Comment by srenault-meeds** [comment]
To check please @margondicco

**Comment by margondicco** [comment]
Go Fonc 

Just one point


> If needed, this list can be updated by configuration

without overwriting customizations

**Comment by srenault-meeds** [comment]
Ok thanks @margondicco 
Description updated

**Comment by boubaker** [comment]
Ready for tech review by DAO Members (eXo : @rdenarie )

**Comment by rdenarie** [comment]
Ok for me, go tech

**Comment by boubaker** [comment]
Meeds PRs:
- https://github.com/Meeds-io/gatein-portal/pull/904
- https://github.com/Meeds-io/platform-ui/pull/785
- https://github.com/Meeds-io/commons/pull/613
- https://github.com/Meeds-io/social/pull/3859
- https://github.com/Meeds-io/layout/pull/104
- https://github.com/Meeds-io/gamification/pull/1598
- https://github.com/Meeds-io/kudos/pull/494
- https://github.com/Meeds-io/wallet/pull/520
- https://github.com/Meeds-io/analytics/pull/185
- https://github.com/Meeds-io/notes/pull/991
- https://github.com/Meeds-io/content/pull/108
- https://github.com/Meeds-io/task/pull/387
- https://github.com/Meeds-io/meeds/pull/2092
- https://github.com/Meeds-io/meeds-qa-ui/pull/263

eXo PRs (just to help FYI, don't hesitate to change @rdenarie if needed)
- https://github.com/exoplatform/commons-exo/pull/38
- https://github.com/exoplatform/ecms/pull/2362
- https://github.com/exoplatform/mail-integration/pull/67
- https://github.com/exoplatform/news/pull/1190
- https://github.com/exoplatform/chat-application/pull/744
- https://github.com/exoplatform/agenda/pull/657
- https://github.com/exoplatform/agenda-connectors/pull/111
- https://github.com/exoplatform/processes/pull/368
- https://github.com/exoplatform/documents/pull/1262
- https://github.com/exoplatform/onlyoffice/pull/246
- https://github.com/exoplatform/digital-workplace/pull/134
- https://github.com/exoplatform/data-upgrade/pull/222

**Comment by boubaker** [comment]
Ready for test on ACCs and PRs available in [comment](https://github.com/Meeds-io/MIPs/issues/139#issuecomment-2147859042)

(cc @margondicco @rdenarie )

**Comment by srenault-meeds** [comment]
> Ready for test on ACCs and PRs available in [comment](https://github.com/Meeds-io/MIPs/issues/139#issuecomment-2147859042)
> 
> (cc @margondicco @rdenarie )

Ok for me FYI @margondicco 
I let you check once more

**Comment by margondicco** [comment]
Hello ok tested and validated. Thank you @boubaker !!

**Comment by rdenarie** [comment]
Ok for me, you can proceed to merge

**Comment by boubaker** [comment]
All PRs merged. Thanks to all involved.
