### ISSUE TITLE
Page Branding Options

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#143]
## Rationale

The Meeds Layout Manager provides few options to brand a page thanks to app options (border, margin, radius).
First feedbacks from actual users of the platform have been encouraging. We'd like to push these value propositions much forward for more capabilities for our users to customize their pages.

That way, the Meeds Layout Manager will not only be visible to admin / content managers users. Indeed, the items we'd like to bring it up will address the UI experience of readers, and any other regular users./

### Top User Stories

1. Customizing Page Background
When editing a page, then before the preview option, I have an option to set metadata for the page.
When accessing the option, then a drawer suggests me to update the background with different options:
- color picker (full or gradiant)
- upload an image

2. Customizing Section Background
While editing a page, I can currently edit a section to change the column or fixed layout.
From there, I have new options to set a background as well:
- color picker (full or gradiant)
- upload an image

This background will be set to the whole width of the window, and not only to the current width.
We might study another option to enable or not the background display to whole width or only to single page app width.

3. Customizing Apps UI
While editing a page, I can edit apps properties to change their UI (border, margin, radius)
In addition to that, we will provide 2 more options:
- Add a shadow effect with option to display it only when hovering the app or not
- Add a background (color or image) with ability to set an opacity for each
Considering that sometimes, image or color can be lighter or similar to the text, we must give an option to users to customize the text-color as well.

4. Previewing the page before publishing it
While editing a page, as I can do lots of customization, I need a preview so I can check it out in a new tab.
This is different than the current WYSIWYG. Indeed, sometimes, apps cannot be displayed and often, we have "zones" related to layout edition to add apps.
This preview aims to help the admin & content-managers before publishing the page.

#### Gamification
NA

#### Notifications
NA

#### Analytics
NA

#### Unified Search
NA

### Expected Volume & Performance

N/A

### Security 

The image attachments of page containers must follow page access and edit permissions.

### Extensibility 

N/A

### Configurability 

N/A

### Upgradability

N/A

### Existing Features

N/A

### Feature Flags

N/A

### Other Non Functional Requirements

N/A

### Security

An Image Attachment plugin has to be implemented to check on page containers attachments.

### Access 
   - No change on REST API no security model

### Services & processing

N/A

### Data and persistence

The CSS properties of `Page`, `Container` and `Application` models will be stored in `properties` field `Map` as made for existing CSS properties, such as `borderColor` and `cssClass`.

**Comment by srenault-meeds** [comment]
@margondicco Can you please check this MIP out? 
I am preparing some visual assets so you can also see what we are talking about

**Comment by margondicco** [comment]
ok Go fonc :-)

**Comment by boubaker** [comment]
Ready for Tech review by DAO members (eXo : @rdenarie )

**Comment by rdenarie** [comment]
ok, go tech

**Comment by boubaker** [comment]
PRs and ACCs ready for test & review (eXo: @margondicco & @rdenarie )

Meeds PRs:
- https://github.com/Meeds-io/gatein-portal/pull/911
- https://github.com/Meeds-io/platform-ui/pull/787
- https://github.com/Meeds-io/social/pull/3880
- https://github.com/Meeds-io/gamification/pull/1612
- https://github.com/Meeds-io/layout/pull/109
- https://github.com/Meeds-io/wallet/pull/524
- https://github.com/Meeds-io/app-center/pull/329
- https://github.com/Meeds-io/analytics/pull/190
- https://github.com/Meeds-io/notes/pull/1002
- https://github.com/Meeds-io/content/pull/122
- https://github.com/Meeds-io/task/pull/391
- https://github.com/Meeds-io/meeds/pull/2148

eXo PRs:
- https://github.com/exoplatform/data-upgrade/pull/233

**Comment by rdenarie** [comment]
Ok to merge

**Comment by boubaker** [comment]
Thanks, merged to develop.
