### ISSUE TITLE
Space Settings & Roles

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#147]
## Rationale

We have, few weeks agos, allowed current space host to edit navigation and layout of their space.
This implies hosts knowing what they are doing.

In addition to that, permissions of spaces roles are not well understood by users, specifically the space host.
AND some permissions are too sensitive: space host can delete the space without knowing what they are doing.

Furthermore, the space banner is only editable from the stream. Problems are:
- Users mix this with image banner. Result is not the same. Space Banner is reminded in the spaces directory, in the search card of spaces
- Users can remove it from the layout. To edit it, you need to put it back available only on the stream page
- Users can update settings of the space from the related app excluding the space banner. Which makes the UX not consistent.

Thus, we propose by this MIP to enhance space settings for consistency and for UX sakes.

### Top User Stories

**Overview Settings**
From the space settings, I can customize my space in few clicks, including the space banner.
That means that the space banner is no more provided in the space home layout. It is replaced by an image portlet
AND the space banner is no more suggested in the portlet catalog/registry when editing layout
<img width="460" alt="image" src="https://github.com/user-attachments/assets/bc924218-df2b-44f1-a768-1832c53c60b7">

**Access & Visibility**
From the space settings, I can setup access & visibility from a dedicated option.
<img width="200" alt="image" src="https://github.com/user-attachments/assets/c336f874-42c8-4db6-aac0-74888ab11147">

**Roles**
From the space settings, I can view roles currently used in the space with their description and users.
<img width="437" alt="image" src="https://github.com/user-attachments/assets/bfc9e85c-1aae-422f-b83a-9af884d45645">

When needed I can click to the list of users. From there, I am able to:
- filter the list
- remove users from the role
- add new user from the space members
- **ONLY for members list**, option to invite people to join the space

<img width="263" alt="image" src="https://github.com/user-attachments/assets/52564929-e4d6-4fc0-96db-7790eb46f5c5">

Adding user as admin:
<img width="256" alt="image" src="https://github.com/user-attachments/assets/1a4d4f6f-e41b-4c47-9463-bc3bf2995f43">

In order to centralize the roles management, setting users as publisher or redactors will be only possible from this roles management. Hence, options from the members app will be removed.
Indeed, these roles need to be explicited and the better location for that is the space settings. 

Thus, to make the space as a "redactional" one, the admin will have to enable the option.
<img width="185" alt="image" src="https://github.com/user-attachments/assets/e43d9e59-0458-4eca-b9ee-b5dc93aac9d6">

When doing so, a drawer opens to explain the purpose of the Content Creation Restriction. Moreover, publishers previously identified are listed so you can understand they are identified as redactors and you can remove this role for some publisher.
If no publisher, a placeholder is proposed.

<img width="240" alt="image" src="https://github.com/user-attachments/assets/06511ebf-37e4-406e-a64e-bd44faa48ccb">

_Precision: Roles will be updated as follow._
- Space host will be renamed as space admin (using Crowdin)
- Space Publisher will be able to write even when a redactor is identified
- Redactor role can be removed to publishers if needed

-> The user who creates a space becomes a "Space Administrator", he can invite other members and promote them to be admin or managers or redactors
-> The space cannot have no space admin.

#### Gamification
--

#### Notifications

--

#### Analytics
--

#### Unified Search
NA

### Expected Volume & Performance

No change on stored data. The performances shouldn't be affected as well by the roles modifications.

### Security 

The Space Roles checks (ACL) has to be centralized in a dedicated API which has to be reused everywhere.

### Extensibility 

The possible actions associated to each role has to be extensible using `extensionRegistry` mechanism as made in all other extensible UI component in the platform.

### Configurability 

Default Space Template Banner has to remain, but the default space home page configuration has to change in predefined `Crowd Funding` Space template to use an `Image` portlet instead of `Space Banner`

### Upgradability

No data upgrade will be necessary, since the old Space Layout should remain as is by using the deprecated `Space Banner` portlet. Whereas, the `Space Banner` portlet instance should be deleted from portlet instances list.

### Feature Flags

N/A

### Security

All existing spaces permission checks, has to rely on this centralized points, thus a deep code cleanup has to be made to not copy/paste the algorithm of ACL but reuse the one defined and centralized in `SpaceService` API.

### Access 

The Space Settings has to **keep** its **extensibility** to let other **sections** to be added into it.
Besides, the Space invitation UI has to be reusable to use the same UI & UX from Space Members and Space Settings.

**Comment by srenault-meeds** [comment]
To check please @margondicco

**Comment by margondicco** [comment]
Hello Go fonc thank you

**Comment by boubaker** [comment]
Ready for spec tech review by DAO Members (eXo : @rdenarie )

**Comment by srenault-meeds** [comment]
Reviewed as discussed

FYI @margondicco

**Comment by margondicco** [comment]
Hello @srenault-meeds a simple request  : 

In the new drawer "admin list" , "member list" etc, coud il be possible possible to add the information "join the space the 2024.09.10" or "granted admin the ..." etc. with the hours on hover. It could be very usefull for some support use case. 

Thank you

**Comment by srenault-meeds** [comment]
Something like this?
<img width="395" alt="image" src="https://github.com/user-attachments/assets/cb1dabf8-86cb-48a5-b316-76a40325eda9">

Indeed, I find it interesting and more contextual.
I don't know if we already have this information though.

**Comment by boubaker** [comment]
> Ready for spec tech review by DAO Members (eXo : @rdenarie )

Reviewed as well and ready for tech review again.

**Comment by boubaker** [comment]
> Indeed, I find it interesting and more contextual. I don't know if we already have this information though.

No, it doesn't exist but is added as requested in the Board Tasks.

**Comment by srenault-meeds** [comment]
> > Indeed, I find it interesting and more contextual. I don't know if we already have this information though.
> 
> No, it doesn't exist but is added as requested in the Board Tasks.

I didn't add it the functional requirements for now.
We will see if to be improved later

**Comment by boubaker** [comment]
> > > Indeed, I find it interesting and more contextual. I don't know if we already have this information though.
> > 
> > 
> > No, it doesn't exist but is added as requested in the Board Tasks.
> 
> I didn't add it the functional requirements for now. We will see if to be improved later

The creation date of user & space relationship/membership has been added in this task https://builders.meeds.io/portal/contribute/tasks/taskDetail/7517 for invited & requests. This information is so available for any type of relationship (member, manager, publisher & redactor) The display isn't added for other type of relationship than pending, invited, external email invitation.

**Comment by boubaker** [comment]
> I don't know if we already have this information though.

The information is made available with this MIP but not yet displayed

**Comment by srenault-meeds** [comment]
Ok so we are able to display it if needed. Thanks a lot!
Last question:
Is that also available for old users? I mean users added to spaces before the MIP147

**Comment by rdenarie** [comment]
Hello. 
I have only one question.

> The Space Roles checks (ACL) has to be centralized in a dedicated API which has to be reused everywhere.

Can you confirm that Space Roles in the dedicated API will still rely on Organization Service under the hood ?

Thanks

**Comment by boubaker** [comment]
> Hello. I have only one question.
> 
> > The Space Roles checks (ACL) has to be centralized in a dedicated API which has to be reused everywhere.
> 
> Can you confirm that Space Roles in the dedicated API will still rely on Organization Service under the hood ?
> 
> Thanks

No change, a member will be `member:/spaces/XYZ`, a manager will be `manager:/spaces/XYZ`... A super `Spaces Administrator` or member of group `/platform/administrators` will be able to access spaces, publish and redact on spaces. The change made is just a code replacement but not a business logic change, except for publication process as described in the functional requirements.

**Comment by rdenarie** [comment]
ok. So, go tech

**Comment by boubaker** [comment]
> ok. So, go tech

welcome :)

**Comment by boubaker** [comment]
ACCs & PRs ready for review:

- Meeds-io/MIPs#147 Meeds-io/gatein-portal#975
- Meeds-io/MIPs#147 Meeds-io/platform-ui#837
- Meeds-io/MIPs#147 Meeds-io/social#4054
- Meeds-io/MIPs#147 Meeds-io/layout#222
- Meeds-io/MIPs#147 Meeds-io/gamification#1739
- Meeds-io/MIPs#147 Meeds-io/kudos#529
- Meeds-io/MIPs#147 Meeds-io/perk-store#348
- Meeds-io/MIPs#147 Meeds-io/wallet#561
- Meeds-io/MIPs#147 Meeds-io/analytics#224
- Meeds-io/MIPs#147 Meeds-io/notes#1129
- Meeds-io/MIPs#147 Meeds-io/content#239
- Meeds-io/MIPs#147 Meeds-io/poll#168
- Meeds-io/MIPs#147 Meeds-io/meeds#2422
- Meeds-io/MIPs#147 Meeds-io/meeds-qa-ui#285

(**Edit**: automatic tests added and [successfully run on mips ACC](https://ci.exoplatform.org/view/PLF%20-%20QA%20UI/job/exo-qa-ui/job/qa-ui-auto-meeds/877/Serenity/))

For eXo addons, a small adaptation has been made to make the code compiling and reusing the Backend API improvements. For the functional behavior and UI, I let you @rdenarie & @margondicco take care of this part.

The first adaptation PRs are:
- exoplatform/ecms#2402
- exoplatform/onlyoffice#266
- exoplatform/agenda#692

I see some UI incoherence, that fit the **old margins** and UX definition, like:

![image](https://github.com/user-attachments/assets/2c443b7a-e0f6-48ab-8553-8f2e9b293e02)

**Comment by margondicco** [comment]
OK bravo ! it works very well !  Also when i copy paste 200 mails 👍

Just a little point because i'm annoying

Could you add the hours when i  hover  on the date ?

![image](https://github.com/user-attachments/assets/d4a1c720-7329-4c9e-a21b-fd8c6d85c73e)

cc @srenault-meeds 

Great job

**Comment by srenault-meeds** [comment]
> OK bravo ! it works very well ! Also when i copy paste 200 mails 👍
> 
> Just a little point because i'm annoying
> 
> Could you add the hours when i hover on the date ?
> 
> ![image](https://private-user-images.githubusercontent.com/31288011/370476373-d4a1c720-7329-4c9e-a21b-fd8c6d85c73e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTEyNzksIm5iZiI6MTcyNzI1MDk3OSwicGF0aCI6Ii8zMTI4ODAxMS8zNzA0NzYzNzMtZDRhMWM3MjAtNzMyOS00YzllLWEyMWItZmQ4YzZkODVjNzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA3NTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkN2RmMTM2Yjk3NjNlNTExZjFlNTRmNGQ3OGE3NjE3NDVhZmQ0ZmIwMDI5YzQwODhhMTdiNzM4MGQzNDZiNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.b2IQ19DvJHT5p18zxhaZrHhI75vuzmiEAitDOEcDFAI)
> 
> cc @srenault-meeds
> 
> Great job

Ok thanks @margondicco.

As this one is an improvement, this is not blocker IMO for the delivery.
However, we will consider it as an enhancement once delivered.
Hence, it will be done during a maintenance time.

Tell me if you want to discuss it.

**Comment by rdenarie** [comment]
Hi,
Ok for merge on my side.
I add 2 prs on eXo side for the margin pb : 
exoplatform/chat-application#772
exoplatform/web-conferencing#334

**Comment by boubaker** [comment]
Merged to develop
