### ISSUE TITLE
Space Templates Management

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#150]
## Rationale

The software provides to user one template to use when creating a space. This helps the creator to get a pre configured space (access control, apps) so it is quicker to add a space.

Problems are that:
- only one template is provided
- this template cannot be edited
- new templates cannot be added

### Top User Stories

When accessing the administration site, I can access a templates management page for space templates.
From there, I will be able to:
- Add new template
- List existing ones
- Edit existing ones

**Each template must be extensible**
So I can
1. Duplicate it if needed (by UI)
2. Allow any Product teams to define the layout, the list of apps to be in predefined space templates

For each template, I can:
- see the icon, the name, the description
- check which members group can create spaces using each template
- list spaces created using templates
- enable / disable the use of templates
- access options to: edit properties, duplicate, delete

By default, items are sorted alphanumerically

Product Templates cannot be deleted. They can be disabled.
![image](https://github.com/user-attachments/assets/e34a393c-2b13-48fe-ad4c-97a7af16fb56)

When creating a template, then:
- First, I have to:
   - add a name
   - add a description
   - select an icon
- Then I will have to decide about the configuration of the template:
   - Mandatory creation steps: does user need to add a name, to invite users, to add properties, to update access control rules when creating the space?
       - Minimum step: Name or Invitation
       - Default config: all steps required
   - Access Control: What is the default rules to access and list the space?
       - Default config: Open / Listed
   - Permissions: 
       - Who can create a space? (default: admins)
       - Who can edit navigation of the space? (default: admins)
       - Is the space an editorial one? 
           - That means that you can decide if the content creation restriction is ON or OFF
           - If ON, only space admin and content writers can add contents
           - If OFF, any member can add contents
           - Default config: OFF
       - Who can delete a space?
![image](https://github.com/user-attachments/assets/8cb66303-aeb3-4455-a144-75dd377b774e)

Once saved, the template is listed in the templates list
AND users when creating a space will see it listed in the current dropdown of space templates.
![image](https://github.com/user-attachments/assets/8488d5ee-d704-49ee-b6c1-4c0023ad190d)

**Precisions: Default Product Space Template**
Remove the current space template
AND add following ones:

| Project  | Community | Announcement | Circle |
| ------------- | ------------- | ------------- | ------------- |
| Navigation: Space Home, Tasks, Notes More: Members, Settings | Navigation: Space Home, More: Notes, Wallet, Members, Settings | Navigation: Space Home, Apps: Notes, Tasks, Members, Settings | Navigation: Space Home Apps: Tasks, Notes | 
| Creation Steps: Name, Properties, Access Control, Invitation | Creation Steps: Name, Properties, Invitation | Creation Steps: Name, Properties | Creation Steps: Invitation | 
| Access Control: Invite Only, Listed | Access Control: Request Approval, Listed | Access Control: Open, Listed | Access Control: Invite Only, Hidden | 
| Permissions: Editorial mode off, anyone can create, admins can edit nav, space admins can delete spaces | Permissions: Editorial mode off, anyone can create, admins can edit nav, space admins can delete spaces | Permissions: Editorial mode on, only admins / web-contributors can create, admins can edit nav, only admins can delete spaces  | Permissions: Editorial mode off, anyone can create, admins can edit nav, space admins can delete spaces  | 

**Precisions: Circles**
Circles can be created without giving any name. Indeed, by default, the name is composed of first names of the user:
- If John creates a circle and invites nobody then call the space John
- If John creates it and invites Jane at the creation step: call it John, Jane
- If John creates it and invites Jane and Alfred, call it John, Jane and _1_ more
_1_ being the number of invited people

When inviting more people after the creation, no change done to the name. 
Name can be updated from space settings
No need to make sure the name is already used. Indeed, this can happen if same name used.
Default Avatar is created on this base, as it is currently. Unless it is updated manually of course.

Project Home
![image](https://github.com/user-attachments/assets/1108acfe-8555-4f28-8ab8-7553746e78dc)

Community Home
![image](https://github.com/user-attachments/assets/a66a2f87-905b-4bd9-a550-4a9bfa7cbf93) 

Announcement Home
![image](https://github.com/user-attachments/assets/5b5fed20-819f-45eb-9c6c-ccb60c19293f)

Circle Home
![image](https://github.com/user-attachments/assets/79122e6c-bfc5-4959-b2e0-62c4f460bf30)

#### Gamification
NA

#### Notifications
NA

#### Analytics
Use of space templates

#### Unified Search
NA

### Security 

Space Administrators and Platform Administrators should be able to access Space Templates Management.
The usage of Space Templates has to be restricted switch user permissions, except for Spaces Administrators and Platform Administrators who should be able to manage templates and use it to create spaces independently from specific permissions on the template.
The Space Creation process has to check allowed fields on the space template and to forbid changes from REST calls when the fields aren't allowed switch Space Template Model.
The Layout Editor Button in TopBar should be displayed switch Space Layout Permissions which should be initialized switch Space Template Layout permissions.

### Extensibility 

The current possibility of SpaceTemplate pages extensibility shouldn't be possible anymore, since the Space Template Layout has to be defined once the Space Template is imported from sources.
Thus, the Space Template definition has to be made in a single location, in Meeds project in `sites.war`.

The Meeds DAO members will be able to define their own Space Templates without having to inherit automatically the list of Space Templates defined in Meeds.

### Configurability 

The Space Templates Definition has to be simplified without XML, but with JSON `space-templates.json` (as made for `portlet-instances.json` and app center `applications.json`).

### Upgradability

The old Notion of Space Template will be deleted,, thus the `TEMPLATE` field will be removed and replaced by a field to reference the Template Identifier.

### Existing Features

The space creation drawer will reference the new stored templates list switch user permissions.

### Feature Flags

N/A

### Other Non Functional Requirements

N/A

### Access

   - A new portlet has to be added in Administration site to be able to manage space templates
   - A Dedicated REST endpoint has to be added to GET/POST/PUT/DELETE/PATCH Templates

### Services & processing

   - The Space creation process will change to be able to restrict space creation switch Space Template Permissions
   - The Space with no name specified has to be created using a generated UUID. The Space Display in this case has to be interperted and internationalized in FrontEnd using I18N files content
   - The Space Settings application has to evolve to allow/deny modification of certain settings switch associated space template
   - When deleting a space template, the flag `DELETED` has to be turned `ON` and ENABLED flag to `OFF` without affecting other space template properties. This will allow to get characteristics of the space template to handle spaces already created with it
   - The Layout Editor Button has to be made visible to all users (`*:/platform/users`) in order to allow fine check the permissions of the user whether it can be displayed or not switch Space Layout `edit-permission` field

> [!NOTE]
> This new development should use Spring Based Beans and REST endpoints. Thus, the `social-portlet` Web Archive has to be renamed to `social` in order to allow having clean REST URLs with pattern `/social/rest/...`. The Upgrade Plugin `io.meeds.layout.plugin.upgrade.LayoutApplicationReferenceUpgradePlugin` will be used for each Social Portlet to ensure to update the references in existing pages.

### Data and persistence
   - The field `TEMPLATE` has to be removed from `SOC_SPACES` to be replaced by a field `TEMPLATE_ID` to reference the Space Template Entity. 
   - A new Table will be added for Space Template Entities:

![Space Template Table](https://github.com/user-attachments/assets/7cc9cc3d-cfa6-4e4f-935f-f17c5d12d5cc)

**Comment by srenault-meeds** [comment]
To review @margondicco 
Thanks

**Comment by margondicco** [comment]
Hello 

> Minimum step: Name or Member

name or invitation ? isn't it ?

> Does the space is an editorial one? (default: no)
i don't understand this point. It's a space with redactor ? What is the purpose ?

Thank you

**Comment by srenault-meeds** [comment]
> name or invitation ? isn't it ?

yes

> Editorial space

I have added a meaning so it is easier to understanc:
       - Is the space an editorial one? 
           - That means that you can decide if the content creation restriction is ON or OFF
           - If ON, only space admin and content writers can add contents
           - If OFF, any member can add contents
           - Default config: OFF

Thanks

**Comment by margondicco** [comment]
Thank you
Go fonc

**Comment by boubaker** [comment]
Ready for spec review by DAO Members (eXo: @rdenarie )

**Comment by boubaker** [comment]
> Ready for spec review by DAO Members (eXo: @rdenarie )

A new note has been added as agreed for the `social-portlet` web archive renaming.

**Comment by srenault-meeds** [comment]
I have added following requirements:

> **Each template must be extensible**
So I can
1. Duplicate it if needed (by UI)
2. Allow any Product teams to define the layout, the list of apps to be in predefined space templates

> Default Layout of each space home

cc @margondicco

**Comment by boubaker** [comment]
After discussion with @margondicco and @rdenarie , it has been agreed to:

1. Give the possibility in Space Site to access global pages in order to be able to access space applications from each other (From Stream to Note by example) independently from Space Site navigation Tree
2. Give the possibility to extend the definition of the space template to introduce more pages in eXo package. In addition we will have to use dynamic containers to allow adding widgets in predefined pages in Meeds.
3. We will not rely anymore on Applications definitions for the Space Template but the whole pages layouts and navigation tree.

**Comment by rdenarie** [comment]
> 2\. Give the possibility to extend the definition of the space template to introduce more pages in eXo package. In addition we will have to use dynamic containers to allow adding widgets in predefined pages in Meeds.

> The current possibility of SpaceTemplate pages extensibility shouldn't be possible anymore, since the Space Template Layout has to be defined once the Space Template is imported from sources.
Thus, the Space Template definition has to be made in a single location, in Meeds project in meeds.war.

Hi, Is there a contradiction here ? 
The second quote is in the MIP technical part, perhaps it should be updated

**Comment by rdenarie** [comment]
Ok for me on tech side

**Comment by boubaker** [comment]
> Hi, Is there a contradiction here ?
> The second quote is in the MIP technical part, perhaps it should be updated

In fact in Meeds context (as the MIP gives concrete steps in Meeds context only), the space pages will be centralized.

As explained after, in the same **Extensibility** paragraph (Meeds DAO members = eXo):
> The Meeds DAO members will be able to define their own Space Templates without having to inherit automatically the list of Space Templates defined in Meeds.

eXo will be able to fully redefine the space template site layout in `digital-workplace`  using the Kernel files override mechanism (same files path definition in an addon with higher priority)

You 're right, the sentence given in the comment `Give the possibility to extend the definition of the space template to introduce more pages in eXo package` should be `Give the possibility to` **override** `the definition of the space template...`.  And I will change the location from `meeds.war` into `sites.war` in spec.

Thanks for the Heads-up.

**Comment by boubaker** [comment]
The files location changed from `meeds.war` to `sites.war` in spec. Thanks again.

**Comment by boubaker** [comment]
> [!NOTE]
> Referencing PRs in a comment since the `Development` Links Section of the MIP **doesn't allow adding more than 10 PRs**

Meeds PRs:
- https://github.com/Meeds-io/gatein-portal/pull/992
- https://github.com/Meeds-io/social/pull/4131
- https://github.com/Meeds-io/layout/pull/237
- https://github.com/Meeds-io/gamification/pull/1762
- https://github.com/Meeds-io/wallet/pull/604
- https://github.com/Meeds-io/kudos/pull/547
- https://github.com/Meeds-io/perk-store/pull/354
- https://github.com/Meeds-io/analytics/pull/236
- https://github.com/Meeds-io/notes/pull/1184
- https://github.com/Meeds-io/content/pull/277
- https://github.com/Meeds-io/poll/pull/173
- https://github.com/Meeds-io/task/pull/439
- https://github.com/Meeds-io/pwa/pull/26
- https://github.com/Meeds-io/meeds/pull/2517
- https://github.com/Meeds-io/meeds-qa-ui/pull/294

**Comment by boubaker** [comment]
[PRs](https://github.com/Meeds-io/MIPs/issues/150#issuecomment-2432176400) and ACCs ready for review by DAO Members (eXo: @margondicco @rdenarie )

BTW, some Adaptations was made on eXo codebase, there are still some changes to handle to define which eXo app to add in predefined templates. All you have to do is to copy the Sites definition from [this location](https://github.com/Meeds-io/meeds/tree/feature/mips/webapps/plf-sites-extension/src/main/webapp/WEB-INF/conf/portal/group/template) and define it in digital-workplace in order to make the needed modification switch your business need.

**Comment by rdenarie** [comment]
Hi @boubaker 
I have few references to social-portlet in exo code.

Let me a moment to create PR about it, before validating this MIP, thanks

**Comment by boubaker** [comment]
> Hi @boubaker I have few references to social-portlet in exo code.
> 
> Let me a moment to create PR about it, before validating this MIP, thanks

Take your time, you have a whole week as agreed in established MIP process to review and validate

**Comment by rdenarie** [comment]
One more question : 
for existing pages and portal, how the application-ref is modified from social-portlet to social ?

**Comment by boubaker** [comment]
> One more question : for existing pages and portal, how the application-ref is modified from social-portlet to social ?

In Meeds PR:
![image](https://github.com/user-attachments/assets/afe3d844-d8eb-483e-b36d-1cfbb7916990)
https://github.com/Meeds-io/meeds/pull/2517/files#diff-317a216f3a7b08fa33b197ade61a176187978f3e09d8040b0e4dda2514c8980fR800

**Comment by rdenarie** [comment]
Ok for me on technical side

**Comment by srenault-meeds** [comment]
FYI, documentation ready [here](https://docs.meeds.io/meeds-guides/admin-guide/organizing-communities/managing-space-templates)
I will review the video once we can edit layout and navigation + once I have fixed the audio pb of my headset

**Comment by margondicco** [comment]
Hello everything is ok

thank you @srenault-meeds 

cc @Julien-Dubois-eXo FYI for our internal KB

Thank you

**Comment by boubaker** [comment]
Will wait for Meeds-io/MIPs#165 in order to merge all items together and avoid to upgrade custom Space Templates.

**Comment by rdenarie** [comment]
Feedbacks : 

- Currently, some template requires to invite at least one user at creation. We often have the usecase of a user who want to prepare a space before invite another member. This will be no more possible for community and project spaces. @margondicco should we keep that ? or remove the "invitation" requirement ? => feature improvment issue : https://github.com/Meeds-io/meeds/issues/2551
- In template list, the status column miss a tooltip to explain what is the switch. We have this switch in user management and it is clearer. Can we add the tooltip for space templates ? This point is not mandatory before merging the mip.

**Comment by boubaker** [comment]
> Feedbacks :

Thanks for the Feedbacks, can you please @rdenarie open dedicated issues for this since the MIP is supposed to be in "To merge" status.

**Comment by margondicco** [comment]
Hello everything is ok. Thank you

cc @boubaker @srenault-meeds

**Comment by boubaker** [comment]
> Hello everything is ok. Thank you
> 
> cc @boubaker @srenault-meeds

Thanks @margondicco , the Go for merge is already given for this MIP ([here](https://github.com/Meeds-io/MIPs/issues/150#issuecomment-2441638530)) do you mean ok for merge on Meeds-io/MIPs#165 ?

**Comment by margondicco** [comment]
Yes it's a OK for merge

Thank you

**Comment by srenault-meeds** [comment]
Ok we consider it as a go for the #165 .

Thanks @margondicco

**Comment by boubaker** [comment]
Merged to develop
