### ISSUE TITLE
Space Public Site

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#151]
## Rationale

Meeds provides an option to create subgroups thanks to spaces.
Rules to access the space depends on the space admin's will. Indeed, it can be completely private (unlisted / closed) while it can be open to anyone.

The problem is that when a user wants to know more about the space, its goal or its members, the user has to join the space.
In the meantime, other social network tools provide easy way to display these informations to non member. 
This helps user to know if that can be interesting to join it or to request to join it.
Moreover, even closed spaces but listed can get the need to publish what the community is working on with a simple description, news, etc.

Currently, it is not possible. So we propose to provide an option to publish a space public site.

### Top User Stories

Space administrators will have a new option from the settings of their space to enable, edit and manage a space public site.

<img width="343" alt="image" src="https://github.com/user-attachments/assets/c284476e-02df-4438-843e-999333677db9">

When accessing it, they'd be able to:
- Make it visible for:
1. space admins only (default value)
2. Members only
3. Users only (excl. external users)
4. Users & External Users
5. Anyone (even non platform members)
- access the edition of the public site
- copy link

> URN: PrettyName of the space at the time the Space Public Site is created
The edition / customization of the name of the space will be worked during a dedicated MIP for Space URL IMPV.

**Precision: In case the space is hidden, then it will not be possible to make it visible. An information will be sent to the user (tooltip or text) so he is aware about it**

<img width="313" alt="image" src="https://github.com/user-attachments/assets/f79729e0-673b-42a2-b432-8f2b329a888f">

When editing the public site, they will see a default layout provided with:
- Space banner
- description
- admins
- members
For this, we need to create 3 portlets:
- Description
- Members
- Admins

They will be able to:
- edit the layout so they can add more apps or so they can review the layout if needed
- view as a user

<img width="407" alt="image" src="https://github.com/user-attachments/assets/50ff9046-61f3-4883-ba2c-a463fd37527a">

Once the public site is made visible, then:
- Name of the space public site
> Default name = space name. From the space public site edition drawer, option to set another name (see above)
> URL= /portal/[name of the site]

- Members of the space can access it through an info added in the space home layout (description app):
<img width="331" alt="image" src="https://github.com/user-attachments/assets/9f9eb92b-9a53-4635-8975-b9b8b45232ff">

> In that case, they have a "Enter" CTA from the topbar to access the space in the same tab

- Non members of the space can access it by clicking to the space card / space name when not being member of it
> In that case, they have a "Join" or "Request" CTA or nothing from the topbar to request to join the space when possible
<img width="532" alt="image" src="https://github.com/user-attachments/assets/9d14710a-1af8-47aa-8fbe-27b01ee95c38">

- Non members of the platform can access it thanks to shared link
> In that case, they have a "Login" / " Sign up" CTA from the topbar to login / sign up into the platform
> When doing so, then, depending on the ability to access the space (open / validation / closed), they will be considered as a member (open) or requester (validation). That way, they can find this space in their spaces list once joined.

<img width="534" alt="image" src="https://github.com/user-attachments/assets/9d5ee4fb-8f8d-4590-8683-7e03da5b024c">

#### Gamification
--

#### Notifications
--

#### Analytics
--

#### Unified Search
Access the space public site when searching for the space and not member

### Security 

The Space ACL and roles management has to remain as it is currently (No change is needed to ACL model).

### Extensibility 

N/A

### Configurability 

N/A

### Upgradability

N/A

### Existing Features

The Space Access Page has to remain as is to be used for spaces not having a published public site visible to the connected user.

### Feature Flags

N/A

### Other Non Functional Requirements

N/A

### Security

The Space Access check algorithm defined in `SpaceAccessHandler` has to remain as is and should evolve to allow redirection to space public site switch required business logic.

### Access 

- Three new Portlets will be added for `Members`, `Managers` and `Description`
- The existing Portlet `SpaceInfos` will remain to not break existing spaces pages and let the upgrade be made manually when needed/requested by the space manager
- A new dedicated REST endpoint will be used to allow manage the Space Publication properties only (The Space manager doesn't have access to change the site layout nor configuration through regular REST endpoints, thus a dedicated endpoint has to be added to allow such operation)

### Services & processing

- The `SpaceAccessHandler` has to evolve to let users access by default to public site when it's published
- The Permanent Link API will be used to be able to copy the direct access link to the public site independently from its `uri`
- The Space public sites will remain all time as standalone sites
- The site access permissions will be used to store the user preference

### Data and persistence

- A new field `PUBLIC_SITE_ID` will be added in `SOC_SPACES` TABLE to reference the public site technical identifier even when not published
-  A new field `PUBLIC_SITE_VISIBILITY` will be used as a flag to store the choice of Space public site visibility.
- The existing field `PORTAL_SITES.PROPERTIES` will be used to set the new property `SPACE_ID` to reference the associated space
- The existing field `PORTAL_SITES.PROPERTIES` will be used to set the new property `IS_SPACE_PUBLIC_SITE` as a flag with default value `true` (could be useful for future usages, especially when having more than one site associated to the space)

**Comment by srenault-meeds** [comment]
To check please @margondicco 
Thanks

**Comment by margondicco** [comment]
Hello my points


**Point 1**
> Space administrators AND space managers will have a new option from the settings of their space to enable, edit and manage a space public site.

only spaces managers if the platorm administrator add the permissions in space management ?

**Point 2**
can i open the public site of the space form the space directory ?


**Point 3**
as we did with the portlet top bar login, could it be possible to add a dedicated portlet for the action "Joint "Request", etc. in order to customize the standard page. For exemple if i want to add the button in another place.

Thank you

**Comment by srenault-meeds** [comment]
Hello,

> Point 1

My bad. No space admins can enable & manage public site

> Point 2
Can i open the public site of the space form the space directory ?

Yes, when not member of the space, you click to the card, it sends you to the space public site
And if member, you can access the space public site from the description app.

> Point 3
as we did with the portlet top bar login, could it be possible to add a dedicated portlet for the action "Joint "Request", etc. in order to customize the standard page. For exemple if i want to add the button in another place.

I don't understand the feedback. Let's discuss it :)

**Comment by margondicco** [comment]
Go fonc

**Comment by srenault-meeds** [comment]
Added requirements:
- If Name (URI) already used, then error so the user sets a new name
- If Name (URI) previously used by another space BUT deleted, then ability to use the same URI
- Option to make the public site the default home for space members
- If the space is hidden, this won't be possible to make the space public site enabled.

**Comment by boubaker** [comment]
Ready for technical review by other DAO Members ( eXo: @rdenarie )

**Comment by srenault-meeds** [comment]
Edit: No customization of space public Name for now.
It will be worked during a dedicated MIP.

Cc @margondicco

**Comment by boubaker** [comment]
Meeds PRs:
- https://github.com/Meeds-io/gatein-portal/pull/981
- https://github.com/Meeds-io/platform-ui/pull/840
- https://github.com/Meeds-io/commons/pull/659
- https://github.com/Meeds-io/social/pull/4082
- https://github.com/Meeds-io/layout/pull/226
- https://github.com/Meeds-io/gamification/pull/1746
- https://github.com/Meeds-io/kudos/pull/531
- https://github.com/Meeds-io/wallet/pull/572
- https://github.com/Meeds-io/analytics/pull/229
- https://github.com/Meeds-io/notes/pull/1150
- https://github.com/Meeds-io/meeds/pull/2455

**Comment by boubaker** [comment]
Thanks for the 'Go-tec' label @rdenarie 

Ready for Review @margondicco @rdenarie 

Meeds PRs:
- https://github.com/Meeds-io/gatein-portal/pull/981
- https://github.com/Meeds-io/platform-ui/pull/840
- https://github.com/Meeds-io/commons/pull/659
- https://github.com/Meeds-io/social/pull/4082
- https://github.com/Meeds-io/layout/pull/226
- https://github.com/Meeds-io/gamification/pull/1746
- https://github.com/Meeds-io/kudos/pull/531
- https://github.com/Meeds-io/wallet/pull/572
- https://github.com/Meeds-io/analytics/pull/229
- https://github.com/Meeds-io/notes/pull/1150
- https://github.com/Meeds-io/meeds/pull/2455

eXo PRs:
- https://github.com/exoplatform/ecms/pull/2408
- https://github.com/exoplatform/dlp/pull/63
- https://github.com/exoplatform/onlyoffice/pull/268
- https://github.com/exoplatform/data-upgrade/pull/249
- https://github.com/exoplatform/chat-application/pull/774
- https://github.com/exoplatform/jitsi/pull/153
- https://github.com/exoplatform/web-conferencing/pull/336
- https://github.com/exoplatform/platform-private-distributions/pull/391

**Comment by boubaker** [comment]
> Ready for Review @margondicco @rdenarie

I 've adjusted as well the styling of Conf call button and fixed the bug of chat drawer opened under other drawers with dedicated PRs attached in the edited comment here https://github.com/Meeds-io/MIPs/issues/151#issuecomment-2390785889

**Comment by srenault-meeds** [comment]
@margondicco FYI, documentation ready [here](https://docs.meeds.io/meeds-guides/user-guide/administering-a-space/showcasing-your-space)

**Comment by rdenarie** [comment]
Ok for me thanks.

**Comment by margondicco** [comment]
Hello one little feedback.

Even if the space isn't hidden or closed, the following message is displayed

![Image](https://github.com/user-attachments/assets/09a47e0d-5b51-46ad-a4d7-a0f08e5c5515)


cc @srenault-meeds 

Thank you

**Comment by srenault-meeds** [comment]
Yes we take care of it. Thanks

**Comment by boubaker** [comment]
> Hello one little feedback.

Fixed. Thanks.

**Comment by margondicco** [comment]
Hello go

**Comment by boubaker** [comment]
Meeds PRs merged to develop @rdenarie. To continue the merge of eXo PRs, I let you rebase the branch develop-exo
