### ISSUE TITLE
Rewards Management Review

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#154]
## Rationale

Every week, hubs are using our rewarding feature to reward their contributors.
After years of using it, it comes to the team to review the Rewards Management as it is currently implemented.

Indeed, we have multiple problems to solve, including:
- Better UX to set the budget, to send rewards and to follow the sending (globally or per user)
- Inform when the wallet balance is not ok with the budget configuration
- Inform when the UEM has been sent
- Provide options to access achievements, rewarding details of each user

In addition to it, this review will prepare the next steps for:
- allocating a budget for each program
- delegating budget management for program owners
- rewarding with other tokens than the MEED one

#### Access to reward / UEM / wallet / perkstore

To guarantee we can use gamification without forcing the usage of wallet, rewards, perkstore, we reorganize functionally the admin menu:
- Gamification: Kudos configuration, Connectors, Badges
- Rewards & Blockchain: Setup, Wallet, Rewards

That also means that we must be able to use gamification without installing the rewards addon.
Indeed, only if rewards addon is in the package, then wallet, wom connection, perkstore are also listed and proposed in the platform

##### 1. Access to Budget Setup

As admin or rewarding admin, I can access the budget setup from the same page to manage rewards
Rewards & Blockchain > Rewards

##### 2. Page when no budget yet configured
**With placeholder and CTA to fund the wallet and to connect to WoM**
<img width="622" alt="image" src="https://github.com/user-attachments/assets/de186615-3e11-4abf-b934-68a2c431fae7">

##### 3. Budget Setup Options

When requesting to setup the budget, a drawer opens to provide different configuration options:
- Periodicity, timezone of contributions
- Threshold to get rewarded
- Budget type: Fixed or Per Contributor 
- Budget value
_Precision:_ No more fixed budget per point. It has not been used at all for now.

Depending on the parameters, a distribution forecast is proposed below those options so the admin can see if that fits his requirements

<img width="243" alt="image" src="https://github.com/user-attachments/assets/25fdfc76-ac16-40c3-9702-555c10d1e312">

Once the budget has been setup, then the configuration is reminded. 

<img width="469" alt="image" src="https://github.com/user-attachments/assets/11fd0805-9d80-48fc-9d7f-03652dcd430f">

Then you can reward contributors as soon as you have contributions during the period

##### 1. Manage Rewards

As admin or rewarding one, I can access the rewards management from the same page you use to set the budget up.

Below the budget configuration, I have reward reports sorted chronologically from the current period to previous ones. These are listed as card and depending on the periodicity selected in the budget configuration.

Each card provides key infos as:
- Period
- Status (waiting for the period to end, to reward, rewards sent)
- Contributors number
- Participants number
- Contributions number
- Budget

<img width="475" alt="image" src="https://github.com/user-attachments/assets/b79bbff0-1f62-4f29-9d68-bb40043c60e5">

##### 2. Access to a period details

Clicking to a card allows the admin to see the rewarded users list, sorted from the most rewarded to the less one, including no participants.
From there, it is possible to:
- export the current list displayed to a .xlsx file
- filter the list per user

<img width="584" alt="image" src="https://github.com/user-attachments/assets/05e81ef8-1ada-464d-8fe5-d3648a72905b">

When the rewards have not been sent yet, then the admin can click to reward
Once done, a placeholder tells the admin it is in progress
<img width="100" alt="image" src="https://github.com/user-attachments/assets/17522a2a-78a6-4063-88fa-da9f078da674">

If WoM connected, a placeholder tells him the report is being sent
<img width="100" alt="image" src="https://github.com/user-attachments/assets/d721327e-28e8-4482-a596-e2f45fd0a98d">

Once ok, then the info about the reward status (AND if the case, the UEM report) is reminded
<img width="100" alt="image" src="https://github.com/user-attachments/assets/9f7904e7-6d62-45f3-8e0a-8f85ea71ce34">

If this process has encountered difficulties, then the placeholder is updated so the admin can better know what needs to be done with a CTA when possible

#### Gamification
Admin entry to manage gamification items

#### Notifications
NA

#### Analytics
NA

#### Unified Search
NA

### Expected Volume & Performance

N/A

### Security 

N/A

### Extensibility 

N/A

### Configurability 

N/A

### Upgradability

N/A

### Existing Features

N/A

### Feature Flags

N/A

### Other Non Functional Requirements

N/A

### Security

N/A

### Access 

In this MIP we will make some UI and UX adjustments for admin rewards management and update admin navigations for gamification and rewarding.
We will create a new portlet to set the reward budget (through a new drawer component) and list the reward reports with different details and remove all old unnecessary components.

### Services & processing

N/A

### Data and persistence

N/A

**Comment by AzmiTouil** [comment]
Ready for Tech review by DAO members (cc @rdenarie )

**Comment by srenault-meeds** [comment]
And ready for func review @margondicco :)

**Comment by margondicco** [comment]
Hello thank you and well done ! Go Fonc. :-)

**Comment by rdenarie** [comment]
Go tech, thanks

**Comment by AzmiTouil** [comment]
PRs and ACCs ready to be reviewed by DAO Members (@rdenarie @margondicco )

**Comment by rdenarie** [comment]
PRs are ok for me.

But, I have still a problem on community-dev : the reward page does not load.
It works the last moment I check, on friday morning

The last information I had was that you want to modify the configuration for wallet and blockchain access. Did you modify it ? did it fix the problem ? Why it is not loading now ?

Thanks

**Comment by boubaker** [comment]
> PRs are ok for me.
> 
> But, I have still a problem on community-dev : the reward page does not load. It works the last moment I check, on friday morning
> 
> The last information I had was that you want to modify the configuration for wallet and blockchain access. Did you modify it ? did it fix the problem ? Why it is not loading now ?
> 
> Thanks

There can be an unstable Blockchain problems on community-dev, thus I think we shouldn't waste more time. Let's stick to the process for now, is it ok for you on ACCs ? We will deal with maintenance issues if something happens on Tribe, since we already tested all migrations and everything on Builders.

**Comment by rdenarie** [comment]
ok for me on tech side, you can process to merge

**Comment by boubaker** [comment]
Merged to develop

**Comment by srenault-meeds** [comment]
Documentation added/reviewed for:

- review of contributions
- rewarding management
- joining UEM

https://docs.meeds.io/meeds-guides/admin-guide/managing-rewards/rewards-management
https://docs.meeds.io/meeds-guides/admin-guide/managing-rewards/meeds-rewards-program
