### ISSUE TITLE
Contribute Site Review

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#155]
## Rationale

After few months using it, the Contribute Site needs to be reviewed for better understanding.
Moreover, pages and portlets listed in this site needs to be updated for compliance with layout options (style framework, responsiveness of portlets depending on the height, etc.)

### Top User Stories

**Navigation Review**

The contribute site navigation will be reviewed as follow:
- Root: Overview Page
- Programs
- Actions
- Wallet

**Pages Review**
- Overview Page and portlets will be reviewed to make sure this is compliant with new options provided by the Layout Manager:
1. New layout: Review of layout and addition of the contribution board
<img width="491" alt="image" src="https://github.com/user-attachments/assets/6231d196-2ea8-4d17-9533-3cf0569c5b3e">

2. Image Portlet: 
- Ensure the width of the image is still displayed no matter the device used
- Provide options for users to crop image depending on the zone where the image is added
- Compliance with Fixed or Dynamic Section

3. Display options for portlets to make sure the user can set it upon the expected layout
- Remove the maximum of items to list for programs and actions
- Propose for each portlet options to sort the list and to display a number of items
_Example:_
<img width="749" alt="image" src="https://github.com/user-attachments/assets/ce6b4f42-3530-489c-b35e-6be124ccf31a">

- Option to display more attributes if needed
_Example:_
<img width="920" alt="image" src="https://github.com/user-attachments/assets/cb6d4b4a-e2eb-4a2c-a98e-4f3ce5db37be">

3. Rework of badges display
- Better look / Bigger badge
<img width="420" alt="image" src="https://github.com/user-attachments/assets/d793af44-0dfb-4006-a981-f2bfe89578c3">

- Access of badges list review when clicking to it, and detail of contributions for a program
<img width="617" alt="image" src="https://github.com/user-attachments/assets/434099ff-6dca-404b-a4af-89aed8e1c781">

4. Review of Rewards, kudos portlet
- Kudos: Rework the portlet to be compliant with new layout and style
- Rewards: Rework the portlet to be compliant with new layout and style
- Ability to see transactions and rewards activity
<img width="611" alt="image" src="https://github.com/user-attachments/assets/3d54d296-6e1b-46b9-9b84-89678f3f5584">

5. Contributions Board: only list the contributions of the current user. Keep the "hosted" view for program owners only in an other app

- Other pages will be reviewed to adapt some cases
**Precisions:**
- Contribute Site will be imported for every platforms, including existing ones
- Apps that have been reworked will be inheritated by default for any platform
- Existing platforms will need to remove application like My Reputation

#### Gamification
NA

#### Notifications
NA

#### Analytics
NA

#### Unified Search
NA

### Expected Volume & Performance

N/A

### Security 

N/A

### Extensibility 

N/A

### Configurability 

N/A

### Upgradability

Contribute Page has to be automatically upgraded since its layout is updated. 

### Existing Features

N/A

### Feature Flags

N/A

### Other Non Functional Requirements

N/A

### Security

N/A

### Access 

The UI of existing portlets will change to make the display dynamically updated using the [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) API. The limit of items to fetch to display has to be independent from height to not having to refetch results each time the blocks are resized. Thus, a maximum of items has to be retrieved by default, only if the whole block isn't displayed.

### Services & processing

N/A

### Data and persistence

N/A

**Comment by boubaker** [comment]
Ready for Func & Tech review by DAO members (cc @margondicco @rdenarie )

**Comment by rdenarie** [comment]
Hi,
You will you manage the update of existing portal ?

**Comment by rdenarie** [comment]
Ok for me

**Comment by margondicco** [comment]
@srenault-meeds ok for me

**Comment by boubaker** [comment]
PRs & ACCs ready for review (eXo: @margondicco @rdenarie )

**Comment by srenault-meeds** [comment]
Thnaks @boubaker 
I have added programs, actions and I have used apps and layout. 
LGTM.

I let @margondicco check.

I will prepare the documentation once ok for you

**Comment by margondicco** [comment]
Hello

the portlet My reputation is displayed in the app registry 

![image](https://github.com/user-attachments/assets/2a5ae3dd-e6f2-400b-8d0c-dbc65857eef9)

IMO we must remove the portlet

**Comment by boubaker** [comment]
> the portlet My reputation is displayed in the app registry

In fact, it's deleted for new servers, but for the servers which had deployed the 7.0.0-M07 (App Registry MIP), it has to be deleted manually. If not deleted and used in a page, the instance will display the `Kudos Overview` (An upgrade plugin has been already used to modify the instance reference).

**Comment by srenault-meeds** [comment]
hello @margondicco 

Two documentation items have been added:
- [Overview page layout and management of this page](https://docs.meeds.io/meeds-guides/admin-guide/introduction/onboarding-users-with-actions)
- [Sharing informations and using the image croping tool](https://docs.meeds.io/meeds-guides/user-guide/collaborating-in-spaces/sharing-and-interacting)

I let you confirm if ok to merge it

**Comment by margondicco** [comment]
Hello ok for me

**Comment by boubaker** [comment]
> Hello ok for me

Thanks, @rdenarie WDYT ?

**Comment by rdenarie** [comment]
Ok for me, you can merge this MIP
