### ISSUE TITLE
My Craft Site Review

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#156]
## Rationale

After few months using it, the Contribute Site needs to be reviewed for better understanding.
Moreover, pages and portlets listed in this site needs to be updated for compliance with layout options (style framework, responsiveness of portlets depending on the height, etc.)

### Top User Stories

**Navigation Review**
The contribute site navigation will be reviewed as follow:
- Root: Stream Page (no more in the meeds site)
- Tasks ("My Tasks")
- News ("My Content")
- Team ("My Team")

**Pages Review**

<img width="800" alt="image" src="https://github.com/user-attachments/assets/f9f2ce97-ee10-4df5-b27b-0efc018a76d0">

Stream page will be moved to this site. 
**Precision:**
- External stream page will be merged to this page **(only for new platforms)**
- Who's online gadget must be listed only for non - external users

And this stream page will be reworked a little:

Section (Dynamic 2 columns - 8+4)
- Stream
- Who's Online
- Tasks
- Actions
- Spaces List

Following portlets will be removed from stream page
- No more getting started portlet
- No more User Activity Portlet
- No more Suggestions

_Precision for spaces gadget:_
1. Gadget listing spaces with different settings proposed for the administrator:
- List spaces the user is member of (set to true by default)
- Spaces of the current user: 4 by default (from 0 to 25)
- Spaces recently visited during a period: 2 by default (from 0 to 25) for 30 days by default (from 1 to 90 days)
- Spaces most active during a period: 2 by default (from 0 to 25) for 30 days by default (from 1 to 90 days)
**Precisions: External users won't see recently visited and most active. Only their spaces are listed**
2. If the height is fixed and there are too much items to list, a scrollbar is proposed
3. A see all allows the user to access the complete list, organized by type (spaces, recent, most active) in a drawer with load more if needed
4. Header display, contextual depending on what to display
- If two or more space type to list, then display "Spaces"
- If only spaces of the current user, display "Your Spaces"
- If only most active spaces, display "Popular Spaces"
- If only recently visited, display "Recent Spaces"
5. Item display
**Spaces**
- Space Avatar
- Space Name (2 lines maximum)
- In case, the space is hidden or has been deleted, then the space will be identified as "Hidden" and not accessible

**Removal of instances**
- The old spacesList instances will be removed and replaced by this new one
- The popular spaces instance will be removed from contributions' instances
- The popular spaces gadget will be replaced by this gadget listing 10 most active spaces, incl. spaces you are not member of

Other pages will be reviewed to adapt some cases

**Precision: For existing platform, don't override the root page as some customers have customized it**

#### Gamification
NA

#### Notifications
NA

#### Analytics
NA

#### Unified Search
NA

### Expected Volume & Performance

N/A

### Security

N/A

### Extensibility

N/A

### Configurability

N/A

### Upgradability

No auto upgrade will be made for sites `meeds` and `mycraft` to not affect existing layouts.

### Existing Features

N/A

### Feature Flags

N/A

### Other Non Functional Requirements

N/A

### Security

N/A

### Access 

This MIP will just make some UI adjustments and reconfigure the `mycraft` site pages and navigations. We will need, to add an additional Widget to develop in `Social` which will list the recent spaces. In addition, the Who's online widget has to be reworked to hide itself when an external user attempts to display it.

### Services & processing

N/A

### Data and persistence

N/A

**Comment by boubaker** [comment]
Ready for Func & Tech review by DAO members (cc @margondicco @rdenarie )

**Comment by rdenarie** [comment]
ok for me

**Comment by srenault-meeds** [comment]
@margondicco I let you check please.

Regarding the notes App, this is not sure we will provide a widget. Indeed, we know that you're working on notes currently and we don't want to create something that will need to be reviewed weeks after.

Thanks

**Comment by margondicco** [comment]
Hello 

The MIP128 will be merged soon. If it's possible the notes widget could be a great improvement. 

Some clients customize the site My craft. So the improvements must not removed the customization

For example : 

![Image](https://github.com/user-attachments/assets/0c919a62-523d-4e66-9573-893b143b484a)

**Comment by srenault-meeds** [comment]
Ok requirement added regarding the root page.

**Comment by margondicco** [comment]
Thank you go fonc

**Comment by srenault-meeds** [comment]
Edit: Added detailed specification regarding notes gadget to make sure we are aligned about it

**Comment by srenault-meeds** [comment]
Edit: @margondicco I suggest you to review the spec as I have reviewed it following internal discussions.
Thanks

**Comment by margondicco** [comment]
Hello re go fonc :-)

**Comment by srenault-meeds** [comment]
Thanks.

I let you check @boubaker if the tech spec needs to be reviewed

**Comment by boubaker** [comment]
> Thanks.
> 
> I let you check @boubaker if the tech spec needs to be reviewed

Thanks, ready for tech spec review again (eXo: @rdenarie )

**Comment by rdenarie** [comment]
Ok for me

**Comment by boubaker** [comment]
ACCs & PRs ready for review (eXo @rdenarie @margondicco )

BTW: I recommend to test MIPs Bundle on **Tribe Dev** in order to test the modifications on an existing installation.
BTW2: I think an adaptation is needed for MyCraft Site definition overridden here https://github.com/exoplatform/digital-workplace/blob/develop/digital-workplace-webapps/src/main/webapp/WEB-INF/conf/sites/portal/mycraft/navigation.xml

**Comment by rdenarie** [comment]
Ok for me, you can proceed to merge

DW PR : https://github.com/exoplatform/digital-workplace/pull/142

**Comment by srenault-meeds** [comment]
Documentation added @Julien-Dubois-eXo @margondicco if needed

https://docs.meeds.io/meeds-guides/user-guide/exploring-a-meeds-hub/entering-your-workspace
