### ISSUE TITLE
Spaces Directory IMPV

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#158]
## Rationale

The space directory lists all space the user is member of and any other space he can see (space visible, not hidden).

Options are proposed to users so they can access space, see more informations, make it a favorite space, etc.
Problems are those options are not well accessible and sometimes there are nothing to display. Without forgetting the display of banner and avatar which needs to be updated for better modernity.

Problems list:
_Space banner_
- We cannot see the featured image 
- It is partially hidden by the space avatar

_Make a space a favorite_
- If the banner is darker or same tone as the star icon, then we cannot see

_Options position_
- leave or join or request to join at the bottom
- Three dots at the top
- Favorite at the top

_Access to space info (verso of the card)_
- You need to be member of the space to see the description and the admins list

Moreover, users request to send a kudos to a whole space and they cannot do this. It could be interesting to make it a quick-win.

### Top User Stories

**Spaces Card Review:**
- Review of banner and avatar position
- Display the name in 2 lines
- Display the description in 3 lines
- Display number of members
- Add the red dot of unread activities when there are some

<img width="648" alt="image" src="https://github.com/user-attachments/assets/27794eca-ea68-47b2-a0fc-0dac09644d7f">

_When member of_
- Suggest options at the bottom to make it a favorite, to send a kudos to space members, to leave the space

_When admin of_
- Suggest three dots to edit settings, to leave and to delete

_When public site enabled and available for members_
- Suggest link in the card with a globe icon

**Spaces Filter Review**
- As we plan in the future to list spaces per category, per template
- Review the way quick filters are proposed -> Suggest an advanced filter option (better display for mobile in the same time)

<img width="226" alt="image" src="https://github.com/user-attachments/assets/9ff5eed0-414a-4d97-bb40-fabb94a11f19">

**Send a kudos**
- Option to send a kudos to the whole space
- Kudos sent to the space and posted in the space feed
- Space members can get notified for it (as mentioned or as a new notification - to study)
- Space Kudos = User Kudos for number of kudos allowed per user to send
- New gamification event: Send a kudos to a space
- Add this kudos type in the list of kudos in the overview page

<img width="230" alt="image" src="https://github.com/user-attachments/assets/4f74b776-e82a-4c1e-9868-7ee5ac6262ff">

#### Gamification
Send a kudos to a space - New action

#### Notifications
Kudos to a space - Notification to add OR notification for every member of the space

#### Analytics
--

#### Unified Search
Ensure the space card in the unified search is reviewed as well

### Security 

No modification on ACL design.

### Extensibility 

Make sure that the Space Card bottom buttons are extensible so that addons can define its actions with priority/order definition.

### Configurability 

N/A

### Upgradability

No change on data model is requested, thus no data upgrade will be needed.

### Existing Features

N/A

### Feature Flags

N/A

### Other Non Functional Requirements

N/A

### Security

There is no modification on current ACL model.

### Access 
   - Use the extension registry to define new actions to add in Spaces Card
   - No API change should be made here, but for Kudos endpoint to ensure it allows sending Kudos to spaces

### Services & processing
   - The Kudos Data Model relies on Social Identity Id, thus any Identity Provider (Social, User, Group ...) should be able receive a Kudos. We will have to ensure just that the business logic supports this new entity type to receive a Kudos.

### Data and persistence

N/A

**Comment by margondicco** [comment]
Hello ok for me Go Fonc

**Comment by boubaker** [comment]
Ready for Tec Spec Review by DAO Members (eXo: @rdenarie )

**Comment by rdenarie** [comment]
Go tech

**Comment by boubaker** [comment]
PRs and ACCs ready for review by Meeds DAO members (eXo: @margondicco @rdenarie )

**Comment by srenault-meeds** [comment]
Documentation updated:

[Browsing spaces](https://docs.meeds.io/meeds-guides/user-guide/exploring-a-meeds-hub/browsing-people-and-spaces)
[Sending a kudos](https://docs.meeds.io/meeds-guides/user-guide/earning-recognition/encouraging-and-congratulating)

**Comment by rdenarie** [comment]
Hi,

I have functionnal point I don't understand :
- there is no possibility to send a space kudos through the activity composer. The only way to send a space kudos is in space directory ?
- In space card in unified search, we have the favorite button, but not the kudo button. Wanted behaviour ?


As it is only functionnal question, it is ok for me to merge

**Comment by margondicco** [comment]
Hello my  feedbacks. Great improvements ! Thank you

**### 1/ We lost the button chat** 

![image](https://github.com/user-attachments/assets/6006e89d-b187-481c-9f2b-ac511c575d2b)

Here
![image](https://github.com/user-attachments/assets/53c2d2cc-84b8-4e16-9717-42622c46aa04)

here
![image](https://github.com/user-attachments/assets/842dc888-1ffa-43e5-a38e-a1b0f09b3be6)

and  here

![image](https://github.com/user-attachments/assets/3b1f53ba-d313-4c10-a5bf-5429a6522991)


and here
![image](https://github.com/user-attachments/assets/8e25d816-afe8-4646-a3a1-8fa1f2aca09e)

2/ Accessibility issue here

Buttons do not have an accessible name

<img width="837" alt="image" src="https://github.com/user-attachments/assets/a419baef-3247-4c72-af9d-299901601fda">

**Comment by boubaker** [comment]
> ### 1/ We lost the button chat

Same on Tribe actually

1/ For **Space Popover** (Not chat extension)

![image](https://github.com/user-attachments/assets/8460f803-d603-4cf0-95ed-7fd1f5bfcff6)

2/ And **Left Menu**

![image](https://github.com/user-attachments/assets/dc0a8f51-8a87-479a-85e7-d33f2857dd52)

> 2/ Accessibility issue here

It's a maintenance issue not related to the MIP since it's about the accessibility of generic **Application Toolbar** component

**Comment by boubaker** [comment]
BTW, in Tribe we don't have Chat option in

3/  Spaces list neither

![image](https://github.com/user-attachments/assets/341d6e2f-c5dc-4cd4-80b7-cd97f713c11e)

**Comment by margondicco** [comment]
yes It seems like an older regression. We'll check it but i have a concern

I'am worried about the many button here if we had the button chat

![Image](https://github.com/user-attachments/assets/b6f570a6-5b1e-42c4-bf33-28b9f3346b71)

@srenault-meeds what do you think ?

**Comment by srenault-meeds** [comment]
Thanks for your feedbacks.

To summarize, we have following feedbacks. I have added suggestions to improve it:
- **No option to send kudos to space from the composer:** 
Not for this MVP. Indeed, that'd require check on permissions to audience / visibility and that'd bring confusion between personal network and space. So for now, you can send kudos from the card and by hovering the space name

**- Kudos option in search card**
We will see what we can do to improve this for this MIP or as a maintenance issue

**- Missing Chat option for space popovers / left menu**
It seems to be an old regression. After discussing it with Morgan, we suggest you take care of it

**- Space details panel**
Once the MIP is delivered, we will propose an enhancement of the actions list to make it more readable.
A 3-dots option will suggest to make the space the homepage and it will suggest too to mute the space
Only following options will be listed: mark as unread, bookmark and kudos
![image](https://github.com/user-attachments/assets/3110be76-fc92-41c6-aba5-7b7a44c790d2)

Example for eXo:
![image](https://github.com/user-attachments/assets/6615eff8-a09a-4b66-abdd-96957d9d3376)

**Comment by srenault-meeds** [comment]
Thanks for your feedbacks.

To summarize, we have following feedbacks. I have added suggestions to improve it:
- **No option to send kudos to space from the composer:** 
Not for this MVP. Indeed, that'd require check on permissions to audience / visibility and that'd bring confusion between personal network and space. So for now, you can send kudos from the card and by hovering the space name

**- Kudos option in search card**
We will see what we can do to improve this for this MIP or as a maintenance issue

**- Missing Chat option for space popovers / left menu**
It seems to be an old regression. After discussing it with Morgan, we suggest you take care of it

**- Space details panel**
Once the MIP is delivered, we will propose an enhancement of the actions list to make it more readable.
A 3-dots option will suggest to make the space the homepage and it will suggest too to mute the space
Only following options will be listed: mark as unread, bookmark and kudos
![image](https://github.com/user-attachments/assets/3110be76-fc92-41c6-aba5-7b7a44c790d2)

Example for eXo:
![image](https://github.com/user-attachments/assets/6615eff8-a09a-4b66-abdd-96957d9d3376)

**Comment by srenault-meeds** [comment]
@margondicco @rdenarie feedback for search card of spaces is fixed:
![image](https://github.com/user-attachments/assets/d13d0f77-1830-478c-8a99-d60253fff5b0)

Regarding others, please review my summary: https://github.com/Meeds-io/MIPs/issues/158#issuecomment-2402076595

**Comment by margondicco** [comment]
OK for me

we'll take the point of the chat button after the enhancement you suggest

Thank you

**Comment by srenault-meeds** [comment]
yes, the enhancement will not be done right now but soon. I will inform you as soon as we do it

**Comment by boubaker** [comment]
Merged to develop
