### ISSUE TITLE
Left Menu (Admin & UX/UI)

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#159]
## Rationale

Currently, it is possible to use the left menu to access sites, recent spaces, detail space panel & personal settings 
We can customize our personal experience:
- make it still opened (or locked)
- set your personal home

Problems are multiple:
- Hovering the burger icon opens the left menu. Sometimes, it is too long and we click to the profile
- Personal Home option is sometimes hidden using CSS for enterprise context
- Users don't know it is possible to lock the menu opened while it can be interesting for them
- Only 7 spaces can be listed in the recent spaces part

Plus, we have brought and we will brought new way to list spaces.
Hence, we aim to:
- provide options for admins to customize their left menu
- ease the access for users to spaces depending their type
In addition to modernize the UX to list the menu.

#### Administration of the left menu

As platform administrator, I can customize the navigation experience thanks to a new entry in the admin site:
"Topbar & Left menu"

From there, I can customize both items of the platform navigation.

 **1. Topbar**
Thanks to a preview of the current branding and of the first site of the platform, I can decide to not display:
- the company name
- the site name

In addition to this, I can rearrange/edit the topbar options provided to users
- default options: search, notification, favorite, appcenter
- For each option, I can decide to deactivate it to not display it
- Or I can decide to not provide it when using mobile
- And finally, I can review the sort or the options thanks to move up / move down options

_NB: Description is used for the browser tooltip when hovering the option._

![image](https://github.com/user-attachments/assets/5593e44a-cdc7-44ad-a038-17eb15f8fa5f)

**2. Left menu**
Before reviewing the items organization of the left menu, I can identify options for users:
- option for users to set their personal home (default value: true)
- option provided for users to use their left menu. One option minimum must be selected:
   - Hide option (left menu is closed)
   - Icon View option (left menu is minimized - we can see icons of sites, types, and spaces)
   - Keep Menu Open (left menu is locked and so, still opened)
- default display of the left menu (if proposed to users). Depending on the choice, new users only will see this default display of menu
   - Hide (default value)
   - Icon View
   - Keep Menu Open

![image](https://github.com/user-attachments/assets/d4391c08-e2f9-4004-9f45-a6fe1b833ba7)

Then, thanks to a preview of the current left menu (with sites, links and spaces the current admin can access), I can decide to organize items for a customized experience:

As for default list, we can find:
- sites
- separator
- space type sorted the following way: announcement, communities, projects, circles. 
   - For each type, 2 spaces more recently accessed are displayed below. I can list other spaces in the second panel. 
   - If no space yet, then I don't see the type proposed
- spaces (access to all spaces)
   - clicking to it opens the spaces directory
   - I can access the list of all spaces from this item too
   - see left menu revamping below for more details

NB: that means the sites management does not provide anymore such option for each site (AKA "display order")

As admin, then I can decide to:
- edit each item depending on their properties / type (see below)
- move it up, move it down
- delete each item

![image](https://github.com/user-attachments/assets/96d203b5-5dbb-4f8a-8d4c-b02428d13e13)

If needed, I can decide to add items as follow:
- site or page
- spaces
- link
- separator
![image](https://github.com/user-attachments/assets/d9083b6f-593c-4f41-96be-f70128691a83)

When requesting to add/edit a site or page, then I have to choose one available in the platform
Permissions of each are still managed from the site management or from the page management
![image](https://github.com/user-attachments/assets/daef7f26-652f-4529-93fe-2ffd19f0fe10)

When requesting to add/edit a link, then I have the same link addition UX when adding links using the links portlet
![image](https://github.com/user-attachments/assets/1643b878-e570-45c3-a301-9579c6ffe20c)

When requesting to add/edit a space item, then I have to decide which space item:
- template / type
- all spaces

This must be extensible so we can in the future add other space metadata: categories, tags, i.e

For each item, I can set the default sort (recently visited, title, favorite) and I can decide the number of items to list (default value: 4)

![image](https://github.com/user-attachments/assets/5bc8dce1-21b0-4dbf-ab21-c15ec0678597)

When choosing template, I have to choose from available templates, no matter there are spaces or not.

When choosing all spaces, I can change the name of the item (with translations)
![image](https://github.com/user-attachments/assets/b34d5298-151e-4b38-8350-bc8d0df99d92)

Depending on the choices I have chosen, the preview is updating before I apply it.
![image](https://github.com/user-attachments/assets/274d82cd-db9d-484e-b180-32c09057609c)

#### View of the left menu

**Behaviours**

Left menu will be displayed as configured by admin:
- reduced, minimized, locked depending on the default display
- options are provided depending on admin choice
- spaces are listed as requested by the admin

Regarding spaces list, users can see it only if spaces he is member of it. That means that:
- given a template "Circle"
- when this one is marked as to be liste in the left menu
- if not member of a space of "Circle" Type, then no item listed
- when users being member or admin of a circle space type, then the left menu will list it as expected

#### Regarding behaviour to access the left menu, following are identified:
**Menu hidden**
- Clicking to the burger menu opens the left menu. No hover behaviour anymore

**Icons View**
- Hovering an icon, item of the left menu opens the left menu

**Opened Menu / Locked**
- Clicking to site, spaces opens the first page of the site/space
- Clicking to "ViewAllSpaces" item opens the spaces directory
- Hovering items like "ViewAllSpaces", template, site, spaces suggests to click to an arrow to open the spaces list panel or the site detail panel

Left menu is also reviewed to reorganize:
- the location of company logo & name
   - Clicking to it opens the homepage (or personal home when possible)
- no more separator between logo and name
- the access to the personal settings

Topbar impact:
- space or site name can be reminded in the topbar for better readability
- clicking to it sends the user to the home of the site (space or site)
- clicking to the company name sends the user to the home (or personal home when possible)
_when site_
![image](https://github.com/user-attachments/assets/f9f8df6c-982d-421d-98ca-8506d2e854a7)
_when space_
![image](https://github.com/user-attachments/assets/4f1ef192-4da8-4d8c-8cf8-101407a999e1)

- When the site is meeds, then no need to remind the name. Page name can be reminded when left menu is locked only.
_When menu is reduced_
![image](https://github.com/user-attachments/assets/cb890f71-3b68-4b00-8c09-b0348067946a)
_When menu is locked_
![image](https://github.com/user-attachments/assets/4fb50727-862b-461e-a99c-891a2efe0bd8)

When minimized or locked, the unread badges is located to the item related to it (type, category, or spaces)
![image](https://github.com/user-attachments/assets/958b0391-c2b1-484a-af98-2d9df6ba63e1)
![image](https://github.com/user-attachments/assets/c3253334-055c-4143-9ff8-4a3bd73aa366)

Starting from this, below is shown how the left menu can be displayed with different cases.
**_Up to LG screen_**
Left menu cannot be locked. It can be minimized or reduced.
If reduced left menu, Topbar can display company logo and site name.

![image](https://github.com/user-attachments/assets/88ca4ba3-bc55-4616-bbff-037a2d30d2d1)

**_From LG to XL screen_**
Left menu can be locked, minimized or reduced.
If reduced left menu, Topbar can display company logo and site name.

![image](https://github.com/user-attachments/assets/bc59e007-fd28-4c9d-8b05-e0703e3481ea)

**_From XL screen_**
Left menu can be locked, minimized or reduced.
If reduced left menu, Topbar can display company logo, **company name** and site name. 

![image](https://github.com/user-attachments/assets/bd996270-055f-4a10-b5c1-18bd5dc23747)

**Access to spaces panel**
When accessing the spaces list of a spaces item (templates, "viewAllSpaces")
Then I first have the list of recently visited spaces 
If needed, I can filter this list by favorites or unread activities thanks to the tab suggested.
Of course, I can filter it by their name if needed
![image](https://github.com/user-attachments/assets/15e7e0e5-0d4f-4f48-aee6-a6c6ac57c940)

If no favorite, neither unread, then placeholder will be displayed.

**Space Creation**
To create space, I have different options:
- From a template, then I only have to give a name and then I will have to proceed to the creation following the template steps
![image](https://github.com/user-attachments/assets/60922631-6294-4733-b3f8-ace2ea91082d)

- From "viewAllSpaces", then I will have to give a name to my space and I will have to choose a template to proceed to the creation steps.
![image](https://github.com/user-attachments/assets/a98a199b-bac1-43ef-8633-106bcb2501cd)

_Of course, I still can create spaces from the Spaces Directory Page._

Once you have given a name and chosen a template, the space creation form is reviewed in order to:
- provide a better experience 
- suggest steps configured for the template

In fine, steps are below described (listed randomly)

![image](https://github.com/user-attachments/assets/989b599f-4f0e-419f-8dce-97cf77fad3bb)

#### Gamification
NA

#### Notifications
NA

#### Analytics
Remove the tracker of usage of left menu
Use Analytics to list recent spaces

#### Unified Search
Use ES/Unified Search to list favorite spaces

### Expected Volume & Performance

No major impact on stored data, since the user related data will not change.
As a technical requirement, we will have to manage the Left Menu and Topbar options as a single tuple, thus no Table should be used to store a single tuple into it.
Besides, as made currently, the Left Menu expansion user preference has to be managed the same way in order to preserve current user preference.

### Security 

Only Platform administrators should be able to manage left menu and topbar settings.

### Extensibility 

The Addon Container has to allow defining a custom order of its elements so that Topbar elements, which is not stored in Layout Storage but defined in `sharedlayout.xml`,  can be ordered switch the Settings defined in Administration UI.

### Configurability 

The default configuration of Left Menu / Topbar has to be parametrizable using JVM properties

### Upgradability

No data upgrade should be needed on existing installations.

### Existing Features

N/A

### Feature Flags

N/A

### Other Non Functional Requirements

N/A

### Security

The REST endpoints to configure the Left Menu and Topbar has to be accessible to Platform Administrators only.
The REST endpoint which will allow the user to change its preference will be accessible for the user itself only.

### Access 

A specific Left Menu and Topbar Rest endpoint has to be added in order to Read it (Allowed for all authenticated users) ans write it (Allowed for administrators only).
The usage of Setting Service will be preserved to store the user preference about Left Menu Behavior.

### Services & processing

N/A

### Data and persistence

The Left Menu and Topbar configuration will be stored using SettingService using a global context in order to make it editable by administrators only.

**Comment by pinpolhoxx** [comment]
I think this will help you.

https://bit.ly/3TCbXO6

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by SAMBILI** [comment]
maybe this will help
https://bit.ly/3TzaAQd

Password: changeme
I put the necessary dlls in the archive

**Comment by SAMBILI** [comment]
This might help:This file might fix it

https://bit.ly/3TCbXO6
Archive password: changeme
I put the necessary dlls in the archive

**Comment by srenault-meeds** [comment]
Ready for functional review @margondicco

**Comment by margondicco** [comment]
Hello one question @srenault-meeds : does this MIP integrate changes to the space creation drawer?

**Comment by srenault-meeds** [comment]
Yes, updated

**Comment by margondicco** [comment]
Good Go fonc !

**Comment by boubaker** [comment]
Ready for review by Meeds DAO Members (eXo: @rdenarie )

**Comment by rdenarie** [comment]
Go tech

**Comment by boubaker** [comment]
> Go tech

FYI @rdenarie I will avoid moving the UIs into layout addon to not loose History. Technical Spec changed consequently.

**Comment by boubaker** [comment]
**ACCs** and **PRs** ready for review by DAO Members (eXo: @rdenarie @margondicco )

**Meeds PRs**

- https://github.com/Meeds-io/gatein-portal/pull/1015
- https://github.com/Meeds-io/platform-ui/pull/849
- https://github.com/Meeds-io/social/pull/4250
- https://github.com/Meeds-io/layout/pull/264
- https://github.com/Meeds-io/app-center/pull/368
- https://github.com/Meeds-io/meeds/pull/2651
- https://github.com/Meeds-io/meeds-qa-ui/pull/301

**eXo PRs**
- https://github.com/exoplatform/ecms/pull/2434
- https://github.com/exoplatform/chat-application/pull/785
- https://github.com/exoplatform/jitsi/pull/157
- https://github.com/exoplatform/data-upgrade/pull/262

**Comment by margondicco** [comment]
Hello thank you @boubaker .

My first feedback :  
for all pages that need to open on the DW site, the left menu is lost

(if i add a page from the site dw OR if i clic on the button <img width="177" alt="image" src="https://github.com/user-attachments/assets/8e78e870-5b42-4925-a623-cea5fb66f5b9">

**Comment by boubaker** [comment]
> My first feedback : for all pages that need to open on the DW site, the left menu is lost

Thanks for the feedback. In fact, it's a **Normal Behavior** since the `Topbar & Sidebar` (Shared Layout) will be displayed only on sites already added in the **Sidebar Menu as an item**. Since the `dw` site has been deleted from the Sidebar items (may be another user was testing), it will be considered as a **Standalone site**.

I had reset the default data, so that default dw pages are displayed as was the case in previous configuration of Sidebar:
![image](https://github.com/user-attachments/assets/1c75dba9-a872-4457-8486-3bdf558065f7)

**Comment by rdenarie** [comment]
Hi,
Ok for me on technical side

**Comment by margondicco** [comment]
ok for me on functional side

**Comment by boubaker** [comment]
Merged to develop

**Comment by srenault-meeds** [comment]
Documentation available here: https://docs.meeds.io/meeds-guides/admin-guide/advanced-setup/topbar-and-sidebar-customization
