### ISSUE TITLE
Left menu review

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#16]
## Rationale

When using the platform, you have a left menu accessible from the burger menu.
This left menu offers the user access to generic pages like, stream, people, spaces, recent spaces, settings and administration when having administrator role
By default, the menu is collapsed and the user needs to open it to display the list. Then, it collapsed back.
From this menu, we can open second level menu like spaces of the current user and administration when being administrator.

Since it has been proposed to users, we collected feedbacks and we brought new options including for spaces that we need to adress to make the platform browsing smooth and smart.

## 1. Functional requirements
- Firstly, we'd like to review the way we can access to spaces to be clearer and consistent with the platform: 
** from the left nav, the arrow to display second panels (recent spaces or admin) are not displayed by default. The user needs to hover the line to see it and then he can click to it to display the second panel. This to avoid opening the panel while the user doesn't want to see it. (using mobile, you can click to the whole line)
** position the "add a space" access from the left nav directly to be consistent with other tools using this way to create spaces / communities. That way, the recent spaces panel proposes only a way to filter by space
** when the second panel is opened, the arrow (and the plus item for recent spaces) is remained displayed, the user can click to it to close the second panel
![access to second panel](https://user-images.githubusercontent.com/58853195/190340799-66311171-c3f4-4c26-905a-7fde78c7fa4c.jpg)

![access to second panel mobile](https://user-images.githubusercontent.com/58853195/190340775-c3294a11-9fc3-4b23-b0f7-58bbd3e4c967.jpg)

- Then, for any space listed in the main left nav or in the recent spaces panel, the user will have access to more options so he can directly access an app or so he can manage to do an action: bookmark it for example (mobile or desktop)

Items listed in the space details panel depends of:
* actual items listed in the space navigation (sort, name)
* the permissions to the page (i.e settings only for space hosts)
* any new item added from the settings in a space should be listed depending the name, the sort and permissions

![space details panel](https://user-images.githubusercontent.com/58853195/190341215-eb64c36b-e624-4e4d-9eac-e6f661979a56.jpg)

![space detail panels from recent spaces](https://user-images.githubusercontent.com/58853195/190341210-878010bb-cee2-43d3-a00a-b8fb0f4ef505.jpg)

![space detail panel - mobile view](https://user-images.githubusercontent.com/58853195/190341206-36fbdc8c-6b9c-4a54-ae59-54221ad41209.jpg)

#### 2.1. Performance requirements
Knowing that navigation menu is displayed in all pages, it should be as much performant as before when changing the current new UI behaviors. Thus, the pre-loaded urls has to be updated when changing the fetched resources by UI improvements made.

#### 2.2. Feature Flag
* Feature flag name: `exo.feature.leftMenuReview.enabled`
* Default value: true
* By disabling this feature flag, the Left menu will be reset to use the Legacy Old Behavior without any improvement made by the current MIP.
* To set a target audience, you can use `exo.feature.leftMenuReview.permissions` to select a group of users.

#### 2.3. Security requirements (Authentication, Authorizations, Audit track / traceability, data retention…)
No addition security context is required to the existing one, which is:
- Display only authorized pages in Menu
- Display only authorized and accessed spaces in Menu
- Display administration menu only if user can access to one or multiple administrative pages

## 3. Impacts
- Documentation to update

#### Access (GUI, API…)
No new REST API endpoints will be added.

#### Services & processing
No change on Service & Storage layer will be made by this improvement.

**Comment by srenault-meeds** [comment]
+ icon to be removed? To check with analytics usage tracking
Perf to be studied to make sure the left menu displays smoothly (currently, it is sometimes long to display)

**Comment by margondicco** [comment]
Number of line for the description area : i prefer 4 line

Is the order of the applications present in detail the one defined by the space host ?
Is the permissions on the page associated with the node taken into account ?
Do we display all the nodes associated with the navigation of the space ?

**Comment by srenault-meeds** [comment]
> Number of line for the description area : i prefer 4 line

Let's try it with 2 lines as it is the case for topbar space popover and let's see if we need to improve it afterwards.

> Is the order of the applications present in detail the one defined by the space host ?

Yes, it should be

> Is the permissions on the page associated with the node taken into account ?

Yes, it should be

> Do we display all the nodes associated with the navigation of the space ?

Yes, it should be

I updated the detail

**Comment by srenault-meeds** [comment]
> Let's try it with 2 lines as it is the case for topbar space popover and let's see if we need to improve it afterwards.

Ok, after discussing it let's do it a 4 lines description max so it is better and useful.

**Comment by rdenarie** [comment]
Technically ok for me.

Functionnally, I'm afraid that we add more clicks to access to recent spaces list or to space detail. I like the current behaviour that when I hover "Recent spaces", the second panel opens. Now, I will have to point the arrow (small target), then click on it to see all recents spaces. 
I think it is just a feeling for the moment, but perhaps we need to study this feedback after the development.

**Comment by srenault-meeds** [comment]
> I think it is just a feeling for the moment, but perhaps we need to study this feedback after the development.

Sure will do

**Comment by margondicco** [comment]
Hello @Samuel-Renault-eXo feature flag here ?

**Comment by srenault-meeds** [comment]
yes

**Comment by margondicco** [comment]
Hello

`Feature flag to be added when merged to develop - true by default` 

I prefer false by defaut

**Comment by boubaker** [comment]
> Hello
> 
> `Feature flag to be added when merged to develop - true by default`
> 
> I prefer false by defaut

The Feature Flag doesn't exist in fact. I will specify  this in a dedicated section for more clarity. (It was added performances requirements section, in case we will add a feature flag for it)

**Comment by boubaker** [comment]
Feature Flag section added:
> #### 2.2. Feature Flag

@rdenarie @Samuel-Renault-eXo

**Comment by boubaker** [comment]
> > Hello
> > `Feature flag to be added when merged to develop - true by default`
> > I prefer false by defaut
> 
> The Feature Flag doesn't exist in fact. I will specify this in a dedicated section for more clarity. (It was added performances requirements section, in case we will add a feature flag for it)

Done for Feature Flag sentence in performances section and moved in the dedicated section of Feature Flag, @margondicco

**Comment by srenault-meeds** [comment]
We should have the feature flag added and at least true by default. Afterwards, exo can decide to make it false by default in their package if needed.
I check with the team why this missing

**Comment by boubaker** [comment]
Feature Flag section updated with newly added Property

**Comment by boubaker** [comment]
@rdenarie to review please

**Comment by rdenarie** [comment]
done

**Comment by rdenarie** [comment]
PRs validated.

**Comment by boubaker** [comment]
> PRs validated.

Thanks
