### ISSUE TITLE
Spaces Management & Permissions

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#160]
## Rationale

This MIP aims to solve two different problem type:

### 1. Super Space Admin Permissions
Currently, platform admins can manage permissions to allow users or group members to:
- manage any space

Problems are that the permissions to manage a space is not understood by platform admins:
> What will these _super space admins_ be able to do?
> What will they be able to access?
> Do they need to be members of space to manage it?

### 2. Spaces Permissions Management
Currently, space admins can delete their space and cannot access the option to edit layout / navigation
Of course, space templates configuration can know provide such permissions. Yet, it must be possible to specify permissions for a space

Problems are:
- when deleting a space, all data are removed. And this option must be given to users who are aware about this impact.
- few space admins can be trained to layout/navigation management. It is not possible to give them access to this feature unless you pre configure space templates as is. Yet, sometimes, it must be possible to specify permissions for one space and not any space.

Starting from this, the spaces management page will be reviewed to unify with the global platform UX.

### Top User Stories

**Spaces Management Page Review**
Admins of the platform can decide to review the permissions for space admins and management thanks to the whole new spaces management page.

_Only platform admins can access this page._

![image](https://github.com/user-attachments/assets/b3bde9ca-9cbc-4fe3-ac22-e421050e2fe3)

From there, each space is listed to admin even when not member of it.
For each space, it is possible to:
- access settings
- sync members (AKA group binding)
- apply template 
- save as template
- manage permissions 
- delete space

![image](https://github.com/user-attachments/assets/62f5ca54-41ee-4499-9c50-e47c78c861e7)

For sync members, we will review the UX as follow:
- drawer to manage auto-import rules
- from this drawer, access to import reports in a full screen

<img width="550" alt="image" src="https://github.com/user-attachments/assets/7dec42da-da3a-44cd-ba65-1c2c17a81978">

When requesting to apply a template, then admin has to choose a template.
Once applied, layout and navigation of template is applied to the space (overwriting previous layout and navigation)
And permissions can be updated too on demand, by the platform admin

![image](https://github.com/user-attachments/assets/a9460caa-111e-4af7-a4c1-6a53d7c3b808)

When requesting to save as a template, then admin has to proceed to the template creation as expected.
Layout, navigation and preferences are saved to create the template.

No change for following options:
- edit settings
- delete

**Bulk Actions**

When selecting multiple spaces, then admins can access bulk actions:
- Sync members
- Apply template
- Update Permissions
- Delete spaces

![image](https://github.com/user-attachments/assets/24c03ba9-bb7d-4bf4-a067-5170d26af1e6)

When the page doesn't list all items, then a suggestion to select all ones matching the filter is done.
![image](https://github.com/user-attachments/assets/0f581483-9f9a-4fc3-ba42-d90696d0c98c)

When doing a bulk action, then a loader is proposed next to add CTA.
From there it is possible to list ongoing actions. 
Until it is done, no more bulk actions can be done. It has to be finished so the admin can launch another processing.
![image](https://github.com/user-attachments/assets/91d83efd-4c3b-40be-8c84-5887a9b5b129)

**Permissions per space**

When willing to update permissions for a space, then following permissions are proposed to be updated:
- Navigation Management
- Space Public Site Enablement
- Deletion

If space templates already configured permissions, then remind this configuration to admins to avoid confusion

![image](https://github.com/user-attachments/assets/a1b4fa26-eaa8-4904-8483-2b728dca1210)

**Super Space Admins**

In addition to this, the platform admin can identify "Super Space Admin" per template. That means we don't have anymore the permission for spaces management.

Thus, from the space template configuration, we need to review the stepper:
1. Creation steps
2. Template Management
3. Space Configuration
4. Space Permissions

From template management, we have two options to decide:
- who can create spaces? 
- who is super space admin?

With an option to see an explainer of this profile.
Once identified, super space admin does not have access to the spaces management page.
Yet, they can create spaces, edit its settings and navigation, manage space public site, and delete it.
Even if not members of those spaces.
When a template is applied to a space, then identified super space admin access this new space.

![image](https://github.com/user-attachments/assets/23af15fd-fbd3-4345-b01f-8034481c71b9)

Space Permissions groups from now on these items:
- navigation management
- public site management
- space deletion
These items can be overwritten from spaces management as explained above

![image](https://github.com/user-attachments/assets/bb3be9cf-24a8-4de2-8e79-2e4ee01cd33c)

### Expected Volume & Performance

N/A

### Security 

The centralized Spaces Management will be deleted in favor of Spaces Management permission per Space Template.
Thus, no absolute Spaces Administrators feature is allowed, but it will depend on the Space's associated template permissions.

### Extensibility 

The Spaces Administration Toolbar actions has to be extensible to allow making bulk administrative operations from an addon.

### Configurability 

N/A

### Upgradability

N/A

### Existing Features

N/A

### Feature Flags

N/A

### Other Non Functional Requirements

N/A

### Security

The Spaces Administration ACL has to change to consider the used template of the space. Thus, the `AuthorizationManager` Service defined in Social (which extends `UserACL` Service coming from Portal) has to consider the associated template of the space to make ACL checks.

### Access 

   - The old UI has to be dropped and reworked with new UI/UX guidelines
   - The `SpacesAdministrationRest` is not needed anymore, thus has to be dropped

### Services & processing

   - A new field for Spaces Managers will be added in `SpaceTemplate`, which will not be duplicated in created `Space`, but centralized in `SpaceTemplate`. This means that changing the spaces managers group on a template has to affect all existing spaces created with the associated template.

### Data and persistence

   - A new field `SPACE_MANAGER_PERMISSIONS` will be added in Table `SOC_SPACE_TEMPLATES`.

**Comment by srenault-meeds** [comment]
@margondicco to check.
Thanks

**Comment by margondicco** [comment]
Hello @srenault-meeds is it interesting to add a column "space template" ?

**Comment by srenault-meeds** [comment]
yes :)

![image](https://github.com/user-attachments/assets/73558789-6087-456d-bac2-d47958142b71)

**Comment by srenault-meeds** [comment]
Updated with:
- template info in the table
- bulk actions added: permissions, auto import members

**Comment by margondicco** [comment]
Hello Go fonc

Sorry for the delay

**Comment by srenault-meeds** [comment]
@margondicco as discussed, I have reviewed the way we will identify Super space admins and I have reviewed the way we can manage bulk actions.

Please check it again.

**Comment by margondicco** [comment]
Hello perfect @srenault-meeds  Go Fonc

**Comment by boubaker** [comment]
Ready to review the technical specification by DAO members (eXo: @rdenarie )

**Comment by rdenarie** [comment]
Go tech

**Comment by boubaker** [comment]
Meeds PRs (not ready to review yet):
- https://github.com/Meeds-io/gatein-portal/pull/1002
- https://github.com/Meeds-io/social/pull/4191
- https://github.com/Meeds-io/layout/pull/257
- https://github.com/Meeds-io/analytics/pull/245
- https://github.com/Meeds-io/gamification/pull/1774
- https://github.com/Meeds-io/kudos/pull/553
- https://github.com/Meeds-io/notes/pull/1209
- https://github.com/Meeds-io/content/pull/309
- https://github.com/Meeds-io/poll/pull/178
- https://github.com/Meeds-io/task/pull/449
- https://github.com/Meeds-io/meeds-qa-ui/pull/297

**Comment by boubaker** [comment]
Ready for review by Meeds DAO association Members (eXo : @margondicco @rdenarie )

Meeds PRs :
- https://github.com/Meeds-io/gatein-portal/pull/1002
- https://github.com/Meeds-io/social/pull/4191
- https://github.com/Meeds-io/layout/pull/257
- https://github.com/Meeds-io/analytics/pull/245
- https://github.com/Meeds-io/gamification/pull/1774
- https://github.com/Meeds-io/kudos/pull/553
- https://github.com/Meeds-io/notes/pull/1209
- https://github.com/Meeds-io/content/pull/309
- https://github.com/Meeds-io/poll/pull/178
- https://github.com/Meeds-io/task/pull/449
- https://github.com/Meeds-io/meeds-qa-ui/pull/297

eXo PRs:
- https://github.com/exoplatform/ecms/pull/2431
- https://github.com/exoplatform/processes/pull/416

**Comment by rdenarie** [comment]
Hello. 
I observe 2 problems : 

To reproduce : 
- Create a space
- In the space, click on "Article" to create an article
- Fill the article, and publish it. 1st pb, the confirmation is displayed twice : 
![image](https://github.com/user-attachments/assets/c251a9a6-d17b-457c-b44d-d5d9f5cc9432)
- Continue to update the article (do not close or change tab). 
- Save. 2nd problem, there is an error when saving + the popup is displayed twice : 
![image](https://github.com/user-attachments/assets/ffd99a13-267c-4505-9e8b-244efbbb890a)

**Comment by margondicco** [comment]
Hello ok for the functional review

**Comment by boubaker** [comment]
> Hello. I observe 2 problems :

> * Fill the article, and publish it. 1st pb, the confirmation is displayed twice :

**Fixed**, thanks, it **was a regression** on reusable Alert component in social which has been improved to allow a whole custom Vue component.

> * Save. 2nd problem, there is an error when saving + the popup is displayed twice :

Not related to this MIP since it's reproduced in Experience FT ACC as well when being in the same test conditions, see video:
[Capture vidéo du 2024-11-16 06-31-35.webm](https://github.com/user-attachments/assets/6d066e80-0cef-423f-8942-b22564febc44)

In fact, as I see, it's a **known behavior** and to fix it you made a **workaround** by disabling the "Save" button until the "**Draft gets saved**". The server stack trace is:

```java
Error when updating the news 45 io.meeds.news.rest.NewsRest<http-nio-0.0.0.0-32001-exec-15> 
java.lang.NullPointerException: Cannot invoke "org.exoplatform.wiki.model.DraftPage.getId()" because "draftPage" is null
	at io.meeds.news.service.impl.NewsServiceImpl.updateArticle(NewsServiceImpl.java:1834)
	at io.meeds.news.service.impl.NewsServiceImpl.updateNews(NewsServiceImpl.java:317)
	at io.meeds.news.rest.NewsRest.updateNews(NewsRest.java:235)
```

The workaround isn't on `develop` yet, thus you see the error when saving quickly the article before the draft gets saved.

**Comment by srenault-meeds** [comment]
Feedback report:
Given making the space public site visible to registered users
When I am not member of the space and i click to the space card 
Then a blank page opens instead of seeing the space public site 
Precision: it is ok when making it visible to anyone 

@margondicco FYI

**Comment by boubaker** [comment]
> Feedback report: Given making the space public site visible to registered users When I am not member of the space and i click to the space card Then a blank page opens instead of seeing the space public site Precision: it is ok when making it visible to anyone
> 
> @margondicco FYI

Fixed, thanks.

**Comment by srenault-meeds** [comment]
Hello,
Thanks @margondicco and @boubaker 

@rdenarie as the error message for posting an article is not related to this MIP, Do you have other feedbacks?
Thanks

**Comment by rdenarie** [comment]
No, it is ok on my side, go for merge

**Comment by boubaker** [comment]
Merged to develop

**Comment by srenault-meeds** [comment]
Documentation done
