### ISSUE TITLE
News to notes - Part 5 - Publication of a article and note

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/MIPs#161]
## Rationale

We need to review the publication drawer to enhance the publication experience for notes and news. Here are the gaps expressed by end-users: 

- not possible to publish a note in a news list
- scheduling option is enabled only if the space is on editorial mode and only for redactors and space admin
- not possible to hide the redactor and the redaction on a news

### Publication drawer

- UX at opening = expand by default

- **Check properties (metadata)**
  - Quick edit for both properties

- **Publication location:** 
  - Activity stream 
  - news list targets:
    - rework of target selected display
    - review of publishing permission in a news list
    - Currently, space admins are identified as publisher so they can publish articles. Content Writers still cannot publish 
    - Publishing option suggested only if you have one target and for which following permissions are set: [**Publisher/space hosts + the space has permission on a target**] OR [**member of a group that has permission on a target**]

- **Schedule**: 
    - Post on the Stream and publish the News list
    - Depublication only for the News list
    - Available to all members no matter if a redactor is present or not
    - Selection of a period: [**between, from, until**]
      - If only member or redactor, only the scheduling is proposed ("from")
      - If space admin or publisher, scheduling and depublication scheduling are possible ("from", "between", "until")
      - Default date proposition:
        - Publication: next day at 08:00 AM
        - Depublication: in two weeks at 08:00 PM
  
- **Advanced settings**
  - Hide redactor: choose if the redactor's name is displayed or not on the article and the news list
  - Hide reaction: enable/disable the reaction on the article (like, comment, kudos, share) on the article and the article activity in the stream

**Edit publication**
Edit publication displays only the publication options (step 2), no more check the properties after the publication.

**Publication drawer with no Publish permission**
![Image](https://github.com/Meeds-io/MIPs/assets/105866381/4dd3fa8d-0bce-417e-9abd-a2a01916bf85)

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/ce5d7722-2894-4985-a225-e568918aa440)

**Publication with Publish permission**

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/c1c47066-ca07-437a-bbfb-3d14838f6283)

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/72dbc8a0-992d-4213-8fc0-22801403092f)

### Note publication

- To publish a note, you need to save it then access the option in the three dots
- Add publish options in the 3 dots actions menu of a note
  - Publish/post a note will display the article activity with the content of the note.
  - It's the same content displayed in different places.
  - A modification on the note will be also available in the article and vice versa. 

![image](https://github.com/Meeds-io/MIPs/assets/105866381/321c4f38-15a8-406a-bdda-96ce6e94064f)

### News referencing
- Add the ability to reference an article in a note tree
- Undo the referencing of an article in an a note tree

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/c747a981-db52-4110-bd66-b3d96a51c998)

### News display
- "Open in Notes app" option in the 3 dots of the article when the article is published from a note.
  - Open the note related to the article
  - Only for space members AND for admin AND for super space admin

#### Notifications
- 

#### Unified Search / Metadata / Bookmarks, favorites
When bookmarking a note that being an article (or an article being referenced as a note), ensure the content is still bookmarked

### Existing Features

- A new "publish" option should be added to the the three dots of the Notes detail component.
- A new "Derefer" option should be added to the the three dots of the Notes detail component.
- A new "Refer into a note" option should be added to the three dots of the News detail component.
- A new "Go to the note" option should be added to the three dots of the News detail component.

### Access 
   - GUI 
     - A new **"Publication"** drawer vue component should be implemented in notes.
     - A new **"ReferToNote"** drawer vue component should be implemented and called from News detail component.

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds @boubaker I split the MIP129 in two. Here is the new MIP. No evolution,  it's just a copy/paste of a part of the previous MIP129. 

We need your GOTECH and GOFUNC please.

**Comment by srenault-meeds** [comment]
Hello, 

Feedbacks:
> schedule only limited to space with redactors

Do you mean only when a space is on editorial mode AND only for space admin and content writers?

> when editing the publication: check box "Go up to the stream" to choose to post again or go up the activity in the stream

I don't understand your sentence.

> space host must have by default the publish permission

Space admins are already publishers. Hence, no need to do anything

> display only if: [Publisher/space hosts + the space has permission on a target] OR [member of a group that has permission on a target]

Not understood

> Depublication only from the News list

I know we talked about it but still not understood the purpose of it.

> if no publishing permission (only posting in the stream) only "From"

Do you mean "if no publisher", then only from option is proposed?

> UX at opening = expand by default

Is that suggested when publishing the first time? Or do I need to post first the article in the stream then publish?

> Note publication will be no longer available during the edition

What does that mean?
-> note not available during the time it is edited (not listed anymore in the newslist)?

**Question**
Can we publish the note while editing it?
Or do I need to save it first?

> A modification on the note will be also available in the article and vice versa.

I don't understand what you want to mean

> "Open in Notes app

Is that proposed only when it is referenced?
If so, can you invert case in the description to make it easier to understand?

> Only for users with access to the space

And admin and super space admin IMO

> Review of notification condition

What about the notification for watched activity?

> Other feedback

When bookmarking a note that being a note (or a news being referenced as a note), does that change anything to users for their bookmark list?

**Comment by srenault-meeds** [comment]
Ok reviewed. And Go-Func

**Comment by boubaker** [comment]
> [!IMPORTANT]
> No objection and `Go-Tech` label added.

**Comment by rdenarie** [comment]
Hi, 
@srenault-meeds @boubaker 

Mips acceptances, and PRs are ready for review.

Thanks for your feedback

**Comment by boubaker** [comment]
> Hi, @srenault-meeds @boubaker
> 
> Mips acceptances, and PRs are ready for review.
> 
> Thanks for your feedback

ok for me

**Comment by boubaker** [comment]
Just a question: did the labels reflect the current status of the MIP ?
![Image](https://github.com/user-attachments/assets/7b066f1c-0b1e-4cfa-9f32-f890f3483f3c)

**Comment by rdenarie** [comment]
Thanks @boubaker, labels updated

**Comment by srenault-meeds** [comment]
My feedbacks:

> Problem with the targets drawer

When clicking outside, the drawer must close itself
Currently, it is not the case and that creates confusion, and UX problem.

See GIF:
![pb drawer targets](https://github.com/user-attachments/assets/2dd403bf-2e98-4820-9525-c5768e65988c)

> Schedule

I don't understand the UX.
When I have published something, I can decide to schedule. 
- The only option is Until
- I don't have a way to decide the start date

To do so, I can decide to unpublish (as a workaround) then I can try scheduling the publication.
And thus, it suggests me to unpublish while I have already done that before

Finally, after emptying my cache and waiting a little, I can see I can schedule it.
Problem: I cannot decide to publish from a start date

Video: 
https://github.com/user-attachments/assets/b4043f42-8c74-4ad5-ab15-6a4686e53eba


> Author and reactions hidden

It is not hidden:
- Author is still visible in newslist
- reactions are still identified in newslist (not really engaging to have 0)
![image](https://github.com/user-attachments/assets/39001b97-280e-4452-bd91-cf958ba8142c)

**Comment by srenault-meeds** [comment]
After discussing it with @Julien-Dubois-eXo, to check:
- deactivate then activate the target: cancel unpublishing must not be proposed again (seems to be a browser cache problem)
- (only viewable on meeds): alignement NOK when editing scheduling between start and end date. see screenshot
![image](https://github.com/user-attachments/assets/3dd1ff38-5d35-49e3-94de-e59e4949c4c1)
- Publish option must be disabled when no target selected
![image](https://github.com/user-attachments/assets/67132a43-0c91-4d96-b511-437f6cc2bc18)

No blocker for me for the merge to develop. I leave you work this as maintenance issue as discussed

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds ok thanks. Find here the documentation around news publication https://community.exoplatform.com/portal/g/:spaces:base_de_connaissances/base_de_connaissances/notes_1/25834 and around note publication https://community.exoplatform.com/portal/g/:spaces:base_de_connaissances/base_de_connaissances/notes_1/25932
