### ISSUE TITLE
Space Template Layout Edition

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#165]
## Rationale

Admins can add and edit space templates. Each template is preconfigured with a layout (home) and with a menu (apps).
In order to help our admins customizing their environment, editing each template layout would be more than interesting.

Indeed, that would provide a whole feature of adding / editing templates.
Moreover, saving a space layout and navigation as a template would be a plus so admins can easily catch nice customization and so they can earn in productivity.

#### Adding a template
When adding a template
Then you access the current form to add characteristics, and to preconfigure permissions, access control, creation steps.
Once done, you will be invited to update the default layout and navigation.

![image](https://github.com/user-attachments/assets/39fb45cc-242b-418c-b63c-69e194694ef4)

From there, you can customize the layout of each page, one by one
- updating apps,
- adding contents and pref of apps
- updating sections, 
- customizing their style (page or section or app)
AND you can add, remove, update nodes / navigation

Each change is saved and stored for the space template.
Indeed, when using this template to create a space, then any preference (layout / nav) is reused so the user can easily create a space as expected.

#### Editing a template layout
When accessing options of a template
It is possible to edit the layout 
Once requested, the navigation drawer is proposed so you can manage nodes and layout.

When saving it, then the template is updated and only new space created using it will get this new layout/navigation.

**Precision**: Product Templates cannot be edited
![image](https://github.com/user-attachments/assets/7e789e26-de3f-408b-a396-22c6f88e4c73)

![image](https://github.com/user-attachments/assets/57b54fb7-45dd-4779-9f49-49aae5a263b1)

#### Gamification
--

#### Notifications
--

#### Analytics
--

#### Unified Search
--

### Security 

The Space Templates Management has to be allowed to administrators only. The Pages Content of type SNV/Image/Links has to be re-imported when instantiating a space template for a given space so that all permissions are re-computed switch new space Group identifier.

### Extensibility 

Study whether it's possible or not to allow to extend the Space Template navigations without having to override the whole space site template.

### Configurability 

N/A

### Upgradability

The already existing Space Templates (prepared with Meeds-io/MIPs#150) has to use the new strategy of space Layout definition.

### Existing Features

N/A

### Feature Flags

N/A

### Other Non Functional Requirements

N/A

### Security

Knowing that SNV/Image/Links portlets are using the contextual information about the current page to check ACL, when instantiating the pages or the portal layouts, the SNV/Image/Links content has to be exported in order to re-import it with the new preferences and contextual information about the current space pages. This strategy already exists and is used in page template duplication process.
For containers attached Backgrounds, its permissions will be set to `Everyone` in order to allow all spaces to reuse the attached background.

### Access

   - The UI will reuse the same Navigation Drawer to display the list of available pages for the space site template
   - The same App and pages will be re-used to manage pages layout

### Services & processing

   - A new `PortalConfig` type will be added in addition to existing ones, of type:
     - PORTAL
     - GROUP
     - USER
     - GROUP_TEMPLATE (**new**)
     - PORTAL_TEMPLATE (**will not be handled here but in a future** Meeds-io/MIPs#149)
   - The current existing behavior of Site template declaration will be improved to import the group site template rather than reading it from configuration when being instantiated. This will allow to manage the site layout, navigation and pages layout using UI. The import mode strategy on startup has to be preserved as well as any type of sites.

### Data and persistence

N/A

**Comment by srenault-meeds** [comment]
To check @margondicco please thanks!

**Comment by margondicco** [comment]
Hello @srenault-meeds 

My first feedbacks

1-
In your screenshots, i can see some content (for the stream app, description, administrators, etc.) : just for the example ? Or can we define some default datas in the template 


2-
For the function sav as template : i am not confortable with the button in the top bar. IMO it's a secondary functionality. Couldn't we propose an action in the space settings section?

Thank you

**Comment by srenault-meeds** [comment]
Sorry, I have to review it a little in fact. This is why I removed my last comment. 

Regarding the content, only data like links, snv, image and preferences will be kept yes. Not the description IMO. Indeed, this can be too much personalized. 

Regarding the option to save it as a template. I am not ok with you solution neither. Indeed, only platform admins can access this option. And some spaces can not provide de settings app (circle template for example).
The other solution I thought about was an option in the spaces management. Still, I found it too much hidden. This is why I proposed this option in the top bar. I will think about it more. 

Thanks

**Comment by srenault-meeds** [comment]
@margondicco ok to check. Thanks

**Comment by margondicco** [comment]
Hello Go Fonc

**Comment by boubaker** [comment]
Ready for Tech review by DAO members (eXo : @rdenarie )

**Comment by rdenarie** [comment]
Hello, Go tech

**Comment by boubaker** [comment]
Meeds PRs:

- https://github.com/Meeds-io/gatein-portal/pull/997
- https://github.com/Meeds-io/commons/pull/666
- https://github.com/Meeds-io/social/pull/4153
- https://github.com/Meeds-io/layout/pull/251
- https://github.com/Meeds-io/gamification/pull/1767
- https://github.com/Meeds-io/perk-store/pull/356
- https://github.com/Meeds-io/notes/pull/1193
- https://github.com/Meeds-io/content/pull/292
- https://github.com/Meeds-io/task/pull/443
- https://github.com/Meeds-io/meeds/pull/2543

**Comment by boubaker** [comment]
ACCs up and running and ready for review by DAO Members ( eXo: @margondicco @rdenarie )

PRs ready:
- Meeds PRs: https://github.com/Meeds-io/MIPs/issues/165#issuecomment-2449277879
- eXo PRs:
  - https://github.com/exoplatform/ecms/pull/2425
  - https://github.com/exoplatform/agenda/pull/714
  - https://github.com/exoplatform/chat-application/pull/775
  - https://github.com/exoplatform/digital-workplace/pull/146
  - https://github.com/exoplatform/onlyoffice/pull/271
  - https://github.com/exoplatform/web-conferencing/pull/337
  - https://github.com/exoplatform/documents/pull/1300
  - https://github.com/exoplatform/processes/pull/411
  - https://github.com/exoplatform/data-upgrade/pull/254
  - https://github.com/exoplatform/platform-private-distributions/pull/393

@rdenarie I let you create PRs of you three commits on eXo repositories:
- https://github.com/exoplatform/commons-exo/commit/e0e58c8ef70f0f205109d8437cd85deca5b8ca5e
- https://github.com/exoplatform/data-upgrade/commit/f8e76df863f3c9e240e0808e308d8b9701f66d3e
- https://github.com/exoplatform/digital-workplace/commit/022fb6cc67c52f7d8a097d9661bc37391b7cf6ef

Thanks in advance for all involved.

**Comment by rdenarie** [comment]
Hello,

PRs checked. 

I add commit https://github.com/exoplatform/data-upgrade/commit/f8e76df863f3c9e240e0808e308d8b9701f66d3e on your PR on [data-upgrade](https://github.com/exoplatform/data-upgrade/pull/254)

 I add commit https://github.com/exoplatform/digital-workplace/commit/022fb6cc67c52f7d8a097d9661bc37391b7cf6ef on your PR on [digital-workplace](https://github.com/exoplatform/digital-workplace/pull/146)

I create a PR for commons-exo : 
https://github.com/exoplatform/commons-exo/pull/52


Functionnaly, I see a problem on the acceptance, templates are duplicated : 
![image](https://github.com/user-attachments/assets/c345c149-b307-46ca-9827-e6ef7a40b89e)

**Comment by boubaker** [comment]
> Functionally, I see a problem on the acceptance, templates are duplicated :

Yes, expected as it's really duplicated using "**Duplicate**" button menu 

![image](https://github.com/user-attachments/assets/677c4086-94cd-4d47-8cdf-7e13071c12f5)

https://exo-mips-ft.meeds.io/portal/administration/home/development/template/spaceTemplates

**Comment by boubaker** [comment]
ACC restarted with clean data to delete Custom Space Templates

**Comment by rdenarie** [comment]
Ok for duplication, no more present.

**Comment by srenault-meeds** [comment]
Go added by @margondicco from there: https://github.com/Meeds-io/MIPs/issues/150#issuecomment-2454034408

**Comment by margondicco** [comment]
Go for merge :-)

**Comment by rdenarie** [comment]
Go for merge for me too

**Comment by boubaker** [comment]
Merged to develop

**Comment by srenault-meeds** [comment]
Documentation updated for editing space template layout and nav
