### ISSUE TITLE
Common version history drawer component

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/MIPs#19]
## Rationale

The Drawer of versions history of the Notes project is needed to be used in other projects (like the Documents app) so to avoid duplicating it we will need to make it available for any addon on top of meeds.
To do that we will move the drawer  to the Social project as a common and reusable component.

## 1. Functional requirements

- We need to reuse the version history drawer to :

    *See a previous version of any Item 
    *Restore a previous version of any Item 
    *Add summary on dedicated version

- No functional changes on the version history drawer of notes for an end user. Notes will used the common composer, and it must not create functional modification.

## 2. Non Functional Requirements

* The component should be updated to be generic and configurable to fit the needs of any application that need to display the version history of any Item.

* The component will be added in a new module under "vue-app" in the social project it will be named "version-history-drawer"

* A "Description" field is needed for  "Documents app" but not for "Notes" so thsi component will be added to the Drawer and cxab enabled or desabled by specific prop.

## 3. Impacts

-  The style part related to the drawer should be moved to the platform-ui project under a new module.

### Feature Flag :
No Feature Flag

**Comment by srenault-meeds** [comment]
Hello,

One observation related to this 

> So we need to copy this drawer on social so that it will be a reusable component

I'd rather describe it by this:
> So we need to make sure it is reusable and consistent depending both use case. 

Other observation: Can you precise please that the "add version summary" option is new for notes so it is well understood as not only a "copy" but a "reuse" with enhancement of use case of versions checking.

WDYT? @margondicco

**Comment by mkrout** [comment]
> Hello,
> 
> One observation related to this
> 
> > So we need to copy this drawer on social so that it will be a reusable component
> 
> I'd rather describe it by this:
> 
> > So we need to make sure it is reusable and consistent depending both use case.
> 
> Other observation: Can you precise please that the "add version summary" option is new for notes so it is well understood as not only a "copy" but a "reuse" with enhancement of use case of versions checking.
> 
> WDYT? @margondicco

Description updated

**Comment by rdenarie** [comment]
There are 3 PRs for this MIP : 

- https://github.com/Meeds-io/social/pull/1884
- https://github.com/Meeds-io/platform-ui/pull/497
- https://github.com/Meeds-io/notes/pull/622

They are ready for review. 

cc @boubaker

**Comment by boubaker** [comment]
Feature Flag section is mising @rdenarie

**Comment by rdenarie** [comment]
added

**Comment by rdenarie** [comment]
PRs are ready for review

**Comment by boubaker** [comment]
> PRs are ready for review

Yep, reviewed

**Comment by rdenarie** [comment]
@boubaker PR are updated to anser to your review.
Can you check ?
Thanks

**Comment by boubaker** [comment]
> @boubaker PR are updated to anser to your review. Can you check ? Thanks

reviewed again to answer replies.
