### ISSUE TITLE
Update icons for Recent favorites drawer

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#2]
## Rationale

Details of the GAP ( problem(s) to address ) expressed by few words using some screenshots.
Icons for contents in recent favorite drawer are not consistent with other icons in the platform

<img width="229" alt="image" src="https://user-images.githubusercontent.com/58853195/174881736-1046b7ea-4f2f-474a-ac11-0490bed26bbc.png">

## 1. Functional requirements
- Icons in this drawer should remind to end-users the content-type they have bookmarked
- Activities type are not well distinguished: challenge, poll, kudos and other activities
- So we suggest to display icons related to the content-type as described in this design: https://xd.adobe.com/view/8a95df71-94c0-47f1-a7ae-bd429c7d4c75-dfc6/screen/3de6fb22-a835-4d82-a186-e9046e441641/specs/
- screenshot here: 
<img width="268" alt="image" src="https://user-images.githubusercontent.com/58853195/174882451-272e1768-3bf5-435f-b64f-382433bc5fc9.png">

## 2. Non Functional Requirements
- Files and News content should be done by eXoers and other contents will be taken care of by MeedsLabers
- Activities type will be implemented for kudos, poll, challenge type of activity
- No feature flag needed

## 3. Impacts
- Documentation to update

## 4. Feature Flags

> **Note**: No feature flag needed

**Comment by boubaker** [comment]
Section added:

> ## 4. Feature Flags

@rdenarie @Samuel-Renault-eXo
