### ISSUE TITLE
Sticky Menu

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#20]
## Rationale

As you know, Meeds software is not only an engagement and a rewarding tool. It is also a collaboration tool where anyone can:
✔ share information
✔ document anything in notes
✔ organize teamwork with kanban board
 
Lately, we provided a new way to see what's up in your communities thanks to unread activities notifications.
 
To pursue this UX enhancement, we'd like to provide you a way to stick the menu. 
 
That would mean the left menu could remained displayed no matter which page you are opening.
That way:
👉 while you are reading a note
👉 while you are working in a task project

✅ You will be able to see where you have received new unread activities without opening the left menu to check.

## 1. Functional requirements

- Opening the left menu would be changed
* Desktop: hover the burger menu opens the left menu. 
* Mobile: swiping the menu from the left to the right opens the left menu.

Users can still click to it if needed to open the left menu

- When using mobile or tablet, no way to stick the menu

- When using desktop, from 1280px (equal or more)
* Then in the left menu, right in front of the profile access item, I should have an option to stick the menu
* When deciding to click to this, then the menu is displayed as "sticky". This means that:
1. the topbar is reduced so we can see it even if the left menu is displayed
2. the page is resized so we see the page and do anything inside
3. when scrolling down the page, topbar and left menu are fixed
4. when browsing any other page, the left menu remains displayed

- When clicking back to the option, then the left menu is back to default status

![proposition 1 - Stick the menu](https://user-images.githubusercontent.com/58853195/218526818-4eb06a85-655c-420a-ba34-4984f2430347.gif)

**Precision**
This preference should be saved for the user so no matter what he is using, the preference he has chosen should be reminded.

### Feature Flags

No feature flag required for this feature

### Access 
   - GUI 
   - API 

### Services & processing
   - Ex: Scheduled Jobs

### Data and persistence
   - Macro data model
   - Persistence layer 
   - Use of caches
## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts 
   - References

**Comment by boubaker** [comment]
Do we need a **Feature Flag** @Samuel-Renault-eXo ?

**Comment by srenault-meeds** [comment]
Yes

**Comment by srenault-meeds** [comment]
Duplicated with the issue related to left menu sticky
