### ISSUE TITLE
Stream activities - Mobile view of activities

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#21]
## Rationale

We have identified improvements to make the stream activities UI up to date regarding the mobile usage we can provide.
Indeed, when using mobile, the activities are displayed the same way it is when using desktop. The problem is that when long name for user or space, the UI is KO: we cannot see the whole user name and more often, the audience (which is the space name cannot be seen)

So we suggest to make Activities UI more responsive to our use case.

## 1. Functional requirements
- Activities UI when using mobile
When using the mobile view and browsing the general stream, I should have a topbar activity UI that way (similar to other social networks)
![image](https://user-images.githubusercontent.com/58853195/191917292-39978363-87e8-4cb9-b519-31a29ef3dda6.png)

When browsing the space stream, no need to remind the audience (space) since we are browsing the space stream
![image](https://user-images.githubusercontent.com/58853195/191917377-97e5b14a-b424-4be8-aed8-d94c9a9d6bc3.png)

## 2. Non Functional requirements - Feature Flags

 >**Note**:  No feature flag needed

**Comment by margondicco** [comment]
Probably 2 MIP : 
one for top bar activities for mobile and desktop
one for the see more option for short message and comment

@Samuel-Renault-eXo WDYT ?

**Comment by srenault-meeds** [comment]
yes indeed i'll do that

**Comment by srenault-meeds** [comment]
Done

**Comment by margondicco** [comment]
only mobile view ?

*Morgan Argondicco*

+33 (0) 6 67 62 02 03 <+33%206%2067%2062%2002%2003>



*[ *Site <https://www.exoplatform.com/fr> *] **[ *Blog
<https://www.exoplatform.com/blog/fr/> *] **[ *Community
<http://community.exoplatform.com/portal/dw> *]*


Le jeu. 29 sept. 2022 à 16:57, Samuel Renault ***@***.***> a
écrit :

**Comment by srenault-meeds** [comment]
Yes @margondicco as it is identified in the title btw, no?

**Comment by plamarque** [comment]
please indicate in the MIP description  if there is no feature flag needed.

**Comment by boubaker** [comment]
> please indicate in the MIP description if there is no feature flag needed.

it was already mentioned, but I did a modification to add it into a dedicated paragraph.


> ## 2. Non Functional requirements - Feature Flags
>  >**Note**:  No feature flag needed

**Comment by boubaker** [comment]
@rdenarie Ready for review https://github.com/Meeds-io/social/pull/1960

**Comment by rdenarie** [comment]
PR commented
