### ISSUE TITLE
[Suggestor] Add the ability to search on all groups for admins 

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/MIPs#23]
1. ## Rationale

In the field suggester which allow to add space or group, as adminstrator i can only add the group that i am membre.

**Note**: avoid describing the solution here.

## 1. Functional requirements
When tapping name of group, suggester should display :

- For administrator : suggest all groups in suggester even his not member 

**Precision :**  All groups whatever the sections (Platform, Organization, and any other groups created manually or by the synchronization with an AD.) 

- For member : member of the group platform/user should be able to add groups in which I'm member whatever the sections (Platform, Organization, and any other groups created manually or by the synchronization with an AD) 

- when suggester search for users, there is no modifications

## 2. Non Functional Requirements
- #### No data volume to add or performance impact
- #### Should not impact the current rest API responses

## 3. Impacts
- #### Identity suggester will be updated to support the need to get all groups for admin users (new parameter to add)

## 4. Software Architecture
- The Rest point used for the groups suggester will be updated by adding a new query param "allGroupsForAdmins" that mean if this param is set to True the service should return the list of all groups if the user is an administrator no matter if he is a member of the group or not.
- The list of returned groups should be filtered to not include spaces groups since the suggester will propose the related spaces. Two new methods will be added to the groupsHandler to get a filtered list of groups that don't contain a list of groups types (spaces and root groups in our case)

1.  findGroupsOfUserByKeyword((String user, String keyword, String List<String> excludedGroupTypes))
2. findAllGroupsByKeyword((String keyword, String List<String> excludedGroupTypes))

### Feature Flag
No feature flag

**Comment by srenault-meeds** [comment]
Hi,
Please can you explain how is that related to meeds? Indeed, the title identifies apps Meeds doesn't support that indeed eXo does. If that does concern Meeds, then we need to discuss it please.

**Comment by plamarque** [comment]
> In the field suggester
which one ? We need a clear inventory of all locations where this would be applied.

> member of the group platform/user should be able to add groups in which I'm member whatever the sections

may expose technical/internal/private/sentitive group structure to user space. There should be much more restrictions for users.

**Comment by mkrout** [comment]
> > In the field suggester
> > which one ? We need a clear inventory of all locations where this would be applied.
> 
This change will be only for suggesters used in process and document apps, with no impact on the other locations. (a pram to enable suggestion of groups already added to not impact other locations)

**Comment by mkrout** [comment]
> Hi, Please can you explain how is that related to meeds? Indeed, the title identifies apps Meeds doesn't support that indeed eXo does. If that does concern Meeds, then we need to discuss it please.

Functionally this is not related to meeds, as this will only be enabled in eXo apps, but some changes are needs in portal rest point that return the list of groups of users.

**Comment by margondicco** [comment]
> may expose technical/internal/private/sentitive group structure to user space. There should be much more restrictions for users.

There is a natural restriction : as a "simple" user (not an member of platform/administrator) i cannot mention a group if i am not member of.

**Comment by plamarque** [comment]
> There is a natural restriction : as a "simple" user (not an member of platform/administrator) I cannot mention a group if i am not member of.

This MIP is not only about the mentioning use case. this suggester is used elsewhere, such as for inviting members ot a new space. In this situation the rule was (so far) to allow to invite only member of spaces where you are host, not user.

**Comment by margondicco** [comment]
> > There is a natural restriction : as a "simple" user (not an member of platform/administrator) I cannot mention a group if i am not member of.
> 
> This MIP is not only about the mentioning use case. this suggester is used elsewhere, such as for inviting members ot a new space. In this situation the rule was (so far) to allow to invite only member of spaces where you are host, not user.

no impact for these feature if the suggestor for inviting members doesn't have the configuration : cf software architecture sections

**Comment by boubaker** [comment]
Feature Flag is missing @rdenarie

**Comment by rdenarie** [comment]
added

**Comment by rdenarie** [comment]
PRs for this mip : 

- https://github.com/Meeds-io/core/pull/74
- https://github.com/Meeds-io/gatein-portal/pull/443
- https://github.com/Meeds-io/social/pull/1926

**Comment by rdenarie** [comment]
cc @boubaker for review

**Comment by boubaker** [comment]
> cc @boubaker for review

Done

**Comment by rdenarie** [comment]
3 PRs are merged. The Mips is closed
