### ISSUE TITLE
DRAFT - Mobile application

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#24]
## Rationale

Details of the GAP ( problem(s) to address ) expressed by few words using some screenshots.
The Meeds software has no mobile application while eXo has one. As we have a common functional and technical base for the software, we identify that we should do the same for mobile application purpose.
Indeed, this aims to give to Meeds Association a way to provide a mobile app for meeds software and in the same time, eXo would be able to extend this app with its use case so eXo users continue using the eXo mobile app.

## 1. Functional requirements
- Meeds related features from the mobile app should be moved to Meeds so we can have a mobile app for it.
* That means that Meeds users should benefit from same usage we have when accessing the current mobile app (onboarding way, notifications) but without addons that we don't need when using meeds - see below
* That means that meeds should have its own mobile app in both stores (iOS and Android) -> eXo will keep its app and Meeds will have a dedicated one.

- eXo related features and not related to meeds one should be kept for eXo usage only
* That means that we should make sure it is extendable so eXo can benefit from the Meeds product core + its addon
* That means that in any case eXo needs to improve something related to meeds product core, this will need to be deployed for meeds usage as well (by making sure it is ok for stakeholders of the association)

- Below, we have listed behaviours, features, we need to have in both product
* Meeds which will be core-product
** Ability to scan QR code to download the app
** Ability to scan QR code to open the right platform
** Push notifications
** Open external link in the preferred browser of the device
** Ability to have a multiple server page so I can access different platform from the same app
** Ability to get mobile analytics

* eXo which use the core-product + its addon
** Meeds core product
** Ability to get notification when a chat message is received
** Share media files, documents from my device to the platform and its spaces
** Ability to launch a jitsi meeting (use the jitsi app if existing OR open it in the browser of the mobile device)

## 2. Non Functional Requirements
- #### Expected volume & Performance requirements
- #### Security requirements (Authentication, Authorizations, Audit track / traceability, data retention…)
- #### Extensibility requirements (Identified extension points, plugables implementations...)
- #### Configurability requirements (properties introduced, default settings, jobs, etc...)
- #### Requirements related to existing users data
- #### Requirements related to existing features (ex: Add a button to existing modules...)
- #### Feature Flag (property name, default status, target audience, functional behaviour)
- #### Other NFR (ex: Use of VueX, Vue, Vuetify)

## 3. Impacts
- #### Documentation to update?
- #### Training level / Change management needs

## 4. Software Architecture
- #### Security
- #### Access (GUI, API…)
   - Rest API design (Entry points, domain objects)
   - Portlet Vue & Vuetify, simple portlet, extension WAR ...
- #### Services & processing
   - Ex: Scheduled Jobs
- #### Data and persistence
   - Macro data model
   - Persistence layer (RDBMS, elasticsearch...)
   - Use of caches
- #### Support for clustering
- #### Support for multitenancy
- #### Integrations
- #### Migration strategy

## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts (ex: impact on public REST/Java API)
   - References (links...)

**Comment by srenault-meeds** [comment]
Items listed with @Julien-Dubois-eXo - To be reviewed in few days before submitting it to a technical study

**Comment by Julien-Dubois-eXo** [comment]
Following a call in eXo to discuss Mobile works I used what we defined in the MIP to explain some of my words. It was noticed that these elements are not be in the perimeter of the mobile app:
** Authentication with eXo form (login / password)
** Authentication with OIDC / SAMLv2
** Authentication with Metamask

It's in the perimeter of the server. 

I will edit it accordingly.

**Comment by srenault-meeds** [comment]
Closed as it is being partially implemented currently by the #134 MIP
