### ISSUE TITLE
Resize Images

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/MIPs#25]
## Rationale

Meeds does not have a solution to automatically resize images before serving it. So, when a user upload a large avatar for example, we display it in full size, even if we display it in a square 45x45.
A such service could be use for other user provided images elsewhere in the platforme.

## 1. Functional requirements
This feature must not change actual behaviour for avatars.

## 2. Non Functional Requirements
- #### Expected volume & Performance requirements
  - Resizing and image before serving it should be fast. It should be more effective to resize it and serv, than to serve the original image.
  After analyzing this point, resize the image take around the same time than serve it. So if we have no solution to store the resize image, the service is useless. 
So, when resize an image coming from FileService, we will store the resized image with FileService, and link the resized image with the original one with a Metadata
- #### Security requirements (Authentication, Authorizations, Audit track / traceability, data retention…)
  - No modification with actual behaviour
- #### Extensibility requirements (Identified extension points, plugables implementations...)
  - No extensibility requirements
- #### Configurability requirements (properties introduced, default settings, jobs, etc...)
  - No configuration 
- #### Requirements related to existing users data
  - No change
- #### Requirements related to existing features (ex: Add a button to existing modules...)
  - About avatars explicitly, there are 3 size for avatars : the activity's author is displayed 45x45. The comment's author, and in who's online block is displayed in 33x33. On profil page, the avatar is displayed in 165x165. Other usages are one of these 3 options. 
As 45x45 and 33x33 are relatively close, we want to use 45x45 as default size for avatar. If another size is needed, as in profile page, we can require it in different size.
- #### Feature Flag (property name, default status, target audience, functional behaviour)
  - No feature flag
- #### Other NFR (ex: Use of VueX, Vue, Vuetify)
  - This resize feature already exists in eXo modules. We want to make it available in meeds, to be able to use it for avatars in a first time, and for other images if needed. In a second time, it could use for banner for example, and in general for all images provided by a user.

## 3. Impacts
- #### Documentation to update?
  - No documentation to update
- #### Training level / Change management needs
  - No change management needs

## 4. Software Architecture
- #### Security
  - No security change
- #### Access (GUI, API…)
   - RestServices which serve avatar for users and spaces will be modified to add a non mandatory parameter allowing to ask size different from the default size.
- #### Services & processing
   - We create a new service named ImageThumbnail which will call MetadataService :
![Resize Image](https://user-images.githubusercontent.com/807839/200353599-6863361b-079b-4bfa-8849-0d1273500f93.png)

- #### Data and persistence
  - Metadata Type Component Plugin
We will define a new Metadata Type by creating a component plugin to extend the Metadata API.
The component plugin will be responsible of :
    - Defining an identifier of type Long for the Metadata type. For Thumbnail Metadata, we will use “5”
    - Defining a name of type String for the Metadata type. For Thumbnail Metadata, we will use “thumbnail”
  - Table METADATA
For Thumbnail Metadata, we will use one metadata for all the platform :
    - Name = “thumbnail”
    - TYPE = Thumbnail ID from Component plugin ( = 5 )
    - CREATOR_ID = 0
    - AUDIENCE_ID = 0
We use ‘0’ for creator_id and audience_id as theses parameters are not relevant for Thumbnail metadata.
  - Table METADATA_ITEM
Each time a file is resized, we store the resized image in FileService. Then we store a metadata item to link resized image file with original image file :
    - METADATA_ID = In Thumbnail Metadata, we will have a relation One To Many with Metadata Item
    - OBJECT_ID = Original File Technical Identifier
    - OBJECT_TYPE = “file”
    - PARENT_OBJECT_ID = Resized File Technical Identifier
    - CREATOR_ID = 0
We use ‘0’ for creator_id as this parameter is not relevant for Thumbnail metadata.
In addition, we will need to access to Thumbnail Metadata by the original file identifier. As MetadataService has function to get metadata item by object id, we decide to keep to original file id in objectId and the resized file id in parentObjectId. 
  - Table METADATA_PROPERTY
When we store a new resized file, and so a new metadata_item, we will also store image width and height in metadata item property table.
So, for each metadata_item, we will use 2 properties : 
    - “width”
    - “height”

- #### Support for clustering
- #### Support for multitenancy
- #### Integrations
- #### Migration strategy

## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts (ex: impact on public REST/Java API) 
   - References (links...)

**Comment by rdenarie** [comment]
Add Technical Specification
cc @boubaker

**Comment by rdenarie** [comment]
Three PRs for this MIP : 

- https://github.com/Meeds-io/commons/pull/417
- https://github.com/Meeds-io/gatein-portal/pull/473
- https://github.com/Meeds-io/social/pull/1998

We are checking a last point before requesting validation

**Comment by rdenarie** [comment]
Add go tech flag as no objection

**Comment by rdenarie** [comment]
The 3 PRs are ready for review

**Comment by rdenarie** [comment]
PRs are ready for review
cc @boubaker

**Comment by boubaker** [comment]
> PRs are ready for review cc @boubaker

Yep, commented, thanks.

**Comment by rdenarie** [comment]
PR updated.
Thanks !

**Comment by boubaker** [comment]
> PR updated. Thanks !

Commented

**Comment by boubaker** [comment]
PRs approved !

**Comment by rdenarie** [comment]
Feature Merged
