### ISSUE TITLE
feat: Compile and run with JDK 17

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/MIPs#26]
## Rationale

To follow jdk versions, we need to update the compile and the run of the project with the last LTS version : jdk 17

## 1. Functional requirements
- No functional requirements
## 2. Non Functional Requirements
- #### Expected volume & Performance requirements
- #### Security requirements (Authentication, Authorizations, Audit track / traceability, data retention…)
- #### Extensibility requirements (Identified extension points, plugables implementations...)
- #### Configurability requirements (properties introduced, default settings, jobs, etc...)
- #### Requirements related to existing users data
- #### Requirements related to existing features (ex: Add a button to existing modules...)
- #### Feature Flag (property name, default status, target audience, functional behaviour)
  - No feature flag
- #### Other NFR (ex: Use of VueX, Vue, Vuetify)

## 3. Impacts
- #### Code impact : 
To compile code with jdk17, we have some code modifications to apply : 
  - javadocs parameters : must be update to new syntax 
  - Remove org.exoplatform.services.security.jaas.JAASGroup class which implements  java.security.acl.Group. Group is no more present in java library, and JAASGroup class is not used.
- #### Documentation to update?
  - Developer guide to update with new guidelines
- #### Training level / Change management needs

## 4. Software Architecture
- #### Security
- #### Access (GUI, API…)
   - Rest API design (Entry points, domain objects)
   - Portlet Vue & Vuetify, simple portlet, extension WAR ...
- #### Services & processing
   - Ex: Scheduled Jobs
- #### Data and persistence
   - Macro data model
   - Persistence layer (RDBMS, elasticsearch...)
   - Use of caches
- #### Support for clustering
- #### Support for multitenancy
- #### Integrations
- #### Migration strategy

## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts (ex: impact on public REST/Java API)
   - References (links...)

**Comment by GouadriaHanen** [comment]
Related PRs:
https://github.com/Meeds-io/maven-parent-pom/pull/33
https://github.com/Meeds-io/maven-depmgt-pom/pull/111
https://github.com/Meeds-io/kernel/pull/51
https://github.com/Meeds-io/core/pull/76
https://github.com/Meeds-io/ws/pull/36
https://github.com/Meeds-io/gatein-sso/pull/25
https://github.com/Meeds-io/gatein-portal/pull/453
https://github.com/Meeds-io/commons/pull/408
https://github.com/Meeds-io/social/pull/1947
https://github.com/Meeds-io/gamification/pull/576
https://github.com/Meeds-io/kudos/pull/236
https://github.com/Meeds-io/perk-store/pull/215
https://github.com/Meeds-io/wallet/pull/304
https://github.com/Meeds-io/notes/pull/636
https://github.com/Meeds-io/poll/pull/52
https://github.com/exoplatform/jcr/pull/283
https://github.com/exoplatform/ecms/pull/1941
https://github.com/exoplatform/mail-integration/pull/31
https://github.com/exoplatform/agenda-connectors/pull/52
https://github.com/exoplatform/news/pull/664
https://github.com/exoplatform/documents/pull/593
https://github.com/exoplatform/processes/pull/209
https://github.com/exoplatform/anti-bruteforce/pull/11

**Comment by GouadriaHanen** [comment]
Related PRs:
https://github.com/Meeds-io/maven-parent-pom/pull/34
https://github.com/Meeds-io/maven-depmgt-pom/pull/112
https://github.com/Meeds-io/kernel/pull/52
https://github.com/Meeds-io/core/pull/77
https://github.com/Meeds-io/ws/pull/37
https://github.com/Meeds-io/gatein-sso/pull/26
https://github.com/Meeds-io/gatein-portal/pull/459
https://github.com/Meeds-io/commons/pull/413
https://github.com/Meeds-io/social/pull/1967
https://github.com/Meeds-io/gamification/pull/591
https://github.com/Meeds-io/kudos/pull/239
https://github.com/Meeds-io/perk-store/pull/217
https://github.com/Meeds-io/wallet/pull/308
https://github.com/Meeds-io/notes/pull/638
https://github.com/Meeds-io/poll/pull/53

**Comment by rdenarie** [comment]
@boubaker PRs can be reviewed

**Comment by boubaker** [comment]
The source and Target compiler are always those of JDK 11:
```
    <maven.compiler.target>11</maven.compiler.target>
    <maven.compiler.source>11</maven.compiler.source>
```
https://github.com/Meeds-io/maven-parent-pom/blob/9151c6daefee0035b182c61e30a98cc1cc649674/pom.xml#L215-L216

It should be updated to be able to use new APIs of JDK 17
Example of previous upgrade of JDK11 https://github.com/Meeds-io/maven-parent-pom/commit/c8acbd56ada3928b9a8117e38dc5038ff2e57ab9

@rdenarie

**Comment by rdenarie** [comment]
@GouadriaHanen @ahamdi can you add a commit in the maven-parent-pom PR to fix the point observed by Boubaker ?
Thanks

**Comment by rdenarie** [comment]
Feedback from @boubaker updated.
All PRs have been rebased and can be validated.

Next steps : 

1. validate PR
2. synchronize with ITOP to ensure smooth merge on meeds side

**Comment by boubaker** [comment]
Ready for PRs Merge & Approved.
