### ISSUE TITLE
feat: Ckeditor custom configuration enhancement

### ISSUE THREAD

**Issue by azayati** [Meeds-io/MIPs#27]
## Rationale

Currently, for each module using Ckeditor, in order to configure a custom ckeditor with custom plugins, we base on /commons-extension/ckeditorCustom/config.js, this my cause problems with custom plugins displaying 

## 1. Functional requirements

This feature must not change the display of the custom ckeditor plugins for each module.

## 2. Non Functional Requirements
- #### Expected volume & Performance requirements
  - No change.
- #### Security requirements (Authentication, Authorizations, Audit track / traceability, data retention…)
  - No modification with actual behavior
- #### Extensibility requirements (Identified extension points, pluggable implementations...)
  - Define a ckeditor custom config as a shared js module for each module using ckeditor instead of commons one (/commons-extension/ckeditorCustom/config.js)
  - This may need a fix in [require.js](https://github.com/Meeds-io/gatein-portal/blob/develop/web/eXoResources/src/main/webapp/javascript/eXo/core/require.js) to be checked and confirmed:   
    - [eXo.require.config = cfg = requireJs](https://github.com/Meeds-io/gatein-portal/blob/develop/web/eXoResources/src/main/webapp/javascript/eXo/core/require.js#L195)
    - [eXo.require.config = cfg = require](https://github.com/Meeds-io/gatein-portal/blob/develop/web/eXoResources/src/main/webapp/javascript/eXo/core/require.js#L202)
  - Introduce the load-group tag in module configuration of gatein-resources.xml which will avoid the module loading by a dedicated portlet injected in an addon container as we are doing generally. This will be based on this [change ](https://github.com/Meeds-io/gatein-portal/commit/fee6d4a1317a8051d0f826d0a2a3874e9f1ef9a0)
- #### Configurability requirements (properties introduced, default settings, jobs, etc...)
  - No configuration 
- #### Requirements related to existing users data
  - No change
- #### Requirements related to existing features (ex: Add a button to existing modules...)
  - No change.
- #### Feature Flag (property name, default status, target audience, functional behavior)
  - No feature flag
- #### Other NFR (ex: Use of VueX, Vue, Vuetify)
  - No change.

## 3. Impacts
- #### Documentation to update?
  - No documentation to update
- #### Training level / Change management needs
  - No change management needs

## 4. Software Architecture

Architectural impact has to be evaluate with a technical study

- #### Security
  - No security change
- #### Access (GUI, API…)
  - No change.
- #### Services & processing
  - No change.
- #### Data and persistence
   - No data model modification
- #### Support for clustering
  - No change.
- #### Support for multitenancy
  - No change.
- #### Integrations
  - No change.  
- #### Migration strategy
  - No change. 

## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts (ex: impact on public REST/Java API) 
   - References (links...)

**Comment by rdenarie** [comment]
@margondicco I put this mip in open status, as there is no priority on that

**Comment by plamarque** [comment]
requirements will be covered by MIP-59

**Comment by rdenarie** [comment]
@azayati can you confirm that MIP-59 cover your needs and close this one if yes.
Thanks

**Comment by boubaker** [comment]
@azayati @rdenarie
This was my suggestion to give some solutions about an MIP that was in progress at that time by you.
Knowing that it was a cross cutting concern, I though you will do it before we do, which wasn't the case because we needed this technical enhancement on Gamification Connectors (**MIP** #64) and Rich Editor Configuration Extensibility (**MIP** #59).

So, both enhancements was already considered in previous MIPs.
Thanks for having created the MIP. You can close it @rdenarie @azayati if you are ok.

**Comment by azayati** [comment]
> So, both enhancements was already considered in previous MIPs.
Thanks for having created the MIP. You can close it @rdenarie @azayati if you are ok.

closed @boubaker
