### ISSUE TITLE
Auth Pages Redesign

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#29]
## Rationale

Details of the GAP ( problem(s) to address ) expressed by few words using some screenshots.
- The current login page and its related page (forgot password page, reset password, onboarding, etc.) misses modern UI and some UI are different
- The current login page when having other authentication way is different if sign in with metamask or if OIDC enabled (open id connect with google, office, etc.)
- The onboarding UX has been implemented the first time months ago and after using it in different ways (external onboarding, onboarding invitation, register UX), we have observed improvements to do in order to have consistencies

## 1. Functional requirements
- Review the way the login page is displayed to have Modern UI
* Left side displayed if desktop with primary color background with Title and subtitle
* Right side displayed with external authentication if enabled (metamask / OIDC)
* Company name branding + logo branding displayed as it is already the case currently
* Primary color for connection button and left side background
* Secondary color for separators if other authentication way enabled
* Login items UI review

<img width="511" alt="login page" src="https://user-images.githubusercontent.com/58853195/198069718-2749ea5e-0784-4e47-a007-4acfd8d1ca91.png">

> mobile view
![mobile login review](https://user-images.githubusercontent.com/58853195/198069684-8ccf2f52-9c37-44f5-916b-42b64ee79963.png)

**Meeds related text in the left side should be in meeds package
eXo related text would be in eXo package**

- Ensure consistencies between different login page 

* Forgot password page
<img width="681" alt="Forgot password" src="https://user-images.githubusercontent.com/58853195/198070110-fd8957a0-f496-4a16-ba2e-75bdbc2e1cfd.png">

* Reset password page
![reset password page](https://user-images.githubusercontent.com/58853195/198069897-80134258-afe1-4764-a348-4cbaa4460ac8.jpg)

* Link expired
![link expired](https://user-images.githubusercontent.com/58853195/198070492-2e9a4a36-540e-4156-96a6-fc545f256a65.jpg)

* register

> FYI, we plan the following, for consistency's sake of external users VS self-registered users:
- When the platform is an open community + users can self-registrate (Sign up option from the login), then anyone using this self-registration will be identified as an internal AND anyone invited by email from a space will be identified as is too. 
- When the platform is a closed community but users can self-registrate, then anyone using this self-registration will be identified as external and anyuser invited by email from a space would be considered as external too

![Register form ](https://user-images.githubusercontent.com/58853195/198070326-12e04d59-6103-4b8f-ae4d-1829ee549e80.png)

- Review the onboarding page and make it consistent depending the case

* Onboarding when registering from the login page

> **Precision**: only register from the login page with an email or metamask will be enabled here. Indeed, a whole review of the oAuth / registeronfly should be reworked to enable the registration with an account. Another MIP will be proposed to work such item.

<img width="493" alt="review register onboarding" src="https://user-images.githubusercontent.com/58853195/198070401-a709ea74-fa82-426b-b1f8-ae4e3bc28819.png">

![onboarding following email request](https://user-images.githubusercontent.com/58853195/198070179-15ba4a99-e026-4d14-af99-76cef050fabf.png)

* Onboarding when invited by users management or external feature
![Onboarding page](https://user-images.githubusercontent.com/58853195/198070019-7bbfb579-0bcb-4e36-ae8d-342a7468c286.jpg)

We should have the same UX for onboarding excluding that we cannot display the username for the external users until names are set.

### Access (GUI, API…)
  The Login And Register Pages has to be added using Vue & Vuetify application to benefit from a good UX.
  The title and subtitle added in left side of page skeleton has to be configurable in two ways:
1. Allow to custom packaging on Top of Meeds Package (such as eXo's package) to define their own default labels that they can internationalize
2. Allow to Tenant Managers to personalize this through properties

To do this, in order to change those string two way of extensions were added:
1. Define the labels `UILoginForm.label.pageTitle` and `UILoginForm.label.pageSubTitle` to redefine the default ones.
2. Allow to define for specific installation customizations, the folllowing properties :
* `portal.authentication.title`
* `portal.authentication.subtitle`
The values can be I18N keys of strings to display as is.

### Services & Processing

All registration types will lead to one simple form before going further to confirm registration, except for oauth which has a OnFly Registration Mode.
By centralizing the registration mode, we are able to add all invitees into one or multiple groups **as member** (Membership Type /role), by default this group is `/platform/externals` (as it's now when registering after space invitation).
This group can be changed to use one or multiple groups through property `meeds.register.onboarding.memberships` (Multivalued comma separated values).

> **Note** to enable self registration by email, you will need to add property `meeds.register.onboarding.enabled=true`

**Comment by srenault-meeds** [comment]
@margondicco can you please check this one?

**Comment by margondicco** [comment]
IMO the left column with title and subtitle could be optional (and in the second MIP)

**Comment by srenault-meeds** [comment]
As discussed together yesterday, the left column will be set the following way:
- background color = primary color of the platform (set in current branding feature)
- text displayed in the example = related to Meeds package / Should be different for eXo package

Description updated accordingly

**Comment by srenault-meeds** [comment]
@boubaker We need a technical spec right?

**Comment by srenault-meeds** [comment]
FYI, we have added an item concerning externals (invited by email from a space) and users who sign up from the self-registration option.
> FYI, we plan the following, for consistency's sake of external users VS self-registered users:
- When the platform is an open community + users can self-registrate (Sign up option from the login), then anyone using this self-registration will be identified as an internal AND anyone invited by email from a space will be identified as is too. 
- When the platform is a closed community but users can self-registrate, then anyone using this self-registration will be identified as external and anyuser invited by email from a space would be considered as external too

cc @margondicco @rdenarie

**Comment by rdenarie** [comment]
> FYI, we have added an item concerning externals (invited by email from a space) and users who sign up from the self-registration option.
> 
> > FYI, we plan the following, for consistency's sake of external users VS self-registered users:
> 
> * When the platform is an open community + users can self-registrate (Sign up option from the login), then anyone using this self-registration will be identified as an internal AND anyone invited by email from a space will be identified as is too.
> * When the platform is a closed community but users can self-registrate, then anyone using this self-registration will be identified as external and anyuser invited by email from a space would be considered as external too

Hello
How will you differenciate both case ? open community vs closed community ? property ? which one ? what will be the default value ? 
Thanks

**Comment by srenault-meeds** [comment]
Hello @rdenarie 
> How will you differenciate both case ? open community vs closed community ? property ? which one ? what will be the default value ?

AFAIR yes we have properties to differentiate such cases.
Isn't it @boubaker ?
Thanks

**Comment by srenault-meeds** [comment]
Precision added for "registeronfly" use case when using oAuth. Will be detailed in another MIP

**Comment by boubaker** [comment]
> Hello How will you differenciate both case ? open community vs closed community ? property ? which one ? what will be the default value ? Thanks

Hi, I added some details about it in Technical Specification.

**Comment by boubaker** [comment]
Ready to be reviewed,  PRs 

https://github.com/Meeds-io/maven-depmgt-pom/pull/120

https://github.com/Meeds-io/platform-ui/pull/574

https://github.com/Meeds-io/gatein-portal/pull/505

https://github.com/Meeds-io/social/pull/2104

https://github.com/Meeds-io/meeds/pull/524

**Comment by rdenarie** [comment]
Hello.
PRs are reviewed and commented.

The acceptance exo-mips is in progress, we should have it at the beginning of the week.
I'll validate PRs after feedbacks treatement and after some tests on our acceptance.

**Comment by rdenarie** [comment]
> * rs can self-registrate (Sign up option from the login), then anyone using this self-registration will be identified as an internal AND anyone invited by email from a space will be ide

As I understand, you resolv the problem by defining the property meeds.register.onboarding.memberships
All users which use the registration form, will be added in groups defined by this property, right ?
So, by default, if I invite someone in a space, he will be added in group /platform/external. 
And if I activate the self registration mode, user which self register will be also external. But they will be in any space. Only external.
@margondicco does this last point is ok for you ?

**Comment by rdenarie** [comment]
PRs validated
