### ISSUE TITLE
Bookmark spaces as favorite

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#3]
## Rationale

Details of the GAP ( problem(s) to address ) expressed by few words using some screenshots.
- Bookmarking contents is enabled for notes, activities in meeds software and this aims to help users to organize their contents.
- Bookmarking spaces will be a nice way to easily access the favorites spaces without searching for it.
- Bookmarking space can only be done from the spaces page or the unified search

## 1. Functional requirements
- Bookmark/Unbookmark space from the space card in spaces page or in the unified search 
- Enable a new filter in the dropdown filter in spaces page in addition to All spaces, My spaces
- List favorite spaces in the favorite drawer with space avatar and space name reminded
- Bookmark/Unbookmark space from the two space popovers proposed (topbar space popover and space popover from space or anywhere else)
- Review the space popover so it is consistent with user popover

Check this below:
![Bookmark spaces](https://user-images.githubusercontent.com/58853195/176912080-a8166d9b-14f6-4781-ac64-66b6c992ed30.gif)

## 2. Non Functional requirements - Feature Flag

(Same Feature Flag used in https://github.com/Meeds-io/MIPs/issues/5 as well for filter combobox)

* Feature flag: `exo.feature.SpaceFavorites.enabled`
* Target audience: all (no possible change)
* This feature flag is applied to allow marking spaces as favorite from spaces page & popover & left Menu in Recent Space details. Once enabled, a new entry in Activity Stream filters will be added in Main stream only.
* The default value of it is set to `true`

## 3. Impacts
- Documentation to be updated

**Comment by srenault-meeds** [comment]
Delivered to exo-develop

**Comment by boubaker** [comment]
Added section :
> 2. Non Functional requirements - Feature Flag

@rdenarie @Samuel-Renault-eXo
