### ISSUE TITLE
[Challenges] add status to challenges with possibility to enabled or disable it 

### ISSUE THREAD

**Issue by Imenmakni** [Meeds-io/MIPs#30]
## Rationale
Program feature has been provided lately , so now by adding possibility to delete a program so related actions (automatic / manual) are disabled but not deleted
So to be able to reuse the challenge we need to enable it 

## 1. Functional requirements
- Add switch button status  ( enabled / disabled ) when creating new challenge or updating old one
- Add two value ( enabled / disabled ) on quick filter 

![statuts challenge](https://user-images.githubusercontent.com/83289222/198297356-8bc9a04c-736c-4636-aa71-b455c5f213cf.png)

## 2. Non Functional Requirements
- #### Expected volume & Performance requirements
- #### Security requirements (Authentication, Authorizations, Audit track / traceability, data retention…)
- #### Extensibility requirements (Identified extension points, plugables implementations...)
- #### Configurability requirements (properties introduced, default settings, jobs, etc...)
- #### Requirements related to existing users data
- #### Requirements related to existing features (ex: Add a button to existing modules...)
- #### Feature Flag (property name, default status, target audience, functional behaviour)
- #### Other NFR (ex: Use of VueX, Vue, Vuetify)

## 3. Impacts
- #### Documentation to update?
- #### Training level / Change management needs

## 4. Software Architecture
- #### Security
- #### Access (GUI, API…)
   - Rest API design (Entry points, domain objects)
   - Portlet Vue & Vuetify, simple portlet, extension WAR ...
- #### Services & processing
   - Ex: Scheduled Jobs
- #### Data and persistence
   - Macro data model
   - Persistence layer (RDBMS, elasticsearch...)
   - Use of caches
- #### Support for clustering
- #### Support for multitenancy
- #### Integrations
- #### Migration strategy

## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts (ex: impact on public REST/Java API)
   - References (links...)

**Comment by srenault-meeds** [comment]
Deleted from the project as it is included in the contributions center cc @Imenmakni
