### ISSUE TITLE
Authentication configuration

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#32]
## Rationale

Meeds Software provides way to setup the platform in a simple way: only branding and authent page customization can be done. 
However, we should let admin possibilities to manage more than branding, for example:
- authentication configuration (only possible to do that currently without UI)
- authentication conditions (platform opened or closed)

## 1. Functional requirements
- Add in general settings access to authentication customization settings
<img width="892" alt="image" src="https://user-images.githubusercontent.com/58853195/216298285-1879e0f5-430a-4265-ad1b-918477cfb1c1.png">

- In authentication configuration, 2 items to manage authentication conditions (access options) and authentication configuration
* default status: platform opened and meeds password authentication mode are enabled
<img width="686" alt="image" src="https://user-images.githubusercontent.com/58853195/216298600-71b180d1-23f8-4768-8870-5a32fafb87e3.png">

* I can decide to change the access mode to a closed one and by doing this, I can decide to authorize or not the external invitation (by default, set to false as it is a closed platform)
<img width="688" alt="image" src="https://user-images.githubusercontent.com/58853195/216298877-fa396016-0cf2-4f9b-8330-32d1b7d3a418.png">

* I can decide to provide additional authentication mode to the password one.
<img width="674" alt="image" src="https://user-images.githubusercontent.com/58853195/216299347-39421db2-52d9-4d46-80f2-7464fd94c0b9.png">

- if platform is opened, then provisioning can be enabled
<img width="134" alt="image" src="https://user-images.githubusercontent.com/58853195/216299524-04b67f88-4760-4926-81ff-d51009771ea4.png">

- if platform is closed, then provisioning cannot be enabled. Users should be created to access the platform.
<img width="164" alt="image" src="https://user-images.githubusercontent.com/58853195/216299441-bda6eba8-f95c-4f58-be44-8e4f1ffa99e8.png">

* When the user wants to manage its accounts, he can do so thanks to user settings
- when password created:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/58853195/216299836-288240bd-2873-470b-8e07-f31c9002d1b0.png">

- when password not created and logged with another authentication way:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/58853195/216300000-305bb108-bcbb-40fa-82d8-6e3404c94012.png">

### Feature Flags

> No feature flag needed

### Access 
   - GUI 
   - API 

### Services & processing
   - Ex: Scheduled Jobs

### Data and persistence
   - Macro data model
   - Persistence layer 
   - Use of caches
## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts 
   - References

**Comment by srenault-meeds** [comment]
@margondicco can you please check this one?

**Comment by margondicco** [comment]
Hello

i'd like to choose some images and not only one
How can we check the chosen visual in mobile version
Couldn't we provide here an image editor : at least to crop on the expected template

**Comment by srenault-meeds** [comment]
By default:
- primary color as the background
- text by default precised in properties

Admin can add an image and can edit the text

**Comment by rdenarie** [comment]
Hello. 
Does this MIP concern the login page rework ? or this rework will come in another MIP (which would be done before) ?
What will control the feature flag ?

**Comment by srenault-meeds** [comment]
Hello,

I have updated the description accordingly to what we discussed yesterday @margondicco 
@rdenarie I have added a note in functional requirements regarding this. Indeed, this is related to the login pages review BUT it should be done after it.

**Comment by srenault-meeds** [comment]
Merged with this MIP https://github.com/Meeds-io/MIPs/issues/33

**Comment by srenault-meeds** [comment]
Reopened as the https://github.com/Meeds-io/MIPs/issues/33 needs to be splitted after studying it with Boubaker

**Comment by srenault-meeds** [comment]
Scope Reviewed and thus I close this one as cancelled
