### ISSUE TITLE
Publisher Role

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/MIPs#35]
## Rationale

The current permission management in a space is too restrictive. We have the need to promote the user as a new role to delegate, within a space, specific permissions  on the subject of information diffusion. 

## 1. Functional Requirements

- Be able for a host to promote users as "Publisher" in the space.
- This role gives permission to these users to achieve new actions.
- Be able to filter by the publisher in the member list in the space.
- We are using the same UI and UX in mobile as now => bottom drawer.

![FT News - Publisher role](https://user-images.githubusercontent.com/105866381/202683653-0bd8b865-9e8e-4d4f-a128-07ddea92cb6e.jpg)

### Feature Flags

- **Functional behavior:** Hide (false) or display (true) the option "promote as publisher" in the 3 dots option in the member tab of a space
- **Property name:** exo.feature.publisherRolePromotion.enabled
- **Default status:** false
- **Target audience:** all users
- **Remove:** Keep the flag at the end of the iteration but switch the default value to true in eXo Package and keep it false in the Meeds package.

### Access 

Space members portlet should be updated in order to add:

- A new "profile-extension" action which allows to "Set user as publisher"
- A new "profile-extension" action to "remove publisher"

### Services & processing

- "ProfileEntity" should be updated by adding "isSpacePublisher" property.
- The existing "publisher" organization role will be used.
- The following rest POST service "/v1/groups/memberships" should be called in order to set/remove "publisher" membership on the space

**Comment by Julien-Dubois-eXo** [comment]
@Samuel-Renault-eXo @margondicco tell me if it's better with this update of the Rational and functional part.

**Comment by azayati** [comment]
Technical part finished, to be validated @rdenarie

**Comment by rdenarie** [comment]
Go tech needed @boubaker

**Comment by rdenarie** [comment]
Add go tech flag as no objection

**Comment by boubaker** [comment]
One objection @rdenarie : why adding this role in Meeds codebase while this role isn't needed by Meeds Features and while you can make it through extensions ? The MIP can be simply: "allow to extend roles management in Spaces UI".

**Comment by rdenarie** [comment]
On functional side, it is a feature which should be used in mid/long term on meeds side.
That why we keep it in meeds.

cc @Samuel-Renault-eXo

**Comment by srenault-meeds** [comment]
Yes I agree and I discussed it with Morgan before

**Comment by azayati** [comment]
Draft PRs created:

- https://github.com/Meeds-io/social/pull/2041

**Comment by plamarque** [comment]
Would rather leave this feature flag to disabled by default, because the publisher role will be useless in meeds alone.  We don't want to add a uui that users could not leverage.

**Comment by srenault-meeds** [comment]
> * **Property name:**: exo.feature.publisherRolePromotion.enabled
> * **Default status:** false

Hello, I see this information in the MIP:
> Property name:: exo.feature.publisherRolePromotion.enabled
Default status: false

So we are ok, isn't it? It will be disabled by default

**Comment by rdenarie** [comment]
In fact the Mip says that : 

> Feature Flags
Functional behavior: Hide (false) or display (true) the option "promote as publisher" in the 3 dots option in the member tab of a space
Property name:: exo.feature.publisherRolePromotion.enabled
Default status: false
Target audience: all users
Remove: Keep the flag at the end of the iteration but switch the default value to true ==> Needs for Meeds

We initially plan to set the feature flag to true at the end of the development to expose the new feature.

But Patrice prefer to let this feature deactivated, even if finished in meeds context.

@Samuel-Renault-eXo is it ok for you ?

**Comment by srenault-meeds** [comment]
> Remove: Keep the flag at the end of the iteration but switch the default value to true ==> **Needs for Meeds**

Actually, I agree with Patrice as I didn't get this last mention.
IMO, the MIP shouldn't explain how we manage the implementation, but only how we manage the delivery. This is why I might have got confused.

So yes, if we can make this flag set to false by default, it would be better please.

**Comment by rdenarie** [comment]
@margondicco is it ok for you ? 
If yes, We should update the MIP description

**Comment by Julien-Dubois-eXo** [comment]
> > Remove: Keep the flag at the end of the iteration but switch the default value to true ==> **Needs for Meeds**
> 
> Actually, I agree with Patrice as I didn't get this last mention. IMO, the MIP shouldn't explain how we manage the implementation, but only how we manage the delivery. This is why I might have got confused.
> 
> So yes, if we can make this flag set to false by default, it would be better please.

@srenault-meeds Originally I mentioned keeping the flag with the default value on "false" to that's why there is the mention "Needs for Meeds". When we decide to switch I just forgot to remove the Needs for meeds.

**Comment by srenault-meeds** [comment]
Ok so, would it be true or false in the end?

**Comment by Julien-Dubois-eXo** [comment]
We are waiting for the approval of @margondicco to keep the flag at "false" by default as you request.

**Comment by boubaker** [comment]
> We are waiting for the approval of @margondicco to keep the flag at "false" by default as you request.

Default value `false` in Meeds package, but it can be `true` in eXo Package in fact (as default value I mean).

**Comment by margondicco** [comment]
> > We are waiting for the approval of @margondicco to keep the flag at "false" by default as you request.
> 
> Default value `false` in Meeds package, but it can be `true` in eXo Package in fact (as default value I mean).

voilà

**Comment by Julien-Dubois-eXo** [comment]
ok thanks. @azayati FYI. I have updated the description of the relative task according to this decision.

**Comment by azayati** [comment]
> > We are waiting for the approval of @margondicco to keep the flag at "false" by default as you request.
> 
> Default value `false` in Meeds package, but it can be `true` in eXo Package in fact (as default value I mean).

@boubaker For meeds package, I will keep the default 'false' value in social, and for eXo package I will define the default 'true' value in eXo private distribution, WDYT ?

**Comment by margondicco** [comment]
Agrée

**Comment by azayati** [comment]
PR https://github.com/Meeds-io/social/pull/2041 review needed
@rdenarie @boubaker

**Comment by boubaker** [comment]
PR approved

**Comment by azayati** [comment]
> PR approved

@boubaker can you approve again ?

**Comment by srenault-meeds** [comment]
Hello, is the feature flag still available? exo.feature.publisherRolePromotion.enabled
Indeed, I don't find it listed in the configuration of an acc and I needed to check something
@azayati @Julien-Dubois-eXo

**Comment by azayati** [comment]
@srenault-meeds yes the feature flag is only enabled for eXo since Meeds still not need this feature

**Comment by srenault-meeds** [comment]
Ok, but this description is not clear to me:

> Remove: Keep the flag at the end of the iteration but switch the default value to true in eXo Package and keep it false in the Meeds package.

As I understand, if no flag, then no enable of the option
