### ISSUE TITLE
Add filter options to task projects

### ISSUE THREAD

**Issue by Julien-Dubois-eXo** [Meeds-io/MIPs#40]
## Rationale

We have a [request ](https://community.exoplatform.com/portal/dw/tasks/taskDetail/61280) from one of our customers about these gaps: 

- Task projects can't be archived, only their tasks can be.
- Also, as we can add colors to these projects yet it's not possible to organize or filter them by these colors

## 1. Functional Requirements

To address these gaps we could imagine a way to be able to : 

- To archive a project
- Filter by archived projects
- Filter by colors of projects

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  |   |   |   |

### Access 
   - GUI 
   - API 

### Services & processing
   - Ex: Scheduled Jobs

### Data and persistence
   - Macro data model
   - Persistence layer 
   - Use of caches
## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts 
   - References

**Comment by srenault-meeds** [comment]
Hi @Julien-Dubois-eXo 

Can you please update the title? Indeed, it was not cleared to me at first that it is related to project filtering and archiving.

In addition, can we please elaborate more the MIP? Indeed, we have now way currently to filter projects. So it might be interesting to think about ways to organize and manage projects. Thus, this MIP will address more than one or two feedbacks.

WDYT?
Thanks

**Comment by Julien-Dubois-eXo** [comment]
Can be closed
