### ISSUE TITLE
feat: Cleanup Meeds Package Dependencies

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/MIPs#42]
## Rationale

The Meeds Package currently holds a lot of unused Third Party libraries dependencies which affect the performances and makes the security upgrades more frequent.

In addition, the pre-packaged third party libraries of Meeds Package aren't available for addons by adding Social Maven Artifacts, thus some addons has to repeat the same dependencies in their own artifacts, even when it's not directly used by the addon itself (bad transitive dependencies tree).

Besides, the same thing is observed in Unit Tests using the IoC container, the configuration has to be repeated in addons from bottom layers to make it work properly which reduces considerably the maintainability and development of new addons and features on top Meeds Package.

## 1. Functional Requirements

No functional requirements.

### Expected Volume & Performance

Some minor performance improvements are expected due to the reduced number of classes to manage & load by JVM.

### Security 

No change.

### Extensibility 

To add a new addon, we will not have to import additional third party libraries not used by the addon itself. All required libraries by bottom layers has to be imported implicitly with Maven transitive dependency mechanisms.

Addionally, the required artifact for Building & Unit Testing has to be imported automatically as well:: JUnit, Mockito (Core & Inline), lombok and hsqldb.

The usage of PowerMock library has to be deleted since it duplicates Mockito-Inline.

### Configurability 

The configuration of Unit Tests of addons has to be simplified so that no additional bottom layer configuration would be required to be able to execute the instruction `PortalContainer.getInstance()` without errors and with the core components preloaded and well configured.

### User Data

No change on runtime

### Existing Features

No change on runtime

### Feature Flags

No change on runtime

### Other Non Functional Requirements

The addons has to be updated to clean third party libraries already added in Core Package (Social & Bottom layer). The not needed JARs by the Core Package has to be moved into addons if only one single addon uses it, so that it will be automatically deleted when the addon is removed.

### Training 

How to make Unit Tests on top of Meeds Core Package ? (A reminder about best practices)

### Third party libraries cleanup

Currently, the Meeds package holds the following useless JARs that has to be cleaned :

![Capture d’écran du 2023-01-02 11-27-39](https://user-images.githubusercontent.com/594824/210221368-24d638a5-e342-4288-8aad-64e43ecf6cf2.png)
![Capture d’écran du 2023-01-02 11-28-30](https://user-images.githubusercontent.com/594824/210221387-179beae4-699b-4155-8d33-fb7c93180c32.png)
![Capture d’écran du 2023-01-02 11-28-43](https://user-images.githubusercontent.com/594824/210221400-99e3f4a7-a277-457c-9cd0-210c3c577710.png)

The major part of those libraries are imported indirectly from `exo.core.component.document` which has to be deleted knowing that it's not used by Meeds Package anymore. In fact, gamification is using `org.apache.poi:poi-ooxml` and `org.apache.poi:poi` to export the realizations table in `xls` format and doesn't need the whole dependencies of this artifact. 

Thus it has to be deprecated in Core Module and remove its dependency from Meeds Package since it's not used.

### Maven Dependency Tree Update

Currently, the maven dependency tree doesn't help to get all dependencies of Core Modules in Transitive way, so that developing and maintaining an addon isn't sufficiently easy.

To make this easier, the dependencies in core Module itself has to be rearranged to make it transitively imported when referenced inside an addon. To do this, all third party libraries of each project (Portal, Commons & Social) has to be imported in a the API Module. Some exceptions has to be made for exclusive dependencies that aren't common and that are special to the implementation of the module, such as for OAuth Module which imports OAuth Providers Java Libraries to parse OAuth Tokens and interact with Providers.

The Unit Test JARs (JUnit, Mockito...) has to be centralized inside `exo.portal.component.test.core` to be imported in transitive way in all projects. The Meeds Packaging project will have to exclude all Test modules to avoid packaging them for runtime (simply by excluding `exo.portal.component.test.core`).

### Unit Tests

Each Module in Core Package (Portal, Commons & Social) has to define its own configuration that any addon on top of it will be able to reuse without additional configurations. To do this, the `test-jar` type artifacts has to be generated for every module by adding the following configuration in parent POM of each project:

```xml
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <executions>
            <execution>
              <phase>package</phase>
              <goals>
                <goal>test-jar</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
```

This configuration will encapsulate the Test resources (classes & configurations) inside a dedicated jar that can be referenced in addons with artifact type `<type>test-jar</type>`. This will allow to import pre-configured Services from Core layers to make the Portal Container ready to Test for Addon artifact with builtin services.

**Comment by rdenarie** [comment]
Hello
Some questions on my side :

> The addons has to be updated to clean third party libraries already added in Core Package (Social & Bottom layer). The not needed JARs by the Core Package has to be moved into addons if only one single addon uses it, so that it will be automatically deleted when the addon is removed.

What if a library is used by more than one addon ? 

> The major part of those libraries are imported indirectly from exo.core.component.document which **has to be deleted** knowing that it's not used by Meeds Package anymore

I think we should change to **has to be moved** in eXo package.

**Comment by boubaker** [comment]
> What if a library is used by more than one addon ?

--

> if only one single addon uses it

If it's used by multiple addons, until we improve `addons-manager`, we will have to keep it in Core Project (Social for Meeds & ECMS for eXo).

> I think we should change to has to be moved in eXo package.

Yep, in fact, in this MIP I didn't mentioned what to change on eXo, only what to change on Meeds Package, deprecate it as first step in Core Project (+ delete from Meeds Package) and then remove it from Core once it has been forked in eXo, yep.

**Comment by boubaker** [comment]
@rdenarie as agreed, the following PRs are the target of this MIP, added as draft since it will have some impacts on Tests on eXo addons as well. Please take your time to review and validate until you get prepared for it, once done, I will be able to add this in feature/mips FB of Meeds projects to let you the time to review impacts and prepare PRs as well on eXo side :

* https://github.com/Meeds-io/maven-depmgt-pom/pull/121
* https://github.com/Meeds-io/gatein-portal/pull/512
* https://github.com/Meeds-io/commons/pull/439
* https://github.com/Meeds-io/social/pull/2130
* https://github.com/Meeds-io/gamification/pull/784
* https://github.com/Meeds-io/kudos/pull/274
* https://github.com/Meeds-io/perk-store/pull/238
* https://github.com/Meeds-io/wallet/pull/350
* https://github.com/Meeds-io/push-notifications/pull/41
* https://github.com/Meeds-io/notes/pull/652
* https://github.com/Meeds-io/poll/pull/64
* https://github.com/Meeds-io/task/pull/161
* https://github.com/Meeds-io/meeds/pull/530

**Comment by boubaker** [comment]
PRs rebased for review @rdenarie

**Comment by boubaker** [comment]
MIP commits added to feature/mips to let you analyze its impact on your addons @rdenarie

**Comment by rdenarie** [comment]
PRs on exoplatform side :
https://github.com/exoplatform/jcr/pull/294
https://github.com/exoplatform/ecms/pull/2022
https://github.com/exoplatform/mail-integration/pull/39
https://github.com/exoplatform/dlp/pull/22
https://github.com/exoplatform/agenda/pull/538
https://github.com/exoplatform/news/pull/822
https://github.com/exoplatform/onlyoffice/pull/190
https://github.com/exoplatform/saml2-addon/pull/15
https://github.com/exoplatform/documents/pull/793
https://github.com/exoplatform/processes/pull/270
https://github.com/exoplatform/anti-bruteforce/pull/14
https://github.com/exoplatform/anti-malware/pull/13
https://github.com/exoplatform/data-upgrade/pull/136

**Comment by boubaker** [comment]
MIP merged on develop
