### ISSUE TITLE
Action and challenge merging

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#49]
## Rationale

Now that the contributions center has been delivered to users, we need to improve some UX.
Indeed, we have received feedbacks regarding:
- action to add in a program but not challenge (needs to be done in challenges tab)
- challenges are grouped by programs in the challenges tab. What is the difference with programs tab?
- when it comes to add a challenge, we have to put start date and end date. Why not making it optional?
- challenge or action cannot be locked. Unfortunately, program owners would like to use the programs to help a project onboarding and proposing actions to do step by step would be more than useful
- sometimes challenge or action is done multiple times while it has to be done once only

In addition to this, when you create a program, we have inconsistent UI and UX:
- Fields are not respecting UX guidelines
- We cannot crop/resize the banner
- We cannot choose any as the audience and this is blocking for some case
- Once created, the program doesn't guide the user and the program is enabled while there are no actions yet

## 1. Functional Requirements

We suggest then to enhance few items in the contributions center so it is better self-explanatory and using it is easier to do.

1. Add an action
- From a program, it will be possible to add an action (automatic or manual/declarative)
- Each action will have same characteristics: name, description, points
- The creator can decide to add conditions to each action: duration (start date OR end date), action (to lock the current action until another one is done), recurrence (to lock the current action once it is done)
- Once the action is created, a success notification proposes to publish the new action on the audience stream
- From the list, a new option proposes to publish the action to be done on the audience stream

2. Challenge list review
- Remove the add challenge
- If possible, merge all actions in this list (auto and challenge) and rename the tab as "Actions" or "Incentives"
- Remind the number of actions active and when filtering the actions, update the total
- Default view of the actions list should be grouped this way:
* 3 challenges that are ending the most
* 6 challenges the most recently added
- When filtering the challenge, replace the default list by results

3. Program UX Review
- Review the program drawer creation/update with:
a. stepper to introduce the program first (banner, title, description) and then detail audience & owners
b. expanding the drawer shows both steps at once
- Ability to choose an audience as any internal user (not default choice) so achievements can be done by anyone without being member of a space (for onboarding purpose for example)
- Ability to add translations to both name and description
- Ability to resize the banner with a frame so the user is not lost when choosing a banner
- Once created, the program is displayed as disabled and a CTA invites the user to add an action
- Once an action is added, a reminder is displayed to the user telling him the program is still disabled

### User Data

We shouldn't have impact nor migration to do on current users data.

### Feature Flags

No feature flag is needed here

### Access 

The main changes will be made on Vue components. A cleanup of useless components has to be made after switching Chanllenge drawer to merge it with rule drawer. 

### Services & processing

The existing `RuleEntity.startDate` and `RuleEntity.endDate` fields will be used to save the information of availability period of a Challenge. This business rule exists already in backend and was used before Contribution Center V1 already. This business rule has to be propagated to Automatic Rules as well to be able to give an period validity into it.

Knowing that the business rule will be the same of the Entity `RuleEntity`, whether it's automatic or manual, we should refactor the services to merge behaviors and not having a dedicated `ChallengeService` anymore. In fact, it should be merged with `RuleService`.

**Comment by margondicco** [comment]
No feedback for me.

**Comment by boubaker** [comment]
Technical Design added, @AzmiTouil @rdenarie FYI (to review and comment please if needed)

**Comment by rdenarie** [comment]
Ok for me

**Comment by plamarque** [comment]
ETA mid-may

**Comment by srenault-meeds** [comment]
Description updated as expected and introduced during last Product Committee
@margondicco FYI

**Comment by boubaker** [comment]
@rdenarie @margondicco The MIP is ready to be reviewed on ACC and linked PRs for Meeds package.
To help you on adaptations on your side, I provide those PRs:
* https://github.com/exoplatform/agenda/pull/554
* https://github.com/exoplatform/news/pull/866

**Comment by rdenarie** [comment]
PRs validated and ready to merge
