### ISSUE TITLE
Filter the stream

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#5]
## Rationale

Lots of activities can be shared now in communities and it becomes more and more difficult for users to check what's new.
So we propose to add filters in the user personal stream so users will be able to filter their stream

## 1. Functional requirements
- Add a topbar above the user personal stream (not the space stream and not above an activity detail)
- From this topbar, have a title "Activity stream" or "Post something" action if post from general stream enabled
- From this topbar, propose to the top-right dropdown filters: Any activity, My posted activities, My favorite activities, Spaces I host, My favorite spaces
Design: https://xd.adobe.com/view/9969f71e-ad47-416e-bb70-f01f55052d34-cc3a/

- If no result can be listed when filtering the stream, a page explaining why will be displayed:
Design: https://xd.adobe.com/view/4f3ab0e3-8363-474e-b9e4-1d6d2cef916c-1a69/

- Once the user has chosen a filter, next time he comes back he'll get the same filters applied

### 2.1. **Filter** Feature Flag

* Feature flag: `exo.feature.StreamFilter.enabled`
* Target audience: all (no possible change)
* This feature flag is applied to enable/disable the filter combobox in Main (& Spaces) Activity Stream which will allow to display specific activities of the stream for currently authenticated user.
* The default value of it is set to `false`

### 2.2. **Favorite Spaces** Feature Flag

* Feature flag: `exo.feature.SpaceFavorites.enabled`
* Target audience: all (no possible change)
* This feature flag is applied to allow marking spaces as favorite from spaces page & popover & left Menu in Recent Space details. Once enabled, a new entry in Activity Stream filters will be added in Main stream only.
* The default value of it is set to `true`

## 3. Impacts
- Documentation to update

## 4. Annexes

**Comment by plamarque** [comment]
eeds Product commiteed approved funcitonal requirements. Technical commitee needs to instruct the imapcts, NFR and architecture sections.

**Comment by boubaker** [comment]
Added Section :
> ## 2. Non Functional Requirements - Feature Flags

@rdenarie @Samuel-Renault-eXo
