### ISSUE TITLE
Contributions UX & Navigation

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#50]
## Rationale

After more than a year of using the contributions center, we need to review the way users access programs, actions and achievements.
Here are some concerns reported by users:
- from the overview page, almost anything is accessible with a drawer and if need to see more, it is possible. Not the case with programs
- programs and related actions have audience. The problem is that when visiting a space, we don't know which actions are proposed to this audience. We need to go see the contributions center to figure it out
- Challenges announcements become more and more noisy for users on the activity stream
- When seeing an announcement activity, users cannot access the action detail without accessing the contributions center
- Apps of the contribution center became more and more detailed, complete and we also have tabs/views for almost each app. Navigation needs to be better provided
- Actions triggered by meeds events are not up to date and needs to be reviewed

## 1. Functional Requirements

1. Actions announcement are comments of a main activity
- When creating an action, option to publish the activity on the related audience's stream (set to true by default)
- Ability to opt it off and then to update the action and choose to publish it
- Each announcement done for achieving the action will generate a comment of this activity
- If the action had'nt been pubished, then activity will be hidden. Activity and related comments will still be accessible from the direct URL
- Activity for announcement will be reviewed to get the program avatar instead of the avatar of the app
- When hovering the action summary, a popover will display to access the summary of it and when clicking to it, the action detail drawer opens without going to the contributions/actions page
- Notifications for action activity and for announcement comment will be added to distinguish activity notifications with those activities type (email, onsite and unread activities notifications). By default, those notifications will be added by default to any existing users

2. Access a program summary drawer from the overview page

3. Actions gadget to improve for overview
- Overview: list 4 items instead of 3
- Overview: merge action and challenge
- List action upon their status: ending soon + available actions
- Propose to have it in the stream page for meeds package (set to false for other)

4. Actions gadget decentralized by space if related to an audience and visible from the stream page as well
- Same gadget UI and UX used in overview page
- Add a gadget in the space when actions are proposed to be done for this audience with a sort as the following:
a. by default from the most rewarding one to the less (4 max) 
b. and if actions needs to be done step by step, propose these one first
c. if action to do once and done as agreed, then list other action
d. No see more as the space can be used as an audience for different programs
- Add this widget in the stream page to list all actions the user can do 

This gadget will be added automatically to any space if a program is related to it, and to the stream page if an action is listed as available, soon available for the user.

5. Contributions center navigation
- From the topbar, three pages are proposed in a submenu of the contributions item: Programs, Actions, Achievements
- Each item is a page
- Review the app from the appcenter to be "Contributions programs" so the user access the programs page
- Review the way programs and actions are listed and can be found: tags by program and actions can help the user find by "category", programs are listed in programs page and actions page alphabetically

6. Actions - Meeds events review
- Some event are not working while proposed: receive like on activity's comment, become space host
- Others are not consistent with what we are looking to trigger: update profile avatar is not ok (only when adding after default one), update profile banner is not ok (only when adding after default one), names for activities actions on own activity stream need to be reviewed
- Others need to be removed: log in, Receive activity (network -> redundant with another one) -> network and own activities triggers will be removed and only one trigger for each will be considered (no matter it is in a space stream or in a network stream). Transition of these changes will be done manually with UI
- one need to be removed from meeds package (to be moved to exo package?): upload document
- Few are missing to engage the user discovering more the platform and sharing more: fill profile informations, update a space as space host, pin an activity, poll creation/participation, bookmark usage, tags use, wallet initialization

### Security 

The widget must display a contextual information and permits to see only permitted challenges to announce. The endpoints has to be secured as well to not retrieve only allowed audience members to access challenges switch associated program target audience.

### Feature Flag

No feature flag will be needed to introduce this feature.

### Upgradability

The widget must be able to be plugged into Space Home page (same as Stream Page) without a migration existing pages. In fact, to do this, we will have to use the already existing dynamic containers to inject the widget.

Besides, the new notifications that will be introduced by this MIP has to be enabled by default to all existing users. Thus a new Upgrade plugin has to be added.

### Other Non Functional Requirements

Reuse existing components instead of redefining them to preserve same UX as Oveview Page.

### Access 

The overview widget components has to be added in a reusable module so that we can reuse it. In fact, the reusable component has to be imported using load-group to optimize the number of JS files to load when loading the Space Home page with this widget.

### Services & processing

No change, we will have to reuse the same portlets of Overview page with contextual parameter of current space as audience to retrieve challenges and programs.

**Comment by margondicco** [comment]
Hello my feedback 

what is the sort rules ?

could we add the portlet in the Contribution section of the app registry ?


![Image](https://user-images.githubusercontent.com/31288011/221623944-9d2d2b2f-254b-4cb1-8b4d-e2d52efc0f1b.png)

**Comment by srenault-meeds** [comment]
Hello,

The sort is identified as the following:

> a sort by default to the most rewarding one to the less (4 max) and if actions needs to be done step by step, propose these one first

That means that the minimum sort will be from the most rewarding incentive (aka action / challenge) to the less one 
BUT (if possible) we will think about a different sort when you have locked incentive. For example:
- Omega action is locked by Beta action (you need to do beta action first)
- Beta action is locked by Alpha action (you need to do alpha action first)
Thus the list will be sorted that way:
1. Alpha action
2. Beta action
3. Omega action
4. any other action freely available

Of course, once you have done these actions, the list will propose new actions to do depending the points to get

I have edited the requirements accordingly.

**Comment by srenault-meeds** [comment]
Regarding your request to add it to the app registry, Meeds doesn't support this capability.
I let @rdenarie and @boubaker tell us how you would be able to get this.

**Comment by boubaker** [comment]
We will handle this as done for Overview Widgets, to be added by configuration Meeds Package in fact.

**Comment by boubaker** [comment]
Technical Design added, @AzmiTouil @rdenarie FYI (to review and comment please if needed)

**Comment by srenault-meeds** [comment]
To review again @boubaker 
Indeed I reuse the old MIP for gadget decentralization to group all items

**Comment by boubaker** [comment]
> Some event are not working anymore: create notes page, receive like on activity's comment, become space host

It's a regression from MIP#49 ? If yes, the MIP shouldn't be merged into develop without having known regressions IMO @srenault-meeds

**Comment by srenault-meeds** [comment]
Indeed. Updated

**Comment by boubaker** [comment]
@srenault-meeds no major change in technical specification. I still waiting for a "Go-Fun" to be able to submit this for Tech review.

**Comment by margondicco** [comment]
My comment : 

> Actions gadget decentralized by space if related to an audience

be careful not to inject  the gadget into dynamic containers or it will drive me mad 🥹

**Comment by srenault-meeds** [comment]
Solution proposed during PC & **validated**
* inject dynamically and if needed, can be removed from layout edition to be replaced by static container + app

Regarding the strategy of reloading the default page layout for overview, it is possible to update the configuration if needed.

**Comment by srenault-meeds** [comment]
Edit: Added notifications for action activity and announcement comments

**Comment by rdenarie** [comment]
Ok for me.

**Comment by srenault-meeds** [comment]
Hello, FYI, we used to have two or three events for activities. Example:
- Like activity in a space
- Like an activity (network)
- Like an activity (own)
We will merge these to one event: Like an activity
AND events related to network and own stream will be removed. 
If needed, I suggest to take the action to update your platform's contributions center .

OK for you @margondicco ?

**Comment by srenault-meeds** [comment]
@margondicco FYI, I have updated the MIP as we have added a widget in the stream page to list all actions upon their status

@boubaker Regarding this:
> The widget must be able to be plugged into Space Home page without a migration to a modified space Home Page Layout. In fact, to do this, we will have to use a dynamic container to inject new space widgets.

AND the fact that this widget is also available in the stream page

Do you mind if I update the information by myself? Or do you want to add anything there?

**Comment by boubaker** [comment]
> AND the fact that this widget is also available in the stream page

Updated, Thanks.

**Comment by boubaker** [comment]
Ready to review @rdenarie @margondicco 

1. Technically:

**9 PRs** Meeds to review (linked to MIP in `Development` section):
* https://github.com/Meeds-io/gatein-portal/pull/631
* https://github.com/Meeds-io/commons/pull/482
* https://github.com/Meeds-io/social/pull/2670
* https://github.com/Meeds-io/gamification/pull/1155
* https://github.com/Meeds-io/kudos/pull/312
* https://github.com/Meeds-io/wallet/pull/390
* https://github.com/Meeds-io/task/pull/220
* https://github.com/Meeds-io/meeds/pull/1029
* https://github.com/Meeds-io/meeds-qa-ui/pull/166

**2 PRs** for obvious adaptations to make in eXo side:
* https://github.com/exoplatform/news/pull/888
* https://github.com/exoplatform/agenda/pull/564

2. Functionally, the new features of current MIP can be tested in dedicated ACCs and can be found in Builders.

**Comment by rdenarie** [comment]
Majority of PR approved. 

One little feedback on https://github.com/Meeds-io/gatein-portal/pull/631
One question on : https://github.com/Meeds-io/social/pull/2670

**Comment by boubaker** [comment]
> Majority of PR approved.
> 
> One little feedback on [Meeds-io/gatein-portal#631](https://github.com/Meeds-io/gatein-portal/pull/631)
> One question on : [Meeds-io/social#2670](https://github.com/Meeds-io/social/pull/2670)

Thanks, considered.

**Comment by rdenarie** [comment]
All PR approved

**Comment by boubaker** [comment]
> All PR approved

Thanks @rdenarie . All Meed PRs merged. I let you `cherry-pick` https://github.com/exoplatform/news/pull/888 and https://github.com/exoplatform/agenda/pull/564 into `develop` branch of eXo projects.

**Comment by boubaker** [comment]
@rdenarie I missed a small PR https://github.com/Meeds-io/poll/pull/79 , can you please review it
