### ISSUE TITLE
 Manage Navigation

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/MIPs#51]
## Rationale

- Create a navigation or a page is confusing 
- Users don't understand the architecture of the information
- The training courses are complex and involve a lot of technical expertise 
- Our UI and UX are outdated and we need to redesign the use cases carried by the CMS

![image](https://user-images.githubusercontent.com/31288011/221537088-5d88f048-108f-42e1-a287-a0495e5d14a5.png)

## 1. Functional Requirements

V1 - https://youtu.be/qGRH96JkgLk
V2 - after brainstorm meeting (20230224)  

### 1.1. General requirements

**We could :**
- Filter a node (cf below)
- from a button create a new node and open another drawer. We could create a node and we define what will be linked to the node : a new page from a template, linked an existing page (search page functionality), linked an URL (that is a new capabilities).
- from a button : option the edit page layout if a page is linked to the node and open the existing edit layout (Of course, - there is an objective to redesign this functionality : not here)
- Quick access (cf below) : display the principle informations of the node ; quick action : delete node, move up, move down, edit node, cut and paste,
- manage access  on the node and page. (We simplify : a permission on the node will be the permission on the associated page. We can put a permission on a node that will not have a page)

**Existing features that we remove**
 
- Edit inline : very little use (only for accounts with portal uses or with many SCVs). Goals : redesign the single content function to allow simplified editing without having to go into the back office
- SEO : No use
- Edit site layout : in a first iteration : only from the administration functionality : /portal/g/:platform:administrators/portalnavigation
- Create a site : in a first iteration : only from the administration functionality : /portal/g/:platform:administrators/portalnavigation 

### 1.2. General flow
![image](https://user-images.githubusercontent.com/31288011/221537475-9ee41bdd-0957-40aa-b505-fa8557663982.png)

### 1.3. Top bar

![image](https://user-images.githubusercontent.com/31288011/221540582-e77c0f46-369b-4715-921c-1802b59d07ba.png)

- Create an new button "Site Navigation"  from right side to left side (near the branding logo)
-- The button is displayed only with a hover on the top bar
- The icon is available for any other member granted the edit permission of the current site. Defaut behavior for a standard page manager:platform/administrator
- The old drawer is hidden by a feature flag. Goal : ensuring the transition for our old "portal" client"

###1.4 Site navigation Drawer

![image](https://user-images.githubusercontent.com/31288011/221549320-22f910b9-2951-4888-abe8-821278828ba9.png)

#### 1.4.1 - General information

- Header entitled "Site navigation" and a close icon
- Must have : Expand button in order to see all the label if we have many level and long title and display additional informations
- Nice to have Filter on node name : a click on the filter button display the input field
- Site name followed by its node tree and available actions. We could not create a node directly in the first level. Goals : limit the risk of error. This will continue to be possible via the existing functionalities /portal/g/:platform:administrators/portalnavigation
- Permission on node : if i cannot edit the node, the node and its childen isn't displayed
- 3 dots icon: opens a popup with these possible actions

#### 1.4.2 - Actions
- must have : Edit page layout : displayed only if the node type is "Page" : open the edit page layout in a new tab
- must have : Add node : open the drawer create node
- must have : Edit node : open the drawer edit node
- must have : Delete node : a message asks for validation of the deletion. We need to validate for the modification to be taken into account. If the user cancels the node remains in its original location
- must have : Cut node/Pasted node : A message indicates the node has been cut and it can be pasted. The user chooses another parent node and can make the choice « paste" on the new parent node. We need to validate for the modification to be taken into account. If the user cancels the node remains in its original location
- must have : Move up and Move down allow to change the node's position. We need to validate for the modification to be taken into account. If the user cancels the node remains in its original location
- must have : Manage access : open the permissions drawer
- nice to have: Informations : open the informations drawer

If the user clicks outside the drawer and a modification has not been validated, it is proposed to cancel the modifications

#### 1.4.3 Manage access
![image](https://user-images.githubusercontent.com/31288011/221549708-228dfb7d-c3aa-49fe-b436-47dd50c6b468.png)

**Goals** :

Manage the access on the node and linked page

**Why** ? Currently, we cannot define a permissions on a node if there isn't page linked. Moreover as we could add a node with an url, we also should define permissions on the node.

_Rules :_ 

- Edit rules : no change same rules. Only manager or * can edit page. Sometimes it could be content management. the rule * is not understandable. It is replaced by the label "All rules".
- View rules : 2 options
1. Everyone : previous Any
1. Designed group : the choice platform/users is overloaded by the label "Internal users. the user will be able to choose the groups (all types of groups without restriction: it must be possible to choose a group present in the group profile, platform, spaces, profile or others). The user could define the role.
  
**Rules on page linked**
If i change the permissions one the node, the permissions on the page linked should change
No heritage rule from a parent node  (probably sooner) 

#### 1.4.4 Informations (Priority 2)

![image](https://user-images.githubusercontent.com/31288011/221549961-aa2972da-2187-43a3-aaa2-de93122c9259.png)

Goals : 
Make new information available to the persona content manager.  
Page indexing and search

Description: describe the purpose of the page by including tags. Eventually this field will be searchable
Modified and created : 
URI :
Node type : identifier les caractéristiques du noeud et par le bouton edit pouvoir modifier le noeud en ouvrant l'édit node drawer
Page name : 
Insights : 4 insights 

#### 1.4.5 Expand version (nice to have)

![image](https://user-images.githubusercontent.com/31288011/221550266-0b12189a-ca3d-4244-b99c-5dd171c9d7cb.png)

**Goals :** 
simplify page management and delete the /portal/g/:platform:administrators/administration/pageManagement page

**Filters**
- the filter input field is displayed
- a new filter in order to filter by node type (groupe, link, page)

**4 added columns :** 
- node type : link, group or page
- last updated : clic on the information button or on the date open the informations drawer
- Visibility : is the node is visible or not or the publication is scheduled
- Access : 3 distinct images  : everyone, all internal users, only designed groups. Clic on the image open the manage access drawer

## 1.5 Create / Edit node drawer

![image](https://user-images.githubusercontent.com/31288011/221550576-94fd88c2-5230-41fb-9d5b-bc9295e79702.png)

**Upper section**

- Header entitled "Add Node" or "Edit note" with a close and expand icon
- Node name: The page's name that will appear in different trees and on the browser tab: a text field allowing. It could be modified. It can define different multilanguage. (Multilingual composant)
- Node ID: text field allowing to define the node ID which will be contained in the page's URL, not editable in Edit mode. Leaving the field,  we apply a control on  forbidden characters. The field is set to red and the alert is proposed under the field. The field is presetted with the node name
- an information message about the page's URL to be created /siteName/Parentpage/nodeID
- Icon field: a selection field allowing to open icons list. Allows to associate an icon to the node
- Description : a text area

**Visibility section**

- Information button : Popup content  "Choose if you want to display the node for everyone who will have a right of access"
- Visible : a switch button allowing to make the node visible or not for all users in the different navigation portlet 
- If field "Schedule the publication of the node" and the filed visible start publication date and hours and End publication date and hours

**Node type section**

- Boolean Group or page/link node
- If boolean page or link node is active  and If an element has already been defined, edit element option is displayed. the type of element  (page or link) and the name of the page or the url are displayed
- Edition mode Clic on the edit element option open the drawer Elements
- Creation mode : the button save is replaced by a button Next which is opened the drawer elements 

## 1.6 Define Elements

4 options the users could select in a dropdown menu

- New page
- Existing page
- Link

2 actions : cancel or save

#### 1.6.1 New page

![image](https://user-images.githubusercontent.com/31288011/221550811-d1ac6a1c-9d81-46ed-ab31-0c6e67856523.png)

The following are displayed

- Target with two choice : Open a new tab, Open the same tab
- Template with 3 choice normal page, analytics page, blank page
- An image illustrating the template
- Save : open the edit layout in a new tab. Datas are saved and the drawer is closed

#### 1.6.3.  Link
![image](https://user-images.githubusercontent.com/31288011/221550916-f37eb4eb-80c1-48fc-9910-a97c227adf57.png)

The following fields  are displayed

- Target with two choice : Open a new tab, Open the same tab
- Link : text field wit no input rules (it could be a url like https://www.google.fr/ or /portal/dw or javascript:document.getElementById('appcenterLauncherButton').click() )

Save : The drawer is closed

#### 1.6.3.  Existing page

![image](https://user-images.githubusercontent.com/31288011/221551022-d2b7ce06-d719-4898-872d-51146d64c3aa.png)

 The following information are displayed

**Target with two choice** : Open a new tab, Open the same tab

**Link an existing page section**
 

- 2 chips "All sites" or "Select a site or a space". You could select only one chip.
- Field site filter : displayed with the choise : "Select a site or a space". i can search on site or space name. The selected site is displayed in a chip with a button delete
- Field page filter : i can search on page title (filtered by site or note if the previous field has been filled in. A droplist presents the results with the following information (site - page title). I coud select only one result. The selected page is shown into the search field. I can delete it

note : If the page node is changed, this should not break the link to the existing page

**Rule on filter operations** 

To optimize the search performance, a time-out should be launched after each typing. The search is launched when the timer reaches 0: 

- Duration:  300ms
- Each time a new typing action is done, the timer is reset and launched again
- During the time out, a visual indication is displayed to warn the user the search is in progress
- No results are displayed during the time out

The search should not be case sensitive
No restriction of search on special chars 

- All chars should be searchable
- All accentuated chars should be searchable. Correspondance rules should be implemented in order to facilitate the search of accentuated chars i.e. é=e, a word including an "é" should also give results without the accent and vice versa (for example:  desert should give the result "desert" and "désert")

No restriction of search on numerical chars i.e. I can search only numbers or have a number in my "keyword"
The search is done in the char chain
In the case of several keywords, it's a AND search that is applied i.e. both keywords should be contained in the name or contents to be proposed as results. Examples : 

- Keywords: Metric test
- Possible result: Metrics and test file

### Expected Volume & Performance

No big impact on data volume: Only two properties to add to the table: PORTAL_NAVIGATION_NODES
Performance when creating or getting navigations should not be affected.

### Security 

Only users of the group/roles who can edit the site

### Extensibility 

Navigation node types (page, link, objects...) should be extensible. Thus, the implementation and conception have to be extensible to allow easily adding of new types with their handlers by other applications.

### Upgradability

New properties added to the model should be added to existing navigation nodes  in the first server start (upgrade plug-in needed here)

### Existing Features

Current edit pages and sites menu should be hidden by a feature flag, then removed from the page header.

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  exo.feature.newEditNavigationDrawer.enabled|  false |   editors|   enable/disable the new edit navigation drawer|
|  exo.feature.oldEditNavigationMenu.enabled|  true|   editors|   enable/disable the display of the old edit navigation menu|

### Security

- In REST APIs, we will have to use @RolesAllowed to restrict access to endpoints to the allowed group of users
- External links should be opened in new page and the link should contain **rel="noopener"**  to prevent "Target="_blank" vulnerability (check this [link ](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/)for more details)

### Access 
   - GUI 
 
     - A new portlet will be added for Navigation management, it will contain: 
       - Site navigation Drawer (extensible)
       - Permissions Drawer
       - Information Drawer
       - Add/Edit node Drawer
       - Edit Page/Link Drawer

#### Rest & Websocket APIs
NavigationRest service will be updated to add new methods:
             -  POST: /v1/navigations (addNavigationNode) 
             -  PUT: /v1/navigations (updateNavigationNode
             -  DELETE: /v1/navigations (deleteNavigationNode
             -  GET: /v1/page (getPages)
             -  PUT: /v1/page (updatePage)
              -  POST: /v1/page  (addPage)

### Services & processing

Since, currently, we add permission only for pages so navigation nodes are filtered based on their related pages, 
we will need to also apply Access permission to grouping and link nodes. to do that we will need to add new properties to pages (pageType and link), so every navigation node will be related to a page to be able to apply permissions 

### Data and persistence
  
- [ ] Two new properties should be added to the table PORTAL_PAGES: 

(int) pageType
(String) link

- PAGE_TYPE: an integer to define the type of page and should have the value 0 by default (Page).
-  LINK: a String for the link of an external page

Related JPA Entity should be updated to add new attributes and the pageType will be related to an enum with the following list of values(PAGE,LINK, GROUP)

- [ ] Two new properties should be added to the navigation node table PORTAL_NAVIGATION_NODES : 

(int) target
(String) description

- TARGET: an integer to define if the page will be opened in a new tab or in the same tab this added property should have the value 0 by default (SAME_TAB).
- DESCRIPTION: a String to define a description.

Related JPA Entity should be updated to add new attributes and the target will be related to an enum with the following list of values(SAME_TAB,NEW_TAB)

**Comment by margondicco** [comment]
cc @srenault-meeds could you take a look here before the next commitee ? Thank you

**Comment by boubaker** [comment]
> the permissions should be stored in PORTAL_PERMISSIONS table ( PermissionEntity) with:

I think changing the current permissions management in Portal Layer by duplicating them will lead to incoherence, so it's better to avoid changing the current model and rely on existing one.

But, if the need is make a permission on specific tree of nodes in New Top navigation portlet, you can add, on top of GateIN-Portal Services, another service that should give more flexibility on Navigation items to display for users switch their roles & groups.

**Comment by mkrout** [comment]
> PORTAL_PERMISSIONS



> > the permissions should be stored in PORTAL_PERMISSIONS table ( PermissionEntity) with:
> 
> I think changing the current permissions management in Portal Layer by duplicating them will lead to incoherence, so it's better to avoid changing the current model and rely on existing one.
> 
> But, if the need is make a permission on specific tree of nodes in New Top navigation portlet, you can add, on top of GateIN-Portal Services, another service that should give more flexibility on Navigation items to display for users switch their roles & groups.

We will not change the current model, we will use the permission entity used for pages (https://github.com/Meeds-io/gatein-portal/blob/develop/component/portal/src/main/java/org/exoplatform/portal/jdbc/entity/PermissionEntity.java related to the existing table "PORTAL_PERMISSIONS") with as referenceType "NodeEntity.class.getName()"

**Comment by boubaker** [comment]
> We will not change the current model, we will use the permission entity used for pages (https://github.com/Meeds-io/gatein-portal/blob/develop/component/portal/src/main/java/org/exoplatform/portal/jdbc/entity/PermissionEntity.java related to the existing table "PORTAL_PERMISSIONS") with as referenceType "NodeEntity.class.getName()"

Yep, it's change the model with a flexible Table that supports Typed permissions ... The node didn't have a permission until now and you will add it, isn't it ? This is a redundancy comparing to current behavior which relies on Pages permissions only to know which nodes the user can access to.

**Comment by mkrout** [comment]
> This is a redundancy comparing to current behavior which relies on Pages permissions only to know which nodes the user can access to.

Yes, the service will check the permission depending on the node's type, if the navigation node is related to a page, the service will retrieve and check the page permission and if it's related to a link or to nothing (grouping node) the service will retrieve and check the node permission, I don't see any redundancy here, otherwise, the other solution will be to move all permissions to nodes and don't rely on page permission, here we will need to migrate data and rework the page edit layout web UI component.

**Comment by boubaker** [comment]
ok, as discussed, we may need an abstraction on current Page Model that will allow to add a new Type of Page: External Page. This will allow to preserve currently implemented business logic.

**Comment by rdenarie** [comment]
@boubaker Do we have a go-tech on this Mip ? Thanks

**Comment by boubaker** [comment]
> @boubaker Do we have a go-tech on this Mip ? Thanks

It depends, have you taken into account the last changes, I 'm waiting for your confirmation about changes applied to be able to review again.

**Comment by rdenarie** [comment]
cc @mkrout

**Comment by mkrout** [comment]
@boubaker all requested changes were taken into account, please check.

**Comment by boubaker** [comment]
ok for me, thanks.
("Go-Tech" label added)

**Comment by azayati** [comment]
There is a detail to be changed, after discussion with @margondicco a navigation node with type "Group" doesn't need access/edit permissions, so it will not be linked anymore to an empty page as mentioned. 
In that case IMO the new field pageType of PORTAL_PAGES table will have only two values (PAGE, LINK).
cc @boubaker @rdenarie @mkrout

**Comment by mkrout** [comment]
> There is a detail to be changed, after discussion with @margondicco a navigation node with type "Group" doesn't need access/edit permissions, so it will not be linked anymore to an empty page as mentioned. In that case IMO the new field pageType of PORTAL_PAGES table will have only two values (PAGE, LINK). cc @boubaker @rdenarie @mkrout

It's Ok for me

**Comment by azayati** [comment]
Another point, since a non admin user can also modify a page according to a specific permissions (example editor:/platform-web-contributors & site editor), in the manage access drawer, we need to display in the dropdown the list of available membershipTypes for access permissions and edit permissions parts. Currently the rest endpoint **Get: /v1/membershipTypes** has @RolesAllowed admins, we need to change it to users in order to allow getting the roles for an non admin user, do you have any objection ?
cc @boubaker @mkrout @rdenarie ?

**Comment by boubaker** [comment]
This is a detail of implementation, I let you manage it as you want @azayati , we will see the code details in PR reviews instead of here. The Go-Tech remains unchanged even with new questions and propositions.

**Comment by plamarque** [comment]
ETA end of may

**Comment by azayati** [comment]
PRs ready for review:
- https://github.com/Meeds-io/gatein-portal/pull/570
- https://github.com/Meeds-io/social/pull/2520

cc @boubaker @rdenarie

**Comment by boubaker** [comment]
> PRs ready for review:
> 
> * [feat: Implement "Manage navigation feature" - Meeds-io/MIPs#51   gatein-portal#570](https://github.com/Meeds-io/gatein-portal/pull/570)
> * [feat: Implement "Manage navigation feature" - Meeds-io/MIPs#51  social#2520](https://github.com/Meeds-io/social/pull/2520)
> 
> cc @boubaker @rdenarie

Thanks, seems ok for me, just a small comment to use same REST endpoint options as others in product.

**Comment by boubaker** [comment]
PRs approved, Thanks.
