### ISSUE TITLE
Attach Images

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#53]
## Rationale

When it comes to post a message, to announce an achievement, to send a kudos or to comment an activity or a task, end-users cannot attach any file type, starting by simply an image.

This is missing on a UX point of view. Indeed, any other social platform proposes such option.
In addition to this, proofs are requested for some declarative challenges and it is not possible to attach an image, a photo. This creates a feeling that the product is not "finished" as it is really missing.

## 1. Functional Requirements

- Access to the option
1. When posting an activity or announcing an achievement or sending a kudos message, I have an option in other editor options providing me a way to attach image files
2. When commenting an activity or a task, I have this option proposed in the editor option fields as well
3. When pasting or droping an image file to the composer field, then it is considered as an attached image file

- Image edition
1. When attaching an image, an option to edit it is provided to the user
2. By editing the image, a second drawer opens so the user can:
* decide to crop, resize, rotate it. If the image is a .gif file, this option should not be enabled (a tooltip or any other information tip will be displayed to the user so he can understand he cannot do such edition)
* add an alternative text for accessibility purpose

- Indexation
Indexation of attached files will be done later in another MIP

- Performance & Rendering
We suggest to optimize the image rendering once uploaded and posted like it is done currently for space and users avatars, banners.
So any image file added would be compressed without losing any quality.
That way, the rendoring is still ok but the size of the media file itself is reduced.

- Media files definition
1. Only image files are authorized to be attached: png, jpg, etc. and any **GIF file**.
Video files and any other file type won't be accepted for now. It will be studied after users confirmation.
4. Files limitation: as it is an image file, we recommend to accept maximum 20Mo per image
Performance topic of image rendering and display will be considered in another MIP.

- Extensibility
As this might be improved later, we need to make sure this option is extensible: 
*only image files to start. But this option might be reused in the future (particularly for preview, thumbnails and UX to attach files) for ohter file type.
*for now, files will be stored on dataserver. But we might go to other file storage like Web3 tool (IPFS, arweave, web3.storage, etc.)
*in any case a DAO member has its own files preview, it is needed to be sure any files using this new option can be preview the same way it is for other files
*the preview will only propose for now one option to download the media file. Still, it needs to be extensible so we can add options in the future

### Feature Flags

- This option of attaching images will be enabled by default for Meeds package and this option would be disabled by default for any other package. Of course, up to any other DAO member to enable this option once it is needed.

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
| exo.feature.EditorAttachImage.enabled | true (in Meeds Package only) | All | Enables a button in Rich Editor of some entities to allow attaching files |

### 4.1. Access 

- A new reusable component will have to be developed in a dedicated module that will be added in dedicated JS groups to load it when needed
- In this new JS module (Vue project), we will have to define the drawer for image/file attaching and a component to display it in different manners, like carrousels or listing
- The `/portal/upload` will be used to upload data to server
- A new REST endpoint `/portal/rest/social/attachments` will be added to allow attaching files into an existing entity, read the attachments of an entity and delete it.
- A new CKEditor Plugin has to be developed to add image attachment option

### 4.2. Services & processing

- The FileStorage will be used to store uploaded files
- The association between entities (like activity, task ...) and the attached file will be made by MetadataService (For activities, org.exoplatform.social.core.jpa.storage.RDBMSActivityFileStoragePlugin has to change to rely on MetadataService by example)
- Each entity type that would like to allow attaching files has to inherit from an API to define permissions on elements switch its ids
- When the attached file is an image, the thumbnail processing should be used to optimize image size

#### 4.2.1. Attach an image

The following sequence diagram gives the main idea about attaching image process

![AttachActivityFiles](https://user-images.githubusercontent.com/594824/229764905-0783aef9-88ab-4779-96b4-a661ae622cc2.png)

#### 4.2.2. Display attached images

The following sequence diagram gives the main idea about retrieving attached images process

![GetAttachedActivityFiles](https://user-images.githubusercontent.com/594824/229773127-1abfa21d-71ba-480e-b530-c2becd8feb19.png)

### Data and persistence

- No data model change

**Comment by srenault-meeds** [comment]
@boubaker can you please take a look at it?
I'll send you an event invitation so we can discuss it.

**Comment by margondicco** [comment]
Hello 

quick comment : 

_> For performance's sake and environment's substainability, any media file added would be compressed without losing any quality. That way, the rendoring is still ok but the size of the media file itself is reduced_

- the orientation of the image must be correct
- an animation gif must be kept

**Comment by srenault-meeds** [comment]
please @boubaker take a look at it following our meeting yesterday

**Comment by boubaker** [comment]
> please @boubaker take a look at it following our meeting yesterday

Yep, noted, I 'll study the expected functional behavior and attempt to provide an adequate software architecture.

**Comment by srenault-meeds** [comment]
Updated accordingly

**Comment by boubaker** [comment]
@rdenarie Tech Spec review needed please

**Comment by rdenarie** [comment]
The current library used to resize images is Scalr (https://github.com/rkalla/imgscalr)
When using scale function of this lib, we loose the animation of gif and the orientation of images. 
Do you plan to  change this library ? 

It is an implementation detail, so it is a Go-Tech for me.

**Comment by boubaker** [comment]
> The current library used to resize images is Scalr (https://github.com/rkalla/imgscalr) When using scale function of this lib, we loose the animation of gif and the orientation of images. Do you plan to change this library ?
> 
> It is an implementation detail, so it is a Go-Tech for me.

( ok could you please add the label & delete "To Check" label @rdenarie )

If it's complex to treat, yep @srenault-meeds , since it's a bugfix/enhancement, can you please make it available outside this MIP so that it will be available for eXo as well as this MIP is intended to add a feature for Meeds package only.

**Comment by rdenarie** [comment]
> this MIP is intended to add a feature for Meeds package only.

What do you mean ? Why it is for "meeds package only" ?

**Comment by srenault-meeds** [comment]
> > this MIP is intended to add a feature for Meeds package only.
> 
> What do you mean ? Why it is for "meeds package only" ?

To start, it will be set to true in meeds package and once it is ok, you would be able to set it true for you as well

**Comment by rdenarie** [comment]
Ok, so, it is not a feature for "meeds package only", right ?

**Comment by srenault-meeds** [comment]
yes indeed. I update it:)

**Comment by srenault-meeds** [comment]
Updated! @rdenarie 

> This option of attaching images will be enabled by default for Meeds package and this option would be disabled by default for any other package. Of course, up to any other DAO member to enable this option once it is needed.

**Comment by plamarque** [comment]
ETA end of may

**Comment by srenault-meeds** [comment]
Hello, @margondicco I d like to add the fact that images can be edited before posting/updating the messages (to crop, to resize, to rotate, to add an alternative text). Is that ok for you? Does that change your Go-Fonc decision?
Thanks

**Comment by margondicco** [comment]
> Hello, @margondicco I d like to add the fact that images can be edited before posting/updating the messages (to crop, to resize, to rotate, to add an alternative text). Is that ok for you? Does that change your Go-Fonc decision? Thanks

Good idea

**Comment by srenault-meeds** [comment]
Item added and here is the visual of this edition option:
1. left image when adding an image (canvas is square as the card is square itself)
2. when editing the image, a cancel button displays to set the default image back
<img width="317" alt="image" src="https://user-images.githubusercontent.com/58853195/234574906-f3ed41f4-6d39-48a8-aacd-4bf077455a41.png">

**Comment by srenault-meeds** [comment]
cc @boubaker if you need to add any technical spec

**Comment by boubaker** [comment]
yep, no change on technical requirements and software architecture sections

**Comment by srenault-meeds** [comment]
@margondicco Hello, sorry for my mistake, but I forgot to precise how end-users will get notifications for images activity/comment.
I suggest to not display images in the email notification to avoid too much work for this. Indeed, I would like to review the notification topic in a dedicated MIP.
However, I recommend to inform the mail notification receiver about the images attached the following way:


```
[John Doe] has posted a new activity in [SpaceAlpha]. See the post:
> lorem ipsum lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum
[xx] images attached 

```


WDYT?

**Comment by srenault-meeds** [comment]
Updated the Flag properties from  exo.feature.richeditor-attachments.enabled to exo.feature.EditorAttachImage.enabled

**Comment by plamarque** [comment]
ETA end of sep

**Comment by SaraBoutej** [comment]
Update made to introduce new feature flag exo.feature.EditorAttachImage.enabled 
**OK** for Meeds mips acceptence (true)
**KO** for eXo mips acceptence (false)
@rdenarie

**Comment by SaraBoutej** [comment]
PRs and ACCs ready for review by DAO Members (eXo : @rdenarie )

**Comment by rdenarie** [comment]
All Pr validated

**Comment by boubaker** [comment]
> All Pr validated

Thanks. @rdenarie I added the PR for meeds-qa-ui, I forgot it in fact.
