### ISSUE TITLE
Composer UX additions

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#54]
## Rationale

The composer provides different options currently:
1. write a message
2. create a poll

It misses a way to send kudos as it is also a message. For clarity sake and for unified UX, it seems to be interesting to get this access from the composer as well.

In addition to this, when it is possible to write a message from the general stream, end-users cannot choose their audience. The UX is not clear to end-users and thus, this option is disabled.
While it is requested by end-users to easily write a message and choose an audience.

## 1. Functional Requirements

1. From the general stream, propose to write a message 
- with a call to action clearly proposed to the user

- with a way to choose an audience among his network or one of spaces he is member of - or redactor if needed (only one space, and if current user is member of it)

> this option of choosing "your network" audience will be provided by default. 
Information: A property will be added to remove this so only spaces can be chosen as audience

<img width="314" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/1e406fbb-e7b0-49fd-807b-cad215b52187">

> This whole option of posting from general stream needs to be enabled/disabled by config

- with option left to filter so it is known by users they can send a kudos from there:
<img width="718" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/e894b0d5-5c3d-4152-a28e-a7457955e749">

When sending a kudos from there, an audience can be chosen as well as the kudos receiver 

<img width="305" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/e17fff2f-a3d5-410e-a47e-9df1a65f52c2">

5. From a space, propose same UX but filtered to the actual audience of course with CTA to send kudos and attach poll:
 
- create a poll for a community
- send kudos in the current community

<img width="724" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/d8cdbdb1-7f89-4a76-b68b-b452f5514187">

### Extensibility 

The list of **Activity Composer Quick Actions** must be extensible the same way as done for **Activity Composer Drawer Actions** with a different __extensionName__.

### Existing Features

**Activity Composer Drawer Actions** must remain compatible with its extensibility API using extensionRegistry.

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
| exo.feature.PostToNetwork.enabled | true (in Meeds Package only) | All | Allows to a user to post on his network or not. Default set to true to allow users to post in their personal stream. |

### Access 

- The main change is about Frontend components update, thus no change will be needed on REST endpoints
- A new component has to be defined for **Activity Composer Quick Actions** where we will be able to define by extensionRegistry the actions that will be listed there

### Services & processing

No notable backend

**Comment by srenault-meeds** [comment]
@boubaker can you please take a look at it?
I'll send you an event invitation so we can discuss it.

**Comment by srenault-meeds** [comment]
@boubaker I have reviewed the MIP functional requirements. I let you check

**Comment by srenault-meeds** [comment]
@margondicco I let you read this and give me feedback if needed

**Comment by boubaker** [comment]
> @boubaker I have reviewed the MIP functional requirements. I let you check

@srenault-meeds we need the Go-func before seeking for Go-tech status

**Comment by margondicco** [comment]
Hello my feedbacks : 

 I understand and I'm ok with the objective of clarifying the call to action, especially on the general stream

On the other hand, I have trouble understanding what happens on the different actions

What happens if I click on a picture or a poll?

IMO we lose space with a new option line.

**Comment by srenault-meeds** [comment]
> On the other hand, I have trouble understanding what happens on the different actions
What happens if I click on a picture or a poll?

I have added some explanations regarding it. You're right, it missed clarifications. So there it is:

> That means this:
1. When clicking to send kudos, I have the send kudos directly opened
2. When clicking to attach image, I can choose the images to attach and once done, it opens the composer with images attached to it (like linkedin)
3. When clicking to create a poll, it sends the user to the create poll drawer directly and once done, he can add a message

**Comment by margondicco** [comment]
OK Go Fonc and as DAO member we will have to work on it with the extension points

**Comment by srenault-meeds** [comment]
@boubaker your turn now :-)

**Comment by boubaker** [comment]
ok, thanks, @rdenarie ready for Tech review

**Comment by rdenarie** [comment]
Ok for me

**Comment by srenault-meeds** [comment]
Hello, I have edited the MIP description as we needed to improve the UX of choosing an audience when posting from general stream.
In addition to this, we need to study the addition of a property to enable/disable the choice of Network audience. Of course, I have detailed it in the description

**Comment by plamarque** [comment]
ETA end of september

**Comment by boubaker** [comment]
Update made to introduce new feature flag `exo.feature.PostToNetwork.enabled` @rdenarie

**Comment by boubaker** [comment]
@rdenarie Ready to review (PRs linked in Development section & ACCs up to date)

**Comment by rdenarie** [comment]
By checking acceptance, I didnt see button "Create a poll" nor "Share image"
Was it removed ?
Did I miss a property ?

**Comment by boubaker** [comment]
> By checking acceptance, I didnt see button "Create a poll" nor "Share image" Was it removed ? Did I miss a property ?

Yep, the poll action is possible in a space stream only.

**Comment by srenault-meeds** [comment]
> By checking acceptance, I didnt see button "Create a poll" nor "Share image" Was it removed ? Did I miss a property ?

Yes, my bad, I forgot to update the description. 
So, to summarize:
- No poll option from general stream (only in spaces)
- no add images as it is in the editor

**Comment by rdenarie** [comment]
I centralize comments about PR here, to have all in the same place : 
- It is not possible to publish an activity in mips-ft acceptance. The publish button stay disabled
- Kudos extension is type composer-action-item, and poll extension is type activity-composer-footer-action. Why such a difference ? I think it should be same type no ?
- When I add a new extension with type activity-composer-footer-action, for news for example, I have this : 
![Image](https://github.com/Meeds-io/MIPs/assets/807839/df5e6214-4265-464b-b825-bfea36387334)
There is no margin between extensions. We should add one, but where ? in each component ? in the extension-registrycompoent ? I let you choose, and I'll adapt my extension
- Icon size in drawer are not consistent : kudo is 37,5x50
![Image](https://github.com/Meeds-io/MIPs/assets/807839/4454df76-158b-4503-94b8-54bbe25188fa)
poll is 36,75x42 : 
![Image](https://github.com/Meeds-io/MIPs/assets/807839/24691283-41c6-4244-b231-b0ca28fe8204)
Could we keep a standard squarred size, so all icon will be consistent and aligned. We could choose 42x42 for example
- Before this MIP, the poll button have a subtext ("Add poll to your activity"). It was removed, does it is intended ? Should we readd it ?
- In toolbar extension (poll and kudo), the title of the button have a bottom margin (mt-1). By no using a bottom margin, the text is better vertically centered : 
With bottom margin : 
![Image](https://github.com/Meeds-io/MIPs/assets/807839/74d9b280-cf81-452c-8ede-a300fe6d2bf8)
Without bottom margin : 
![Image](https://github.com/Meeds-io/MIPs/assets/807839/a902165c-c7fe-44ba-b40b-119bdb8aff3b)
- The margin between toolbar button and toolbar text is quite large. You use ms-5, I think ms-3 is sufficient.

**Comment by srenault-meeds** [comment]
> It is not possible to publish an activity in mips-ft acceptance. The publish button stay disabled

Can you precise where? Because here https://mips-ft.meeds.io/portal/meeds/stream it is ok for me
and there https://exo-mips-ft.meeds.io/portal/dw/stream ok too

> Kudos extension is type composer-action-item, and poll extension is type activity-composer-footer-action. Why such a difference ? I think it should be same type no ?

Sure, maybe the difference between is that the kudos can be in the composer itself (see general stream). @boubaker any idea?

> There is no margin between extensions. We should add one, but where ? in each component ? in the extension-registrycompoent ? I let you choose, and I'll adapt my extension

yes a padding between each component IMO so each component has a margin-bottom 

> Could we keep a standard squarred size, so all icon will be consistent and aligned. We could choose 42x42 for example

No square size possible as it is an icon taken from fontawesome. However, you're right, the font-size applied for both icon is not the same (42px for poll and 50px for kudos). 
Requirement is 50px + icons need to be aligned vertically + label needs to be aligned to the left and vertically.
@MayTekayaa can we take care of this please? WDYT?

> Before this MIP, the poll button have a subtext ("Add poll to your activity"). It was removed, does it is intended ? Should we readd it ?
Yes it is expected.

> In toolbar extension (poll and kudo), the title of the button have a bottom margin (mt-1). By no using a bottom margin, the text is better vertically centered :

See my comment above

> The margin between toolbar button and toolbar text is quite large. You use ms-5, I think ms-3 is sufficient.

Can you please attach a screenshot?

**Comment by boubaker** [comment]
> Sure, maybe the difference between is that the kudos can be in the composer itself (see general stream). @boubaker any idea?

Yes, indeed.

**Comment by rdenarie** [comment]
> > It is not possible to publish an activity in mips-ft acceptance. The publish button stay disabled
> 
> Can you precise where? Because here https://mips-ft.meeds.io/portal/meeds/stream it is ok for me and there https://exo-mips-ft.meeds.io/portal/dw/stream ok too

I go in 'test space 1', click on 'start a message', fill the activity content, the "publish" button stay disabled :
![image](https://github.com/Meeds-io/MIPs/assets/807839/471b1b3d-73f7-43bb-95bb-afd1a116f0cd)
> 
> > Kudos extension is type composer-action-item, and poll extension is type activity-composer-footer-action. Why such a difference ? I think it should be same type no ?
> 
> Sure, maybe the difference between is that the kudos can be in the composer itself (see general stream). @boubaker any idea?

So I don't understand why. 
@boubaker what is the difference between 'composer-action-item' and 'activity-composer-footer-action' ?

> 
> > The margin between toolbar button and toolbar text is quite large. You use ms-5, I think ms-3 is sufficient.
> 
> Can you please attach a screenshot?

Current : ms-5
![ms-5](https://github.com/Meeds-io/MIPs/assets/807839/d9340956-f042-4f43-a90d-8390c4d04e60)
With ms-3
![ms-3](https://github.com/Meeds-io/MIPs/assets/807839/46b8758b-215a-4a37-a019-a3f4d202a124)
With ms-2 
![image](https://github.com/Meeds-io/MIPs/assets/807839/a192d47c-95c9-4e0f-b675-abb2d65140b7)

**Comment by srenault-meeds** [comment]
@rdenarie here my answers:

> I go in 'test space 1', click on 'start a message', fill the activity content, the "publish" button stay disabled :
Indeed, reproduced as well. I don't reproduce it on my side.

> The margin between toolbar button and toolbar text is quite large. You use ms-5, I think ms-3 is sufficient.

No, we keep it that way please. Indeed, if less than 20px, it is found as too much tight.

**Comment by rdenarie** [comment]
> @rdenarie here my answers:
> 
> > I go in 'test space 1', click on 'start a message', fill the activity content, the "publish" button stay disabled :
> > Indeed, reproduced as well. I don't reproduce it on my side.

Hum, did your reproduced ? or not ? :) It is not clear

**Comment by boubaker** [comment]
> So I don't understand why.
> @boubaker what is the difference between 'composer-action-item' and 'activity-composer-footer-action' ?

@MayTekayaa can you answer please

**Comment by srenault-meeds** [comment]
> Indeed, reproduced as well. I don't reproduce it on my side.

Reproduced on exo-mips but not in the meeds acc.
BUT after discussing it with Mayssa, we will take care of it.

**Comment by srenault-meeds** [comment]
To summarize @rdenarie, we take care of the following:
* icons size of CTA in drawer
* margin-bottom of CTA in drawer 
* problem of post disabled in a space

Remains the question regarding action-item and footer-action. We will let you know

**Comment by rdenarie** [comment]
I think you miss this point also 

> In toolbar extension (poll and kudo), the title of the button have a bottom margin (mt-1). By no using a bottom margin, the text is better vertically centered :
> With bottom margin :
> ![Image](https://github.com/Meeds-io/MIPs/assets/807839/de8b06bc-75eb-476b-8e90-0e1e8e99375e)
> Without bottom margin :
> ![Image](https://github.com/Meeds-io/MIPs/assets/807839/40316ecf-4a87-4128-9a8c-638ff7546c3e)

**Comment by srenault-meeds** [comment]
indeed, it is considered in Icons size of CTA in drawer

**Comment by rdenarie** [comment]
Ok, but it is not in the drawer, it is in the toolbar action. 
Are we agree ?

Thanks

**Comment by srenault-meeds** [comment]
ah ok sorry. I don't get your point.
Indeed, it has to be horizontally aligned as it is currently

**Comment by rdenarie** [comment]
Currently it is aligned on the bottom : the bottom of the image is on the same level as the bottom of the text. 

Should we align vertically the text  ? to center it with the icon ?

**Comment by srenault-meeds** [comment]
Yes it has to be align vertically to the icon but most importantly, it has to be horizontally aligned between items.
Here it is well done for kudos and poll (not article)
<img width="439" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/9ef46fa9-e78b-4919-989a-273217c77fca">

And article difference:
<img width="655" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/d00580bc-220c-4403-a6d6-278790e65ed8">

**Comment by rdenarie** [comment]
:+1 
I'll take care of this for article

**Comment by srenault-meeds** [comment]
@rdenarie thanks to @MayTekayaa, fixe are available on mips-ft acc

- icons size of CTA in drawer and alignements of label
- margin-bottom of poll CTA in drawer
- problem of post disabled in a space
- alignement of CTA below composer toolbar

**Comment by rdenarie** [comment]
All Prs validated
