### ISSUE TITLE
Image optimization & performance

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#55]
## Rationale

> Following MIP 53

When adding image to a page, to a comment, an activity, performance can be reduced and this becomes frustrating for end-users 
when displaying pages that are loading.

## 1. Functional Requirements

We suggest to optimize the image rendering once uploaded and posted.
So any image file added would be compressed without losing any quality.
That way, the rendoring is still ok but the size of the media file itself is reduced.

> *Other characteristics*
In the same time, we should make sure that: 
- when the image is a GIF (animated image), then it is well displayed animated.
- and the orientation of the image is taken as it is from the device it has been uploaded

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  |   |   |   |

### Access 
   - GUI 
   - API 

### Services & processing
   - Ex: Scheduled Jobs

### Data and persistence
   - Macro data model
   - Persistence layer 
   - Use of caches
## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts 
   - References

**Comment by srenault-meeds** [comment]
As discussed @boubaker a dedicated MIP for image optimization and perf

**Comment by margondicco** [comment]
Hello + maintain the properties of orientation (90°, 180°, etc.)

**Comment by srenault-meeds** [comment]
Updated accordingly

**Comment by plamarque** [comment]
Following decision of the product committee, this MIP is rejected. the requirements will be integrated into MIP-53.

**Comment by srenault-meeds** [comment]
Rejected and included there: https://github.com/Meeds-io/MIPs/issues/53
