### ISSUE TITLE
Spring Integration

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/MIPs#57]
## Rationale

The Development frameworks, standards and dependencies evolves over the time very quickly. Currently, we have a custom stack of Core features that even implements some JSRs. This stack of features is very hard to maintain and evolve. Most of implemented JSRs are outdated and even are incompatible with new Jakarta EE specifications.

Knowing that Meeds product aims to provide high level applications rather than being a framework provider, we will need to reuse a set of third party libraries to ease the production of features.

In order to make Meeds product development process smoother and community learning curve optimized, we aim by the current MIP of making Spring Framework the new core framework.

## 1. Functional Requirements

No functional change is needed.

### Expected Volume & Performance

No performance regression should be observed by this MIP.

### Security 

No major change in the Security model has to be made, we still using deprecated PicketLink IDM library until this first step of Spring integration is made.

### Extensibility 

The old definition of Meeds Kernel IoC components has to remain possible in addition to the fact that Spring Beans are possible to use as well. This should help to progressively migrate Components from Kernel IoC definition to Spring Beans.

### Configurability 

The usage of Spring has to remain builtin and doesn't need additional JARs installation.

### Upgradability

No need for data upgrades in this MIP. The data stores should remain exactly the same.

### Existing Features

A first addon full upgrade has to be made to make it as an example of Spring integration.

### Feature Flags

No feature flag is needed.

### Security

A Spring integration has to be made to reuse the existing JAAS login module `gatein-domain`. This login module with its map of roles has to be mapped with Spring Security in order to use `@RolesAllowed` or `@Secured` in Spring Rest Controller Beans.

### Access 

The REST endpoints of each addon has to be accessible from the **W**eb**AR**chive of the addon itself. We will no more need to use a single entry point for all REST endpoints (`/rest`). This will help to separate the addons in Microservices when need in the architecture evolution later.

### Services & processing

Each addon will be able to define its own Spring application by using the following annotation:

```
@SpringBootApplication(
  scanBasePackages = {
      "io.meeds.XYZ",
      "io.meeds.spring.integration"
  }
)
```

The package `io.meeds.XYZ` is the specific package of the addon that will be used to scan for components.
The package `io.meeds.spring.integration` has to be used as well to allow retrieving the builtin beans used to make the integration between `Meeds Kernel IoC` and Spring Beans. The beans of this package aims to:
- Make `Meeds Kernel IoC` single Service instances injectable using `@Autwired` or similar annotations (like `@Autwired`)
- Inject Application `Spring Beans` into `Meeds Kernel IoC` in order to make it accessible using `container.getInstanceOfType`
- Disable Logback initialization in WebApp context after having initialized it already in Meeds Server globally
- Propagate JAAS `principal` into `Spring Security Context` for a given user Request on API
- Initiate `ExoContainerContext.setCurrentContainer` and `RequestLifeCycle.begin` for Transaction management for each HTTP call on Application REST endpoint.

### Data and persistence

No data model change

**Comment by boubaker** [comment]
Not prioritized for now

**Comment by boubaker** [comment]
Ready for tech spec review by DAO Members (eXo : @rdenarie )

**Comment by rdenarie** [comment]
Go tech

**Comment by boubaker** [comment]
Ready for Review with ACCs Up & Running.

### Meeds Package PRs
* https://github.com/Meeds-io/maven-parent-pom/pull/45
* https://github.com/Meeds-io/maven-depmgt-pom/pull/143
* https://github.com/Meeds-io/gatein-wci/pull/20
* https://github.com/Meeds-io/kernel/pull/61
* https://github.com/Meeds-io/core/pull/94
* https://github.com/Meeds-io/gatein-pc/pull/22
* https://github.com/Meeds-io/gatein-sso/pull/34
* https://github.com/Meeds-io/gatein-portal/pull/799
* https://github.com/Meeds-io/commons/pull/579
* https://github.com/Meeds-io/social/pull/3362
* https://github.com/Meeds-io/gamification/pull/1404
* https://github.com/Meeds-io/kudos/pull/453
* https://github.com/Meeds-io/perk-store/pull/313
* https://github.com/Meeds-io/wallet/pull/483
* https://github.com/Meeds-io/push-notifications/pull/57
* https://github.com/Meeds-io/app-center/pull/313
* https://github.com/Meeds-io/analytics/pull/165
* https://github.com/Meeds-io/notes/pull/914
* https://github.com/Meeds-io/poll/pull/125
* https://github.com/Meeds-io/task/pull/330
* https://github.com/Meeds-io/gamification-github/pull/139
* https://github.com/Meeds-io/gamification-twitter/pull/35
* https://github.com/Meeds-io/addons-manager/pull/29
* https://github.com/Meeds-io/meeds/pull/1502
### Meeds Deed Addons PRs
* https://github.com/Meeds-io/deeds-dapp/pull/690
* https://github.com/Meeds-io/deeds-tenant-provisioning/pull/29
* https://github.com/Meeds-io/deeds-tenant/pull/48
### eXo PRs:
* https://github.com/exoplatform/maven-exo-depmgt-pom/pull/12
* https://github.com/exoplatform/jcr/pull/312
* https://github.com/exoplatform/ecms/pull/2263
* https://github.com/exoplatform/mail-integration/pull/63
* https://github.com/exoplatform/dlp/pull/50
* https://github.com/exoplatform/agenda/pull/627
* https://github.com/exoplatform/agenda-connectors/pull/93
* https://github.com/exoplatform/chat-application/pull/692
* https://github.com/exoplatform/digital-workplace/pull/114
* https://github.com/exoplatform/layout-management/pull/305
* https://github.com/exoplatform/news/pull/1048
* https://github.com/exoplatform/onlyoffice/pull/227
* https://github.com/exoplatform/web-conferencing/pull/209
* https://github.com/exoplatform/multifactor-authentication/pull/60
* https://github.com/exoplatform/documents/pull/1160
* https://github.com/exoplatform/processes/pull/346
* https://github.com/exoplatform/automatic-translation/pull/74
* https://github.com/exoplatform/anti-malware/pull/23
* https://github.com/exoplatform/data-upgrade/pull/180
* https://github.com/exoplatform/platform-private-distributions/pull/356

BTW, those 4 parents has to be **released sequentially** to make sure that each one will use the latest version of the dependency, freshly released:
* maven-parent-pom
* addons-parent-pom
* maven-exo-parent-pom
* addons-exo-parent-pom

BTW2, the package https://github.com/exoplatform/platform-public-distributions seems not on feature MIPs.

**Comment by rdenarie** [comment]
All prs validated, you can proceed to merge

**Comment by boubaker** [comment]
All PRs Merged.
