### ISSUE TITLE
Rich Editor Configuration Extensibility

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/MIPs#59]
## Rationale

The CKEditor (WYSIWYG Rich Editor) configuration can't be extended easily. In fact, most of the time, rich editors actions and tools depends on two things:
* Installed addons
* Rich Editor instance Type (Activity, Achievement Description, Task Description ...)

We need to have a way to extend CKEditor configuration depending on those two parameters.

## 1. Functional Requirements

No functional change should be observed by applying this change

### Extensibility 

* An addon has to be capable of defining new CKEditor configuration parts such as plugins, toolbars, buttons ... configure existing plugins.
* Each Rich Editor instance Type has to use a unique identifier when retrieving its configuration to be able to extend its specific configuration without impacting other Rich Editor instance types 

### Configurability 

It must be possible to include JVM properties in injected CKEditor configurations to allow defining some properties values using `exo.properties`.

### Upgradability

All CKEditor instances has to adopt new Rich Editor configuration endpoint instead of static old URLs to benefit from the supported and maintained CKEditor configuration.
The static JS file has to be kept in order to preserve a backward compatibility for addons developed outside Meeds-io.

### Feature Flags

No need to use a feature flag

### Access 

A REST endpoint has to be added to retrieve the configuration of a CKEditor instance, example of URL:

* `/portal/rest/richeditor/configuration?type=ActivityStream`
* `/portal/rest/richeditor/configuration?type=Achievement`

### Services & processing

The CKEditor configuration Service (`RichEditorConfiguration`) will allow to add one or multiple type of component plugins:
* A component plugin to be able to add a generic configuration to include in all Rich Editor instances
* A component plugin to be able to add a specific configuration to include in a specific Rich editor instance

**Comment by boubaker** [comment]
@rdenarie needs review

**Comment by plamarque** [comment]
@boubaker  please indicate that the feature will be backward compatible.

**Comment by boubaker** [comment]
> @boubaker please indicate that the feature will be backward compatible.

Done, thanks for the feedback.

**Comment by boubaker** [comment]
> @rdenarie needs review

PRs are ready to review as well @rdenarie (PRs linked to current MIP)

**Comment by rdenarie** [comment]
PRs validated

**Comment by boubaker** [comment]
> PRs validated

Thanks, merged. Can you please add the Go-Tech label @rdenarie if it's ok for you
