### ISSUE TITLE
DRAFT - Post from the stream and choose an audience

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#6]
## Rationale

Details of the GAP ( problem(s) to address ) expressed by few words using some screenshots.
From the user personal stream, it is usual to start a post in any other social tools. 
Currently, we can do that by enabling a property which is set to false by default. Indeed, users when having this option don't know where they are posting so we decided to disable this option.
In the meantime, we suggest to improve this option by proposing to users to choose an audience where there message will be posted in.

## 1. Functional requirements
- Above the user personal stream only, in front of the stream filters, I will have a field proposing me to start a post
- Once the user clicks to it, the composer opens with an autofocus to the composer field
- If needed, the user can decide to choose where to post this message thanks to a suggestor above the composer field. By default, it is set to "My connections"
- Once the user posts the message, it appears dynamically to the stream and a success notification toast is displayed to the user

Design: https://xd.adobe.com/view/872676e0-99c0-4489-b4aa-ecd37eb0ad66-d275/

## 2. Non Functional Requirements
- To be studied

## 3. Impacts
- Documentation to update
- Change management needs: check if this has to be enabled or not with a webinar for example

## 4. Software Architecture
- To be studied

## 5. Annexes
   - To be studied

**Comment by margondicco** [comment]
@Samuel-Renault-eXo 

`If needed, the user can decide to choose where to post this message thanks to a suggestor above the composer field. By default, it is set to "My connections"`

Would it be possible to provide a property to leave the suggestor empty AND not allow "my connections" to be chosen?

Goals : Force users to post to a space

Thank you

**Comment by srenault-meeds** [comment]
Cancelled as done by https://github.com/Meeds-io/MIPs/issues/54
