### ISSUE TITLE
Media embedded with iframely in notes

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/MIPs#65]
## Rationale

- iframely is used in a "hidden" way via the ck editor
- iframely is executed when integrating a URL into a short message and a comment. A preview of the link is offered after publication and if it's a youtube, dailymotion or vimeo video, the video is cast.
- This behaviour is also present in note  but is not expected: pasting the link creates a thumbnail but it cannot be moved, sized or viewed after publication.
- The market considers our ability to integrate third-party media to be very/too poor. A platform has to be able to aggregate different media directly in the body of a note

## 1. Functional Requirements

- No change expected in the stream
- In notes, remove the automatic generation of the thumbnail after pasting a URL
- In notes, remove the video insertion plugin
- In note, integrate the native Ck editor media embed component connected to our iframely installation
- In note, ensure that the embedded media is displayed in consultation view
- In note, ensure the ability to edit embedded media in editing mode
 
the following requirements will not be processed in this MIP

- In note, enable resizing of the embedded media
- Nice to have : Iframely, depending on the embedded source, can offer additional display options. enable the ckeditor component to be extended to allow editing of these additional parameters ; size, start from, end on
 

Example of integration that would be possible in note  : Detailed list and example: https://iframely.com/domains

## 2. Technical Requirements
This feature will consist in modifying the ckeditor configuration for notes editor.
- Video insertion plugin will be removed
- Automatic generation of thumbnail after pasting url will be removed
- Add the default ckeditor "embed"

After having updating this configuration, we must ensure that :
- the embedded media is displayed in consultation view
- we can edit the embedded media in editing mode

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  |   |   |   |

### Access 
   - GUI 
   - API 

### Services & processing
   - Ex: Scheduled Jobs

### Data and persistence
   - Macro data model
   - Persistence layer 
   - Use of caches
## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts 
   - References

**Comment by margondicco** [comment]
Hello @rdenarie could you prepare the technical part ?

cc @srenault-meeds

**Comment by rdenarie** [comment]
> In notes, remove the automatic generation of the thumbnail after pasting a URL

Remove plugin autoembed => complexity : low

> In notes, remove the video insertion plugin

complexity : low

> In note, integrate the native Ck editor media embed component connected to our iframely installation

Add plugin embed or embedsemantic. I didn't find any difference between

> In note, ensure that the embedded media is displayed in consultation view

complexity : medium

> In note, ensure the ability to edit embedded media in editing mode

We need to resolv previous point to see how to do this one. complexity : medium

> In note, enable resizing of the embedded media

This is not possible with both plugin embed or embedsemantic. It is a feature required for a long time in ckeditor (https://github.com/ckeditor/ckeditor5/issues/6593#issue-597548484)
If we want to do that, we need to override ckeditor existing plugin
complexity : high

> Nice to have : Iframely, depending on the embedded source, can offer additional display options. enable the ckeditor component to be extended to allow editing of these additional parameters ; size, start from, end on

This is not possible with both plugin embed or embedsemantic. 
If we want to do that, we need to override ckeditor existing plugin
complexity : high

**Comment by plamarque** [comment]
ETA begin of october

**Comment by rdenarie** [comment]
Technical requirements added. 
No other changes needed. 

CC @boubaker for go tech

**Comment by rdenarie** [comment]
After further discussion, fonctional requirements of this MIPs are included in meedsio/MIPs#71
I close this one.
