### ISSUE TITLE
Toolbar application composant

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/MIPs#66]
## Rationale

- Standardise behaviour in eXo
- Simplify design by defining common rules
- Limit overloading of native vuetify components
- Respect accessibility rules

### Top bar position

- Top bar height: 64px
- Padding left and right in relation to the edge of the application: 16px
- Padding top in relation to the edge of the application: 17px
- Bottom padding on the rest of the application: 17px
- note: on some apps the padding is applied to the whole app, on others it's applied per element.

![image](https://github.com/Meeds-io/MIPs/assets/31288011/80c8fefa-3372-4c2b-bd6c-c7ff69799268)

### Buttons: 

- vertical-align : center
- All buttons have the same height of 38px (standard vuetify height)

 
 #### Create button
 

- Full primary colour
- Click effect: no border

![67056a18ac12000d4bd20f977de0a023](https://github.com/Meeds-io/MIPs/assets/31288011/a3462379-3223-4b36-8257-f6c103f9ee5d)

#### Views button

- Text in lower case. Note: do not force the characters to be lower or upper case. Depending on the language, the second word may need to be upper case.
- View selected : in primary colour
- Inactive view :  in grey

![6706ffc0ac12000d592e3857a84456cc](https://github.com/Meeds-io/MIPs/assets/31288011/45b90f20-353a-4dda-b151-3e47c72de99a)

#### Filter zone

_**If 1 or 2 options, you can keep the display of two options**_

_Text filter area_

- When typing, the icon takes on the primary colour and a button is used to empty the input.
- Funnel icon size: 16x16

![6748fac1ac12000d34bd5764a067a5d0](https://github.com/Meeds-io/MIPs/assets/31288011/8da5d8dc-4efa-4547-ab8b-b3ca2dfd3fde)

_Advanced filters button_

- must be grey when a filter is not active
- When a filter is active, it should take on the primary colour for the border, icon and text. The number of filters selected is identified

![674b4da9ac12000d27f910fb2062d848](https://github.com/Meeds-io/MIPs/assets/31288011/ccc50da9-3913-4f32-8df0-14bf336c9ba4)

**_If there are 3 or more options, only one filter icon should be displayed._**

- [Fontawesome link
- ](https://fontawesome.com/v5/icons/filter?f=classic&s=regular)
- By clicking on it, the entire top bar is replaced by the filter zone

![674ba078ac12000d17fa4e50c7952dda](https://github.com/Meeds-io/MIPs/assets/31288011/7ddf6f3d-c350-4363-bdb5-6442a9c2ca03)

- Pressing ESC returns to the previous view, retaining the filters you have defined
- After selecting a filter, the filter button is full and takes on the primary colour

![image](https://github.com/Meeds-io/MIPs/assets/31288011/3ea37fce-2f25-44e7-8ebd-06bc70189dc2)

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  |   |   |   |

### Access 
   - GUI 
   - API 

### Services & processing
   - Ex: Scheduled Jobs

### Data and persistence
   - Macro data model
   - Persistence layer 
   - Use of caches
## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts 
   - References

**Comment by srenault-meeds** [comment]
Related issue: https://github.com/Meeds-io/social/pull/2561

**Comment by Julien-Dubois-eXo** [comment]
Here are my comments : 

- when the filter by name is active, the icon is no more displayed only the text field
- in my understanding, the ESC does the same as if we click on the "X". In my mind ESC key = close.

**Comment by margondicco** [comment]
> Here are my comments :
> 
> * when the filter by name is active, the icon is no more displayed only the text field

yes but only if we have 3 elements or more

> * in my understanding, the ESC does the same as if we click on the "X". In my mind ESC key = close.

yes

**Comment by Julien-Dubois-eXo** [comment]
I have edited the MIP to correct the following elements to match the final results:

- padding top and bottom:17px instead of 16px
- button size 38px instead of 36px
