### ISSUE TITLE
Site management

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/MIPs#68]
## Rationale

No functional requirement for meeds.

In general terms, this MIP allows sites to be managed via an administration function and new sites to be created in a module outside the meeds package.

**Note**: avoid describing the solution here.

### Security 

The new functionalities will be accessible by administrators.

### Extensibility 

We will add the possibility to inject new actions implemented from other addons into Space administration portlet using the extension registry mechanism. 

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|exo.feature.newSiteManagement.enabled  |  true (for eXo), false (for Meeds) |users   |enable/disable the new site management entry in administration menu   |

This feature flag will be disabled by default for Meeds, so the new site management entry will not be displayed for Meeds package.

### Services & processing

- We will implement EditPortalLayout action listener for UIWorkingWorkspace in order to let editing portal site layout by interface.
- We will refactor findSites method of PortalImpl service in order to ignore empty sites.

### Data and persistence

- We will change the character set of description column of PORTAL_SITES table to utf8mb4 in order to support emojis insertion.

**Comment by srenault-meeds** [comment]
go func

**Comment by azayati** [comment]
@boubaker We need a go tech on this MIP.
PRs ready for review & validation:

- https://github.com/Meeds-io/social/pull/2748
- https://github.com/Meeds-io/gatein-portal/pull/648

**Comment by boubaker** [comment]
> @boubaker We need a go tech on this MIP.

Yep, in normal case, the Tech review is asked before starting real development to be able to give feedback on concepts. Go Tech ok.

**Comment by boubaker** [comment]
* gatein-portal PR approved (apparently, auto merge applied on it, which is not recommended)
* social PR commented

**Comment by boubaker** [comment]
All PRs approved, thanks @azayati .
