### ISSUE TITLE
[Technical Improvement] Update Password Encoder Algorithm

### ISSUE THREAD

**Issue by rdenarie** [Meeds-io/MIPs#69]
## Rationale
Our password encoder algorithm is outdated and not secure (SHA-256)
We need to update to a more secure one

In addition, the usage of RememberMe token is not secure.

## 1. Functional Requirements
No functionnal modification 

### Security 
We want to use the Argon2id algorithm to hash passwords with parameters 
·	int opsLimit = 2; // 2 iterations
·	int memLimit = 32768; // 32 MB
·	int parallelism = 1; // 1 parallel execution
·	int outputLength = 32; // password hash length
The password Salt has to be 128 bits (16 bytes) of length.

For RememberMe Token, we want to generate it with the Argon2id algorithm with same parameters as password

### Configurability 
As Argon2 parameters could not be changed without reseting all password, we not make it configurable

### Upgradability
The migration strategy have 3 options : 
- keep hash with old algo. When user logs in, update the password hash with the new algo
- Invalidate passwords, so thats users have to update password, which will be hashed with new algo. Not applicable in our case as we cannot "invalidate" password
- Update SHA-256 hashed passwords stored in database. Database stores as password hash oldAlgo(password). Upgrade plugin will update theses hashes to have newAlgo(oldAlgo(password)). So that, all password are hashed with the new algo. The login processus must be able to validate password in both options.

We will use the most secure strategy based on data upgrade : the solution 3

### Existing Features
No modification

### Feature Flags
No Feature flag

### Documentation 
Technical documentation to update

## 4. Software Architecture
Store password process : 
![image](https://github.com/Meeds-io/MIPs/assets/807839/caa4c848-c721-479c-9d75-3d3e65e2f9c3)

Store Password Sequence Diagramm
![image](https://github.com/Meeds-io/MIPs/assets/807839/95275de0-19a5-45e9-b863-f92915394ef8)

Only the red part is to create

Validate Password process
![image](https://github.com/Meeds-io/MIPs/assets/807839/7d47196b-02b2-426d-96d7-d166f54a68e2)

Validate Password pseudo code in AttributeManager.validatePassword (afeter data upgrade execution)
```
Input : username, password

If (not user have attribute passwordSalt128 && user have attribute passwordSalt) {
   // user not connected && not migrated by data upgrade
   Check password with old algo (oldAlgo(password) == hashInDatabase ?)
   If validation is ok, call updatePassword to compute and save a hash with the new algo. During passwordUpdate, we need to ensure to remove passwordSalt attribute

} else if(user have attribute passwordSalt128 && user have attribute passwordSalt) (
   // user not connected && migrated by data upgrade
   Hash = Compute the hash of the password by using the old passwordEncoder  DatabaseReadingSaltEncoder. (oldAlgo(password))
   Then check hash with newAlgo (newAlgo(oldAlgo(password)) == hashInDatabase ?)
   If validation is ok, call updatePassword to compute and save a hash with the new algo. During passwordUpdate, we need to ensure to remove passwordSalt attribute

} else {
  //user connected
  use the current way to check password it will get the default configured PasswordEncoder and use it
      return this.getRepository().validateCredential(this.getInvocationContext(), this.createIdentityObject(user), new PasswordCredential(hash, this.getCredentialEncoder(), user.getKey()));
}

```

Remember me generation : 
![image](https://github.com/Meeds-io/MIPs/assets/807839/0303eb9e-3277-4ad3-8ce2-df6f45d84dc3)

RememberMe Validation
![image](https://github.com/Meeds-io/MIPs/assets/807839/679ee687-37d2-4f00-b3a9-55eb2e2a38d2)

Once remember me token are generated with new algo, we need an AuthenticatorPlugin to authenticate the user.

### Access 
   - GUI 
   - API 

### Services & processing
   - Ex: Scheduled Jobs

### Data and persistence
   - DataUpgrade 

```
for all user without attribute “passwordSalt128” :
   Get password hash in database
   Generate a passwordSalt128 and store it as attribute for the user
   Compute newAlgo(hash) and store it as new hash for the user
```
## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts 
   - References

**Comment by rdenarie** [comment]
@boubaker Could you see to provide a go-tech ? thanks

**Comment by boubaker** [comment]
> @boubaker Could you see to provide a go-tech ? thanks

LGTM, just a small remark

> Update hashed in database. Database stores as password hash oldAlgo(password). Upgrade plugin will update theses hashes to have newAlgo(oldAlgo(password)). So that, all password are encoded with the new algo. The login processus must be able to validate password in both options.

To change IMO to 

`Update SHA-256 hashed passwords stored in database. Database stores as password hash oldAlgo(password). Upgrade plugin will update theses hashes to have newAlgo(oldAlgo(password)). So that, all password are hashed with the new algo. The login processus must be able to validate password in both options.`

=> Changes
* first sentence to add "passwords"
* all password are encoded => all password are hashed : I propose to change 'encoded' to 'hashed' to make it clear that password aren't stored in database with an encryption algorithm instead of a hashing algorithm.

**Comment by rdenarie** [comment]
@boubaker updated. Thanks

**Comment by rdenarie** [comment]
Pull Requests are ready to validate  :
Maven-depmgt-pom : https://github.com/Meeds-io/maven-depmgt-pom/pull/132
Gatein-portal : https://github.com/Meeds-io/gatein-portal/pull/642
Wallet : https://github.com/Meeds-io/wallet/pull/400
Social : https://github.com/Meeds-io/social/pull/2715
Meeds : https://github.com/Meeds-io/meeds/pull/1060
Deeds-tenant : https://github.com/Meeds-io/deeds-tenant/pull/42

Feature is deployed on both mips acceptance to be functionnaly validated.

One thing is not testable : the modification in deed-tenant repository as there is no mips acceptance for that. 
The modification is in the MetamaskSigninFilter

cc @boubaker for validation

**Comment by boubaker** [comment]
> cc @boubaker for validation

Review done

**Comment by rdenarie** [comment]
Thanks @boubaker 

I update PR to answer your feedbacks.

Some are still open to discussion, on which I push an answer.

**Comment by boubaker** [comment]
Reviewd and validated @rdenarie , well done eXo Team !
