### ISSUE TITLE
Stream - Composer UX Enhancement

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#7]
## Rationale

Details of the GAP ( problem(s) to address ) expressed by few words using some screenshots.

Enhance ways message can be written and posted
- Adding a hashtag to activities or comment is not as easy as it looks. End-users has to eventually know it exists
- Adding emojis is not possible from the composer while it is enabled in any other social tools

Improve how the drawer behaviors when closing the composer
- When user close the composer, no warning is displayed so they might lose their content
- Drawer UX is not consistent with other drawers regarding the post button

## 1. Functional requirements

Enhance ways message can be written and posted
- Review the composer editor options to prior options like "add hashtags" or "add emojis" with ability to access other formatting options if needed
- When clicking to hash symbol, the hash will be added as if he has added it from the keyboard. 
- When clicking to emojis symbol, an emoji bank will be proposed so it is easy to add emojis from a bank
- Any emojis added using the keyboard should be recognized as is
Design: https://xd.adobe.com/view/40986df7-d42e-42a8-9656-2c29631602b9-15cb/

Improve how the drawer behaviors when closing the composer
- Post button is proposed to the bottom of the drawer so usage is consistent with other drawers proposed in the platform (only when composing an activity)
- Provide a way to users so they can retrieve their message until it is posted

## 2. Non Functional Requirements - Feature Flag

* Feature flag: `exo.feature.NewEditorToolbar.enabled`
* Target audience: all (no possible change)
* This feature flag is applied to allow enabling/disabling the grouping of WYSIWYG toolbar buttons.
* The default value of it is set to `false`

## 3. Impacts
- Documentation to update
- Flag for composer editor options

## 5. Annexes
- Nothing

**Comment by boubaker** [comment]
Feature Flag section added:

> ## 2. Non Functional Requirements - Feature Flag

@rdenarie @Samuel-Renault-eXo
