### ISSUE TITLE
Multingual in note app

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/MIPs#70]
## Rationale
Within an international context, we might need to propose translation for the same note without being able to duplicate all the knowledge base. 

We should be able to propose one knowledge base with different translation according to the user language settings. 

### **1.1 Translation in Note Editor**

**P1 - Translation option:**  

- The note redactor has a new feature allowing to generate of different translations for one note directly in the editor

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/76399573-4374-4a37-af68-85170a884400)

- When opening the editor, the original version is displayed. The original version is not corresponding to a language. 
- The user can open the translation options by clicking on the Translation button. There is a motion animation to hide all the first line and display the options.
- The user should exit the translation option to publish
- The user can:
  * see the currently selected version
  * see the available translation. 
    * If no translation the label "No translation" is displayed
    * If several translations: 3 translation chips are displayed and the other are displayed under a numerous indicator that open a dropdown
    * display order:
      - First load: by creation date
      - Then after selecting translation: by last selected
      - it's reset after a page refresh
  * select a new language to add a translation. Empty by default

 - When adding a translation, all the fields can be modified (title and body)
 - When a language is already translated it's no more suggested in the language selector
 - We can navigate between translations
 - The translation can be deleted but not the original version.
 - According to its status the language chip will have a different layout
 - Print to PDF is printing the displayed language version
 - No limit to the translation number
 - Breakpoint - Below 960px: 
   * The interface is simplified
   * The indicative labels are removed
   * We display only the selected version and we can change it by clicking on it and select the new version in a dropdown.
   * Just to remind, no editor below 770px

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/6a2e32f5-e3ca-4da9-a7a3-a3a0aa4adba6)

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/c6398c5b-9cef-4c18-b6d2-0259930cda39)

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/d31e0012-dfeb-4e36-b5e2-90e1ac755b02)

### 1.2 Translation in Note viewer

**P1 - Translation options:**

- A "Translation" button is displayed on the same line as the update information. The button is displayed if:
  * at least one translation is available

- By default:
  * if a translation corresponds to the user language is existing we display it - so the option is directly active
  * if not we display the original version - the option is not active
- The version can be selected in a dropdown. The translation button becomes active when a version different from the original version is selected
- Display order of the version: 
  * first: selected version so at first load = original version 
  * then translation by alphabetical order

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/40c9a26f-c5e8-4a5d-8d86-d4e1a44d1769)

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/1b38dd03-8176-4d66-bba2-41ea1ca84c20)

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/f104b51d-7c63-4f0e-ad14-6a6171493c71)

![Image](https://github.com/Meeds-io/MIPs/assets/105866381/1f56454e-da4a-4607-8cd5-7cd0755d38af)

### 1.3 History version

**One history version by language:**

- P1 - Each language version will have its own history version
- P1 - when selecting a translation, the "last update" information (date, time and user) and version thumbnail will be updated according to its history
- P1 - opening the history version by clicking on the option or the thumbnail will open the history of the language version
- P3 - the language version is displayed in the history version when a translation is existing

### Expected Volume & Performance

- Changes to be done should not impact notes app performance.
- The number of notes versions will increase depending on translations added.

### Security 
No changes that can impact app security

### Extensibility 
Nothing to expect

### Configurability 
Nothing to expect

### Upgradability
No migration expected

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
No feature flag

### Documentation 

Notes documentation to be updated

### Access 
   - GUI :  Notes App portlet to be updated ( adding the translation bar to the portlet header, updating the version management drawer)

   - API : Storage, Service and rest Api to be updated the manage notes by language

### Services & processing

- Currently, when a note is retrieved, the published content is stored in the note entity, we will use this field to store the default content, and translated content will be stored in versions and to show translated content we will retrieve the last version by the user language.

- Every change in content should create a new version with the selected language, the version label should be related to the language.

- Version history should be listed by the selected language

### Data and persistence
   - Macro data model
The current data model should be updated to be able to add multilingual notes:
Currently, we have the following data model:
![current](https://github.com/Meeds-io/MIPs/assets/1576267/7023de5e-3a6b-417b-91ee-d460a09baa2c)

**So content is stored in the note (WIKI_PAGE), version (WIKI_PAGE_VERSION), and in draft (WIKI_DRAFT_PAGES),** 
 

- The published content is stored in the note and the last version
- Every time we edit a note a new version is created with the new content and the content in the note table is updated
- Before saving the changes a draft is created.

**To be able to allow multi langs we will need to change the model:**
 

- Content in the note table will store the default content.
- A new column "LANG" should be added to the Version and draft tables

_New data model:_
![new](https://github.com/Meeds-io/MIPs/assets/1576267/92396e5d-128b-4c73-bae1-b2032e0f3d37)

   - Persistence layer 
      
**RDBMS:**

- All JPA entities should be updated according to the changes proposed in the new model.
- Storage API should be updated to add methods to store and get pages, versions, and drafts by a given language

    
 **ElasticSearch:**

- Instead of having an entry for every note with the published content, we will need to have a different entry for every lang so a new field "lang" to be added
- elastic search query should be updated to search on content by language.

### Migration strategy

No migration needed

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds functional requirement ready for review, please. cc @margondicco

**Comment by Julien-Dubois-eXo** [comment]
update the following elements:

- position of the translation option in view mode
- add display order rules in view mode
- add history version for translation

**Comment by Julien-Dubois-eXo** [comment]
Update with print to PDF behavior when a translation is displayed

**Comment by srenault-meeds** [comment]
Hello,

Questions:
1. Original version language:
> "When opening the editor, the original version is displayed. The original version is not corresponding to a language."

* it has to correspond to a language and IMO it is the global language set to the platform (not the user one) and we precise it only when adding a translation so the user knows about it

2. display when tablet
> "Just to remind, no editor below 770px"

You tell this but in the same type I see a mockup below this information with an editor while using 770px. Does that mean you aim to enable the edition when using tablet width? If so, ok with this, but needs to review the UI to display the editor then (other MIP)

**Comment by rdenarie** [comment]
@boubaker Can you make a tech review on this MIPs (for GoTech)

**Comment by srenault-meeds** [comment]
Hello, can we please clarify the following?


> P2 - Automatic translation - Not sure you it's present on Meeds.

Not on Meeds, so to remove from there


> P2 or P3

Can you please clarify the scope detailed in the MIP? Only P1


> Autotranslation mention in the MIP

Do we agree autotranslation here is proposed among user language preference?


> Feature flags

Only during dev?

@Julien-Dubois-eXo @margondicco

**Comment by Julien-Dubois-eXo** [comment]
I remove the automatic translation part as it's not present in Meeds. 

Yes, the feature flag will be present only during the dev, we remove it at the end of the iteration. 

On the MIP there are 3 scopes: P1, P2 and P3. P2 and P3 will probably not be done in view of the progression done so far.

**Comment by boubaker** [comment]
> Yes, the feature flag will be present only during the dev, we remove it at the end of the iteration.

ok, can you please delete the flags as it's not in the expected outcome that will be added in the final result. Thanks.

**Comment by Julien-Dubois-eXo** [comment]
Done

**Comment by boubaker** [comment]
Tech review done.

**Comment by plamarque** [comment]
ETA begin of october

**Comment by mkrout** [comment]
@boubaker @rdenarie merge pr for review: https://github.com/Meeds-io/notes/pull/873
les devs sont deployé sur les acceptances MIPS

**Comment by boubaker** [comment]
> @boubaker @rdenarie merge pr for review: [Meeds-io/notes#873](https://github.com/Meeds-io/notes/pull/873) les devs sont deployé sur les acceptances MIPS

PR approved. Have a nice weekend :+1:

**Comment by srenault-meeds** [comment]
Hello, 

> No blocker for this one

I have observed a regression in SNV when having multilingual option. The title is mandatory and we cannot add any translation FYI. 
<img width="449" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/7e15fada-c7bd-4059-963b-34fa31a89bc9">

So either we decide to not enable it for SNV at all, either we need to adjust it if really needed.
To study then
