### ISSUE TITLE
Left navigation

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/MIPs#72]
## Rationale

No functional impact for Meeds

This MIP introduces the capabilities to display sites in the left menu, the navigation nodes and allows an administrator to manage the icons associated with each item. Only by configuration (XML)

### Expected Volume & Performance

No big impact on data volume: Only four properties to be added to the PORTAL_SITES table.
Performance when creating or getting navigations and sites should not be affected.

### Security 

All users should access to the meta site and non meta sites with their navigation nodes. 

### Extensibility 

The meta and no meta sites should be created by xml configuration files with the new added properties.

### Upgradability

New properties added to the models should be configured for the existing navigation nodes in the first server start.

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|exo.feature.newLeftNavigationDrawer.enabled  |  false |users   |enable/disable the new left navigation drawer/the old left navigation drawer   |

This feature flag will be removed at the end of the iteration.

### Access

- GUI 
   
We need to update the frontend of HamburgerMenu portlet in order to meet the new look and feel of the left navigation menu.

### Services & processing

SitesRest service will be added with the method:

- **GET: /v1/social/sites (getSites)**: This service will need **expandNavigations** and **displayed** query params in order to retrieve the list of displayed sites with their navigations. 

This service will be moved from layout-management eXo module to social Meeds module.

### Data and persistence
  

- [ ] Four new fields should be added to the PORTAL_SITES table:

(BOOLEAN) DISPLAYED: A boolean which indicates if the site will be displayed in the left navigation of the **meta** site
(INT) DISPLAY_ORDER: An integer which indicates the display order of the site in the left navigation of the **meta** site
(BIGINT) LOGO: A big integer which indicates the file id in the FILES_FILES table corresponding to the site logo
(BIGINT) BANNER_FILE_ID: A big integer which indicates the file id in the FILES_FILES table corresponding to the site banner

- Related JPA Entities (Site and Node) should be updated to add these new attributes in addition to their different layers.
- We should update **NewPortalConfig** to add these new attributes which will be defined into the corresponding object-param of **NewPortalConfigListener** component plugin configuration files.
- We should have **only one meta site**, this will be configured using [default.portal value-param of **NewPortalConfigListener** component plugin configuration files](https://github.com/exoplatform/digital-workplace/blob/develop/digital-workplace-webapps/src/main/webapp/WEB-INF/conf/digital-workplace/portal-configuration.xml#L17).
- We should store the site logo and site banner using file service.

**Comment by azayati** [comment]
go tech needed @boubaker

**Comment by boubaker** [comment]
ok for me, thanks.

**Comment by boubaker** [comment]
@srenault-meeds ok for you for the Go-Func ?

**Comment by srenault-meeds** [comment]
Yes done. Thanks

**Comment by plamarque** [comment]
ETA End of Sep

**Comment by margondicco** [comment]
Hello @srenault-meeds @boubaker ,

 FYI & actions

This MIP will be merged soon. The flag is disabled by default and @azayati and me would like to remove the flag when merging

So you'll need to take action to ensure that things run smoothly.  

-/ Move the people and spaces node from the global navigation to the meeds site navigation
-/ Define the icons of all meeds site navigation nodes in navigation.xml. The value of the icon should be for example of format **fas fa-yin-yang** for solid type, **far fa-window-restore** for regular type, **fab fa-youtube** for brands type. (https://fontawesome.com/v5/search?o=r&m=free)

Thank you

**Comment by srenault-meeds** [comment]
> -/ Define the icons of all meeds site navigation nodes in navigation.xml. The value of the icon should be for example of format **fas fa-yin-yang** for solid type, **far fa-window-restore** for regular type, **fab fa-youtube** for brands type. (https://fontawesome.com/v5/search?o=r&m=free)

So if I understand well, old icons used for people and spaces need to be updated because of this move.
And what about overview and stream? As it is in global, I understand we don't need to do anything.

@margondicco

**Comment by azayati** [comment]
> So if I understand well, old icons used for people and spaces need to be updated because of this move.
And what about overview and stream? As it is in global, I understand we don't need to do anything.

@srenault-meeds 
No overview and stream are already defined as a nodes for Meeds site, for the icons you need to update of those of all Meeds nodes after moving global one (overview, stream, external-stream, spaces and people)

**Comment by srenault-meeds** [comment]
Ok

**Comment by azayati** [comment]
@boubaker 

PRs ready for validation:

- https://github.com/Meeds-io/gatein-portal/pull/647
- https://github.com/Meeds-io/social/pull/2747
- https://github.com/Meeds-io/meeds/pull/1146

**Comment by boubaker** [comment]
PRs commented

**Comment by boubaker** [comment]
All PRs approved
