### ISSUE TITLE
feat: Display banner on pages

### ISSUE THREAD

**Issue by azayati** [Meeds-io/MIPs#75]
## Rationale

The space header portlet is used to display an image as a banner only for space pages. 
The aim is to be able to use also this capability on all the platform's page since currently this portlet does not work outside the context of a space.

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  |   |   |   |

### Access 
   - GUI 
   - API 

### Services & processing
   - Ex: Scheduled Jobs

### Data and persistence
   - Macro data model
   - Persistence layer 
   - Use of caches
## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts 
   - References

**Comment by azayati** [comment]
After your discussion & decision @margondicco @srenault-meeds, I think that this MIP should be deleted.

**Comment by srenault-meeds** [comment]
ok so does this concern become an issue instead?
Thanks

**Comment by margondicco** [comment]
> ok so does this concern become an issue instead? Thanks

no we move this porllet in another package (layout management)

**Comment by srenault-meeds** [comment]
Ok

**Comment by azayati** [comment]
@srenault-meeds should this be closed as not planned ?

**Comment by srenault-meeds** [comment]
yes
