### ISSUE TITLE
Upgrade to Tomcat 10

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/MIPs#76]
## Rationale

The used Servlet container Apache Tomcat had evolved to introduce a newer version `10.1` that is part of `Jakarta EE 9`. This change implies multiple breaking changes and should be operated to benefit from newer third party libraries upgrades.

### Upgradability

This change has to upgrade any third party library that isn't compliant with Servlet Container 6.0. When third party libraries aren't compliant with Jakarta EE, we will have to enumerate them to decide whether to fork or to drop it.

### Impacted components

* `Portlet Container (PC)`: the provided JSR 168 and JSR 286 API Jars aren't compliant with Jakarta EE package names.  Same thing for the JSR 362 which is not implemented in our PC. For Portlet Container bridge, we will have to delete bridges knowing that it's not compliant with Servlet Container of Jakarta EE anymore and just keep the Portlet Container engine as an internal engine to display portlets in a single web page. (Delete compatibility with Portlet Container specifications knowing that it's not compatible with Jakarta EE anymore)
* `Kernel Containers IoC`: the portal container uses the Servlet Context to unify the services definition through addons. This implementation has to evolve to be compliant with Jakarta EE packages.
* Web Container Integration (WCI): this tiny Jar is used to integrate the Kernel mechanisms into Web Cotnainers and has to be moved into kernel to reduce the number of projects to release and reduce maintenance cost of projects at the same time as it has to be upgraded to Jakarte EE 10 packages.
* `WS`: we had implement the JSR 311 (JAX-RS) in the project [ws](https://github.com/meeds-io/ws). This implementation hasn't evolved to JSR 370 and isn't maintained to be useful as framework for community. Thus, we will aim to upgrade our REST APIs to rely on `Spring Rest` APIs in future releases (see [MIP#57](https://github.com/Meeds-io/MIPs/issues/57) ). This API migration will take some time to be done smoothly without breaking the existing implementation using the old implementation. In order, to keep this compatibility, the project WS has to continue being compatible with Jakarta EE and thus being migrated by dropping useless features not used in current RESTful APIs in higher levels.
* `SSO`: we had deprecated some SSO long time ago for `spnego`, `cas` and keep a compatibility for SAML v2 only. By upgrading to Jakarta EE, we will have to rework the SAML v2 integration to replace picketlink with a more modern and maintained third party library for SAML integration, which should be treated in a different MIP. In this MIP, we will have to fork picketlink-federations to update with Jakarta EE package names.

### Impacted third party libraries

* `commons-fileupload:commons-fileupload`: has to be replaced by `org.apache.commons:commons-fileupload2-jakarta` in `UploadService` only. Knowing that this library is used only for processing uploaded files through HTTP Requests. Knowing we have a **dev best practice** to exclusively use `/portal/upload` endpoint for Binary files uploading, we has to delete (instead of upgrading it) the possibility to upload files through REST endpoints.
* `org.apache.portals.bridges:portals-bridges-common`: a dependency that allows to add portlets using third party libraries in JSR 286 compliant Portlet Cotnainer. This dependency has to be dropped as explained above since we don't aim to keep a non-standard JSR implementation inside Jakarta EE compliant Servlet Container.
* `org.juzu:*`: a deprecated dependency that should be completely removed instead of upgrading it to be compliant with Servlet Container 6.0.

**Comment by boubaker** [comment]
**PRs - Part 1**:

* https://github.com/Meeds-io/maven-depmgt-pom/pull/134
* https://github.com/Meeds-io/kernel/pull/57
* https://github.com/Meeds-io/gatein-wci/pull/19
* https://github.com/Meeds-io/core/pull/84
* https://github.com/Meeds-io/gatein-pc/pull/20
* https://github.com/Meeds-io/gatein-sso/pull/28
* https://github.com/Meeds-io/ws/pull/41
* https://github.com/Meeds-io/gatein-portal/pull/651
* https://github.com/Meeds-io/commons/pull/497
* https://github.com/Meeds-io/social/pull/2769
* https://github.com/Meeds-io/analytics/pull/134
* https://github.com/Meeds-io/gamification/pull/1183
* https://github.com/Meeds-io/wallet/pull/401
* https://github.com/Meeds-io/kudos/pull/452
* https://github.com/Meeds-io/perk-store/pull/264
* https://github.com/Meeds-io/push-notifications/pull/47
* https://github.com/Meeds-io/notes/pull/712
* https://github.com/Meeds-io/gamification-github/pull/86
* https://github.com/Meeds-io/gamification-twitter/pull/31
* https://github.com/Meeds-io/meeds/pull/1081

**Comment by boubaker** [comment]
Ready to tech review @rdenarie

**Comment by boubaker** [comment]
**PRs - Part 2**

eXo PRs, to help you make the upgrade as agreed:
* https://github.com/exoplatform/maven-exo-depmgt-pom/pull/7
* https://github.com/exoplatform/commons-exo/pull/18
* https://github.com/exoplatform/jcr/pull/311
* https://github.com/exoplatform/ecms/pull/2251
* https://github.com/exoplatform/agenda/pull/626
* https://github.com/exoplatform/chat-application/pull/691
* https://github.com/exoplatform/layout-management/pull/291
* https://github.com/exoplatform/news/pull/1033
* https://github.com/exoplatform/onlyoffice/pull/226
* https://github.com/exoplatform/saml2-addon/pull/17
* https://github.com/exoplatform/web-conferencing/pull/208
* https://github.com/exoplatform/jitsi-call/pull/84
* https://github.com/exoplatform/jitsi/pull/83
* https://github.com/exoplatform/multifactor-authentication/pull/56
* https://github.com/exoplatform/documents/pull/1146
* https://github.com/exoplatform/platform-private-distributions/pull/355

**Comment by boubaker** [comment]
**PRs - Part 3**
Specific Meeds association addons : 
* https://github.com/Meeds-io/deeds-dapp/pull/685
* https://github.com/Meeds-io/deeds-tenant/pull/47
* https://github.com/Meeds-io/deeds-tenant-provisioning/pull/27

**Comment by boubaker** [comment]
Ready for PRs review @rdenarie

**Comment by rdenarie** [comment]
All Pr validated
I let you merge all ?

**Comment by boubaker** [comment]
> All Pr validated I let you merge all ?

ok, thanks.

As agreed, the SSO part has been reworked to keep Picketlink for now. The new framework to use will be worked after, thus I 've made a change in MIP description:

> * `SSO`:...a more modern and maintained third party library for SAML integration, which should be treated in a different MIP. In this MIP, we will have to fork picketlink-federations to update with Jakarta EE package names.

**Comment by boubaker** [comment]
All PRs merged.

**Comment by boubaker** [comment]
As you reminded @rdenarie (thanks BTW), another project was missing in the list of Mips FB:
* https://github.com/exoplatform/platform-public-distributions/pull/277
