### ISSUE TITLE
Portlet UI Cleanup

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#81]
## Rationale

UI Theme used to display informations needs to be reviewed a bit to make sure we have consistencies between portlets: border, display of title, subtitle, body (padding, font-size, text-transform)
For example, in the stream page, we have:
* Your activity or Activity stream which is displayed differently than other portlet titles
* Border-radius have been applied to some portlet (composer, contributions) but not others
* Uppercase is applied to titles and some are forced as is

<img width="751" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/94020ffc-cda4-45a3-bea3-2ede1ca85f13">

### Top User Stories

Each time we add a new portlet, these characteristics below must be considered.

1. Portlet padding/margin characteristics UI
* Any existing portlet must be displayed with a border-radius of 8px (by default)
* Padding inside needs to be 20px 
* Margin-bottom (external) must be 20px. Other margins will be dealt by container
* Contents inside the portlet needs to be displayed as left aligned AND with margin depending what to display:
a. title (if not only a title): padding: 0 0 20px 0
b. subtitle (if something below): padding: 0 0 16px 0
c. subtitle (if body above): padding: 20px 0 16px 0
d. Body (until there are other items to list): padding: 0 0 16px 0

2. Portlet text styles

Ideally, portlet will have same styles and adding a class for each would be a good way to ensure consistency and reusability. Below, characteristics of each content:

**Title:**
* Font-size: 18px
* No text-transformation (no uppercase). If needed, labels can be updated from Crowdin
* Font-color: allPagesGreyColorLighten1,#707070
* Font-style: regular

**See more:**
* Font-size: 14px
* Font-color: primary color
* Font-style: regular

**Subtitle:**
* Font-size: 16px
* Font-color: --allPagesBaseTextColor: #20282c;
* Font-style: regular

**body main text:**
* Font-size: 14px
* Font-color: --allPagesBaseTextColor: #20282c;
* Font-style: regular

**body subtitle:**
* Font-size: 14px
* Font-color: --allPagesGreyColorLighten1: #707070;
* Font-style: regular

Example:
<img width="419" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/1b3647f3-edd9-4b0c-a800-9ae4daf776cd">

Detail of padding/margin:
<img width="842" alt="portlet review - details" src="https://github.com/Meeds-io/MIPs/assets/58853195/081c7674-5e69-4c53-b47e-87d96cbc8f7e">

### Impacts
Any existing portlet must be updated to get those characteristics applied
Provide a reusable component so the portlet is still used when adding a new portlet 

### Extensibility

Like the drawers, the widgets has to define a single template to reuse for all existing widgets with centralized styled title, borders and margins.

### Access 

We have to use the same manner as overview banner and drawer to define generic and reusable style for widgets. Please refer to [Widget.vue](https://github.com/Meeds-io/gamification/blob/develop/portlets/src/main/webapp/vue-app/commons/components/Widget.vue) to take an example of using slots for overview page.

PS: no specific stylesheet has to be added for this reusable component.

**Comment by srenault-meeds** [comment]
Ready for review @margondicco 
cc @Julien-Dubois-eXo if you want to take a look as well

**Comment by srenault-meeds** [comment]
Ready for review please @margondicco

**Comment by margondicco** [comment]
Perfect Go fonc

**Comment by srenault-meeds** [comment]
Thanks. Ready for tech spec @boubaker

**Comment by boubaker** [comment]
ok, thanks, Ready for Tec Review @rdenarie 

@SaraBoutej FYI.

**Comment by rdenarie** [comment]
👍 go tech

**Comment by Julien-Dubois-eXo** [comment]
@srenault-meeds you did not mention the rules if we have a Setting button (gear icon): font-size, etc). 

I think it could be interesting to include it.

**Comment by srenault-meeds** [comment]
> @srenault-meeds you did not mention the rules if we have a Setting button (gear icon): font-size, etc).

Indeed, to be added afterwards as an enhancement. Thanks for this suggestion

**Comment by SaraBoutej** [comment]
ACCs and PRs ready for review by DAO members (eXo : @rdenarie )
PRs list : 
https://github.com/Meeds-io/gamification/pull/1308
https://github.com/Meeds-io/platform-ui/pull/707
https://github.com/Meeds-io/gatein-portal/pull/721
https://github.com/Meeds-io/wallet/pull/443
https://github.com/Meeds-io/analytics/pull/156
https://github.com/Meeds-io/kudos/pull/426
https://github.com/Meeds-io/perk-store/pull/290
https://github.com/Meeds-io/task/pull/311
https://github.com/Meeds-io/poll/pull/115
https://github.com/Meeds-io/app-center/pull/297
https://github.com/Meeds-io/social/pull/3158
https://github.com/Meeds-io/meeds-qa-ui/pull/216/

**Comment by boubaker** [comment]
> ACCs and PRs ready for review by DAO members (eXo : @rdenarie )

Thanks @SaraBoutej .
@rdenarie FYI, some adaptations are "optional" to b able to apply new border radius on eXo applications as well. (not blocker for MIP delivery on develop, but for better coherence on eXo applications, it would be better to apply the new CSS classes on parent DOM of eXo applications)

**Comment by srenault-meeds** [comment]
> some adaptations are "optional" to b able to apply new border radius on eXo applications as well. (not blocker for MIP delivery on develop, but for better coherence on eXo applications, it would be better to apply the new CSS classes on parent DOM of eXo applications)

Regarding this, tell me if you need any help so that you can follow the same pattern (functionnally speaking I mean OFC)
cc @margondicco

**Comment by rdenarie** [comment]
As I understand, I see 3 css class to apply : 

- card-border-radius => to apply radius on application border
- overflow-hidden => not sure to understand this one
- widget-text-header => to apply style on widget headers

@srenault-meeds I'm interested in a quick overview of the changes

**Comment by rdenarie** [comment]
All PRs except platform-ui one have been validated.

**Comment by srenault-meeds** [comment]
> As I understand, I see 3 css class to apply :
> 
> * card-border-radius => to apply radius on application border
> * overflow-hidden => not sure to understand this one
> * widget-text-header => to apply style on widget headers
> 
> @srenault-meeds I'm interested in a quick overview of the changes

Hello,

> * card-border-radius => to apply radius on application border

We have two types of border-radius item:
- the one that would change the display of widgets and apps and for which the admin can update the value from branding app
-> --allPagesBorderRadius (by default, set to 8px)
- the one that is set for cards (tasks item, tasks project card, actions card, etc.)
-> @baseBorderRadius (by default, set to 4px)

> * overflow-hidden => not sure to understand this one

A fix has been made to make sure that when you have a dialog, it is well displayed. For example, the analytics datepicker wasn't available to use before this.

> * widget-text-header => to apply style on widget headers

I guess it is related to the title and the see more we can find in widget headers

Hope that helps to understand

**Comment by SaraBoutej** [comment]
Thanks @rdenarie, merged to develop.
