### ISSUE TITLE
Public site management

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#84]
## Rationale

Once connected to the WoM, Hubs can be listed in the [hub explorer](https://meeds.io/hubs)
To avoid having something with no contents and only user engagement data, we aim to showcase organization's purpose.
That way, visitors and future contributors or leaders can understand how the hub manager is engaging its contributors.

### Top User Stories

**Public site Management**

As a platform administrator, I can manage the public site from the main settings:
* Make it visible to anyone
* Copy address
* Access the edition of the site

<img width="816" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/5447215a-4e29-4df5-8b48-827baa8fcf45">

**Public site layout**
The layout provided by this public site is dedicated to this site. 
That means the site is considered as "standalone" and provides its own layout:
- topbar
- portlets

**Public site Access**

As platform admin or platform publisher,
- even if not made visible to anyone, I can access the public site to edit it (from the option or from the direct link (/portal/public)
- I can edit portlets proposed in this public site

As regular user, 
- if not made visible to anyone, then when trying to access the public site, I am sent to home or login page if not logged in yet
- if made visible to anyone, then I only see portlets that have been filled by the administrator
- if logged in, the topbar reminds me it and I can access the platform from there
- if not logged in, the topbar suggest me to login

When logged in
<img width="985" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/3d48159d-75aa-4d95-857b-51da6fb1b641">

When not logged in
<img width="982" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/7d10a5fb-e28d-4c12-8615-d389c18219b2">

**Public Site Edition**

As platform administrator or platform publisher, I can edit the content proposed in the layout:
* image portlet (MIP #98)
* link portlet (MIP #92)
* single note view portlet (MIP #93)

<img width="985" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/3d48159d-75aa-4d95-857b-51da6fb1b641">

And other content are not editable from there:
* topbar with branding logo and name + logout/login button to access the platform
* if secondary pages are identified for the public site, then display in the topbar the menu portlet
* To be done later: List of programs and related actions/leaderboard that are "public"

### Impacts
Permissions to access the public site
Topbar - public case

#### Gamification
NA

#### Notifications
NA

#### Analytics
Users coming from public site are identified as well as users who sign-up from public site.

#### Unified Search
NA

### Security 
The public site has to be accessible to `*:/platform/administrators` and `*:/platform/web-contributors` until it's made accessible to `Everyone` when an administrator switches the site as publically accessible.

### Configurability 

The Public site pages has to hide the display of shared layout components. The list of topbar applications has to be defined in portal layout.
This site has to be defined and configured to not be re-imported on server restart.

### Feature Flags

No feature flag is needed.

### Security

The Site `public` of type `Portal` has to define `access-permissions` attribute to `*:/platform/administrators` and `*:/platform/web-contributors`. The `edit-permission` attribute allows only one value, thus it will be made possible to only an administrator (member of  `*:/platform/administrators`) to switch the site as publically accessible.

#### Applications

Two new portlets has to be added:
* Login button / Access button: displayed in topbar
* Public status switcher application: displayed in page body for `*:/platform/administrators` only when the site isn't publically accessible yet.

##### Site definition configuration

The XML definition of the `Public` portal has to be added in `Meeds` module to allow defining the whole page without dynamic containers.
Knowing that :
* the extension `meeds.war` holds the definition of `meeds` site, which is specific to the Meeds packaging (can be excluded by Meeds DAO members to define their own site `Meta`)
* the `public` site is a core feature of the Meeds product and its administration is part of `Main Settings` administration UI

We will have to:
* Define the `public` site in a common `Web Archive Extension` that is decoupled from `meeds.war`
Thus, a new `Web Archive Extension` named `sites.war` will be added in order to centralize the `Meeds core sites` into it including `global` site and `public` site.

##### Layout configuration

The public page has to be configured to hide the shared layout. Thus, until the MIP #85 is ready, we will use the following attribute in page definition :
```xml
<hide-shared-layout>true</hide-shared-layout>
```
The page, applications and containers has to use `access-permission` with value `Everyone` so that the visibility switch operation will take effect on `Portal` access permission only.

#### REST API

To switch the site permissions, anew Method will be added in `org.exoplatform.social.rest.impl.site.SiteRest` with `PATCH` method that will allow to alter the site `access-permissions` value.

**Comment by srenault-meeds** [comment]
I removed the go-func as it needs to be reviewed a bit

**Comment by srenault-meeds** [comment]
Open to review again @margondicco

**Comment by margondicco** [comment]
> topbar with branding logo and name + logout/login button to access the platform


To be added : portlet Menu

Go fonc

**Comment by srenault-meeds** [comment]
Thanks @margondicco 

> To be added : portlet Menu

Added

**Comment by srenault-meeds** [comment]
Ready for tech spec @boubaker

**Comment by boubaker** [comment]
Ready for Tech review by DAO members (eXo: @rdenarie )

**Comment by srenault-meeds** [comment]
Requirement added for access to public site management by publishers:

> That means that publishers (* or publisher in /platform/web-contributors) can access main settings from admin menu. They will access any option from there except the platform access settings.

**Comment by boubaker** [comment]
Update technical section to move definition of public site in `meeds.war` :
> The XML definition of the `Public` portal has to be added in `Meeds` module to allow defining the whole page without dynamic containers. In fact, the public page will have notes, social and gamification applications.

**Comment by srenault-meeds** [comment]
> Requirement added for access to public site management by publishers:
> 
> > That means that publishers (* or publisher in /platform/web-contributors) can access main settings from admin menu. They will access any option from there except the platform access settings.

Removed from MIP detail

**Comment by rdenarie** [comment]
Go tech

**Comment by boubaker** [comment]
A new section has been updated to consider the functional requirement to **Keep Public site inherited** independently from `meeds` site definition which shouldn't be inherited. The added section is :

> The XML definition of the `Public` portal has to be added in `Meeds` module to allow defining the whole page without dynamic containers.
> Knowing that :
> * the extension `meeds.war` holds the definition of `meeds` site, which is specific to the Meeds packaging (can be excluded by Meeds DAO members to define their own site `Meta`)
> * the `public` site is a core feature of the Meeds product and its administration is part of `Main Settings` administration UI
>
>We will have to:
> * Define the `public` site in a common `Web Archive Extension` that is decoupled from `meeds.war`
Thus, a new `Web Archive Extension` named `sites.war` will be added in order to centralize the `Meeds core sites` into it including `global` site and `public` site.

**Comment by boubaker** [comment]
ACCs & PRs ready to review by DAO members (eXo: @rdenarie )

BTW, for eXo, you will have to delete the overriden legacy [definition here](https://github.com/exoplatform/platform-private-distributions/blob/6.5.0-M30/plf-enterprise-tomcat-standalone/src/main/resources/gatein/conf/controller.xml#L185-L199)

**Comment by boubaker** [comment]
> ACCs & PRs ready to review by DAO members (eXo: @rdenarie )
> 
> BTW, for eXo, you will have to delete the overriden legacy [definition here](https://github.com/exoplatform/platform-private-distributions/blob/6.5.0-M30/plf-enterprise-tomcat-standalone/src/main/resources/gatein/conf/controller.xml#L185-L199)

A new PR for Automatic Tests adaptation is added too.

**Comment by rdenarie** [comment]
All Pr validated except the one on social Meeds-io/social#3102

**Comment by boubaker** [comment]
> All Pr validated except the one on social [Meeds-io/social#3102](https://github.com/Meeds-io/social/pull/3102)

Thanks, commented.

**Comment by rdenarie** [comment]
All pr validated

**Comment by boubaker** [comment]
PRs merged to develop
