### ISSUE TITLE
feat: Display rule for a standalone site and an aggregated site (switch)

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/MIPs#85]
## Rationale

Capabilities to define a  site as standalone OR aggregated in the meta site.

## 1. Functional Requirements

- For an aggregated site, the portal layout of the meta site is displayed. The top bar AND the left navigation of the shared layout are displayed. The site is displayed in the left navigation. Its position, name, description, banner, navigation are defined in the properties of the site. The elements (containers, applications) of its portal layout are hidden. 
- For a standalone site, the site isn't displayed in the left navigation, the topbar and the left navigation of the shared layout aren't displayed. The elements of the portal layout are displayed.
- It should be possible to switch a standalone site to an aggregated site.
- It should be possible to switch an aggregated site to a standalone site.
- The content of a portal layout may be different from one site to another. This will be defined in another MIP.
- Currently, all the spaces are binded with the option "Dynamic layout". The rule for this option must be changed to apply this one : when i go to a space, the portal layout must be the portal layout of the meta site.

### Access 

   - API 
     - We should update the [isShowSharedLayout](https://github.com/Meeds-io/gatein-portal/blob/develop/webui/portal/src/main/java/org/exoplatform/portal/webui/portal/UISharedLayout.java#L45) method called from the [processRender](https://github.com/Meeds-io/gatein-portal/blob/042d95639177780d0662491a94a6dc2ee1021bf2/webui/portal/src/main/java/org/exoplatform/portal/webui/portal/UISharedLayout.java#L38) method in order to show the shared layout only if the current site is standalone **(with displayed property value = true**).
     - We should update the [toUIPortal](https://github.com/Meeds-io/gatein-portal/blob/develop/webui/portal/src/main/java/org/exoplatform/portal/webui/util/PortalDataMapper.java#L313) method called from the [UIPortalApplication](https://github.com/Meeds-io/gatein-portal/blob/develop/webui/portal/src/main/java/org/exoplatform/portal/webui/workspace/UIPortalApplication.java#L411) in order to use to the meta site portal layout instead of the current portal layout only if the current site is standalone **(with displayed property value = true**). This will have an impact only on the displayed portal layout and not on the persisted one unlike the case of dynamic layout, we should be always able to display the current portal layout when the site is switched from standalone to aggregated.

**Comment by margondicco** [comment]
@azayati to be completed

**Comment by margondicco** [comment]
@srenault-meeds

**Comment by srenault-meeds** [comment]
Sorry if I don't understand it well

Can you clarify this for me please?

> Currently, all the spaces are binded with the option "Dynamic layout". The rule for this option must be changed to apply this one : when i go to a space, the portal layout must be the portal layout of the meta site.

**Comment by srenault-meeds** [comment]
Ok as discussed with Morgan. Go func

**Comment by azayati** [comment]
@margondicco @srenault-meeds

> For a standalone site, the site isn't displayed in the left navigation and the topbar of the shared layout isn't displayed. The elements of the portal layout are displayed.

Here I say that not only the topbar of the shared layout which will not be displayed, but all the shared layout means the topbar and the left navigation, no ?

**Comment by azayati** [comment]
@boubaker Ready for review

**Comment by boubaker** [comment]
> @boubaker Ready for review

Thanks, ok for me, Go Tech added.

**Comment by azayati** [comment]
PR https://github.com/Meeds-io/gatein-portal/pull/712 ready for review @boubaker

**Comment by boubaker** [comment]
> PR [Meeds-io/gatein-portal#712](https://github.com/Meeds-io/gatein-portal/pull/712) ready for review @boubaker

PR approved.

**Comment by srenault-meeds** [comment]
Hello, I have some feedbacks regarding UI/UX. How can we proceed, please?

**Comment by azayati** [comment]
PR review also https://github.com/Meeds-io/social/pull/3133 @boubaker thanks

**Comment by azayati** [comment]
> Hello, I have some feedbacks regarding UI/UX. How can we proceed, please?

@srenault-meeds This is a technical MIP, for which MIP you have the UI/UX feedbacks ?

**Comment by srenault-meeds** [comment]
> > Hello, I have some feedbacks regarding UI/UX. How can we proceed, please?
> 
> @srenault-meeds This is a technical MIP, for which MIP you have the UI/UX feedbacks ?

Not only technical from what I see in the MIP description.
I have some concerns regarding this for example:
<img width="271" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/923d1a50-31a1-4eb5-9dc0-bedc91c9cf98">
