### ISSUE TITLE
feat: Vertical menu portlet

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/MIPs#86]
## Rationale

A new portlet in order to navigate in the navigation nodes tree of a standalone site.

## 1. Functional Requirements

Display in a left drawer with a width of **350px,** the following informations of the current standalone site:

- Site banner
- Site label (in my current language)
- Site description (in my current language)
- Site root node tree with its sub nodes

The content of the left drawer is the same as the second level of a site in the left navigation: 

![image](https://github.com/Meeds-io/MIPs/assets/31288011/2c0972de-b1bc-4ea8-baf1-a2d765a5913c)

The left drawer could not be neither hidden nor expanded.

### Existing Features

- [MIP72](https://github.com/Meeds-io/MIPs/issues/72) describes the new left navigation menu. 
- In this MIP, we have implemented a Vue component named **site-hamburger-item-details** which is used in the **HamburgerMenu** portlet. 
- This component displays the aggregated non meta site second level. 
- This component is already in social module. 

### Access 
- GUI 
   
This MIP speaks about a new portlet, named **VerticalMenu**, which will be used for a standalone site in order to display its navigation.
This portlet will reuse the component **site-hamburger-item-details** described above in Existing Features section. For that, we need to:

1. Define the component as a dedicated AMD Js module to not have it accessible only by the **HamburgerMenu** portlet.
2. Create the new portlet which will depend on this component js module.
3. The **HamburgerMenu** portlet will depend on this component js module.

**Comment by margondicco** [comment]
same comment as the [MIP86](https://github.com/Meeds-io/MIPs/issues/87#issuecomment-1734069820).

the template linked with the portlet navigation could be "vertical menu" with the following properties : 

display site label : yes
display site banner : yes
display site description : yes
display icons in the tree of node : yes

**Comment by margondicco** [comment]
cc @azayati for technical update
cc @srenault-meeds for functional review

**Comment by srenault-meeds** [comment]
Go fonc for me

**Comment by azayati** [comment]
@margondicco should the vertical menu portlet display all sub nodes tree of any sub level exactly like the second level of an aggregated non meta site in the left navigation ?

**Comment by azayati** [comment]
@boubaker Ready for review cc @rdenarie

**Comment by margondicco** [comment]
> Should the vertical menu portlet display all sub nodes tree of any sub level exactly like the second level of an aggregated non meta site in the left navigation ?

yes exactly the same rules as the second level of the left navigation and also the top bar menu

**Comment by boubaker** [comment]
> Move the component in a common part (to not have it inside the HamburgerMenu portlet)

If this component is used by two portlets only, we shouldn't add it in `common` JS Module, but add it in a dedicated JS Module that will be reused by portlets. Similar to `animations` + `application-toolbar` + `attach-image`...

**Comment by azayati** [comment]
> If this component is used by two portlets only, we shouldn't add it in common JS Module, but add it in a dedicated JS Module that will be reused by portlets. Similar to animations + application-toolbar + attach-image...

Yes that's exactly, what I have meant, maybe not well described. Thanks @boubaker for requesting to clarify more. 
Description updated.

**Comment by boubaker** [comment]
ok, thanks Go tech added.

**Comment by azayati** [comment]
PR ready for review & Mips ACC updated:

- https://github.com/Meeds-io/social/pull/3229
- https://github.com/Meeds-io/gatein-portal/pull/751

@boubaker

**Comment by boubaker** [comment]
> PR ready for review & Mips ACC updated

Thanks, PR commented.

**Comment by azayati** [comment]
@boubaker 

Another PR to be reviewed https://github.com/Meeds-io/gatein-portal/pull/751, thanks

**Comment by boubaker** [comment]
> @boubaker
> 
> Another PR to be reviewed [Meeds-io/gatein-portal#751](https://github.com/Meeds-io/gatein-portal/pull/751), thanks

done

**Comment by boubaker** [comment]
PRs approved
