### ISSUE TITLE
feat: Breadcrumb portlet

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/MIPs#87]
## Rationale

A new portlet in order to display dynamically the navigation nodes tree of a standalone site.

## 1. Functional Requirements

- The portlet displays the label of the root node and then the label of the sub nodes until the current node

- A group node should not be clickable.

![image](https://github.com/Meeds-io/MIPs/assets/31288011/ab658334-4513-4679-a48a-d85b5336be3b)

- A tooltip displays the label of the node.

![image](https://github.com/Meeds-io/MIPs/assets/31288011/4acc7911-9582-4c35-b670-6cc98e3bc075)

If more than 4 nodes, the second and the third items are ellipsed.

Example: Root > ... > Node 3 > Node 4

When hovering the ellipsis, then I have a tooltip displaying the Node 2 with ability to click on, it so we can directly access it (if the node is binded with a page or link)

If the root node is a group node, the first sub node linked with a page or a link (that the user can view) is opened.

**Other specific requirements** 

Category of the Breadcrumb portlet : Navigation
Name of the Breadcrumb portlet : breadcrumb OR (better) a template of a generic portlet "navigation portlet".

### Access 

- GUI 
   
A new vue portlet called **Breadcrumb** should be implemented in social Meeds module.

### Services & processing

NavigationRest service will be updated with the method:

GET: /v1/navigations/node (getSiteNavigationNode): This service will retrieve a node with the nodeName and the siteName (or with the nodeId) and will need **expandBreadcrumb** param in order to retrieve the breadcrumb of the node.

**Comment by margondicco** [comment]
@azayati for technical update : the UI/UX of the breadcrumb is very close of the breadcrumb of the document application. 

To have a long-term vision and make the right technical choices :  

We have several portlets with the same functional goals: top bar menu, analytics breadcrumb, this new portlet and the tree in the level 2 of the left navigation

The ideal situation would be to have a single portlet associated with different models and properties. And we could plan to create versions of portlets with predefined configurations

Example: 

A generic navigation portlet
3 templates available: horizontal breadcrumb menu, currently called the top bar menu, and the vertical menu. For each model, you can choose properties such as icon display, etc.

Finally, the administrator can create a breadcrumb application based on a predefined configuration of the navigation portlet with the breadcrumb template and the icon display property set to false.

**Comment by margondicco** [comment]
cc @srenault-meeds to review

**Comment by srenault-meeds** [comment]
> a popup displays the label of the node
A tooltip, not a popup (I know these are details but well, this is only to make sure)

> navigation in the breadcrumb
To have a better UX, can we make sure that following are considered?
- If more than 4 nodes, then second and third item are ellipsed
Example: Root > ... > Node 3 > Node 4
- And when hovering the ellipsis, then I have a tooltip displaying the Node 2 with ability to click to it so we can directly access it
- WDYT?


+1 for a generic portlet. Not interesting to have different portlet for a generic use case

**Comment by margondicco** [comment]
Description updated

**Comment by srenault-meeds** [comment]
Go-Fonc

**Comment by azayati** [comment]
> We have several portlets with the same functional goals: top bar menu, analytics breadcrumb, this new portlet and the tree in the level 2 of the left navigation

I'm not sure/ok that the functionnal role of the breadcrumbs portlet is the same as the vertical site navigation portlet and the current site top bar navigation portlet. The breadcrumbs portlet displays the tree of the current node only, but the others display the whole site tree.
cc @margondicco @srenault-meeds @rdenarie

**Comment by azayati** [comment]
> If more than 4 nodes, then second and third item are ellipsed
> Example: Root > ... > Node 3 > Node 4

@srenault-meeds @margondicco when we have for example 7 sub nodes, it is always only the second and third nodes which should be ellipsed ?

**Comment by margondicco** [comment]
Hello my proposal

![image](https://github.com/Meeds-io/MIPs/assets/31288011/4aa76d95-57ad-408d-958e-adee56a055fd)


As we do in the doc app : 

we display the root node, the current node and its parent node.

**Comment by srenault-meeds** [comment]
This is it

**Comment by azayati** [comment]
@boubaker Go tech needed 
cc @rdenarie

**Comment by boubaker** [comment]
> @boubaker Go tech needed

you mean _ready for review_, ok thanks will take a look at it

**Comment by boubaker** [comment]
ok for me

**Comment by azayati** [comment]
PR ready for review & Mips ACC updated:

- https://github.com/Meeds-io/gatein-portal/pull/734
https://github.com/Meeds-io/social/pull/3184
@boubaker

**Comment by boubaker** [comment]
PRs approved
