### ISSUE TITLE
feat: Images portlet

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/MIPs#89]
## Rationale

The Images portlet must be moved to be used by Meeds.

## 1. Functional Requirements

- Images portlet can be used anywhere in the platform
- Image added in a portlet is unique. So even if the portlet is used in the same page, each portlet can have a different image
- Default image is the one used for eXo spaces banner
- User can resize, crop the images thanks to the cropper tool
- User can restore the default image if needed

Important information : these requirements could be completed and not deleted.

Who can change the image (same rules as the news list portlet) : 

- Publisher of the group content management when the portlet is in a page of a site
- Publisher of the space OR publisher of the group content management when the portlet is in a page of a space site

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  |   |   |   |

### Other Non Functional Requirements

- A new Images vue portlet should be implemented in social Meeds module.
- The Images portlet will depend on **imageCropper** component.
- The Images portlet will have two preferences **imageFileId** and **imageUrl**.

### Services & processing

ImageRest service will be added with the method:

- GET: /v1/social/image/{imageFileId} (getImage): This service will need the **imageFileId** path param in order to retrieve the stored image InputStream with the given **imageFileId** or the default image if the **imageFileId** param is passed with "default" value.
- POST: /v1/social/image (createImage): This service will need the **uploadFileId** query param in order to store the image with **uploadFileId** and return the corresponding uploaded image rest url explained above.

### Data and persistence

- The default image is located under **images** folder of **social-portlet webapp**.
- The uploaded image is stored into the table **FILES_FILES** using the file service. 
- The **imageFileId** and **imageUrl** of the stored image, will be stored as preferences of the corresponding images portlet instance.
- Since every images portlet instance have its own preferences **imageFileId** and **imageUrl** values, we can instantiate easily one or more images portlet in the same page, so that every images portlet instance can easily display its own image.

**Comment by margondicco** [comment]
@azayati to be completed

**Comment by azayati** [comment]
@margondicco Tech part completed, Go fonct needed @srenault-meeds 
@boubaker Go tech needed cc @rdenarie

**Comment by srenault-meeds** [comment]
Go fonc

**Comment by margondicco** [comment]
Hello i don't know why but this information was deleted

It's an important requirement for Meeds

> New requirement : an administrator must be able to modify the image when the portlet is available on a page of a site or space.

cc @azayati @srenault-meeds

**Comment by srenault-meeds** [comment]
Ok for me. One question: in a space, is the manager able to edit it? I guess yes but only to check.

**Comment by azayati** [comment]
> Ok for me. One question: in a space, is the manager able to edit it? I guess yes but only to check.

@srenault-meeds currently for a space context, only the space publisher can edit it.
In a non space context only the publisher of /platform/web-contributors can edit it.

**Comment by azayati** [comment]
> New requirement : an administrator must be able to modify the image when the portlet is available on a page of a site or space.

should it be managers of /platform/administrators or even members ?

**Comment by margondicco** [comment]
probably *:/platform/administrators

**Comment by boubaker** [comment]
> probably *:/platform/administrators

IMO, this should be dependent from Page Edit permissions.

**Comment by azayati** [comment]
@boubaker Ready for review cc @rdenarie

**Comment by srenault-meeds** [comment]
Need to review the functional requirements together

and @azayati it seems that technical spec is missing. It might be relevant to review it once we discuss the functional scope

**Comment by azayati** [comment]
>  @azayati it seems that technical spec is missing

@srenault-meeds
I have added the technical spec in Existing Features part, since it will be globally just a transfer of code base from layout-management to social.

**Comment by boubaker** [comment]
> Existing Features part

Existing in Meeds ?

**Comment by azayati** [comment]
> > Existing Features part
> 
> Existing in Meeds ?

existing in eXo I mean, I have moved it in to "Other Non Functional Requirements" part

**Comment by rdenarie** [comment]
@azayati Even if the code exists in eXo, we need to explain how the feature works, functionnaly and technically, so that it could be reviewed before merging in meeds.

We need a technical spec here.

**Comment by srenault-meeds** [comment]
Functionally speaking, here is the summary after discussing it with Morgan:
- Images portlet can be used anywhere in the platform
- Image added in a portlet is unique. So even if the portlet is used in the same page, each portlet can have a different image
- Default image is the one used for Meeds spaces banner
- User can resize, crop the images thanks to the cropper tool
- User can restore the default image if needed

Is that it @margondicco?

**Comment by azayati** [comment]
@boubaker Ready for review

**Comment by boubaker** [comment]
> @boubaker Ready for review

May be get a go func (fix the functional scope) on it first before reviewing the technical spec

**Comment by boubaker** [comment]
> The Images portlet must be moved to be used by Meeds.

Does the image permissions (access & edit) follow the page access permissions ?
This is very important IMO. Else, any user can access any image banner even if he's not member of a space + this will limit the users that will be able to edit the image settings.
@srenault-meeds WDYT ?

**Comment by margondicco** [comment]
Functional requirement added.

**Comment by srenault-meeds** [comment]
As discussed during product committee, this MIP needs to be reviewed a little. So back to open and labels removed

**Comment by srenault-meeds** [comment]
Replaced by #98
