### ISSUE TITLE
Draft feat: Recognition settings site

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/MIPs#90]
### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  |   |   |   |

### Access 
   - GUI 
   - API 

### Services & processing
   - Ex: Scheduled Jobs

### Data and persistence
   - Macro data model
   - Persistence layer 
   - Use of caches
## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts 
   - References

**Comment by srenault-meeds** [comment]
Hi,

Here is the expected for recognition settings:
<img width="754" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/51c8d881-bcb2-4b78-864a-2b842f48141b">


Current badges, connectors, rewards and wallet pages will be identified as is.

And then for each item, we need to review their setup access for administration usability:
Kudos (remove current kudos page)
<img width="260" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/38d50137-3ff5-4d92-a012-ea4c2b64afef">

Wallet (remove current wallet tab in wallet management page)
<img width="552" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/17cafce4-5b11-4b78-8158-8092bb650a3a">

Perkstore (remove current perkstore page)
<img width="551" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/4e4f96b5-23d7-411e-b307-a711974c16f6">

Prototype link here: https://xd.adobe.com/view/20c52cf6-d3bd-405a-aac1-80d19ae3a8c4-7596/
