### ISSUE TITLE
feat: Upgrade to JDK 21

### ISSUE THREAD

**Issue by boubaker** [Meeds-io/MIPs#91]
## Rationale

JDK 21 is the latest LTS version and we should migrate into it to benifit from its dvantages and to keep possibility of supporting a "supported JDK" for customers contexts.

### Feature Flags

| Property Name  | Default Value | Target Audience | Functional Behaviour |
| ------------- | ------------- | ------------- | ------------- |
|  |   |   |   |

### Access 
   - GUI 
   - API 

### Services & processing
   - Ex: Scheduled Jobs

### Data and persistence
   - Macro data model
   - Persistence layer 
   - Use of caches
## 5. Annexes
   - Reasoning that explain the technical choices
   - Impacts 
   - References

**Comment by rdenarie** [comment]
As there is no architectural nor functionnal impact, can we give go func and go tech on this MIP ?

cc @boubaker

**Comment by rdenarie** [comment]
Boubaker's remark : 

> Besides, I think we should do a deep cleanup to delete the usage of Security Manager in Core Foundation projects, see https://nipafx.dev/road-to-21-upgrade/ for more information about changes to take care of.

**Comment by boubaker** [comment]
Done, Besides, we may need to upgrade to latest Spring Maintenance version `3.2.5` as well to ensure compatibility with upgraded third party libraries and latest fixes.

**Comment by rdenarie** [comment]
PR : 

https://github.com/Meeds-io/maven-parent-pom/pull/48
https://github.com/Meeds-io/maven-depmgt-pom/pull/151
https://github.com/Meeds-io/kernel/pull/63
https://github.com/Meeds-io/core/pull/96
https://github.com/Meeds-io/ws/pull/42
https://github.com/Meeds-io/gatein-portal/pull/888
https://github.com/Meeds-io/commons/pull/602
https://github.com/Meeds-io/gamification/pull/1589
https://github.com/Meeds-io/meeds/pull/1999
https://github.com/exoplatform/jcr/pull/324
https://github.com/exoplatform/ecms/pull/2356
https://github.com/exoplatform/chat-application/pull/733
https://github.com/exoplatform/agenda-connectors/pull/107
https://github.com/exoplatform/data-upgrade/pull/216

**Comment by boubaker** [comment]
Thanks, just a small remark [here](https://github.com/Meeds-io/gatein-portal/pull/888/files#r1603736641)

**Comment by rdenarie** [comment]
Both mips acceptance are restarted with jdk 21.

@boubaker you can check

**Comment by srenault-meeds** [comment]
Hello, do we need to do a quick functional test?

**Comment by boubaker** [comment]
> Hello, do we need to do a quick functional test?

May be executing the Automatic Tests yes. Else, feel free to make some acceptance/smoke tests on ACCs.

**Comment by rdenarie** [comment]
I launch the automatic tests on meeds acc

**Comment by rdenarie** [comment]
@boubaker PRs have been updated to address [this remark](https://github.com/Meeds-io/gatein-portal/pull/888#discussion_r1604508837)

**Comment by boubaker** [comment]
All good, thanks 👍
