### ISSUE TITLE
Links portlet

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#92]
## Rationale

As a platform admin, it is not possible to add links while it'd be interesting to hilight some links in a page for example in the public page we aim to deliver soon.

### Top User Stories

As a platform admin OR as a space host, I can add links using "Links Portlet" with these characteristics:

**Precision**
* Who can edit it?
A. Platform admin or Publisher (in web-contributors group) for platforms page
B. Space host or space publisher for spaces
-> When doing so, admin or space host remain able to edit links (they are publisher by design). That means this is a delegation the admin can give to other users.
-> That still means that redactors cannot edit links.
* Who can see it?
A. editors (see above)
B. anyone who can access the page (Same access permissions of the current page)

**Links display**
I can choose between 3 display: rows, cards, columns

<img width="1104" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/274bdb61-7e4a-4780-a329-f54884fdfb5d">

For each display, I can decide:
a. to add header
b. to add a see more
c. to show name
d. to use large icons

Depending what characteristic I add to the display, the preview is updated dynamically:
<img width="1340" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/a38feb9e-de02-4d99-bce3-7813f94a0826">

**Links addition**
When I add a link, then I can:
a. name it
b. describe it (to be displayed in a tooltip only)
c. upload an icon (default one is a globe)

Once added, I can decide the order of the links with move up / move down options

<img width="1447" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/b8fe9a6f-0e60-43fb-bf8f-2d67d4ff5cd4">

### Impacts

NA

#### Gamification
NA

#### Notifications
NA

#### Analytics
NA

#### Unified Search
NA

### Security 

The Links portlet content access has to follow the following ACL rules:

**Who can Edit it**

- All Platform administrators
- Publisher in Platform Web Contributors
- (If page in a space) Publisher & Host roles of the space

**Who can Access it**

- Editors (See above)
- Same access permission as the page

### Upgradability

When the `merge` or `overwrite` import mode are applied to pages, the portlet settings has to remain as was set using UI.

### Feature Flags

The feature flag `exo.feature.publisherRolePromotion.enabled` will be removed (introduced by MIP #35) to give full access to the publisher role management in space Members application.

### Security and access

In order to allow reusing the same setting even after restarting a server using sites import mode `merge` and `overwrite`, the settings of the portlet has to be stored in a dedicated Table (we can also use an unstructured data storage like `SettingService` Key/Value, but for better extensibility, we will use database tables to structure the data to store). When the server re-import the page, the Link Portlet settings has to remain. To do this, a portlet preference will be added in portlet definition in XML file to allow referencing the `Link Portlet Settings`. This name is unique, same as a technical identifier and could be reused in different portlet instances in different pages. This complexity of configuration is hidden to end user and will just permit to preserve the settings changed by UI.
If a portlet is added on the fly (by UI by example), the name of the setting will be exactly the same as the portlet technical identifier without having to request user to add a unique name for portlet instance.
The settings has to be accessible through the portlet technical identifier (`name` preference) to retrieve the referenced page and contextual space. The ACL check using page permissions and space will allow retrieving the list of links for current user or deny it. This way, the list of links aren't all time public and could be used in restricted areas/pages.

### Data and persistence

The tables that will be used to store each Links Portlet instance is as following:

![271041890-d257a005-7e6a-4af5-840b-7375adb2bffe drawio](https://github.com/Meeds-io/MIPs/assets/594824/9afb950e-80fc-4d45-bb66-8e9090d262e1)

The Link Setting Header, link name and link description are translated, thus the `TranslationService` API will be used to persist those information instead of storing it in Links Table.
Each link setting will be added to each portlet instance, thus the `PAGE_REFERENCE` and `SPACE_ID` Table columns will be used to store the page reference and contextual space of the page. By using both information, the Links Service Layer will be able to check on users permissions without relying on REST or WebUI contextual information (ConversationState & currently displayed Site).

**Comment by srenault-meeds** [comment]
@margondicco Ready to be reviewed

**Comment by margondicco** [comment]
Ok perfect Go fonc

**Comment by boubaker** [comment]
Ready for Tech review @rdenarie

**Comment by boubaker** [comment]
> Ready for Tech review @rdenarie

More details are added in description about the usage of `PAGE_REFERENCE` Table column and the Model has been reviewed to reduce the columns in favor of stored data using `TranslationService` API.

**Comment by rdenarie** [comment]
I understand that for each instance of the portlet, a line will be inserted in `SOC_LINK_SETTINGS` table.
The reference between the portlet instance and the line in the table is the `PAGE_REFERENCE`

As the name suggest, `PAGE_REFERENCE` identifies a page. With this solution, how can we have different instances of the portlet on the same page ?


If the configuration is done in pages.xml, at startup, we should provide a mechanisms to read the xml configuration (containing links), and store it in the DB. Can you add a paragraph about this requirement ?

In addition, the fact that the overwrite or merge option have no action on the portlet configuration means that the pages.xml configuration will be only use first time. There is NO WAY to say : I want to drop the configuration I did in UI (because I made some tests and it is weird), and reset to initial configuration. @srenault-meeds @margondicco ok with that ?


I not confident with the fact to change how we manage portlet preferences, to have a portlet which not respect importmode option. Would it be possible to keep the actual behaviour (portlet preferences kept in import mode, reset in overwrite mode), and then change the default meeds portal configuration to not use overwrite mode ?
Having this allow to store the preferences in the portlet preferences, without having to create 2 new DB tables, and allow to keep a homogeneous behaviour with importmode (no exception for certain portlet).

**Comment by boubaker** [comment]
> With this solution, how can we have different instances of the portlet on the same page ?

You can see it here in action https://meedsv2-ft.meeds.io/portal/meeds/public
and the commit to instantiate the portlets:
https://github.com/Meeds-io/social/commit/1cb91d0d3c6d6a60a641ce7ebdab6ef8ef6d3e42

In fact, even if the portlet is reinstanciated, the identifier of the application/portlet is the portlet preference `name` https://github.com/Meeds-io/social/blob/cebd38b0586bbc6baec5dd71e2999629b9c660e6/webapp/portlet/src/main/webapp/WEB-INF/portlet.xml#L791-L792 which is the unique identifier for settings `Database Table`.
The `PAGE_REFERENCE` is used to allow retrieving permissions (access & edit) only.

> Can you add a paragraph about this requirement ?

In fact, it wasn't functionally required for now to be able to add links by configuration, but it's a possibility that can be addressed using Component Plugins of `LinkService` API or using portlet preferences. I have removed the `Configurability` section for now.

**Comment by boubaker** [comment]
> I not confident with the fact to change how we manage portlet preferences, to have a portlet which not respect importmode option. Would it be possible to keep the actual behaviour (portlet preferences kept in import mode, reset in overwrite mode), and then change the default meeds portal configuration to not use overwrite mode ?
Having this allow to store the preferences in the portlet preferences, without having to create 2 new DB tables, and allow to keep a homogeneous behaviour with importmode (no exception for certain portlet).

The list of links are data which are independent from portlet preferences.

**Comment by rdenarie** [comment]
Can you provide an example of what will be stored in SOC_LINK_SETTINGS.PAGE_REFERENCE ?


For the xml configuration, can you confirm that you only put the portlet name in portlet preferences ? Links data are not present in the file pages.xml ?

**Comment by boubaker** [comment]
> Can you provide an example of what will be stored in SOC_LINK_SETTINGS.PAGE_REFERENCE ?

`portal::test::overview`

> For the xml configuration, can you confirm that you only put the portlet name in portlet preferences ? Links data are not present in the file pages.xml ?

Yep, links data aren't added in `portlet.xml`, only the name to reference the link setting `NAME`.

**Comment by rdenarie** [comment]
> > Can you provide an example of what will be stored in SOC_LINK_SETTINGS.PAGE_REFERENCE ?
> 
> `portal::test::overview`
> 
So, if you have 2 lines in SOC_LINK_SETTINGS having PAGE_REFERENCE = 'portal::test::overview', how do you know that it is for portlet 'Usefull Link 1' or for portlet 'Userfull Link 2' which are both on the same page ?

**Comment by boubaker** [comment]
> > > Can you provide an example of what will be stored in SOC_LINK_SETTINGS.PAGE_REFERENCE ?
> > 
> > 
> > `portal::test::overview`
> 
> So, if you have 2 lines in SOC_LINK_SETTINGS having PAGE_REFERENCE = 'portal::test::overview', how do you know that it is for portlet 'Usefull Link 1' or for portlet 'Userfull Link 2' which are both on the same page ?

> In fact, even if the portlet is reinstanciated, the identifier of the application/portlet is the portlet preference `name` https://github.com/Meeds-io/social/blob/cebd38b0586bbc6baec5dd71e2999629b9c660e6/webapp/portlet/src/main/webapp/WEB-INF/portlet.xml#L791-L792 which is the unique identifier for settings `Database Table`.
> The `PAGE_REFERENCE` is used to allow retrieving permissions (access & edit) only.

> ...which is the unique identifier...

**Comment by rdenarie** [comment]
Ok. I didnt catch the name attribute.

Ok for me

**Comment by srenault-meeds** [comment]
Hello,

I think that @margondicco have asked this before: Who can edit links?

So, here is my suggestion:
- The Administrator of the current page can add, edit or remove links and can change the display.
That means that: 
1. the platform admin can edit any links in the platform
2. the space host can edit any links listed in its site (the space)

- In addition to this, as it addresses CMS use cases, a new role needs to be considered: publisher.
So an admin (platform admin or space host) can promote another user as publisher to delegate some privilege (here, the right to edit anly links in the site he is identified)

Of course, that means that even if a publisher is identified, the admin remains able to edit any links.

Any objection?
If no, then this business rule can be applied for any CMS portlet we will add in the platform (Single notes view, for example)

Thanks for your answer and open to discussion of course

**Comment by srenault-meeds** [comment]
Agreed with @margondicco 
cc @boubaker I'll add it in the description

**Comment by srenault-meeds** [comment]
Added:


* If needed, the admin (platform admin or space host) can identify a publisher from users to be able to edit this links portlet.
* When doing so, admin or space host remain able to edit links (they are publisher by design).
* That means this is a delegation the admin can give to other users.
* Redactors cannot edit links.

**Comment by boubaker** [comment]
> Added:
> * If needed, the admin (platform admin or space host) can identify a publisher from users to be able to edit this links portlet.
> * When doing so, admin or space host remain able to edit links (they are publisher by design).
> * That means this is a delegation the admin can give to other users.
> * Redactors cannot edit links.

@srenault-meeds does this mean that page `edit-permission` should be ignored ? In other terms, should we consider the edit permission on Link & all upcoming CMS based feature applications this way:
* When the page is outside of a space => `*:/platform/administrators` group members are allowed to edit links
* When the page is inside of a space => `manager:/spaces/SPACE_NAME` and `publisher:/spaces/SPACE_NAME` groups members are allowed to edit links

1/ Is this correct ?
2/ Should we enabled the feature flag provided by #35 in Meeds package to allow "publisher" of a space to edit links ?
3/ What about access permissions ? Who can access the links portlet content, should it follow/reuse the access permissions of the page or is it open to all users including anonymous ?

**Comment by srenault-meeds** [comment]
My answers:
1/ Yes + the fact that publisher of platform must be able to edit it as well
-> Is that possible to add publisher in /platform/admin?
2/ Yes for test purpose only. indeed, we must rework the way roles are provided in spaces before.
3/ I don't understand what is access permissions. Is that "who can see links?"? If yes, then, yes it must reuse the access permissions of the current page.

**Comment by boubaker** [comment]
> My answers:
> 1/ Yes + the fact that publisher of platform must be able to edit it as well
> -> Is that possible to add publisher in /platform/admin?

All roles are attribuable to any group, even spaces group. The list of roles can't be exclusively defined for one group, but it's transverse. Shouldn't we add `/platform/web-contributors` group in platform to be compliant to `eXo` DAO member standard groups ? In fact, giving a role `publisher:/platform/administrators` to a user will allow him making more than changing & publishing contents in pages.

> 2/ Yes for test purpose only. indeed, we must rework the way roles are provided in spaces before.

Sorry, I can't understand this. So you mean, we will enable it in QA/Test environment only without enabling the flag in builtin product to not have a `promote as publisher` button in `Members` space application ?

> 3/ I don't understand what is access permissions. Is that "who can see links?"? If yes, then, yes it must reuse the access permissions of the current page.

`access permissions` : permissions to access the page

**Comment by srenault-meeds** [comment]
1/ and 3/ Yes, so to summarize
- Who can edit it? 
A. any page in the platform: admin and publisher (in web-contributors)
B. any space: space host + space publisher

- Who can see it?
A. editors (see above)
B. Anyone who can access the page (same permissions of the page)

2/ Ok, let's enable the flag to true

Description updated

**Comment by boubaker** [comment]
> Description updated

Ok, thanks.
Tech spec updated as well for review by DAO members (eXo: @rdenarie )

**Comment by rdenarie** [comment]
👍

**Comment by boubaker** [comment]
Ready for review @rdenarie @margondicco on ACCs & attached PRs

**Comment by rdenarie** [comment]
All prs validated

**Comment by boubaker** [comment]
> All prs validated

Thanks will wait for #54 to be merged first.
