### ISSUE TITLE
 feat: Customize the display of space nodes icons

### ISSUE THREAD

**Issue by margondicco** [Meeds-io/MIPs#95]
## Rationale

Currently the icons of space nodes are hardcoded. Here we want to be able to change these icons and customize them by space.

## 1. Functional Requirements

- Default icons (fontawesome) are defined for each node of a space
- I can change the icon 
- After the change, the bottom bar (mobile version) displays the new icons
- After the change, the level 2 of the left navigation displays the new icons

**Default icons**

- stream : fontawesome : stream
- note : fontawesome : clipboard
- tasks :fontawesome : task
- settings : fontawesome : cog
- members : fontawesome : users
- wallet :  fontawesome : wallet
- (document) : fontawesome : folder-open
- (agenda) : fontawesome : calendar-alt

### Configurability 

- We should set the icon attribute for **"SpaceApplication"** fields of **SpaceTemplate** object params configured with SpaceTemplateConfigPlugin. 
- This will allow to set this icon to the created space node corresponding to the configured space template application.
- This configuration should be done in:
  - [**"social"**](https://github.com/Meeds-io/social/blob/develop/extension/war/src/main/webapp/WEB-INF/conf/social-extension/social/spaces-templates-configuration.xml): For "stream", "settings" and "members" nodes.
  - [**"meeds"**](https://github.com/Meeds-io/meeds/blob/develop/webapps/plf-meeds-extension/src/main/webapp/WEB-INF/conf/meeds/space-template-configuration.xml): For "SpaceWallet" node.
  - [**"meeds"**](https://github.com/Meeds-io/meeds/blob/develop/webapps/plf-meeds-extension/src/main/webapp/WEB-INF/conf/social-extension/social/spaces-templates-configuration.xml): For "stream", "members", "tasks", "notes" and "settings" nodes.
  - [**"notes"**](https://github.com/Meeds-io/notes/blob/develop/notes-webapp/src/main/webapp/WEB-INF/conf/wiki/spaces-templates-configuration.xml): For "notes" node.
  - [**"tasks"**](https://github.com/Meeds-io/task/blob/develop/webapps/src/main/webapp/WEB-INF/conf/task-addon/spaces-templates-configuration.xml): For "tasks" node.
  - wallet: For "SpaceWallet" node, the configuration of "community" space template should be added
- This modification will has an effect only for newly created spaces with configured space template.

### Upgradability

- We need to implement an upgrade plugin into [social upgrade modules](https://github.com/Meeds-io/social/tree/develop/component/core/src/main/java/org/exoplatform/social/core/upgrade) order to set existing space navigation nodes icons based on the related page application name. 

### Access 
   - GUI 
     - We should update [SpacePanelHamburgerNavigationItem.vue](https://github.com/Meeds-io/social/blob/develop/webapp/portlet/src/main/webapp/vue-apps/hamburger-menu/components/recent-spaces/SpacePanelHamburgerNavigationItem.vue#L55) in order to get the space navigation node icon directly instead of [hardcoding it](https://github.com/Meeds-io/social/blob/develop/webapp/portlet/src/main/webapp/vue-apps/hamburger-menu/components/recent-spaces/SpacePanelHamburgerNavigationItem.vue#L81)
     - We should update [SpaceMenuItem.vue](https://github.com/Meeds-io/social/blob/develop/webapp/portlet/src/main/webapp/vue-apps/space-menu/components/SpaceMenuItem.vue#L42) in order to get the space navigation node icon directly instead of [hardcoding it](https://github.com/Meeds-io/social/blob/develop/webapp/portlet/src/main/webapp/vue-apps/space-menu/components/SpaceMenuItem.vue#L44)
   - API 
     - We should update [getSpaceNavigations ](https://github.com/Meeds-io/social/blob/develop/component/core/src/main/java/org/exoplatform/social/core/space/SpaceUtils.java#L1999) method called from the space rest API [getSpaceNavigations endpoint](https://github.com/Meeds-io/social/blob/develop/component/service/src/main/java/org/exoplatform/social/rest/impl/space/SpaceRestResourcesV1.java) in order to no more hardcode computing the navigation node icons, the exact stored navigation node icons should be retrieved.

**Comment by margondicco** [comment]
@azayati : to be completed

**Comment by margondicco** [comment]
@srenault-meeds

**Comment by srenault-meeds** [comment]
Ok for me.
If you need an icon for wallet, please use the following instead : money-bill-alt

**Comment by margondicco** [comment]
> money-bill-alt

are you sure ? 

![image](https://github.com/Meeds-io/MIPs/assets/31288011/8f8877ec-9788-45b0-8f7e-e7b0402c94e6)

**Comment by srenault-meeds** [comment]
Well this is what we have set for rewards and we talked about it with Benjamin but ok, let's stick with the current icon then 
And we will update this if needed afterwards

**Comment by azayati** [comment]
@margondicco I suggest to change the title of the MIP **feat: Customize space nodes icons** since the storage of the space nodes icons is already in the PORTAL_NAVIGATION_NODES as any other non space node. We need just to display each space node icon in the needed location instead of the hardcoded one.

Another question, should we change also the icons of the applications under space settings:
![image](https://github.com/Meeds-io/MIPs/assets/1579929/263a0b6f-6d6d-4a37-9b57-e4af150394b6)

**Comment by srenault-meeds** [comment]
> Another question, should we change also the icons of the applications under space settings:

Indeed, it has to be done as well (already the case for meeds apps FYI)

**Comment by margondicco** [comment]
Good catch @azayati yes we also change the icons of the applications. i'm note sure it's already done for meeds in terms of storage

**Comment by azayati** [comment]
@boubaker ready for tech review

> We need to implement an upgrade plugin in order to set existing space navigation nodes icons based on the related page application name.

I have just a doubt about how doing this point for meeds since it not have the data-upgrade addon, should this be done manually ? cc @margondicco @srenault-meeds @rdenarie

**Comment by boubaker** [comment]
ok for me, please delete empty sections to make this easily readable. (same for all MIPs, we intend to delete empty sections in fact)

**Comment by azayati** [comment]
> ok for me, please delete empty sections to make this easily readable. (same for all MIPs, we intend to delete empty sections in fact)

done, even for other MIPs, thanks

**Comment by margondicco** [comment]
> @boubaker ready for tech review
> 
> > We need to implement an upgrade plugin in order to set existing space navigation nodes icons based on the related page application name.
> 
> I have just a doubt about how doing this point for meeds since it not have the data-upgrade addon, should this be done manually ? cc @margondicco @srenault-meeds @rdenarie

Hello 
After our discussion I confirm the need for a upgrade plugin for Meeds.
To manage the different historical situations , we'll need to look at the portlet on the different space page (and not the uri) to apply the right icons

**Comment by azayati** [comment]
PR ready for review & Mips ACC updated:

- https://github.com/Meeds-io/social/pull/3150
- https://github.com/Meeds-io/notes/pull/833
- https://github.com/Meeds-io/task/pull/310
- https://github.com/Meeds-io/meeds/pull/1264
- https://github.com/Meeds-io/wallet/pull/442

@boubaker

**Comment by boubaker** [comment]
> PR ready for review & Mips ACC updated

Thanks, reviewed.

**Comment by boubaker** [comment]
All PRs approved. Have a nice weekend 👍
