### ISSUE TITLE
Mute spaces option

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#97]
## Rationale

❌ When listing notifications in the drawer, I can't mark it as read when using desktop (I can do it only in mobile view by using swipe to the right)
❌ When I receive notifications related to a space I am not active, I cannot mute this space

### Top User Stories

**UX when hovering a notification from the drawer**
✅ Three dots proposed when hovering a notification to remove it or to mark it as read

<img width="215" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/1c29b8ad-c779-4fb2-8efd-cef557f33d39">

**New option to mute notifications for any activity in a space**
✅ Option to mute notifications from a space
* from a space popover
<img width="172" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/6f7e77ea-8873-4c55-9388-73018c2f9f4f">

* from space detail panel
<img width="245" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/5ded3d5e-54e0-41cb-a378-c8c44b9f0152">

* from notification drawer
<img width="211" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/5725115f-11ee-4340-b1b3-73ccb45b6d64">

✅ Ability to mute a space from its popover, its details and from user settings
* List muted spaces and manage it

<img width="334" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/09db4be1-8ee1-41de-98bc-2f1522f76856">

When muted, any notification coming from that space will be muted, except mention:
- mention in activity
- kudos
- mention in tasks comment
- assignee for a task (or coworker)

### Impacts
NA

#### Gamification
NA

#### Notifications
NA

#### Analytics
Usage of spaces that are muted

#### Unified Search
NA

### Expected Volume & Performance

No considerable amount of data should be used to store the muted spaces information per user (a simple list of space identifiers).

### Security 

Only an admin or the user him(her)self should be able to mute a space.

### Extensibility 

We should be able to designate some plugins that are sent even if the associated space is muted.

### Configurability 

The default configuration for all notification plugins has to be `user can mute it` by default, only for some plugins (like for mention based plugins) where we should give a way to make the muting on it is disabled.

### Upgradability

No data upgrade is needed on already existing notifications.

### Feature Flags

No feature flags will be added.

### Access 

A new REST endpoint has to be added to allow muting a space or unmute it. Like enabling/disabling channel endpoint, the used endpoint will be `/notifications/settings/{username}/spaces/{spaceId}` with a Form Parameter to set it enabled or disabled. The existing endpoint to retrieve user settings will be used to retrieve muted spaces list.

### Services & processing

Each generated Notification has to allow to specify the `spaceId`. By default, to reuse the work done in `SpaceWebNotification` (MIP #17 ), by default the space identifier will be retrieved from parameter "spaceId" which is already stored in notifications.
In `UserSetting`, the list of muted spaces will be mapped using `SettingService` as other attributes of User Notification Settings.
Consequently, the notifications processing will be changed to validate for each user whether the space is muted for a given plugin inside a pace or not. If not, send it else ignore its processing for all channels.

### Data and persistence
No change

**Comment by srenault-meeds** [comment]
Ready for review @margondicco

**Comment by srenault-meeds** [comment]
Reviewed the description
cc @margondicco

**Comment by margondicco** [comment]
Hello Go fonc (+ add coworker for tasks)

**Comment by srenault-meeds** [comment]
yes updated thanks

**Comment by srenault-meeds** [comment]
Read for tech spec @boubaker

**Comment by boubaker** [comment]
Spec Tech ready for review by DAO Members (eXo : @rdenarie )

**Comment by rdenarie** [comment]
Ok for me. 
Like for Notification UI upgrade, it will need an update on eXo notification (spaceId is not present in all notification as I can see).

**Comment by boubaker** [comment]
ACCs & PRs ready to review by DAO members (eXo: @rdenarie )

> Like for Notification UI upgrade, it will need an update on eXo notification (spaceId is not present in all notification as I can see).

Yes, you can find an example here:
https://github.com/Meeds-io/kudos/pull/393/files
and
https://github.com/Meeds-io/task/pull/270/files

**Comment by rdenarie** [comment]
All PR approved

**Comment by boubaker** [comment]
> All PR approved

Thanks all PRs merged.
