### ISSUE TITLE
Images portlet

### ISSUE THREAD

**Issue by srenault-meeds** [Meeds-io/MIPs#98]
## Rationale

We have four different banners available:
- profile 
- space
- program
- overview

We need another one for public site use case and for any page that would welcome this content.
To avoid duplicating banner type, we need to merge at least overview and new banner for page.

_In fine_, one unique image component must be provided for consistency sake and for reusability purpose. This is already the case for profile, space and program banners.

### Top User Stories

**Default display**

By default, the primary color of the current platform is used as the background color

**Access to this image portlet:**

_**Management permissions**_ 

Given I am admin or publisher of the site/page
- if platform: admin or publisher
- if space: host or publisher
Then I can edit the image

_**Access to the image (view)**_ 

Given I have access to the page where this image is added
Then I can see the image
-> Same permission as the current page

**Image edition**
When having right to edit it,
Then I have the expected regular options:
- add image, zoom, crop, resize images
- restore default background (aka primary color)
- add alternative text 

In addition to this, I have options to change the display of the image with three options (landscape, portrait, square)
- landscape: same ratio and behaviour than the one used for banners (space) - 1280 / 175 = 7.314285714285714 
- portrait: same ratio and behaviour than the one used for login page - 25 / 35 = 0.7142857142857143
- square: ratio = 1:1 - =1

For any format, the width to apply is the one used in the container where the portlet is 

<img width="1231" alt="image" src="https://github.com/Meeds-io/MIPs/assets/58853195/bc1eb04b-3416-4aa5-ab9d-7e6298065644">

**Precisions**

-> No change for profile, spaces and program banner
Studied and conclusions are:
- Current behaviour is ok
- no changes needed for now

### Impacts
Replace overview banner portlets and remove the "old" overview banner portlet
In the app registry as well

#### Gamification
NA

#### Notifications
NA

#### Analytics
NA

#### Unified Search
NA

### Security 

The Image portlet (same as Links and SNV) content access has to follow the following ACL rules:

**Who can Edit it**

- All Platform administrators
- Publisher in Platform Web Contributors
- (If page in a space) Publisher & Host roles of the space

**Who can Access it**

- Editors (See above)
- Same access permission as the page

### Configurability 

It must be possible to define the default image to display when configuring a portlet in `pages.xml`.

### Upgradability

(_Same as Links and SNV Portlets_)
When the `merge` or `overwrite` import mode are applied to pages, the portlet settings has to remain as was set using UI.

### Feature Flags

No feature flag is needed

### Security

The `CMSPortlet` introduced in MIP #93 will be reused in order to rely on the same Permission settings of CMS portlets.

### Access 

The Attachment REST endpoint introduced by MIP #53 will be used to add image attachments to portlet. To do this a new `AttachmentPlugin` will be added for a new object type `imagePortlet` which will manage object with ids the Setting name associated to each portlet.

### Services & processing

The portlet definition of `CMSImagePortlet` should allow to define a default image to import from sources through a local relative path using a portlet preference with name `image-path`. When this parameter is added in portlet preferences, it should be imported the whole first time the portlet is displayed.

### Data and persistence

The additional portlet parameters will be stored using AttachmentService in associated MetadataService Type (inside `MetadataItem` properties).

**Comment by srenault-meeds** [comment]
Ready for review @margondicco

**Comment by margondicco** [comment]
Hello Go fonc

**Comment by boubaker** [comment]
> Hello Go fonc

Thanks, I 'll take it from here for Tech spec

**Comment by boubaker** [comment]
Ready for spec Review by DAO Members ( eXo: @rdenarie )

**Comment by srenault-meeds** [comment]
@margondicco I have added the description of each format (landscape, portrait and square) as I have explained it to you yesterday

**Comment by rdenarie** [comment]
Go tech

**Comment by boubaker** [comment]
ACCs & PRs ready to review by DAO members (eXo : @rdenarie )

**Comment by rdenarie** [comment]
all pr validated

**Comment by boubaker** [comment]
> all pr validated

Thanks, merged to develop.
